libgdx/libgdx

CHANGES
backends/gdx-backends-gwt/src/com/badlogic/gwtref/GwtReflect.gwt.xml
gdx/src/com/badlogic/gdx/net/HttpRequestBuilder.java

See https://github.com/libgdx/libgdx/pull/2691 ...

Added HttpRequestBuilder

---

gdx/src/com/badlogic/gdx/assets/AssetManager.java

See https://github.com/libgdx/libgdx/pull/2615
This time without an entry in CHANGES as it would again conflict with my other PR....

Added 3d ParticleEffectLoader to AssetManager by default

---

backends/gdx-backends-gwt/src/com/badlogic/gwtref/GwtReflect.gwt.xml

Corrected the wrong package declaration for the 3d particle classes in the GWT reflection includes.

Corrected GWT reflection includes

---

gdx/src/com/badlogic/gdx/utils/UBJsonWriter.java

Add ability to save JsonValue to UBJsonWriter

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java

Appending text should be a standard feature for TextField

TextField - New appendText method

---

CHANGES
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java
tests/gdx-tests/src/com/badlogic/gdx/tests/UITest.java

Clean PR for this one:
https://github.com/libgdx/libgdx/pull/2696

adds horizontal text alignment feature for textfields

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSDevice.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/custom/HWMachine.java

Tested on (one) device. If anyone wants to send me the rest of the devices I can test the rest ;)

Add IOSDevice enum for PPI, fixes #2736

---

gdx/src/com/badlogic/gdx/net/NetJavaImpl.java

This PR fixes #2656. 
I moved the `lock.lock()` and `lock.unlock()` methods to only lock access to the listeners and connections maps. Other methods, especially `listener.handleHttpResponse()`, `listener.failed()` and `listener.cancelled()` are now lock free. Otherwise longer operations within these listener methods (like downloading a huge file) would block access to the connections and listeners maps and therefore new http requests would wait until these methods have finished execution (like the file has been downloaded).

Prevent NetJavaImpl from blocking new requests during listener method execution

---

extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/OisControllers.java

- Removed another unnecessary "toLowerCase" call.
- Made the heavy check for lost window handle only being called once per second, not on each frame
Please note that most of the textual diffs are from my save action adding braces to one-line bodies. I hope you don't mind?

Further improved performance of OisControllers

---

gdx/src/com/badlogic/gdx/maps/tiled/tiles/AnimatedTiledMapTile.java

[#2805] Adding AnimatedTiledMapTile.getCurrentFrameIndex()

---

gdx/src/com/badlogic/gdx/assets/AssetManager.java

This method is added to make possible loading one specified asset synchronously with AssetManager.

Added a method finishLoadingAsset(String)

---

gdx/src/com/badlogic/gdx/utils/BufferUtils.java
tests/gdx-tests/src/com/badlogic/gdx/tests/BufferUtilsTest.java

See http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18322 .
I've extended BufferUtilsTest for verification.

Fixed copyJni() srcOffset parameters.

---

gdx/src/com/badlogic/gdx/graphics/glutils/ImmediateModeRenderer.java
gdx/src/com/badlogic/gdx/graphics/glutils/ImmediateModeRenderer20.java
gdx/src/com/badlogic/gdx/graphics/glutils/ShapeRenderer.java

* Adds `color (float)` to ImmediateModeRenderer inteface and implements
* Optimizes ShapeRenderer methods with cached colour float.

Cache colour float for ShapeRenderer

---

gdx/src/com/badlogic/gdx/utils/PooledLinkedList.java

This PR addresses issue #2824.

Added reverse iteration from tail of PooledLinkedList

---

gdx/src/com/badlogic/gdx/net/NetJavaImpl.java

I have replaced the lock with synchronized methods. Fixes https://github.com/libgdx/libgdx/issues/2847

Fix for Issue #2847

---

gdx/src/com/badlogic/gdx/maps/tiled/tiles/AnimatedTiledMapTile.java

to change the animation speed in runtime

AnimatedMapTile - Getter and Setter fot animationIntervals

---

gdx/src/com/badlogic/gdx/maps/tiled/tiles/AnimatedTiledMapTile.java

Whoops, this is very important to correctly determine the frame.

changing the loopduration

---

gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java

Added id as a property since Tiled recently added unique IDs to objects. Closes #2873.

Added id as a property to MapObject for Issue #2873

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Window.java

When the camera changes position, keepWithinStage set limits in the initial
position. Now, keepWithinStage sets limits depending the Camera.

keepWithinStage method in Window class in Scene2d-ui

---

gdx/src/com/badlogic/gdx/graphics/g3d/Environment.java
gdx/src/com/badlogic/gdx/graphics/g3d/environment/SpotLight.java

Hello,
This is my first Pull Request.
This Pull Request add support of spotlight in environment. It doesn't modify the shader so spotlight can't be used with default shader. But it allows to use spotlight in custom shader.

Add spotlight support in Environment

---

gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java

My eclipse initially added 10 missing `@Override`s (I still don't know why *some* people don't like 'em), so I used the github file edit feature instead.

Fix for #2968

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

Updating VisUI extension version to 0.7.1

Updating VisUI extension

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

I'm hg user and don't trust my git skills enough to rebase #2945 into a single commit so here's a fresh PR.

libgdx-utils as 3rd party extension

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/Chart.java

I've found that I frequently need to adjust the overall transparency of a ParticleEmitter, but it is very tedious to drag all the points on the chart one by one. Usually, there are several points, because I want a nice fade-in/fade-out. The proportional drag is especially useful for this purpose.
Proportional drag works best when the chart is expanded.
Dragging all points only affects Y, not X.

ParticleEditor - Ctrl to drag all points, ctrl-shift to do so proportionally

---

CHANGES
extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
gdx/src/com/badlogic/gdx/graphics/g2d/PixmapPacker.java
tests/gdx-tests/src/com/badlogic/gdx/tests/PixmapPackerTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/extensions/FreeTypeAtlasTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/extensions/FreeTypePackTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

This is a fresh pull request from a fresh branch with the changes from #2993, because my merging and rebasing got messed up.

Improve support for user-supplied packer to FreeTypeFontGenerator

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java

Newest Ashley docs were inconsistent with included version of Ashley.

Updated ashley version to 1.4.0

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java

fixes #3106 
This pull request only changes the text in the textarea

Log wrapped exception messages

---

gdx/src/com/badlogic/gdx/graphics/g3d/particles/batches/BillboardParticleBatch.java

I cleaned the code with the libgdx formatter and then I added the ability to customize blending and depth.

Update billboard particle batch v2

---

gdx/src/com/badlogic/gdx/graphics/g3d/decals/Decal.java

fixes #2986 
Added support for setting custom decal material to Decal class.
Custom material can be applied via constructor or via setter.
Note: This is my first pull request ever and first day of using GIT :)
So any comments are welcome, if I messed up something.

Added support for custom decal material in Decal class.

---

gdx/src/com/badlogic/gdx/graphics/g3d/particles/batches/BillboardParticleBatch.java

Correct error in billboardparticlebatch

Warning - Correct critical error in billboard particle batch

---

gdx/src/com/badlogic/gdx/utils/Bits.java

Fix bugs with Bits.nextClearBit(int)

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/CheckBox.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ImageTextButton.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ParticleEmittersTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/Scene2dTest.java

Allow checkbox and ImageTextButton to be left/right hand sided

---

gdx/src/com/badlogic/gdx/graphics/g3d/environment/SpotLight.java

Exponent is the rapidity of the falloff of light from its target direction.

Add exponent to SpotLight.

---

gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java

See https://github.com/libgdx/libgdx/issues/3227
Fixes #3227

Correct Framebuffer error.

---

gdx/src/com/badlogic/gdx/graphics/g3d/environment/BaseLight.java
gdx/src/com/badlogic/gdx/graphics/g3d/environment/DirectionalLight.java
gdx/src/com/badlogic/gdx/graphics/g3d/environment/PointLight.java
gdx/src/com/badlogic/gdx/graphics/g3d/environment/SpotLight.java

Allow to create lights more easily.

Add builder to lights.

---

gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java

The glsl files are not updated so SpotLight won't work as is with the
DefaultShader. It can be useful to bring his own shader with phong
lightning to see the beauty of spot lights.
I tested it with the light tests and it creates no error.

Add Spotlight in DefaultShader.

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

gdx-setup: Updated libgdx-utils 3rd party extension

---

gdx/src/com/badlogic/gdx/graphics/PixmapIO.java
tests/gdx-tests/src/com/badlogic/gdx/tests/PngTest.java

Also update the test to exercise this code.
Fixes #3113.

Recreate the DeflaterOutputStream in PixmapIO.PNG each time

---

gdx/src/com/badlogic/gdx/math/Intersector.java
gdx/test/com/badlogic/gdx/math/IntersectorTest.java
gdx/test/com/badlogic/gdx/math/Shape2DTest.java
gdx/test/com/badlogic/gdx/math/collision/CollisionTest.java
gdx/test/com/badlogic/gdx/utils/BitsTest.java

This creates an junit test in the style of `BitsTest` in `gdx/test`. Note that this test currently fails at line 28 (test_circle) due to bug in Circle.contains. Fix is in the followup PR. `intersectorTest` is currently not done yet, because I didn't have the time/tools/smarts yet to compute what should be the correct answer. So it wasn't included as a test yet.

Create Intersector unit test from Intersector main

---

gdx/src/com/badlogic/gdx/math/Intersector.java

Fix #3147 (with MathUtils)

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

Updating VisUI extension to latest version.

Update VisUI extension

---

gdx/src/com/badlogic/gdx/utils/PooledLinkedList.java
gdx/test/com/badlogic/gdx/utils/PooledLinkedListTest.java

Add size() method to PooledLinkedList.

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SplitPane.java

Fix error message in split pane. Fixes #3356.

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/DefaultAssetFilter.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/etc1/ETC1Compressor.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePackerFileProcessor.java

Fixed some problems with `*.jpeg` files support, like texture packer ignoring jpeg files. Jpeg and jpg and essentially the same so it's just few lines changed.

Add .jpeg support

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java

Label#setEllipsis(boolean ellipsis) was ignoring boolean argument.

Fixed Label setEllipsis method

---

tests/gdx-tests/src/com/badlogic/gdx/tests/BulletTestCollection.java
tests/gdx-tests/src/com/badlogic/gdx/tests/bullet/TriangleRaycastTest.java

Useful for finding triangles on navigation meshes for example.

Raycast test for picking individual triangles on a collision shape.

---

gdx/src/com/badlogic/gdx/graphics/Color.java

I modified Color.valueOf(String s) so it can now also accept hex strings that start with a '#'

Color.valueOf(String s)

---

tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/ShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/DirectionalAnalyzer.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/LightFilter.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/NearFarAnalyzer.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/ShadowMapAllocator.java

The shadow system pull request has been splitted in 6 parts.
This is the first.
1/6 -> Add interfaces.
See https://github.com/libgdx/libgdx/pull/3347

ShadowSystem 1/6

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java

See https://github.com/libgdx/libgdx/pull/3428

Fix false-positive of vibration support

---

gdx/src/com/badlogic/gdx/math/Vector.java
gdx/src/com/badlogic/gdx/math/Vector2.java
gdx/src/com/badlogic/gdx/math/Vector3.java

Also added a method to set the components of the Vector3 based on a spherical coordinate.

Adds methods to create random vector

---

gdx/src/com/badlogic/gdx/graphics/g2d/Batch.java

Removed outdated OpenGL 1.x documentation.

Batch.java documentation fix

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFileHandle.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFiles.java

Since exists() on non-existant files is extremely slow, I will try to optimize the initialization.

Make AndroidZipFile initialization faster

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java

This PR fixes the extremely ugly formatting.

Fix formatting

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java

Fix for #3486 (Hiero deadlocks on exit)

---

tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/BaseShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/FirstPassBaseShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/ShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/AABBNearFarAnalyzer.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/AllLightFilter.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/FrustumLightFilter.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/LightFilter.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/NearFarAnalyzer.java

This commit refactor shadow system to be more consistent.
Moreover, it adds BaseShadowSystem which is the base for systems.
See https://github.com/libgdx/libgdx/pull/3347

Shadow system 3 / 6.

---

gdx/src/com/badlogic/gdx/scenes/scene2d/utils/DragAndDrop.java

Warn on the use of source actor as Payload#setDragActor(Actor)

Improve DragAndDrop#Payload javadoc

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

I have added my gdx-facebook extension to the 3rd party extension list.
Extension:
https://github.com/TomGrill/gdx-facebook
Example App:
https://github.com/TomGrill/gdx-facebook-app

Added gdx-facebook extension (v1.1.0)

---

tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/BaseShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/FirstPassBaseShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/MainShader.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/MainShaderProvider.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/Pass1Shader.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/Pass1ShaderProvider.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/RealisticShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/main.fragment.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/main.vertex.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/pass1.fragment.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/pass1.vertex.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/utils/BoundingSphereDirectionalAnalyzer.java

Add RealisticShadowSystem.
Good luck for reviewing ! Here come struggle with shaders !
See #3347

Shadow system 4 / 6

---

gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java

when using setFixedWidthGlyphs() - see #3239.

Fix to set first and last glyphs in a glyph run to the correct width

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

set gdx-facebook version to 1.1.1

set gdx-facebook version to 1.1.1

---

gdx/src/com/badlogic/gdx.gwt.xml

#3518
I hope this fixes GWT build.

Add Queue to gdx.gwt.xml

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplication.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplicationConfiguration.java

Add LwjglApplicationConfiguration.preferencesFileType to allow absolute preference path according to (#3602).

Add LwjglApplicationConfiguration.preferencesFileType

---

gdx/src/com/badlogic/gdx/graphics/glutils/FloatTextureData.java

Fix FloatTextureData issue

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java

Improved support for the full-screen Web API by adding support for Internet Explorer 11, Edge and any other browsers implementing the non-prefixed version of the standard.
Furthermore, made sure supportsDisplayModeChange() stops pretending that all browsers can go full-screen, and removed an unused variable.

Improved GWT full-screen support.

---

gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java

Not an ideal solution, but should make it more easy to fix `#version` issues.

Add option to prepend shader code

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java

This fix FrameBufferTest and ShadowMappingTest from crashing in GWT.

Fixed GWT crashing when pixels is null.

---

tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/FirstPassBaseShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/ClassicalShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/MainShader.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/MainShaderProvider.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/Pass1Shader.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/Pass1ShaderProvider.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/Pass2Shader.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/Pass2ShaderProvider.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/main.fragment.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/main.vertex.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/pass1.fragment.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/pass1.vertex.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/pass2.fragment.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/pass2.vertex.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/realistic/RealisticShadowSystem.java

Add classical shadow system!
This system supports point light.
Pass 1 : Compute depth maps.
Pass 2 : Accumulate light in shadow zones.
Main : Remove light accumulated during pass2.

Shadow system 5 / 6

---

gdx/src/com/badlogic/gdx/graphics/g2d/CpuSpriteBatch.java

Related to #3625. Noticed another broken overload.

Fix another draw method.

---

tests/gdx-tests/src/com/badlogic/gdx/tests/superkoalio/SuperKoalio.java

These are some minor edits I made when experimenting with the SuperKoalio file. They do not change any functionality, but I figured I might as well propose them for the master.

Spelling fixes and cleanup in SuperKoalio test

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java

Contribution to #3673. Changes to get Lwjgl3 backend running with our GL3 project.

Added GL3 context creation. Ported GL version checks from Lwjgl backend.

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

https://github.com/libgdx/libgdx/pull/3537

Added gdx-kiwi and gdx-lml to gdx-setup.

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java
backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/input/MockInput.java
backends/gdx-backend-jglfw/src/com/badlogic/gdx/backends/jglfw/JglfwInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglInput.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java
gdx/src/com/badlogic/gdx/Input.java
gdx/src/com/badlogic/gdx/input/RemoteInput.java
gdx/src/com/badlogic/gdx/input/RemoteSender.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java

This is a continuation of a former pull request, https://github.com/libgdx/libgdx/pull/3361.  I've been procrastinating on finishing this up as I'm unfamiliar with the rebase command and needed some schooling, which I acquired here, http://stackoverflow.com/questions/33829117/git-squash-rebase-master-history-concerns

Gyro implementation for Android

---

extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Transform.java

Helps one avoiding have to sin and cos the returned angle from getRotation.

Get orientation as Vector2 on Box2D Transform

---

gdx/src/com/badlogic/gdx/graphics/g3d/Model.java

When extending the Model class, to avoid copy/pasting the whole file, prefer protected method. It's a start.

Make Model extendable

---

gdx/src/com/badlogic/gdx.gwt.xml

Add DistanceFieldFont.java and remove TextMarkup.java.
See https://github.com/libgdx/libgdx/tree/master/gdx/src/com/badlogic/gdx/graphics/g2d

Correct gdx.gwt.xml file

---

gdx/src/com/badlogic/gdx/utils/ScreenUtils.java

Fix ScreenUtils.

---

extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/CollisionJNI.java
extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btCompoundShapeChild.java
extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btDbvt.java
extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btDbvtAabbMm.java
extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btDbvtNode.java
extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btDbvtProxy.java
extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java
extensions/gdx-bullet/jni/swig/collision/btDbvt.i

The Bullet wrapper changes from https://github.com/libgdx/libgdx/pull/3730

Make btDbvtNode and btDbvtAabbMm poolable

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java

Use more lenient casts to prevent crash

---

gdx/src/com/badlogic/gdx/math/Intersector.java

As mentioned in issue #3632 this adds a new Intersector method to determine the overlapping area between two polygons.

Add polygon intersection method.

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java

fix gwt isButtonPressed

---

tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/BaseShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/ShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/ClassicalShadowSystem.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shadows/system/classical/MainShader.java

see #3702
@xoppa can you take a look.

Fix shadow system for HDPI monitor, see #3702

---

backends/gdx-backends-gwt/src/com/google/gwt/webgl/client/WebGLRenderingContext.java

Make code more beautiful and respect indentation rules.

Format WebGLRenderingContext text

---

gdx/src/com/badlogic/gdx.gwt.xml
gdx/src/com/badlogic/gdx/graphics/g3d/utils/CameraHelper.java
gdx/src/com/badlogic/gdx/graphics/g3d/utils/helper/CameraHelper.java

CameraHelper help you to visualize your camera in 3D space.

Add CameraHelper

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

First extension that reached 1.0 :)

Update VisUI extension version

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3GL20.java

See https://github.com/libgdx/libgdx/pull/3803

Fix wrong buffer clear

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java

This would help integrate LibGDX with other tools or game engines that leverage from it.

Add support for selecting modules through command line

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

Updating VisUI to 1.0.1 and VisRuntime to 0.3.1. Also adding new extension: [gdx-lml-vis](https://github.com/czyzby/gdx-lml-vis) which allows to use LML with VisUI.

Updating extensions.xml

---

gdx/src/com/badlogic/gdx/math/Intersector.java

Removed unneeded List operations.

Reduce number of instantiations within IntersectPolygons.

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java

Together with my last pull request, this would help integrate LibGDX with other tools or game engines even further. If no extension is provided then it would have the default behaviour, so wouldn't break existing setups.

Add support for selecting extensions through command line

---

CHANGES
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/glutils/IndexBufferObject.java
gdx/src/com/badlogic/gdx/graphics/glutils/IndexArray.java
gdx/src/com/badlogic/gdx/graphics/glutils/IndexBufferObject.java
gdx/src/com/badlogic/gdx/graphics/glutils/IndexBufferObjectSubData.java
gdx/src/com/badlogic/gdx/graphics/glutils/IndexData.java

Used with IndexBufferObjectSubData, it increases performance and allows
to update a portion of the indices.

Add updateIndices to IndexData

---

gdx/src/com/badlogic/gdx/math/Intersector.java

Addresses Issue  [#3804.](https://github.com/libgdx/libgdx/issues/3804)

Correct duplicate vertices issue when Intersect polygons share points.

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java

Lwjgl3: GL3 core profile hint only mandatory on OS X.

---

tests/gdx-tests/src/com/badlogic/gdx/tests/box2d/OneSidedPlatform.java

These subexpressions are identical.
CLA was signed and sent.

Duplicate subexpressions in OneSidedPlatform.java

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Kerning.java

Adds support for lookup type 9, which is just a way to address subtables with a 32-bit offset in large font files.
Also fixes pair format 2, which wasn't correctly populating class 0, which is a special case: For pair positioning, it gets everything in the coverage that isn't in any other class.
My testing for this has been with Apple's San Francisco fonts, which can be found here: https://developer.apple.com/fonts/
In particular, San Francisco UI display ultralight is one that requires both of these changes to export kerning information properly.
CLA will be signed and emailed shortly.

Hiero GPOS extension support + pair format 2 fix

---

gdx/src/com/badlogic/gdx/graphics/g3d/shaders/default.vertex.glsl

Remove bad preprocessor condition.
See this stackoverflow post to well understand the problem : 
http://stackoverflow.com/questions/36218475/opengl-glsl-preprocessor-issue-with-specific-directive/36221079#36221079

Fix default shader glsl vertex file

---

gdx/src/com/badlogic/gdx.gwt.xml
gdx/src/com/badlogic/gdx/graphics/g3d/utils/RenderableShapeBuilder.java

RenderableShapeBuilder allows to visualize several renderable's properties.
Currently, it can build normal, tangent and binormal.

Add RenderableShapeBuilder

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java

Reverts libgdx/libgdx#3903 see #3997

Revert "Lwjgl2 backend displayMode tweaks"

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/shapebuilders/RenderableShapeBuilder.java
gdx/src/com/badlogic/gdx/graphics/g3d/utils/shapebuilders/SphereShapeBuilder.java

Increase performance in RenderableShapeBuilder.

Fix RenderableShapeBuilder

---

.gitignore
extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/gitignore

Update .gitignore fix #4016

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Input.java

See https://github.com/libgdx/libgdx/issues/3673#issuecomment-186189355 and https://github.com/libgdx/libgdx/issues/3673#issuecomment-179474566

Fix Gdx.input.getCurrentEventTime() not being set, see #3673

---

gdx/src/com/badlogic/gdx/maps/tiled/TiledMapTileLayer.java

Being able to make and modify Cell objects with convenient inline method chaining syntax would be nice.
First pull request I ever made. Hope I'm doing this right.

enabled convenient method chaining for TiledMapTileLayer.Cell

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

Also corrected indentation (changed spaces to tabs - for consistency).

Updated library versions in extensions.xml

---

CHANGES
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowConfiguration.java

Making very nice GLFW feature available.

Add window size limits to LWJGL 3 app and window configurations.

---

gdx/src/com/badlogic/gdx/graphics/glutils/ShapeRenderer.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ShapeRendererTest.java

New methods for the ShapeRenderer to draw ellipses rotated around their center.

ShapeRenderer draw rotated Ellipses

---

extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics/box2d/Body.java

Spell checking and some in-file consistence for the method headers.

Small fixes for JavaDoc in Body.java

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java

See https://github.com/libgdx/libgdx/issues/3673#issuecomment-172115381 and https://github.com/libgdx/libgdx/issues/3673#issuecomment-207808454 .

Fix LifecycleListener's dispose method not being called on LWJGL3 backend

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

version 1.2.1, compatibility 1.9.3, GWT support

gdx-facebook extension update

---

extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/parsing/RobustJavaMethodParser.java

Custom ignore tag

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java

Both variants have some independent improvements that may make sense to carry over.
Sorting simplifies the comparison.

private and public methods sorted by name to simplify syncing with Playn HtmlGl20

---

gdx/src/com/badlogic/gdx/utils/PerformanceCounter.java

clarify seconds are used for performancecounter

clarify performancecounter docs

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java

Fixed GWT gl20

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

set gdx-dialogs extension version to 1.1.0

set gdx-dialogs extension version to 1.1.0

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

gdx-facebook extension version 1.2.2

gdx-facebook extension version 1.2.2

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java

Change gl handle to webgl object hash maps to an efficient jso int mapp (based on sparse js arrays) tailored towards this purpose. Remove unneeded helpers

Change gl handle to webgl object hash maps to an efficient jso int map

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java

closes #3887 Double-click select causes StringIndexOutOfBoundsException

closes #3887 Double-click select causes StringIndexOutOfBoundsException

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java

Same problem as https://github.com/libgdx/libgdx/pull/4177#discussion_r71828088

Fix leaking pixmap

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java

Fixes https://github.com/libgdx/libgdx/issues/4232

Label not setting font scale to 1 (fixes #4232)

---

gdx/src/com/badlogic/gdx/assets/AssetManager.java

Added a simple counter of total tasks created by individual asset loads,
which can be compared against the size of the current task stack to
determine fractional progress towards completion of a single asset.
This increases the fidelity of the progress value returned, which is
especially useful for assets with a large number of dependencies.

Increased fidelity of progress tracking.

---

gdx/src/com/badlogic/gdx/graphics/g3d/ModelInstance.java

Fixed method getAnimation, now it works as described.
Related to #4245 .

Fixed issue 4245

---

gdx/src/com/badlogic/gdx/scenes/scene2d/utils/DragAndDrop.java

I think drag actor should be positioned at the mouse position by default, this also fix #4281

Fix #4281 - Wrong drag actor position

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java

Revert "Fixes #4322: Restore window on correct monitor"

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java

Instead of centering the window when going from fullscreen to windowed, it is now placed at the position it was before we switched to fullscreen. This, I think, is a more intuitive solution, because if the user has positioned the window in a certain way, then this shouldn't be lost, when switching between windowed and fullscreen.
This works, because in Lwjgl3 (or GLFW) all monitors are [part of a virtual screen coordinate system](http://www.glfw.org/docs/latest/intro_guide.html#coordinate_systems). The stored positions are in that coordinate system.
-----
For cases, where developers want to center their window, we could do the following, which is based on the previous code in `setWindowedMode`:
```java
public void centerWindowOnMonitor(Monitor monitor) {
if (!isFullscreen()) {
DisplayMode …
```

Fixes #4322: Restore window on the monitor it was before going fullscreen.

---

gdx/src/com/badlogic/gdx/graphics/glutils/IndexBufferObjectSubData.java

See http://badlogicgames.com/forum/viewtopic.php?f=11&t=23869

IndexBufferObject error and docs cleanup

---

gdx/src/com/badlogic/gdx/graphics/VertexAttribute.java

Like say in #3933 ,just make `private` to `protected`

Modify at VertexAttribute

---

CHANGES
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Input.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowAdapter.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowListener.java
gdx/src/com/badlogic/gdx/Application.java
gdx/src/com/badlogic/gdx/Graphics.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3DebugStarter.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/MultiWindowTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/NoncontinuousRenderingTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

This is an evolved version of #3772 that I worked out with @code-disaster.

Lwjgl3 non-continuous rendering.

---

gdx/src/com/badlogic/gdx/graphics/g3d/attributes/CubemapAttribute.java
gdx/src/com/badlogic/gdx/graphics/glutils/FrameBuffer.java
gdx/src/com/badlogic/gdx/graphics/glutils/FrameBufferCubemap.java
gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java
tests/gdx-tests-android/assets/data/shaders/cubemap-frag.glsl
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/FrameBufferCubemapTest.java

see #4409 
One from the "how the heck did this ever work?" category.
I open a PR because I'd like some extra eyes on what I changed. Esp. if it's a good idea to rename an attribute alias like this - I reckon it may break user shaders.

FrameBufferCubemap fixes

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextArea.java
tests/gdx-tests/src/com/badlogic/gdx/tests/TextAreaTest2.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

Fixes TextArea bug

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java

Fix #4446 (ProgressBar knobAfter)

---

gdx/src/com/badlogic/gdx/math/Rectangle.java

Hi
Added contains method to math.Rectangle to check if a circle is contained in the Rectangle
It might be helpful 
Cumps

Add contains circle to math.Rectangle

---

gdx/src/com/badlogic/gdx/assets/loaders/ShaderProgramLoader.java

Add license header to ShaderProgramLoader

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/reflect/ClassReflection.java
gdx/src/com/badlogic/gdx/utils/reflect/ClassReflection.java

Adds some missing methods to ClassReflection.
The methods already exist but haven't been exposed for general usage.

Add missing methods to ClassReflection

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/util/regex/Matcher.java

Useful method to manage quote replacement in paths

Add useful method

---

backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSApplication.java

fix app crashed by call window()

fix app crashed by call window()

---

gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffect.java

This makes it easier for subclasses of ParticleEffect to create custom
emitters.

added newEmitter method

---

gdx/src/com/badlogic/gdx/scenes/scene2d/actions/RotateToAction.java

First PR, lmk if there is anything I should change.  :)

Adding LERP option to RotateToAction #4154

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml

Set gdx-facebook extension version to 1.3.0

gdx-facebook version set to 1.3.0

---

CHANGES
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java

added ProgressBar.isVertical()

---

extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeType.java

This improves performance a little bit by not calculating known values.
In my case it saved about 200ms.

Improve Performance, don't calculate known values

---

gdx/src/com/badlogic/gdx/assets/AssetDescriptor.java
gdx/src/com/badlogic/gdx/graphics/Cubemap.java
gdx/src/com/badlogic/gdx/graphics/Pixmap.java
gdx/src/com/badlogic/gdx/maps/MapObjects.java

Fixed a bunch of typos in various files

---

CHANGES
extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/ios-moe/build.gradle
extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/ios-moe/xcode/ios-moe.xcodeproj/project.pbxproj
gradle/dependencies.gradle
pom.xml

Fixed moe assets resource handling

Updated moe version to last released

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextArea.java

TextArea drag-selection fix (#4682)

---

gdx/src/com/badlogic/gdx/math/Ellipse.java

Minor nitpick, but the units should be considered arbitrary. World size is confusing enough as it is for newcomers.

Fix Ellipse docs

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/war/index

I'm hoping I've changed this in the correct place.
See issue https://github.com/libgdx/libgdx/issues/4758

Fix issues with key events not firing in a frame

---

gdx/src/com/badlogic/gdx/input/RemoteInput.java

Added two new arrays in RemoteInput, deltaX and deltaY. They record the difference in X and Y position between input readings.
Also updated the existing getDeltaX and getDeltaY methods, to return the corresponding new values.

Added touch input delta to RemoteInput

---

gdx/src/com/badlogic/gdx/utils/Array.java
gdx/src/com/badlogic/gdx/utils/IntArray.java

I added a shift method to Array that shifts every elements by a given offset, as well as a selectMin and selectMax method. I also added a sum method to IntArray that returns the sum of every element in the array.

Added useful utility methods to the Array and IntArray classes

---

gdx/src/com/badlogic/gdx/assets/AssetManager.java

This wasted two minutes of my time, so I'll save everyone else's.

Add CubemapLoader as one of the defaults

---

extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics/box2d/ChainShape.java
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/ChainShape.java

Currently I have to allocate a new `float[]` for each shape even though it would be possible to just use these and pass in my float buffer array.
I have never modified anything JNI related in libGDX, so please somebody check if I'm doing it right.

Add Box2D createChain/Loop variants with offset and length

---

gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
tests/gdx-tests-android/assets/data/maps/tiled-objects/test-load-mapobjects.tmx
tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapObjectLoadingTest.java

Fixed visible state not being loaded for object tiled layers

---

gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java

Fixed offset parsing for image layers saved with tiled 1.0.2+

---

gdx/src/com/badlogic/gdx/graphics/g2d/Batch.java
gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSpriteBatch.java
gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java

To make Batches blending more flexible I added glBlendFuncSeparate support.

Add support for glBlendFuncSeparate blending.

---

gdx/src/com/badlogic/gdx/scenes/scene2d/Actor.java

Found myself looking for these methods so decided to create them.

Added setX and setY methods with alignment argument

---

gdx/src/com/badlogic/gdx/graphics/Color.java

added RGB/HSV color conversion

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/unicodefont/GlyphPage.java

Before adding a new row to a glyph page, see if it actually fits

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java

Parse source.properties using Properties class

---

extensions/gdx-bullet/.classpath

added missing bullet inversedynamics source folder

---

gdx/src/com/badlogic/gdx/maps/tiled/AtlasTmxMapLoader.java
gdx/src/com/badlogic/gdx/maps/tiled/TmxMapLoader.java
gdx/src/com/badlogic/gdx/utils/XmlReader.java

Those methods never throws `IOException`.

XmlReader wrong exception throws fix

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/src/HtmlLauncher

Added a commented example code for a resizable HTML application as discussed in #4762

HTML Template: provide example code for resizable HTML app

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Skin.java
tests/gdx-tests-android/assets/data/uiskin.json

I realize the auto-tagging of built-in styles might be overdoing it, but can we at least support tags in the first place so subclasses can take advantage?

Support class name tags in Skin json

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java

Related to #5023 
`TextField` now relies on `Timer` and update cursor visibility from its callback. This will allow `TextField` to have a blink animation even under non-continuous rendering state.
One drawback should be considered though. There are cases when blinking should be restarted (key input, cursor moved) and since `Timer` API doesn't allow to reset scheduled repeated task immediately, workaround is used and the task imitates reset by making cursor visible and skipping one blink cycle. But this should be fine due to blink ticks happen pretty often and effect is barely noticeable.

TextField uses timer task to perform cursor blinking

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java

Just for correctness, no real impact

Use StringBuilder instead of StringBuffer

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java

Changes robovm input not to throw exception and just log the error in case touch pointer lookup fails.
I receive from time to time a crash report in one of my games (that is pretty touch intensive) caused by a pointer not found ("Couldn't find pointer id for touch event!")
Even if this should never happen in theory it does in some cases (haven't been able to reproduce) but missing a touch event should not be fatal in my opinion.
It also makes it consistent with Android implementation.
**NOTE**
MOE should also be changed for consistency. I'm not familiar with MOE to be confident about making the changes but they should be pretty similar.

Handle input pointer id lookup fail not to be fatal on robovm

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java

moved addEventListeners(); to solve issue #5025

Solves issue #5025

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidAudio.java

Fixes #5059. Sounds randomly not being played on Android

---

gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffect.java

Replace HashMap with ObjectMap in ParticleEffect

---

gdx/src/com/badlogic/gdx/math/Vector2.java

rotateAround / rotateAroundRad methods can be usefull

Vector2.java  rotateAround 

---

gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java

If wrap is set to false it can only be checked once instead of every iteration through the for-loop

GlyphLayout: Optimisation of setText-while-loop

---

gdx/src/com/badlogic/gdx/utils/Array.java
gdx/src/com/badlogic/gdx/utils/ArrayMap.java
gdx/src/com/badlogic/gdx/utils/BinaryHeap.java
gdx/src/com/badlogic/gdx/utils/BooleanArray.java
gdx/src/com/badlogic/gdx/utils/ByteArray.java
gdx/src/com/badlogic/gdx/utils/CharArray.java
gdx/src/com/badlogic/gdx/utils/FloatArray.java
gdx/src/com/badlogic/gdx/utils/IdentityMap.java
gdx/src/com/badlogic/gdx/utils/IntArray.java
gdx/src/com/badlogic/gdx/utils/IntFloatMap.java
gdx/src/com/badlogic/gdx/utils/IntIntMap.java
gdx/src/com/badlogic/gdx/utils/IntMap.java
gdx/src/com/badlogic/gdx/utils/IntSet.java
gdx/src/com/badlogic/gdx/utils/LongArray.java
gdx/src/com/badlogic/gdx/utils/LongMap.java
gdx/src/com/badlogic/gdx/utils/ObjectFloatMap.java
gdx/src/com/badlogic/gdx/utils/ObjectIntMap.java
gdx/src/com/badlogic/gdx/utils/ObjectMap.java
gdx/src/com/badlogic/gdx/utils/ObjectSet.java
gdx/src/com/badlogic/gdx/utils/Queue.java
gdx/src/com/badlogic/gdx/utils/ShortArray.java
gdx/src/com/badlogic/gdx/utils/SortedIntList.java

Pull request for issue https://github.com/libgdx/libgdx/issues/5196

Added .isEmpty() and .nonEmpty() methods to custom LibGDX collections

---

gdx/src/com/badlogic/gdx/utils/Align.java

Just something I stumbled upon.

Removed unnecessary Align. in Align

---

gdx/src/com/badlogic/gdx/graphics/Texture.java

Just thought it'd be nice if we had this.
Text is copied from the badlogicgames.com article

GL20 texture filter types description

---

gdx/src/com/badlogic/gdx/utils/BinaryHeap.java

Contains() method runs in linear time and does not interfere with any other parts of the binary heap, so I believe it would be a useful addition to the collection. I have personally found a use for it in my own game.

Added contains to binary heap

---

CHANGES

Here are the API-Additions forCHANGES which I forgot with the original pull requests (which are already merged...)
See:
https://github.com/libgdx/libgdx/pull/5199
https://github.com/libgdx/libgdx/pull/5260

Added API additions in CHANGES

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtInputTest.java

Maintains an IntSet of pressed keys to clear when the application or browser loses focus.
This is my first (attempted) contribution and pull request so please let me know about any issues or things to improve. I have sent a signed CLA to contact@badlogicgames.com. Thanks!

Fix issue #5134

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/shapebuilders/SphereShapeBuilder.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/MeshBuilderTest.java

It fixes transformed sphere normals and consequetly capsule normals.

fix sphere shape builder normal calculation

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
gdx/src/com/badlogic/gdx/Net.java
gdx/src/com/badlogic/gdx/assets/AssetLoadingTask.java
gdx/src/com/badlogic/gdx/assets/loaders/BitmapFontLoader.java
gdx/src/com/badlogic/gdx/graphics/g2d/DistanceFieldFont.java
gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java
gdx/src/com/badlogic/gdx/graphics/g2d/SpriteCache.java
gdx/src/com/badlogic/gdx/graphics/g3d/attributes/BlendingAttribute.java
gdx/src/com/badlogic/gdx/graphics/g3d/decals/CameraGroupStrategy.java
gdx/src/com/badlogic/gdx/graphics/g3d/environment/DirectionalLight.java
gdx/src/com/badlogic/gdx/graphics/g3d/environment/PointLight.java
gdx/src/com/badlogic/gdx/graphics/g3d/environment/SpotLight.java
gdx/src/com/badlogic/gdx/graphics/g3d/loader/ObjLoader.java
gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleShader.java
gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java
gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java
gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshPartBuilder.java
gdx/src/com/badlogic/gdx/maps/tiled/TmxMapLoader.java
gdx/src/com/badlogic/gdx/math/Intersector.java
gdx/src/com/badlogic/gdx/math/WindowedMean.java
gdx/src/com/badlogic/gdx/utils/I18NBundle.java

Testing on a static code analysis tool gave the some suggestions, decided to make a pr with them.
Mainly improvements on boolean expressions and some list size calls.

Small improvements to the code complexity

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALMusic.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALMusic.java
tests/gdx-tests/src/com/badlogic/gdx/tests/MusicTest.java

fix edge case when seeking close to the end of music. This is only happening with non looping music. I added a loop toggle in tests.

fix #5316 lwjgl music crash seeking to end

---

gdx/src/com/badlogic/gdx/graphics/g2d/PolyBatch.java
gdx/src/com/badlogic/gdx/graphics/g2d/PolygonBatch.java
gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSpriteBatch.java

Usecase being supplying own implementation of PolygonSpriteBatch with something like @NathanSweet's Spine is currently impossible without forking the repo.

Extract PolygonSpriteBatch methods to PolyBatch interface

---

extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics/box2d/World.java
tests/gdx-tests/src/com/badlogic/gdx/tests/Box2DTest.java

Fix for [box2d][gwt] World.getFixtures() missing from sources #5383
- Added missing getFixtures method
- Added a test in Box2DTest

Fix for [box2d][gwt] World.getFixtures() missing from sources #5383

---

gdx/src/com/badlogic/gdx/input/GestureDetector.java
tests/gdx-tests/src/com/badlogic/gdx/tests/GestureDetectorTest.java

It is sometimes useful to use a rect instead of square for this.

Separate width and height for gesture detector

---

gdx/src/com/badlogic/gdx/math/Intersector.java

i couldn't believe this method was missing in the awesome Intersector.

Intersector.intersectSegmentRectangle()

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidZipFileHandle.java

AndroidZipFileHandle.getAssetFileDescriptor() returned a shared AssetFileDescriptor, which is supposed to be closed by the requester, so it's invalidated after it's been used once. The patch returns a new file descriptor each time.
Culprit:
```java
@Override
public AssetFileDescriptor getAssetFileDescriptor() throws IOException {
return assetFd;
}
```
https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidZipFileHandle.java#L57
And you can see in eg AndroidAudio why this is a problem:
```java
/** {@inheritDoc} */
@Override
public Music newMusic (FileHandle file) {
if (soundPool == null) {
throw new GdxRuntimeException("Android audio is not enabled by the application config.");
}
AndroidFileHandle aHandle = …
```

AndroidZipFileHandle returns closed file descriptor

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gdx_backends_gwt.gwt.xml
backends/gdx-backends-gwt/src/com/badlogic/gwtref/GwtReflect.gwt.xml
backends/gdx-backends-gwt/src/com/google/gwt/webgl/WebGL.gwt.xml
extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/box2d-gwt.gwt.xml
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d.gwt.xml
extensions/gdx-controllers/gdx-controllers-gwt/src/com/badlogic/gdx/controllers/controllers-gwt.gwt.xml
extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers.gwt.xml
extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/core/CoreGdxDefinition
extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/GdxDefinition
extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/GdxDefinitionSuperdev
tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/GdxTestsGwt.gwt.xml
tests/gdx-tests/src/com/badlogic/gdx/GdxTests.gwt.xml

According to [this](https://stackoverflow.com/questions/22865648/gwt-module-gwt-xml-xml-validation-warning) Stackoverlfow question these are the new correct urls to the dtd's for the gwt xml files.

Update dtd in gwt.xml files

---

tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtWindowModeTest.java

- Added existing Scene2d Test to GWT test list
- Created new GWT specific Test to Switch window mode from full screen and back in Window Mode in Browser to test issue #5339
Tested both with Firefox (v64), Chrome and Safari.

Added existing Scene2D and new Window Mode to GWT tests list (one of which to test issue #5339)

---

gdx/src/com/badlogic/gdx/math/Intersector.java

this is a replacement for #4966 : 
* simplify array checks
* removed unnecessary code
* improved exeptions messages
* improved javadoc

cleanup intersectRayTriangles

---

backends/gdx-backends-gwt/src/com/badlogic/gwtref/GwtReflect.gwt.xml
tests/gdx-tests-android/assets/data/maps/tiled-objects/test-load-mapobjects.tmx
tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapObjectLoadingTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java

added missing classes to enable reflection with GWT

fix #5469 get tilemap object per type with GWT

---

gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java

Reported by ryuukk_ on IRC, opened the PR because it didn't seem to go anywhere after that and looked valid on first pass.

Remove redundant scissor calculation

---

CHANGES
gdx/src/com/badlogic/gdx/math/MathUtils.java
gdx/test/com/badlogic/gdx/math/MathUtilsTest.java

This is a replacement for #4639 with an additional norm method and only float version of these.

added MathUtils norm and map

---

tests/gdx-tests/.classpath

missing eclipse classpath update in commit 3e5921c33e17f4b4c1c010f995466ae48275509c @Tom-Ski

fix eclipse classpath

---

gdx/src/com/badlogic/gdx/graphics/g3d/ModelInstance.java

I faced with problem when there are many files with animations and need to add them to existed ModelInstance. 
I described the problem in detail here:
https://stackoverflow.com/questions/47092776/libgdx-cant-play-the-animation-on-3d-model

Added the ability to add new animations to an existing ModelInstance

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplication.java
extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java

- Allows generated FreeTypeBitmapFontData to be passed into BitmapFont constructor manually
- Allows overriding of mainLoop() to allow for custom timestep implementations

Updated some method/field visibility

---

extensions/gdx-jnigen/pom.xml
extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/parsing/RobustJavaMethodParser.java
gradle/dependencies.gradle

A retry of #5512. I had to fix some end-of-lines and had to redo a commit.

Upgrade javaparser

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/BuildScriptHelper.java

Fixes https://github.com/libgdx/libgdx/issues/5580

Fix #5580 Missing jcenter repo

---

.travis.yml
gdx/build.gradle

You can see [here](https://travis-ci.com/SimonIT/libgdx/builds/105577057/) that the configuration works. The tests run via `gradlew test`

Unit testing on travis

---

gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java

Cleaned up version of https://github.com/libgdx/libgdx/pull/5374

Particle effects using old format fail meaningfully on GWT

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java

adding usage of the new vibration api on android since sdk 26

---

gdx/jni/Android.mk
gdx/jni/build-ios32.xml
gdx/jni/build-linux32.xml
gdx/jni/build-linux64.xml
gdx/jni/build-macosx64.xml
gdx/jni/build-windows32.xml
gdx/jni/build-windows32home.xml
gdx/jni/build-windows64.xml

Generated files for #5641

---

gdx/src/com/badlogic/gdx/scenes/scene2d/utils/ActorGestureListener.java
tests/gdx-tests/src/com/badlogic/gdx/tests/Scene2dTest.java

PanStop was not passed on from GestureDetector.

Implemented panStop in actor gesture listener

---

gdx/src/com/badlogic/gdx/utils/I18NBundle.java

Final method makes it harder to mock it with Mockito.
The method didn't seem to have any reason to be final.

Made I18NBundle.get non final

---

backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/graphics/MockGraphics.java

I've just read that you don't need an issue for pull requests. Too late, sorry for that. Anyway I hope this code change fixes the problem described in #5818

MockGraphics.getFramesPerSecond should return fps #5818

---

gdx/src/com/badlogic/gdx/utils/LongQueue.java
gdx/test/com/badlogic/gdx/utils/LongQueueTest.java

This adds a LongQueue that works much the same way as the existing Queue class but is specialized to the primitive type. This was done by copying and editing down from the existing Queue class and test.

Add a LongQueue variant

---

CHANGES
gdx/src/com/badlogic/gdx/math/collision/Ray.java

Reverts libgdx/libgdx#5860: needs further discussion.

Revert "#5858 Ray normalise origin vector after set methods"

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/ModelBuilder.java

Tiny PR to fix a copy+paste typo.

Fix sphere part name

---

backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessApplicationLogger.java

This Pull-Request solves Issue #5894

Equalized log outputs of HeadlessApplicationLogger and LwjglApplicationLogger

---

README.md

Add version badges to readme

---

build.xml
extensions/gdx-setup/build.xml

This should fix a couple of issues caused by #5956 until we migrate to Gradle.

Fix Ant script

---

extensions/gdx-box2d/gdx-box2d/pom.xml
extensions/gdx-freetype/pom.xml
extensions/gdx-jnigen/pom.xml

Fix missing change of src to res directory for resources

---

extensions/gdx-controllers/gdx-controllers-gwt/pom.xml
extensions/gdx-controllers/gdx-controllers/pom.xml

Specify res directory for controllers

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglInput.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Input.java

Fixed an index out of bounds error that occurs when you pass 256 into isKeyJustPressed() on Lwjgl3 backend

Iskeyjustpressed index out of bounds on Lwjgl3

---

backends/gdx-backends-gwt/src/com/badlogic/gwtref/gen/ReflectionCacheSourceCreator.java

Replace printing types to standard out through logging with log level info

Use logger instead of printing to standard out

---

gdx/src/com/badlogic/gdx/graphics/g3d/attributes/ColorAttribute.java
gdx/src/com/badlogic/gdx/graphics/g3d/attributes/IntAttribute.java

i checked all the attributes, these one was he only missing.
cull face attribute missing a bit of documentation to help understand what it's used for.

added missing Attribute factory methods and improve doc

---

extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/World.java

hello, i explore gdx source, and on World.java , i see useless code if contactListener is null.
Not a big gain for sure ^^.

box2D World.java contact listener method, dont affect addr if no listener

---

gdx/src/com/badlogic/gdx/graphics/FPSLogger.java

underscores in literals are not supported in -source 1.6
https://libgdx.badlogicgames.com/jenkins/job/libgdx/324/console

Fix jenkins build

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java

Bug is there for like 8 years...
I can easily reproduce it by double clicking screen-lock button on Xiaomi mi4 and mi8.
For some reason when you instantly resume activity that hasn't fully paused then internally android stops trigerring `onDrawFrame` in GL thread what causes deadlock, cos `synch.wait()` needs `notify` from `onDrawFrame`.
It can be solved by executing what we need in GL Thread with `GLSurfaceView#queueEvent`. It doesn't have requirements like usual `onDrawFrame` calls from `GLSurfaceView` (f.e. frame cap, some synchronization etc).
There were multiple PRs that tried to fix this but were dirty hacks that use executors (that may cause pause to be ran from non-gl thread) or used another locking techniques on top of Java synchronized/monitors, that could reason in other …

Fix Android fast pause/resume bug

---

gdx/src/com/badlogic/gdx/math/Intersector.java

The code is adapted from Christer Ericson's Real Time Collision (p. 164):
Note that in the original code e is calculated as `max - center`, thus halfDimensions.
The original code can be found here: https://books.google.com.br/books?id=WGpL6Sk9qNAC&pg=PA164&lpg=PA164#v=onepage&q&f=false

Add method to check if a bounding box and a plane intersect

---

gdx/src/com/badlogic/gdx/utils/FloatArray.java

Fix FloatArray#lastIndexOf

---

extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/OisControllers.java

[OisController] Handle return of methods

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java

Simple autocomplete failure fixed

Fixed AndroidInput isCatchKey()

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNet.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtNet.java
gdx/src/com/badlogic/gdx/Net.java
gdx/src/com/badlogic/gdx/net/HttpStatus.java
gdx/src/com/badlogic/gdx/net/NetJavaImpl.java

Added and documented some more HTTP-Methods
Just to update the existing ones.

Documented HTTP-Methods and added HEAD-Method

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java

Revert "Makes ios-moe generated by gdx-setup.jar work"

---

gdx/jni/gdx2d/stb_image.h

Reverts libgdx/libgdx#6152
iOS build is failing, will have to see why later.

Revert "Update stb_image.h to v2.26"

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextArea.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java
tests/gdx-tests/src/com/badlogic/gdx/tests/TextAreaTest3.java

Also update display when style is changed and expanded test.
See #6133

Fixed TextArea text drawing offset

---

CLA.txt
CONTRIBUTORS

Applying latest branding rule

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java

You guys can surely guess why it's needed :)

Create Pixmap from video element on gwt

---

gdx/src/com/badlogic/gdx/graphics/g2d/Sprite.java

I didn't benchmarked it but it sounds self speaking to me. Not sure it'll improve performance drastically but i think the calls are more consistent now.
This is a replacement for PR #5369

Sprite minor performance improvements

---

backends/gdx-backend-android/.classpath
backends/gdx-backend-robovm/.classpath
tests/gdx-tests-android/.classpath

@NathanSweet i had some classpath issues after fetching jars, i was able to fix them with these changes. However, i'm not sure about these changes because i don't use robovm stuff and i don't have Android device to test, so i can't validate them.

update some eclipse classpath files

---

gdx/src/com/badlogic/gdx/graphics/Mesh.java
gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java

I found some missing corrections in #5925, so I modified for consistency.

Missing correction based on 5925

---

backends/gdx-backends-gwt/.classpath
extensions/gdx-box2d/gdx-box2d-gwt/.classpath
extensions/gdx-box2d/gdx-box2d/.classpath
extensions/gdx-controllers/gdx-controllers-gwt/.classpath
extensions/gdx-controllers/gdx-controllers/.classpath
extensions/gdx-jnigen/.classpath
extensions/gdx-setup/.classpath
tests/gdx-tests-gwt/.classpath
tests/gdx-tests/.classpath

some missing stuff for Eclipse users after #5956 changes.

add missing res folder as source for Eclipse

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/DefaultLwjglInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/DefaultLwjgl3Input.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java
gdx/src/com/badlogic/gdx/Input.java

Adds support for Caps Lock, Print Scr, Scroll Lock, Pause, closes #4739

Add support for Caps Lock, Print Scr, Scroll Lock, Pause

---

gdx/src/com/badlogic/gdx/math/collision/Segment.java

Fixed a small spelling error I came across when reading the documentation.

Fixed spelling error in Segment.java

---

tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/MultipleRenderTargetTest.java

thanks to #6220 it appears that MRTShader had an issue.

fix MultipleRenderTargetTest: MRTShader was inconsistent

---

backends/gdx-backend-android/.classpath
backends/gdx-backend-android/pom.xml
build.xml
extensions/gdx-controllers/gdx-controllers-android/.classpath
extensions/gdx-controllers/gdx-controllers-android/pom.xml
pom.xml
tests/gdx-tests-android/.classpath

Upgraded Android SDK we build against to 30. This will allow support for new features such as Haptics.
Having the android.jar on the repo uploaded by a contributor is not ideal, hopefully https://github.com/libgdx/libgdx/pull/5976 will fix this.

Upgrade Android SDK lib we compile against to 30

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/custom/UIAcceleration.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/custom/UIAccelerometer.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/custom/UIAccelerometerDelegate.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/custom/UIAccelerometerDelegateAdapter.java

Whoops, I didn't expect any comments to be removed in #6368

Readd accidently removed <imports> comments for robovm.

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/core/src/MainClass

Pending from https://github.com/libgdx/libgdx/pull/6341

Use ScreenUtils#clear on Gdx-Setup generated project

---

gdx/src/com/badlogic/gdx/math/FloatCounter.java

At start i just wanted to add toString method on FloatCounter
And i see the reset method,  so im think 'why not poolable' .
Open to remove the implements Poolable, i just need the toString ^^

FloatCounter, add tostring and implement poolable

---

gdx/src/com/badlogic/gdx/graphics/PixmapIO.java
gdx/src/com/badlogic/gdx/math/Frustum.java
gdx/src/com/badlogic/gdx/utils/Array.java

This pull request removes commented code from three files in the `gdx/src/com/badlogic` folder, in order to make these files more neat.

Remove commented code

---

gdx/src/com/badlogic/gdx/net/NetJavaImpl.java

Fixes queuing network tasks if configuration option `maxNetThreads` is set to non-default value (other than MAX_INTEGER).
If non-default value is set then the ThreadPoolExecutor used by NetJavaImpl is created with:
- core pool size to `maxNetThreads` (instead of 0)
- enables `ThreadPoolExecutor#allowCoreThreadTimeOut` to remove core pool threads after the specified timeout
- work queue type `LinkedBlockingQueue` (instead of SynchronousQueue which does not accept any tasks to be queued)
The behavior if `maxNetThreads` is set to default value remain unchanged. Thus this change should not cause any regression.

Fixes #6433: HTTP request gets rejected if configuration option maxNetThreads is set

---

CONTRIBUTORS

I have contributed a few times as seen [here](https://github.com/libgdx/libgdx/pulls?q=is%3Apr+author%3Athechubbypanda+is%3Aclosed), I think that makes me worthy :)

Appended to CONTRIBUTORS

---

build.xml

Seems like this version wasn't adapted after the last releases. Happened here (3ec1d53739f919a4b4690116b4d4cf8803be3b08) as well.

Update gdx version.

---

tests/gdx-tests/src/com/badlogic/gdx/tests/UtfFontTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

Hi, i see test missing in GdxTests lists.
i also add more specials chars in test.

Add UtfFontTest to GdxTests

---

gdx/src/com/badlogic/gdx/utils/Scaling.java

Readd Scaling.contain which was accidently removed in #6391

---

gdx/src/com/badlogic/gdx/utils/AtomicQueue.java
gdx/test/com/badlogic/gdx/utils/AtomicQueueTest.java

In order to improve the test coverage of the code base of libGDX, this pull request is created. 
In this pull request, the following has been done to the file `utils/AtomicQueue`:
- Added the test coverage 
The code coverage has been improved as follows
| File | Class, % | Method, %  | Line, % |
| ------------- |:-------------:|:-----:|:-----:|
| `utils/AtomicQueue` (old)   | 0% | 0% | 0% |
| `utils/AtomicQueue` (new)      | 100% |   100% | 100% |
The changes to AtomicQueuedocumentation are reverted but an artefact is left as I cannot push spaces to git it does not recognize it as any change.

AtomicQueue add test coverage

---

gdx/src/com/badlogic/gdx/utils/FlushablePool.java
gdx/test/com/badlogic/gdx/utils/FlushablePoolTest.java

In order to improve the test coverage of the code base of libGDX, this pull request is created. 
In this pull request, the following has been done to the file `utils/FlushablePool`:
- Added the test coverage 
The code coverage has been improved as follows
| File | Class, % | Method, %  | Line, % |
| ------------- |:-------------:|:-----:|:-----:|
| `utils/FlushablePool` (old)   | 0% | 0% | 0% |
| `utils/FlushablePool` (new)      | 100% |   100% | 100% |
The changes to Align documentation are reverted but an artefact is left as I cannot push spaces to git it does not recognize it as any change.

FlushablePool add test coverage

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/desktop/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/desktop/src/DesktopLauncher
extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java

Update desktop package name to look like other projects (Android, iOS, HTML and core).

Update desktop package name to look like other projects

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSUIViewController.java

iOS Call glViewport on device rotation, fixes #6514

---

extensions/gdx-box2d/gdx-box2d/jni/maven/pom.xml
extensions/gdx-bullet/jni/maven/pom.xml
extensions/gdx-freetype/jni/maven/pom.xml
gdx/jni/maven/pom.xml

Include macosxarm64 libraries in natives-desktop jars

---

tests/gdx-tests/src/com/badlogic/gdx/tests/AssetManagerTest.java

Current AsserManager unit test was covering Bitmapfont, Atlas..
This include a Skin as part of the load
I have regressed test it

Added Skin load in the AsserManager test

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g3d/utils/FirstPersonCameraController.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/MultipleRenderTargetTest.java

```	private int STRAFE_LEFT = Keys.A;
private int STRAFE_RIGHT = Keys.D;
private int FORWARD = Keys.W;
private int BACKWARD = Keys.S;
private int UP = Keys.Q;
private int DOWN = Keys.E;
private float velocity = 5;```
Just put it public to can change it. (I got azerty keyboard) or map it with arrows

FirstPersonCameraController, input keys public to allow mapping changes

---

gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java
gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java

Added some comments about the reason/use behind "lastGlyph" in GlyphLayout and BitmapFont to make the code easier to understand.

Comments added to lastGlyph in GlyphLayout and BitmapFont

---

CHANGES
gdx/src/com/badlogic/gdx/math/Polygon.java

Hi, i think this methods can be usefull.
Its my case, free to close if im solo ^^

Polygon add method getVertex, getNbVertices, getCentroid

---

gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java
tests/gdx-tests/src/com/badlogic/gdx/tests/BitmapFontTest.java

This PR tries to make GlyphLayout a little less intimidating and to make it easier and to reduce the cognitive load working with it.
(This PR also includes changes from https://github.com/libgdx/libgdx/pull/6585 as there will be merge conflicts else)
@NathanSweet @tommyettinger Please check! Thanks!

GlpyhLayout: Cleanup

---

extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/org/jbox2d/dynamics/joints/RopeJoint.java

Applied the Jbox2d fix from #5762, should be ok but haven't tested.

Fixes #5762

---

backends/gdx-backend-headless/build.gradle
backends/gdx-backend-lwjgl3/build.gradle
gradle/dependencies.gradle

* Will have to figure out how to do this better when we do publishing from gradle.

Add gdx-natives to desktop backends for #6369

---

.github/workflows/build-snapshot.yml
.github/workflows/fix-formatting.yml

Checks direct pushes to master for gwt and spotless issues. It fixes also formatting issues automatically in PRs

Improved gha

---

CHANGES
gdx/src/com/badlogic/gdx/math/GeometryUtils.java

Hey again, after work on my issues [#6679](https://github.com/libgdx/libgdx/issues/6679)
I find the answer (polygon p2 muste be clockwise)
I add some methods similar to CCW but for clockWise  (check, ensure)

Geometry utils add

---

extensions/gdx-freetype/README.md

As requested [here](https://github.com/libgdx/libgdx/commit/f369ebb11bab63bd0e26a2a2a05a5813b7b448d2#r63683278) a readme as been added to the freetype extension to detail FreeType version.

Create README.md for FreeType

---

gdx/src/com/badlogic/gdx/Graphics.java

Updated documentation for getDensity() to warn about potentially costly operation

---

extensions/gdx-lwjgl3-angle/src/com/badlogic/gdx/backends/lwjgl3/angle/ANGLELoader.java

See https://github.com/libgdx/gdx-angle-natives/pull/1

Support macos arm64 in ANGLELoader

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtFileHandle.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/files/FileHandle.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/AssetDownloader.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/FileWrapper.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/Preloader.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/PreloaderBundleGenerator.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/widgets/ProgressBar.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/widgets/ResizableWidget.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/widgets/ResizableWidgetCollection.java
backends/gdx-backends-gwt/src/com/badlogic/gwtref/gen/ReflectionCacheSourceCreator.java

I discovered some invalid @throw tags in our gwt sources. By checking the sources I stumbled upon deprecated method usages and replaced them. I cleaned up some other warnings as well
There shouldn't be any functional differences

Some gwt improvements

---

gdx/jni/gdx2d/stb_image.h

See discussion in #6814
Seems to compile [correctly](https://github.com/PokeMMO/libgdx/actions/runs/1971778107) unlike v2.26

Update stb_image.h to v2.27

---

gdx/src/com/badlogic/gdx/net/NetJavaImpl.java

`NetJavaImpl#cancelHttpRequest` cancels pending downloads by canceling the submitted executor service HTTP request task.

Fix #6664: HTTP request cancels the request properly.

---

extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btCollisionObject.java

When this PR got merged https://github.com/libgdx/libgdx/pull/6765  I though swig was going to generate the java code automatically. This PR is to change the java code.

Allow setting null to a bullet body shape

---

gdx/jni/gdx2d/gdx2d.c
gdx/src/com/badlogic/gdx/graphics/glutils/ETC1.java

I didn't test it, I just copy+paste and removed the Android Log calls, the code makes sense because it verify the size of the image before trying to decode it.
Please, test it before merge.
@badlogic 
Closes #6814

Fix vulnerability reported by CVE-2017-0702

---

gdx/jni/gdx2d/stb_image.h

Revert "Update stb_image.h to v2.27"

---

gdx/jni/gdx2d/gdx2d.c
gdx/src/com/badlogic/gdx/graphics/glutils/ETC1.java

Revert "Fix vulnerability reported by CVE-2017-0702"

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java
extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/org/jbox2d/collision/ManifoldPoint.java
gdx/src/com/badlogic/gdx/graphics/g2d/TextureRegion.java

[I](https://media.makeameme.org/created/fills-out-exremely.jpg). [Hate](https://i.redd.it/vqs8v4oht5c51.jpg). [Forms](https://runt-of-the-web.com/wordpress/wp-content/uploads/2017/04/not-my-final-form.jpg).
P.S. Changed "function" to "method" because we're in Java and the rest of libGDX's comments refer to helper methods.

Correct "form" typos

---

gdx/src/com/badlogic/gdx/graphics/glutils/ShapeRenderer.java

void check (ShapeType preferred, ShapeType other, int newVertices)

ShapeRenderer check () method as protected visibility 

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java

fix MeshBuilder with high vertex count

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidSound.java

Fixes https://github.com/libgdx/libgdx/issues/6866

Increase priority of looping sounds

---

gradle/dependencies.gradle

Upgrade spotless to work on jdk16+

---

backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSHaptics.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSHaptics.java

There were a couple of issues on https://github.com/libgdx/libgdx/pull/6274.
Thanks to @Berstanio for finding and reporting them.

Fix to iOS Haptics

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/src/IOSLauncher

Changes to Gdx Setup need to be delayed one version...
I'll merge soon as it affects current Gdx Setup and it's a no risk change.

Remove useHpatics config from gdx-setup template

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SelectBox.java

Currently it is not working as expected as it is unused.

Fixed ScrollPane not using newScrollPane()

---

backends/gdx-backend-robovm-metalangle/build.gradle

For changelogs see here: https://github.com/kakashidinho/metalangle/releases/tag/gles3-0.0.8

Upgrade MetalANGLE to 0.0.8: Fix startup zoom animation

---

gdx/src/com/badlogic/gdx/graphics/g3d/loader/G3dModelLoader.java

line loop primitive type is not part of the current [G3D specification](https://github.com/libgdx/fbx-conv/wiki/Version-0.3-%28draft%29)

fix misleading exception message, fixes #6903

---

backends/gdx-backend-android/build.gradle
publish.gradle

Since AGP 7.1 the tasks aren't needed anymore.
See https://stackoverflow.com/a/42160584

Follow up for #5976 (simplify publishing)

---

CHANGES
extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/FlameMain.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/SavePanel.java
gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleEffectLoader.java

I created a new save panel into Flame tool. Here you can change the JSON output mode and you can enable the pretty mode.

[Flame] Save panel

---

backends/gdx-backend-robovm-metalangle/build.gradle
extensions/gdx-setup/build.gradle
tests/gdx-tests-android/obb.gradle
tests/gdx-tests-lwjgl/build.gradle
tests/gdx-tests-lwjgl3/build.gradle

Minor change, I know. But I want to fix the setup template, and this reared its head.
CLA is in the mail

Fix gradle properties warnings

---

gdx/src/com/badlogic/gdx/math/Intersector.java

We have discuss about merging function that do the same thing with Vector2 or int x , int y with TEttinger & mgsx on Discord.
It make code cleanner (avoid more code lines, avoid the risk to have different behavior between the 2 functions) & less call to x & y of vector2d for a call to one more function.

Remove some duplicate code in Intercector

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java

Fix LwjglGraphics.setupDisplay() choosing the wrong display mode 

---

backends/gdx-backend-robovm-metalangle/generator/JavaCodeGenerator.java
gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java

https://github.com/libgdx/libgdx/commit/209512e20d791f6e28eed09ed209a3f784d45d30
and 
https://github.com/libgdx/libgdx/pull/7147
added CI issues (or made existing issue visible I think, don't know whether libgdx supports compiling with java 7?). 
This PR should fix them.

Two CI fixes

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/build.gradle

Remove 32 bit when building from Gradle as it's not longer supported.

Remove thumbv7 reference

---

build.gradle

Was left in PR #7138
Thank you @ice1000 for noticing.

Remove unnecessary sonatype repository

---

CHANGES

#6394, #6694, #6777, #6838, #6917, #6968, #6979, #7005, #7017, #7073, #7106, #7132, #7145.

Add missing changelog entries

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/build.gradle

Based on https://github.com/libgdx/libgdx/pull/7134/files#r1232921055
/cc @tommyettinger

Revert a change which used to rely on eager evaluation

---

CHANGES
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/Info.plist.xml
tests/gdx-tests-iosrobovm/Info.plist.xml

Depends on https://github.com/libgdx/libgdx/pull/7138

Upgrade min iOS deployment target to 11

---

CHANGES
extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java

Minor change. This is bothering me, as 1.10.1-SNAPSHOT became 1.11.0.
(yeah, my master branch is scuffed - will sort this out if I do something more substantial. Just use merge 6f4366491c2113fe633576cf049eab3212006b0d)

gdx-setup: 1.10.1 -> 1.11.0

---

CHANGES

#7140, #7164, #7172, #7176, #7178, #7179, #7181, #7193, #7196, #7213, #7217, #7239, #7251.

Add missing changelog entries.

---

CHANGES
extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java

fix(gdx-setup): Add jsinterop-annotations as sources dependency

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java

These were missing on latest libGDX release

Set correct versions in DependencyBank

---

CHANGES
gdx/src/com/badlogic/gdx/utils/Timer.java

Fixed Timer#stop, remember time spent stopped and delay tasks when started again.

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/gradle/wrapper/gradle-wrapper.properties
extensions/gdx-setup/src/com/badlogic/gdx/setup/Language.java

Should fix #7300 and #7301.
Just tested the Kotlin project doesn't fail on import.

Upgrade Gdx Setup Gradle and Kotlin versions

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
extensions/gdx-tools/build.gradle

Update GdxSetupUI.java with a new error message and changed build gradle

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java

I have no idea why Github wasn't detecting a branch conflict and has allowed me to merge https://github.com/libgdx/libgdx/pull/7310 with a compilation error. Will merge this immediately.

Fix compilation error

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtAudio.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/webaudio/WebAudioAPIManager.java
tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/client/GwtTestWrapper.java

One thing to notice is, that the `deviceId` is not very readable. But because of the interface we can just return a String. Also, the permission requested by `getUserMedia` is required. Else an empty array gets returned

feat: Change audio device on gwt

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/Info.plist.xml
tests/gdx-tests-iosrobovm/Info.plist.xml

Fixes https://github.com/libgdx/libgdx/issues/7363

Add arm64 capabilities

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/proguard-rules.pro

Fixes https://github.com/libgdx/libgdx/issues/7331

Added Proguard/R8 rules for Scene2d Skins

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java

Fixes https://github.com/libgdx/libgdx/issues/7046

Exceptions occurring on Runnable tasks no longer swallowed

---

gdx/src/com/badlogic/gdx/graphics/Color.java

[GH-7411] New API: Color.set(Color rgb, float a)

---

.github/workflows/build-publish.yml
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglCanvas.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglCursor.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNativesLoader.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Net.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
extensions/gdx-box2d/gdx-box2d/build.gradle
extensions/gdx-bullet/build.gradle
extensions/gdx-freetype/build.gradle
extensions/gdx-lwjgl3-glfw-awt-macos/src/com/badlogic/gdx/backends/lwjgl3/awt/GlfwAWTLoader.java
gdx/build.gradle
gdx/src/com/badlogic/gdx/scenes/scene2d/utils/UIUtils.java
gradle/dependencies.gradle
tests/gdx-tests-lwjgl/src/com/badlogic/gdx/tests/lwjgl/LwjglTestStarter.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/AwtTestLWJGL.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3TestStarter.java

This reverts commit da2495cbf7ab4e12f7c753c13503352544823efa.
Reason: https://github.com/libgdx/libgdx/pull/7275#issuecomment-2298421275

Revert "feat: RISCV native build support (#7275)"

---

.github/workflows/build-publish.yml
.github/workflows/build-pullrequest.yml
.github/workflows/fix-formatting.yml
.github/workflows/gradle-wrapper-validation.yml

This reverts commit 679db22a53193f4fdef94bfa69edf3f42a1869db.

Revert "Update actions (#7457)" Since checkout breaks linux building due to node compatibility

---

.github/workflows/build-publish.yml
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglCanvas.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglCursor.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNativesLoader.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Net.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
extensions/gdx-box2d/gdx-box2d/build.gradle
extensions/gdx-bullet/build.gradle
extensions/gdx-freetype/build.gradle
gdx/build.gradle
gdx/src/com/badlogic/gdx/scenes/scene2d/utils/UIUtils.java
gradle/dependencies.gradle
tests/gdx-tests-lwjgl/src/com/badlogic/gdx/tests/lwjgl/LwjglTestStarter.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/AwtTestLWJGL.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3TestStarter.java

Revert "Revert "feat: RISCV native build support (#7275)" (#7444)"

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java
tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/FragmentTestStarter.java

Support predictive back gesture in fragments

---

CHANGES
extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
gradle/dependencies.gradle

Update MobiVM to 2.3.22

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java

fix: Wayland doesn't support setting window position and icon

---

gdx/src/com/badlogic/gdx/math/Intersector.java
gdx/test/com/badlogic/gdx/math/IntersectorTest.java

fix duplicate points returned in polygon intersection

---

gdx/src/com/badlogic/gdx/utils/LongArray.java
gdx/test/com/badlogic/gdx/utils/LongArrayTest.java

I modified three methods of the LongArray class:
- lastIndexOf took a char argument when it was supposed to be a long since we are working with long arrays ;
- pop() and peekl() did not handle the case of empty arrays so I added this case.
- I then implemented a test class for LongArray, testing all the methods I could (of course I can't test random() for example).
This is a pull request that I have closed and renewed so that it is cleaner.

A few modifications to LongArray and a test class for it (clean)

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/keyboardheight/AndroidXKeyboardHeightProvider.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/keyboardheight/StandardKeyboardHeightProvider.java

Fixes https://github.com/libgdx/libgdx/issues/7537

Defer content view resolve for KeyboardHeightProvider to allow for late setContentView

---

gdx/src/com/badlogic/gdx/utils/Json.java
gdx/test/com/badlogic/gdx/utils/JsonTest.java

Like the writer, the reader can now also be changed

feat: Make reader in Json changeable

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/keyboardheight/AndroidXKeyboardHeightProvider.java

Simple possible fix for the issue mentioned here:
https://github.com/libgdx/libgdx/pull/7553#issuecomment-2599480691

Fix NPE on AndroidXKeyboardHeightProvider#close

---

gdx/src/com/badlogic/gdx/utils/Json.java
gdx/test/com/badlogic/gdx/utils/JsonTest.java

A char is just a number, so it makes sense to be able to deserialise from it

feat: Deserialize char from number

---

gdx/src/com/badlogic/gdx/scenes/scene2d/actions/DelayAction.java
gdx/src/com/badlogic/gdx/scenes/scene2d/actions/FinishableAction.java
gdx/src/com/badlogic/gdx/scenes/scene2d/actions/RepeatAction.java
gdx/src/com/badlogic/gdx/scenes/scene2d/actions/TemporalAction.java

Introduce the FinishableAction interface to allow actions to be manually finished. Updated TemporalAction, RepeatAction, and DelayAction to implement this interface, enabling unified behavior for manual finalization. This facilitates better control over action completion.

Add FinishableAction interface and implement in relevant actions

---

CHANGES
gdx/res/com/badlogic/gdx.gwt.xml
gdx/src/com/badlogic/gdx/maps/objects/PointMapObject.java
gdx/src/com/badlogic/gdx/maps/tiled/BaseTmjMapLoader.java
gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
gdx/src/com/badlogic/gdx/maps/tiled/TmjMapLoader.java
tests/gdx-tests-android/assets/data/maps/tiled-objects/test-load-mapobjects.tmj
tests/gdx-tests-android/assets/data/maps/tiled-objects/test-load-mapobjects.tmx
tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapJsonObjectLoadingTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapObjectLoadingTest.java

Since there has been no activity from the original committer in over a year.
I pulled his PR, rebased and then added the necessary modifications to support it with the new json format as well as added the Point Object to the JsonObject test. (also one tiny parsing fix in the TMJLoader)
Other than that. This is the same PR as seen here #6384.
Once this is merged, we can close the old one.

Added Point Object Support in Tiled. Replacement for PR(#6384)

---

.github/labeler.yml
.github/workflows/labeler.yml

We get a little lazy sometimes with the labels and the PRs, so I think this might come in handy.
I have no idea if this will actually work. So any input is appreciated

Introduce Labeler for Pull Request labeling

---

.github/labeler.yml

Hopefully that fixes everything

ci: Fix labeler typos

---

gdx/src/com/badlogic/gdx/utils/JsonValue.java
gdx/test/com/badlogic/gdx/utils/JsonValueTest.java

I found these necessary when converting JSON to different JSON.

Add JsonValue copy constructor and setChild methods

---

.github/workflows/build-publish.yml
.github/workflows/build-pullrequest.yml

Ubuntu 20.04 runners aren't available anymore
actions/runner-images#11101

ci: Update to Ubuntu 22.04 runner

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidHaptics.java

Tested with `VibratorTest` on an Android 15 Pixel 6 device.

Replace Android Vibrator deprecated methods

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidMusic.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/ZipResourceFile.java

Removes remaining few instances of `e.printStackTrace` found on Android backend plus some other minor improvements.

Logging and other minor code improvements to Android classes

---

CHANGES
gdx/src/com/badlogic/gdx/utils/JsonValue.java

Added JsonValue#toJson that takes a Writer.

---

backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/bindings/metalangle/MGLKViewControllerDelegate.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/bindings/metalangle/MGLKViewDelegate.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/custom/UIAccelerometerDelegate.java
gradle/dependencies.gradle
publish.gradle

Update works and libgdx can compile with java 21 without problems.

Update spotless gradle plugin version to let libgdx compila with java 21

---

extensions/gdx-freetype/build.gradle

Update freetype to v2.13.3

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java

Should fix: https://github.com/libgdx/libgdx/issues/7617

BUGFIX: Prevents crashes when calculating soft buttons bar height.

---

gdx/src/com/badlogic/gdx/utils/async/AsyncExecutor.java

fix misspellings in AsyncExecutor.java

---

gdx/src/com/badlogic/gdx/graphics/VertexAttribute.java

VAO byte calculation add support for int and uint;
