libgdx/libgdx

- gdx/src/com/badlogic/gdx/Game.java
Sometimes it would be nice to be able to switch a screen without `Game` automatically calling `hide()` and `show()`. That's only possible by extending Game currently and overriding the method. However, this option is also not available, because the field is `private` and the extending class isn't able to set it.
> Protected Screen in Game

- gdx/src/com/badlogic/gdx/scenes/scene2d/actions/MoveToAction.java
The alignment must be used to get the starting position of the actor
> Fix MoveToAction with alignment

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Dialog.java
One of the Dialog constructors didn't call `setSkin()` on the Table superclass, resulting in the Table's `skin` property being `null`.
See https://github.com/libgdx/libgdx/issues/2727
> Dialog constructor didn't call setSkin() on Table superclass

- gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java
While using BitmapFont I've faced issue that sometimes fonts have too big line height, which makes drawn multiline text a bit ugly. #setLineHeight method gives an easy way to change it, e.g. make smaller, to have a more pretty text drawing result. This could be helpful when generating several fonts from one font file using gdx-freetype extension.
Sorry for any inconveniences I've not a git expert, this is the corrected PR for the same [old PR](https://github.com/libgdx/libgdx/pull/2695)
> Adding ability to set line height for BitmapFontData

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TextureUnpacker.java
The width and height are in the wrong order when creating the BufferedImage when the region is rotated.
> Fix TextureUnpacker bug when regions are rotated in atlas

- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java
Fixed up struct accessors after accessors were renamed in RoboVM's cocoatouch bindings. Also added logging of whether the app is running in 32-bit or 64-bit mode. (fixes #2734).
> Fixed up struct accessors after accessors were renamed in RoboVM's cocoatouch bindings

- gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFontCache.java
This is usefull when using different colors in the BitmapFontCache ; is you want to fade he text, you need to change alpha and not RGB. The other functions don't do that.
I did not change the draw method of BitmapFontCache to use this instead of setColors because this would make a (small) API change. Just tell me if you would prefer the draw method to only update the alpha part (base don alphaModulation parameter) and I will add the commit.
> Add the ability to set alpha component to BitmapFontCache keeping RGB

- extensions/gdx-freetype/jni/com.badlogic.gdx.graphics.g2d.freetype.FreeType.cpp
- extensions/gdx-freetype/jni/com.badlogic.gdx.graphics.g2d.freetype.FreeType.h
- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeType.java
- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
This is a PR for previously added enhancement by @Doccrazy [PR 2191](https://github.com/libgdx/libgdx/pull/2191). Created to speed up the integration of such an awesome feature.
This PR contains my commit - minor fixing of performance, based on comments from @badlogic and @MobiDevelop (I've compared the font generation in my game and got average ~2.2 seconds instead of ~2.7 without this fixes for 5 font generations on my machine, so it might not be so bad).
However, please review my changes  thoroughly.
> Add outline and shadow rendering to gdx-freetype [Updated]

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/math/Matrix4.java
- gdx/src/com/badlogic/gdx/math/Matrix4.java
Just add the equivalent of glFrustrum to create off-center projection matrix (usefull when you want to use a 3D element in a 2D UI without changing the viewport => you create an off centered 3D view).
There are also a few formatter changes. I checked and I use the libGdx formatter. Seems like previous commit were not formatted right or I missed something.
> Add off-center projection to Matrix4

- .gitignore
“out/”, “classes/” and "gen-external-apklibs/" are generated in Intellij IDEA ,maven and android-maven-plugin environment.
> Add out/, classes/, gen-external-apklibs/ to .gitignore

- extensions/gdx-box2d/gdx-box2d/jni/com.badlogic.gdx.physics.box2d.Body.cpp
- extensions/gdx-box2d/gdx-box2d/jni/com.badlogic.gdx.physics.box2d.Body.h
- extensions/gdx-box2d/gdx-box2d/jni/com.badlogic.gdx.physics.box2d.World.cpp
- extensions/gdx-box2d/gdx-box2d/jni/com.badlogic.gdx.physics.box2d.World.h
- extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Body.java
- extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/World.java
This fixes 2 scenarios mentioned in #2750:
1. EndContact was not called when the fixture destroyed
2. EndContact was not called when the body set to inactive
Also Fixture user data was not set to null as done for Body user data when fixture destroyed
> gdx-box2d: fix for #2750 - EndContact does not called

- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
Adds access to the height and width of a TMX Map object.
I believe these were previously unavailable.
> Height and width properties on the map objects

- gdx/src/com/badlogic/gdx/math/Vector3.java
If I understand the function right, the purpose of this function is to limit the len of the vector to the given limit, which is not what it does right now.
For the time being, the code is:
```java
return limit2(limit * limit);
```
which is not right since scaling factor should be:
```java
vector * limit / len
```
which is not the same as:
```java
vector * (limit * limit) / (len * len) // equivalent of current code
```
This PR fix this (if I'm rightly understanding the expected behavior, of course)
> Fix limit function in Vector3

- tests/gdx-tests-android/project.properties
Since gdx-pay is an external extension I think that these dependencies do not belong here.
> Removed gdx-pay dependencies.

- gdx/src/com/badlogic/gdx/graphics/glutils/KTXTextureData.java
In KTX files, you can set a flag for mipmap generation at load time (see https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/#2.11). You get this type of file when using the --automipmap from the toktx tools for example.
This was incorrectly processed by the current implementation, resulting with empty texture (since numberOfMipmapLevels  = 0 means "please generate mipmaps at load time", and not "there are no mip levels"). This few lines fix this.
> Fix automipmap for KTX files

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationConfiguration.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
Extremely minor, but I need the first for a small project and i've noted a few others asked about it over time too.
The first allows for showing the page behind the canvas, the second is just a different way of transparency. They still default to false, as they affect performance, but with this we have the option if we need them. 
I understand HTML5 isn't exactly the chief target of LibGDX, but I for one would like to do some fancy background things in the HTML5 side of my game :)
> added alpha and premultiplied alpha config values to GWT backend

- extensions/gdx-setup/src/com/badlogic/gdx/setup/Dependency.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtension.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtensionsDialog.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
As discussed yesterday per #2822 setup app required some sort of way to separate third party extensions from main extensions in a different dialog. The other part was for list of third party extensions to be read from an XML file that can be later modified with pull requests. Lastly it was needed to make sure it is clear for user that third party extensions are not maintained by libgdx team.
This is a bit of a big change, so I it probably requires to take a look on it in depth, to test it, and make sure all is correct and the way it should be before this can be considered to be merged. I do not expect it to be merged right away of course.
Would love comments! Maybe some text changes?
Notes / potential issues:
1) The list is currently does not use scroll pane, because at this moment there …
> Third party extensions to be read from XML file (gdx-setup)

- gdx/src/com/badlogic/gdx/math/MathUtils.java
This PR doesn't change any code behaviour.
Motivation: I'm using IntelliJ, and I'm rather pedantic regarding code inspection warnings, especially if they are "live" (always active, shown as yellow marker in editor). The warning itself can be very helpful to catch typos, but this PR removes false warnings created by code such as:
```
int y = MathUtils.floor(bounds.min.y);
```
> IntelliJ code inspection: avoid false warnings.

- gdx/src/com/badlogic/gdx/net/NetJavaImpl.java
In case a HttpResponse does not contain any content, using `HttpResponse.getResultAsString()` will result in a NullPointerException:
java.lang.NullPointerException
at java.io.Reader.<init>(Reader.java:78)
at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
at com.badlogic.gdx.utils.StreamUtils.copyStreamToString(StreamUtils.java:74)
at com.badlogic.gdx.net.NetJavaImpl$HttpClientResponse.getResultAsString(NetJavaImpl.java:75)
This PR adds a nullcheck to `HttpResponse.getResultAsString()` and returns `""` instead.
> Fixed a NPE in HttpResponse.getResultAsString()

- CHANGES
- extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers/Controllers.java
Currently, the only way of removing a previously added `ControllerListener` is by **holding a reference** to that instance. More often than not that is either impractical or, having it accessible, implies a violation of the architecture or forces to bend classes' responsibilities.
I have noticed that the `ControllerManager` interface defines a `clearListeners` method, which is the only one not accessible through a static method on the `Controllers` class. Was there a reason why this one was left behind?
Having this publicly accessible would be pretty handy.
> Expose clearListeners method on ControllerManager

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/GridPacker.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/ImageProcessor.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/MaxRectsPacker.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePackerFileProcessor.java
Added setting to run texture packer in silent mode that doesn't output information about packing progress. This may be useful for tools that uses texture packer from code and doesn't want to output progress information.
> Added TexturePacker silent mode

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SplitPane.java
SplitPane handle does not use parentAlpha while drawing.
When used in window with fade out animation handle stays with alpha == 1, like here:
This PR fixes that.
> Fixed SplitPane handle drawing

- gdx/src/com/badlogic/gdx/utils/TimSort.java
This pull request adds an additional check to search the invariant for the last 4 runs in the
runLength array to shore up an invariant that was not true for sufficiently large array sizes.
Refer to #2877 to get the gist of the reasoning behind the change. The source used to derive the implementation uses an Apache 2 licence for the test suite (see https://github.com/abstools/java-timsort-bug/blob/master/LICENSE), so, from what I can see, the proposed fix is also licensed in the same manner by the same party (due to the different places this invariant would need to be fixed to be universal, such as AOSP).
> Fix TimSort runLength

- CHANGES
- gdx/src/com/badlogic/gdx/graphics/glutils/ShapeRenderer.java
Already implemented by ImmediateModeRenderer20, just not exposed through the ShapeRenderer API.
> ShapeRenderer: allow use of custom shader

- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffect.java
- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java
- tests/gdx-tests-android/assets/data/singleTextureAllAdditive.p
- tests/gdx-tests/src/com/badlogic/gdx/tests/ParticleEmittersTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
In my game I have a layer with many small ParticleEffects, all using the same Texture from a TextureAtlas, and all using pre-multiplied alpha. When this layer is drawn, it results in many unnecessary flushes of the SpriteBatch. Even if a single ParticleEffect is drawn, it results in a draw call for every ParticleEmitter it contains.
This pull request adds an option to ParticleEmitter that allows it to skip the step of returning the SpriteBatch's blend function to the default, which causes a flush whenever a ParticleEmitter is additive or has pre-multiplied alpha. The option defaults to the current behavior, so it will not affect current projects. The Javadoc clearly warns that the programmer must manually set the blend function back to the default if necessary.
I also added a convenience …
> Add option to skip ParticleEmitter's blendfunc clean-up to reduce Batch flushes

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java
Augmented the **TexturePacker.isModified** method with the inclusion of a **TexturePacker.Settings** instance reference, which allows to retrieve the currently configured extension string for the atlas files.
Changed both overloads of the method **TexturePacker.processIfModified** to reflect that change (defaulting to the standard settings if none are passed by the user).
With this change the input string (raw assets folder to pack) will be checked against the generated atlas file that the packer produces. If a change is detected between the **last modified date** of the raw assets folder and the current (if existing) atlas file, the packing process should be triggered.
> Fix conditional packing  for issue #2883

- gdx/src/com/badlogic/gdx.gwt.xml
> [ERROR] Line 19: No source code is available for type com.badlogic.gdx.net.HttpRequestBuilder; did you forget to inherit a required module?
That's what I get when I try to run my game via GWT. This should fix that problem.
> Added HttpRequestBuilder to gdx.gwt.xml

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL30.java
Separated from #2897. Overrides all uses of EXTFramebufferObject with the GL3 core functions.
> Lwjgl30 override EXTFramebufferObject usage

- gdx/src/com/badlogic/gdx/math/EarClippingTriangulator.java
Bug: When vertices array describes multiple polygons then only first polygon is triangulated correctly; offset of all following polygons is ignored and function returns random triangles.
Fix:
1) Added offset when initializing indices
2) Added offset when computing winding
> Fixed bug in EarClippingTriangulator where vertex offset is ignored when computing triangles

- CHANGES
- CONTRIBUTORS
- gdx/src/com/badlogic/gdx/assets/loaders/resolvers/ClasspathFileHandleResolver
Case: The resolver will be useful for libraries that use Libgdx as a backend and have default assets packed in the library in case a desired asset can't be found to draw/play/etc. 
The InternalFileHandleResolver does not suffice, as it prioritizes looking in the internal storage first. From the documentation: "If a file can't be found on the internal storage, the file module falls back to searching the file on the classpath". In my case ClasspathFileHandleResolver will be used because we do not want to potentially use assets with the same name that the user has placed in the assets folder. 
Example: Have a "Missing texture" texture drawn when developer using my library want to draw a texture from a filehandle that does not exist. The "Missing texture" could in this case be located at …
> Added FilehandleResolver for classpaths

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
- gdx/src/com/badlogic/gdx/graphics/GL20.java
- gdx/src/com/badlogic/gdx/graphics/GL30.java
- gdx/src/com/badlogic/gdx/graphics/Mesh.java
- gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSpriteBatch.java
- gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java
- gdx/src/com/badlogic/gdx/graphics/g3d/decals/DecalBatch.java
- gdx/src/com/badlogic/gdx/graphics/glutils/VertexArray.java
- gdx/src/com/badlogic/gdx/graphics/glutils/VertexBufferObjectWithVAO.java
In core profiles glGetString(GL_EXTENSIONS) is deprecated, so a new mechanism is used to test for extensions.
In core profiles VAOs are mandatory, and VertexAttribPointer cannot use
client memory, so I introduced a parallel VertexData implementation,
VertexBufferObjectWithVAO, that is used when gl3 is available.
I have tested on my windows desktop. This fixes the behavior of SpriteBatch and works with my plain Meshes and Shaders. Everything appears to be working now in the core profile.
I have not tested on mac or mobile.
> Allow libgdx to function under 3.2 core profile on desktop.

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java
`onlyFontChars` behaviour was not consistent. It did allow those chars to be pasted, but not written.
For reference, I was using this for emulating iOS text field behaviour when writing letters like ě. Those are written by pressing `e` and `ˇ`. Natively, those chars are combined when rendering (Unicode standard). However, libGDX does not support such combining, so I have to listen for input (setTextFieldListener -> keyTyped) and then combine the chars manually. Problem is, that `ˇ` is not written in the TextField text, because my font does not contain it, so I can not combine it easily.
> Fix TextField not respecting onlyFontChars

- extensions/gdx-setup/src/com/badlogic/gdx/setup/Dependency.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtension.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtensionsDialog.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
Now `gwtInherit` field can be defined in `extensions.xml`. If defined, `inherits name='...'` will be added to `GwtDefinition.gwt.xml` and `GdxDefinitionSuperdev.gwt`
Dependency class now has `gwtInherits` field, so I was able to remove `gwtInheritances` map from `DepedencyBank`. For official extensions gwt inherits now is defined in `ProjectDependency` enum.
Also fixes bug in 3rd party extension dialog. `MouseListener` was used for listening for table changes, where `TableModelListener` should be used. When using `MouseListener` some events may be not reported, like here: [GIF](https://cloud.githubusercontent.com/assets/4594081/6644029/3de7c6b2-c9b1-11e4-926e-167bb160cd4b.gif) (should print random int when check box was changed)
Because that listener is used for updating dependency list, …
> gdx-setup: GWT inheritance support for 3rd party extensions

- gdx/src/com/badlogic/gdx/maps/tiled/AtlasTmxMapLoader.java
- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
- gdx/src/com/badlogic/gdx/maps/tiled/TmxMapLoader.java
As referenced in issue #2929 .
We ourselves have run into this usecase as well, as we use Tiled for creating meta information for maps.
Now with added documentation on usecase.
> Added support for not flipping Y values in a TMX map.

- gdx/src/com/badlogic/gdx/math/GeometryUtils.java
> fix #2974 GeometryUtils#polygonArea(float[], int, int)

- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/GradientPanel.java
Reproduce steps...
1. Duplicate an emitter
2. Add a new marker to emitter 2's Tint timeline or drag an existing marker to a new spot on the timeline
3. Select emitter 1
4. Select emitter 2 (and see the marker is gone)
> Fix 2D Particle Editor bug where the tint timeline does not update the emitter

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Table.java
I don't know why this method is missing from the Table class, but I have run into multiple situations where it would have been useful. This method simply returns the private Skin field that has always been present in the Table class.
> Added getSkin() method to Table

- backends/gdx-backends-gwt/src/com/badlogic/gwtref/GwtReflect.gwt.xml
- backends/gdx-backends-gwt/src/com/badlogic/gwtref/gen/ReflectionCacheSourceCreator.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleEffectLoader.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/ResourceData.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/particles.vertex.glsl
On GWT, the particle 3D loader did not work since ResourceData.AssetData class was not feed to the ReflectionCache, other classes needed to be added manually, and there was missing precision specification for GLSL (Firefox rejected it).
This PR fixes this by:
- forcing inclusion of explicitely declared reflection includes (i.e. they don't need to be used by an accesible class, which is the case here since AssetData is only used in generics) - Note that this will only work when the gdx.reflect.include property is set to a class (and not a package)
- adding the needed includes to the reflection cache spec of GWT backend module definition
- adding the precision marker expected in GLSL
- adding an explicit message when loading fail due to absolute path (used by default in Flame) - Note: when …
> Fix 3D Particles for GWT : loader and GLSL bug

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/gradle/wrapper/gradle-wrapper.properties
Quick change that increases security by a whole lot. Since gradle is also served over SSL/TLS I don't see a point of using HTTP.
> Update gradle distribution to use SSL/TLS

- gdx/src/com/badlogic/gdx/graphics/g3d/utils/CameraInputController.java
Fix a small bug where the camera input controller will not report the touchDown event as handled whereas it is (this is always the case when there is no activation key defined).
> Fix minor bug in CameraInputController

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SelectBox.java
This can be reproduced changing the fontColor in the SelecBoxStyle of the test uiskin.json, to something different from white, and launching the UITest. The text in the SelectBox will stay white.
This PR passes the font color as the default color for the GlyphLayout.
> SelectBox ignores fontColor in style

- gdx/src/com/badlogic/gdx/graphics/glutils/VertexBufferObjectWithVAO.java
Move "bindAttributes" out of the condition in "bind" function.
This Pull Request is linked to this issue: https://github.com/libgdx/libgdx/issues/3050
> Correct error in VertexBufferObjectWithVAO

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SelectBox.java
- gdx/src/com/badlogic/gdx/scenes/scene2d/utils/Disableable.java
A small addition to the `Disableable` interface. All but a single implementation of this class had this anyway, but the interface is not that useful without that method I think.
In my case I wanted to have a generic method that sets the colour of actors to `Colour.GRAY` when an actor is disabled, and to `Color.WHITE` when it's not. I was searching and found that neat interface for exactly that usecase. However, without the getter I would have to do lots of `instanceof` tests.
> Added isDisabled() to Disableable.

- CHANGES
- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/EffectPanel.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java
This is for ease of use when making many variations of a ParticleEffect, or when reusing particular ParticleEmitters in several different ParticleEffects. The Merge button opens a particle file and adds all its emitters to the ParticleEffect that is already loaded.
> Add merge button to ParticleEditor

- CHANGES
- extensions/gdx-tools/src/com/badlogic/gdx/tiledmappacker/TiledMapPacker.java
- gdx/src/com/badlogic/gdx/maps/tiled/tiles/AnimatedTiledMapTile.java
Adds AnimatedTiledMapTile processing to TiledMapPacker when using the option --strip-unused, fixing #3080.
> Fix for issue #3080 Adds animated tile processing to TiledMapPacker 

- gdx/src/com/badlogic/gdx.gwt.xml
Since classpath file handle are supported in GWT, I think this resolver should be enabled as well.
It is usefull when you have resources in your src folders (in my case, string localization for a library project used by other projects) and declare them through ```<extend-configuration-property name="gdx.files.classpath" value=".../res/strings.properties" />``` for example. Then you can use them through ```ClasspathFileHandleResolver``` or ```Gdx.files.classpath("strings.properties")``` on all backends.
> Enable classpath file handle resolver to GWT backend

- gdx/src/com/badlogic/gdx/assets/loaders/SkinLoader.java
Sometimes I preload handy resources in skins so they're available to build the rest of the skin, using SkinParameter. Current implementation forces me to pass a textureAtlasPath, but I don't really need to, so these changes make possible to pass only resources in the SkinParameter.
> More flexibility in SkinLoader

- gdx/src/com/badlogic/gdx/net/NetJavaImpl.java
Added the same check as in `getResultAsString()`, for the same reason...
java.lang.NullPointerException
at com.badlogic.gdx.utils.StreamUtils.copyStream(StreamUtils.java:49)
at com.badlogic.gdx.utils.StreamUtils.copyStream(StreamUtils.java:36)
at com.badlogic.gdx.utils.StreamUtils.copyStreamToByteArray(StreamUtils.java:91)
at com.badlogic.gdx.net.NetJavaImpl$HttpClientResponse.getResult(NetJavaImpl.java:61)
> Fixed a NPE.

- gdx/src/com/badlogic/gdx/files/FileHandle.java
There are no such checks.
To be sure, I've tried both `FileHandle.sibling(...)` as well as `FileHandle.child(...)` with internal, non-existant files and no exceptions were thrown.
> Corrected FileHandle JavaDoc

- CHANGES
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidNet.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessNet.java
- backends/gdx-backend-jglfw/src/com/badlogic/gdx/backends/jglfw/JglfwNet.java
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNet.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSNet.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtNet.java
- gdx/src/com/badlogic/gdx/Net.java
- gdx/src/com/badlogic/gdx/net/NetJavaServerSocketImpl.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/net/PingPongSocketExample.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
I thought this might be useful for gdx-based applications that runs as a server on multi-domain platforms (i.e. game servers).
Added an optional argument "hostname" to method Net.newServerSocket to allow specific domain / ip address binding, it maps 1:1 to Java.net binding interface.
(Re-opening from #3040 because I made a mess. Sorry about that.)
> Bind server socket to a specific hostname or ip address (v2)

- gdx/src/com/badlogic/gdx/math/Polyline.java
no idea why this method was missing, someone probably just forgot it
> added Polyline#setVertices(float[])

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFragmentApplication.java
I have AndroidFragmentApplication that is attached into another fragment and dispose() method is never called.
The issue was that in nested fragments isRemoving() method always returns false.
The solution was to invoke isRemoving() on parent fragment that is attached directly to activity
> Bugfix: dispose never called in nested fragment

- gdx/src/com/badlogic/gdx/utils/Bits.java
I was working on ashley and found a couple of bugs in the `Bits` class. First, `length()` returns the index of the last bit set, rather than the length. Second, `xor(Bits)` clear bits that exceed the argument's internal buffer size. I put together some small code snippets to demonstrate this:
```java
// length() bug
Bits bits = new Bits();
bits.set(0);
System.out.println(bits.length()); // 0
// xor() bug
Bits first = new Bits();
first.set(200);
Bits second = new Bits();
first.xor(second);
System.out.println(first.get(200)); // false
```
This pull request fixes these issues.
> Fix bugs in Bits

- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
Updating overlap2d-runtime version to 0.1.0 to be compatible with libgdx 1.6.2 
Changes in runtime include:
1) BitmapFonts refactorings
2) box2dlights setCombinedMatrix(Matrix) method deprication
3) version updates in gradle
> overlap2d-runtime to support libgdx 1.6.2

- README.md
Or is that somehow intentional?
> Fix robovm logo being stretched unproportionally

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Button.java
This adds option to disable programmatic change events for Button, currently there is no way to change checked state without firing ChangeEvent. By default programmatic change events are enabled so it does not affect existing checkboxes.
> Added method to disable programmatic change events in Button

- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
Made sample location for Android SDK consistent with OS directory structure.
> sdkLocationText uses correct directory structure based on OS name.

- gdx/src/com/badlogic/gdx/graphics/g2d/NinePatch.java
Stumbled upon an easy-to-fix but hard-to-spot bug in NinePatch code. There is a public method *scale(float, float)* which multiplies all corner and side patches, and padding by given factor. If there is no padding set for this NinePatch, however, all padding numbers are ruined as they get multiplied by *scaleX* and *scaleY* (floating-point numbers), then automatically truncated by Java (as class fields are declared as integers). Moreover, by essentially enabling padding for a NinePatch, its left/right/top/bottom sections and their dimensions are always ignored...
Unless someone has a really good reason why we might want to mutliply "magic number" minus-one by an arbitrary floating-point scale factor, then let Java truncate the outcome, it is better to fix this asap.
> Do not scale NinePatch padding if not set

- gdx/src/com/badlogic/gdx/scenes/scene2d/actions/ParallelAction.java
This is fix for issue found in Actions.parallel. Issue may cause crash or malfunction. 
In some cases, when actions to not track it when they are finished and such action is used together with actions that works longer than just one execution (eg. Actions.moveTo(x, y, 1f)). 
Than Actions.parallel() will not care if this small Actions was finished or not, and run it multiple times or even crashes is some cases.
When you have code like this: 
Actions.parallel( Actions.moveTo(x, y, 1f), Actions.addAction( Actions.moveTo(x2, y2, 1f), someActor)); then libgdx crahses.
Actions.addAction is executed several times. "someActor" has several references to same action, when first action is remover, all other have null pointer inside and crashes.
> Fix problem with running already finished actions by ParallelAction.

- gdx/src/com/badlogic/gdx/scenes/scene2d/utils/DragAndDrop.java
Before this commit, `DragAndDrop` fired events just a bit out of order when dragging a Source object across two registered Target objects. 
Formerly, as we drug a source over two targets A then B these firings occurred in this order(hyphens separate the frames):
* targetA:drag()
* -----
* targetA:drag()
* -----                 <--- transition occurs here
* targetB:drag()
* targetA:reset()
* -----
* targetB:drag()
* ...so on
Though probably not a big deal, this could have been a problem if `reset` contained any state regarding the entire drag and drop operation. For example, `reset` may want to turn off a temporary visual indicator which showed where the dragged item would fall amongst a set of sorted targets (drag-sorting a list). But it doesn't want this indicator to turn off when …
> DragAndDrop event firing order fix

- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
Sorry, the version you just merged didn't work with HTML5. This release is just a fix.
> gdx-setup: Updated libgdx-utils 3rd party extension (again)

- gdx/src/com/badlogic/gdx/net/NetJavaImpl.java
- gdx/src/com/badlogic/gdx/utils/Timer.java
This pull request makes all worker threads daemon, so they can't prevent termination of the application if the main thread unexpectedly exits. Fixes #3240, fixes #3226.
> Make all worker threads daemon, so they can't prevent termination

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidAudio.java
`musics.get(i).wasPlaying` is a boolean value, no need to use `== true` to check it.
> Remove unnecessary check for boolean

- gdx/src/com/badlogic/gdx/scenes/scene2d/utils/Selection.java
Selection.getLastSelected() throws an exception in selection.first(), when called on an empty selection set.
> Avoid IllegalStateException if called on empty selection set.

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
TextField and TextArea cursor doesn't blink in GWT due to this:
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java#L397
```java
if (!Gdx.graphics.isContinuousRendering()) {
cursorOn = true;
return;
}
```
and `Gdx.graphics.isContinuousRendering()` returning always `false` in GWT backend, so I changed it to return true, which solves this problem and also makes more sense, since other backends starts with continuous rendering set to true.
> TextField's cursor doesn't blink in GWT backend

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/reflect/ClassReflection.java
- backends/gdx-backends-gwt/src/com/badlogic/gwtref/client/Type.java
- gdx/src/com/badlogic/gdx/utils/reflect/ClassReflection.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/AnnotationTest.java
This PR adds support for getAnnotation() / getAnnotations() which take into account @Inherited annotations in super classes.
Note: The GWT backend collects this information at call time, which means this is a relatively costly operation. It might be possible to do this during construction of the reflection cache, but I'm not sure if this is worth the overhead (it would increase size of the cache even more).
> ClassReflection: added getAnnotation(), getAnnotations().

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidPreferences.java
Accordingly to [Android ref](http://developer.android.com/reference/android/content/SharedPreferences.Editor.html), we should prefer `apply()` over `commit()`. `apply()` will save the state to the object synchronously, but will start an async task to save the object to the disk, while `commit()` will do both synchronously, where it can block if done in the main thread.
> Make Android preferences unblocking

- gdx/src/com/badlogic/gdx/math/Circle.java
`contains(Circle)` would claim that a bigger circle can be contained by a smaller circle, which is wrong. Fixes an assert in IntersectorTest from #3296.
> Fix Circle.contains

- gdx/src/com/badlogic/gdx/math/GridPoint2.java
- gdx/src/com/badlogic/gdx/math/GridPoint3.java
This was more of just a really simple quick fix so that:
* Serialization libraries don't choke on GridPoints since they previously did not implement `Serializable`
* The coordinates of a GridPoint can easily be accessed for debugging purposes with a simple `toString()`
And of course, the Vector class already has both of these anyways.
> Make GridPoint classes implement Serializable and provide toString()

- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
- gdx/src/com/badlogic/gdx/maps/tiled/objects/TiledMapTileMapObject.java
- tests/gdx-tests-android/assets/data/maps/tiled-objects/test-load-mapobjects.tmx
- tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapObjectLoadingTest.java
TilEd is able to have animated tiles and create objects from those. The current implementation in libgdx can only handle single texture regions via `TextureMapObject` though.
This PR adds a new kind of `MapObject` in the `tiled` package. The `TmxMapLoader` will now create `TiledMapTileMapObjects` instead of `TextureMapObjects`. These reference either a `StaticTiledMapTile` or an `AnimatedTiledMapTile`.
For compatibility reasons, it also `extends TextureMapObject` and should work exactly the same.
*This is the very first PR that adds this. There hasn't been any PR like this before.*
> Added TiledMapTileMapObject

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java
I'm working on a 2d game and found that the TexturePacker class has a very handy method which allows you to specify default settings in addition to the per-directory settings.
Unfortunately this argument is not supported via CLI so I had to create a wrapper class for my current project but felt like TexturePacker should support it by default as the method is already present.
> TexturePacker: added [settingsFileName] argument

- CHANGES
- gdx/src/com/badlogic/gdx.gwt.xml
The title says it all. Fixes https://github.com/libgdx/libgdx/issues/3313
Sorry about that. I keep assuming that all libgdx classes would be added automatically there for some unknown reason.
> Fixed GWT by adding TiledMapTileMapObject.

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java
The paste method now takes into account that the selected text is deleted before the pasted text is inserted.
> Fix paste method in TextField. Fixes #3337.

- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
Added VisRuntime library to 3rd party extensions. This library is required to load projects exported from [VisEditor](https://github.com/kotcrab/VisEditor).
> Added VisRuntime extension

- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/AntScriptGenerator.java
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/BuildTarget.java
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/JniGenSharedLibraryLoader.java
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/SharedLibraryFinder.java
I've been working on a project which uses gdx-jnigen for generating and loading native libraries. The project runs on any linux, and is most beneficial on a Raspberry Pi, which has the ARM architecture. 
Currently it is not possible to build a version for 32bit, 64bit and arm architectures at the same time. Therefore, I added some options to the buildscript generator, which gives more freedom, also for future additions.
I also added the ability to detect an ARM platform, and load the appropriate native library.
This will be usefull in all sorts of projects, and will also be helpfull if one would decide to port libgdx to another ARM platform (Iike the Rpi) later.
> [gdx-jnigen] ARM compatibility

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Button.java
- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java
- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Slider.java
This PR adds ability to set knowDown and knobOver drawable for Slider. Those are both optional so it does not affect existing sliders. 
I added protected method `getKnobDrawable` in ProgressBar and Slider overrides it, I'm not sure if there is some better way to do it.
Also fixed small Javadoc mistake.
> Added Slider knowDown and knobOver drawable

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/graphics/MockGraphics.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/input/MockInput.java
- backends/gdx-backend-jglfw/src/com/badlogic/gdx/backends/jglfw/JglfwGraphics.java
- backends/gdx-backend-jglfw/src/com/badlogic/gdx/backends/jglfw/JglfwInput.java
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglCursor.java
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglInput.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java
- gdx/src/com/badlogic/gdx/Graphics.java
- gdx/src/com/badlogic/gdx/Input.java
- gdx/src/com/badlogic/gdx/graphics/Cursor.java
- gdx/src/com/badlogic/gdx/input/RemoteInput.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/CursorTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
This pull request is to solve issue #2839
Basically problem is that currently calling Gdx.input.setCursorImage will create a new (lwjgl) Cursor object everytime, even if pixmaps are identical + it will make some calculations to process the Pixmap.
This is ok if only a few setCursorImage call are made, but if the application requires to cycle a lot through a few cursors then it will eventually crash on Windows (invisible cursor) and also use unecessary memory + cpu.
This pull request adds a new Cursor object that can be created by calling Gdx.input.newCursor, and set anytime using Gdx.input.setCursor, when using this method no other object are created when calling Gdx.input.setCursor. It kinda provides a way for the user to use a cache for cursor creation.
This is my very first pull …
> set mouse cursor using a Cursor object

- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessApplication.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessApplicationConfiguration.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessFiles.java
Hi guys,
I don't know why the config for headless only have one option `renderInterval`, but I need change the `preferencesDirectory` when use headless backend.
I follow the same logic as other backend, it should works.
And a very small fix for HeadlessFiles, it hard code file separator as '/'.
> Add preferences directory in headless config

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtCursor.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
- gdx/src/com/badlogic/gdx/Graphics.java
Added Gwt support for custom Cursors.
Cursors should not work in IE according to
http://reference.sitepoint.com/css/cursor because we convert the canvas
to a data-url of the png format and IE only supports .cur and .ani
files.
IE would also not support setting hotspot coordinates, it only supports
hotspot coords in .cur files.
Not all opera version seem to support cursors using the "cursor:url()"
syntax
Any suggestions?
> Add Gwt support for custom Cursors

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java
Issue #2807 already partially fixed this issue but an additional check is not being made for negative keycodes in onKey causing crashes on some Chinese devices that send -2
```
java.lang.ArrayIndexOutOfBoundsException: length=260; index=-2
at com.badlogic.gdx.backends.android.AndroidInput.onKey(SourceFile:498)
at android.view.View.dispatchKeyEvent(View.java:7338)
```
(The issue also happens in a number of flavors further down onKey)
```
java.lang.ArrayIndexOutOfBoundsException: length=260; index=-2
at com.badlogic.gdx.backends.android.AndroidInput.onKey(SourceFile:530)
```
> Fixes onKey ArrayIndexOutOfBoundsException on negative keycodes

- CHANGES
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/Utf8Decoder.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/io/InputStreamReader.java
This should definitely fix #3350. Utf8 sequences across buffer boundaries are handled properly.
Basically, the Utf8Decoder is a port of [Björn Höhrmann's algorithm](http://bjoern.hoehrmann.de/utf-8/decoder/dfa/).
It's fast and does not allocate additional buffers while decoding.
> Fix for issue #3350

- gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java
glCheckFramebufferStatus() was always called with the default frame buffer bound.
> Check status before binding to default frame buffer again.

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java
Ctrl + Backspace is not a shortcut for cut, the right shorcut is 
Shift + Forward_Delete, which is already implemented.
Reference:https://en.wikipedia.org/wiki/Cut,_copy,_and_paste#Common_keyboard_shortcuts
> Remove wrong keyboard shortcut

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java
This fixes cut, copy, paste and select-all keyboard shortcuts not working on mac as discussed in issue #3340.
> Fix #3340. TextField ignores input on mac if command is pressed.

- gdx/src/com/badlogic/gdx/assets/loaders/resolvers/PrefixFileHandleResolver.java
Add a simple `FileHandleResolver` that allows you to specify a sub-folder to use within the base.
> Add PrefixFileHandleResolver

- CHANGES
- extensions/gdx-tools/src/com/badlogic/gdx/tiledmappacker/TiledMapPacker.java
- extensions/gdx-tools/src/com/badlogic/gdx/tiledmappacker/TiledMapPackerTest.java
- extensions/gdx-tools/src/com/badlogic/gdx/tiledmappacker/TiledMapPackerTestRender.java
- gdx/src/com/badlogic/gdx/maps/tiled/AtlasTmxMapLoader.java
- tests/gdx-tests-android/assets/data/maps/tiled-atlas-processed/test.tmx
- tests/gdx-tests-android/assets/data/maps/tiled-atlas-processed/tileset/packed.atlas
* Searches for maps in nested folders, regardless of depth
* Creates an individual atlas for each map (uses the map name sans extension)
* Fixes loading/rendering problems with multiple tilesets
* Removes isBlended checking and addition of blended property
* Removes unused methods, broken methods, minor cleanup throughout TiledMapPacker class
* Fixes the problem of not locating tilesets with ../ in the map Note: This has only been fixed with the      new functionality (not --combine-tilsets) The old method of combining tilesets into one atlas still has this problem.
* Old functionality can be called with the option "--combine-tilesets"
* Adds two classes to test the options and renders the processed maps
* Changes usage to: Usage: INPUTDIR [OUTPUTDIR] [--strip-unused] [--combine-tilesets] …
> New TiledMapPacker output, fixes multiple tileset problem

- gdx/src/com/badlogic/gdx/math/Rectangle.java
- gdx/src/com/badlogic/gdx/math/Vector2.java
- gdx/src/com/badlogic/gdx/math/Vector3.java
- gdx/test/com/badlogic/gdx/math/RectangleTest.java
- gdx/test/com/badlogic/gdx/math/Vector2Test.java
- gdx/test/com/badlogic/gdx/math/Vector3Test.java
Implementation of parseXXX methods for `Vector2`, `Vector3` and `Rectangle`, as well as enhancements of `toString()` format. The format of `Vector2` is changed from `[x:y]` to `(x,y)`, `Vector3` is changed from `[x, y, z]` to `(x,y,z)`, and the format of `Rectangle` is changed from `x,y,w,h` to `[x,y,w,h]`. This was done for consistency and simplified parsing, and shouldn't break too much stuff.
> Implement parsing methods for vectors and rectangles

- gdx/src/com/badlogic/gdx/math/Polygon.java
- gdx/src/com/badlogic/gdx/math/Polyline.java
- gdx/src/com/badlogic/gdx/math/Shape2D.java
This is the PR for https://github.com/libgdx/libgdx/issues/2880.
Polyline is no Shape2D anymore and `Shape2D` now has two methods `contains(float x, float y)` and `contains(Vector2 point)`.
> Added contains to Shape2D.

- gdx/src/com/badlogic/gdx/audio/Sound.java
Just addressing a very small error in the javadoc for Sound where \</b\> is incorrectly written as \<b\>, causing the rest of the document to be rendered bold.
> Fixed incorrectly ended bold tag on special note.

- extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/BMFontUtil.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Kerning.java
This also cleans up the Kerning class a bit, adds a ByteInputStream
subclass to handle data decoding, reads all of the file into memory in
one go because we need to seek (and it's probably faster), and uses more
efficient data structures (IntIntMap instead of lots of
boxing/unboxing).
Fixes #3442.
> Read kerning data from the GPOS table in addition to the kern table

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/APKExpansionSupport.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidAudio.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFileHandle.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFiles.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidZipFileHandle.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/ZipResourceFile.java
- tests/gdx-tests-android/assets/data/testpackobb
- tests/gdx-tests-android/build.gradle
- tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/APKExpansionTest.java
- tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/AndroidTestStarter.java
- tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/ZipFileHandleResolver.java
The change is transparent to the user, Gdx.files.internal() can be used to access assets inside expansion files.
The application must call ((AndroidFiles)Gdx.files).setAPKExpansion() first, to open the expansion file(s). The function returns true if it was opened successfully.
This replaces https://github.com/libgdx/libgdx/pull/3381
> Add APK expansion support

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidAudio.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFileHandle.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFiles.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidZipFileHandle.java
It seems that if there are lots of entries in the obb file, exists() is rather slow because it has to search a large HashMap. This should make it much faster.
> Make APK expansion initialization faster. Make exists() faster for files

- gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java
on some mobile devices, the packed depth and stencil buffer should be used for framebuffer with depth and stencil buffer enabled
Change-Id: Iba22349416354dbc52e53f3a2197346f69f9e1c1
> Fix issue 3422

- gdx/src/com/badlogic/gdx/graphics/g3d/loader/ObjLoader.java
This is particularly useful when one needs the original mesh names exported from the 3d editor. In case the "default" group is used, the ids are still autogenerated.
> Use group names instead of generated ids in ObjLoader

- gdx/src/com/badlogic/gdx/graphics/g3d/loader/ObjLoader.java
The mtl loader replaces dots with underscored, but ObjLoader does not. Thus ObjLoader is unable to load materials with dots in their name ("Material.001").
> Fix bug causing ObjLoader to not load materials with dots in name

- gdx/src/com/badlogic/gdx/math/CumulativeDistribution.java
Class CumulativeDistribution returned wrong values. Can be easily checked with the next code:
```java
CumulativeDistribution<Integer> cdf = new CumulativeDistribution<Integer>();
cdf.add(1, 1);
cdf.add(2, 1);
cdf.add(3, 1);
cdf.generateNormalized();
int one = 0, two = 0, three = 0;
for (int i = 0; i < 100000; i++) {
int v = cdf.value();
if (v == 1) one++;
else if (v == 2) two++;
else if (v == 3) three++;
}
System.out.println("1: " + one + " 2: " + two + " 3: " + three);
```
Prints before fix:
1: 66714 2: 0 3: 33286
After fix:
1: 33383 2: 33489 3: 33128
> fixed CumulativeDistribution class returned wrong values

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidZipFileHandle.java
If the file doesn't exists AndroidZipFileHandle.length() throws a NullPointerException which is wrong. Looks like the FreetypeFontGenerator uses FileHandle.length() to check if a font is an actual file or has to be generated so that is the most obvious way to catch this.
> Fix AndroidZipFileHandle.length() throwing NullPointerException

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidZipFileHandle.java
- tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/APKExpansionTest.java
FreeType fonts look for the sibling of a file, which in case of AndroidZipFile might be in the internal rather the obb file itself. This patch fixes this case and also adds a test inside the APKExpansionTest.
> Fix freetype font loading when using AndroidZipFile

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTCanvas.java
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
There are a few new steps in initializing LwjglGraphics that were not carried over to LwjglAWTCanvas.
As a result, SwingLwjglTest currently crashes in the tip of tree.
This patch fixes that.
> Fix SwingLwjglTest crash.

- extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btIndexedMesh.java
- extensions/gdx-bullet/jni/swig/collision/btTriangleIndexVertexArray.i
- gdx/src/com/badlogic/gdx/graphics/g3d/Model.java
- gdx/src/com/badlogic/gdx/graphics/g3d/ModelBatch.java
- gdx/src/com/badlogic/gdx/graphics/g3d/ModelInstance.java
- gdx/src/com/badlogic/gdx/graphics/g3d/Renderable.java
- gdx/src/com/badlogic/gdx/graphics/g3d/model/MeshPart.java
- gdx/src/com/badlogic/gdx/graphics/g3d/model/Node.java
- gdx/src/com/badlogic/gdx/graphics/g3d/model/NodePart.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleShader.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/batches/BillboardParticleBatch.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/batches/PointSpriteParticleBatch.java
- gdx/src/com/badlogic/gdx/graphics/g3d/shaders/BaseShader.java
- gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java
- gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DepthShader.java
- gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java
- gdx/src/com/badlogic/gdx/graphics/g3d/utils/ModelBuilder.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/bullet/SoftMeshTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/HeightMapTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/ModelCache.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/ShaderTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/shaders/MultiPassShader.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/voxel/VoxelWorld.java
**This is an API breaking change**
* Removes the `mesh`, `meshPartOffset`, `meshPartSize` and `primitiveType` members of `Renderable` and adds the `meshPart` member instead. 
* Adds the `center`, `halfExtents` and `radius` members to `MeshPart`.
* Rename `MeshPart#indexOffset` to `MeshPart#offset` and `MeshPart#numVertices` to `MeshPart#size`.
The bounds are (and should be) calculated as soon as possible and not more than needed. In case of `Model` this is when the model is loaded from file or created using `ModelBuilder`. Custom implementation that create `MeshPart` instances should be updated accordingly.
Calculating the bounds of the entire `Model`/`ModelInstance` is not affected by these values. That is still a costly operation that takes into account the node transformation.
The …
> Add Renderable#meshPart, MeshPart bounds, rename to #offset and #size

- extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/World.java
Without this the freeFixtures pool is never actually used and new fixtures are always allocated.
When you have many bullets/projectiles/particles getting created/destroyed this causes a lot of GC churn.
Fixes #3364
NOTE: I am placing my code modification in this PR into the Public Domain.  It is small and I don't want to sign the CLA.
> World::destroyBody returns fixtures to pool

- gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java
this error may cause some mistakes in rendering afterward
> fix misuse of glDeleteBuffer for glDeleteRenderBuffer in dispose

- tests/gdx-tests/src/com/badlogic/gdx/tests/bullet/TriangleRaycastTest.java
MyTriangleRaycastCallback needs to find the lowest hitFraction. I assumed the super class handled this, but apparently it does not. The problem did not appear until I started experimenting with more complicated meshes.
> Corrected hitFraction bug in TriangleRaycastTest

- gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java
Generally doesn't seem to be too big an issue since the TouchFocus objects seem to get pulled out of the pool and overwritten fairly often (at least in my case), but still a leak.
> Fixing memory leak related to TouchFocus and pooling

- gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java
This modification does not change anything by default. The reason I did it is because I want to inject custom code between glCreateProgram() and glLinkProgram(). ShaderProgram.createProgram() is declared *protected* to allow @Override in subclasses.
> ShaderProgram: separate create and link stages

- gdx/src/com/badlogic/gdx/assets/AssetManager.java
Added final reference to the FileHandleResolver for which an AssetManager was created using. This is useful if custom AssetLoaders would like to use the same FileHandleResolver as the AssetManager for which they will belong.
> Added final reference to the FileHandleResolver for which an AssetManager was created using

- CHANGES
- gdx/src/com/badlogic/gdx/scenes/scene2d/Actor.java
The actor class has an existing `positionChanged` method that can be overridden to check for position changes.  In addition, there's one for `sizeChanged`.  However, I noticed there was no option for rotation changes so I added it.
I apologize, I haven't actually been able to test these changes because of a Maven issue so if someone could review this that would be great.  In addition, this is my first pull request for libgdx (I have the CLA sent in already).
> adds rotationChanged method for Actor class

- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
I have added my gdx-dialogs extension to the 3rd party extension list.
Extension:
https://github.com/TomGrill/gdx-dialogs
Example App:
https://github.com/TomGrill/gdx-dialogs-app
> added gdx-dialogs to 3rd party extensions list

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNativesLoader.java
Passes in the correct `File` to be extracted.  It's fairly ugly.
> Pass in the correct file for LwjglNative extraction fixes #3578

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Button.java
Added checkedOffset fields to button style. In my use-case, I use the pressed button to represent the checked state, and since my pressed button requires a label offset, I needed to add the following code to make the button look correct in the checked state as well.
> Added checkedOffset fields to ButtonStyle

- gdx/src/com/badlogic/gdx/assets/loaders/MusicLoader.java
- gdx/src/com/badlogic/gdx/assets/loaders/SoundLoader.java
Added protected methods to get the currently loaded Sound or Music object reference. This is nice so that subclasses of these AssetLoaders can override loadAsync and call the superclass method and then grab the asset reference for use. This cleans up subclasses who want to take advantage of the behavior of SoundLoader and MusicLoader greatly.
This PR replaces #3541 and #3542
> Created protected methods so that subclasses of MusicLoader and SoundLoader can get asset reference

- gdx/src/com/badlogic/gdx/utils/Queue.java
- gdx/test/com/badlogic/gdx/utils/QueueTest.java
Adds a simple but efficient queue implementation.
__Motivation:__
`Array` is good for lists and stacks, but it is inefficient for building queues.
__Implementation:__
Queue is implemented as a java array with two indexes which rotate around, wrapping at the end. Details are documented in the code. All basic methods for queue manipulation are present (add/enqueue, remove/dequeue and peek). Queue can't overflow, grows when not enough space in the backing array. On underflow it returns null or specified default value, no exceptions are thrown.
PR includes unit test for the Queue.
> Add Queue collection

- gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java
The same event object is being used for `enter` and `exit` in `fireEnterAndExit()`. If the user decides to `stop()` the `exit` event, then `enter` will be stopped as well.
Fix: fire `enter` with a fresh event object.
> Fix #3604 - missing enter after stopping exit event

- CHANGES
- extensions/gdx-controllers/gdx-controllers-desktop/jni/ois-v1-4svn/src/mac/MacHIDManager.cpp
Bug report (and actually the bug fix description too):
http://steamcommunity.com/app/371430/discussions/1/490121928343760774/
Caused by calling free() on results of getCString() which hasn't always been allocated with malloc().
I was able to reproduce the crash, and test the fix with Space Grunts.
> Only call free() on malloc()'d strings.

- gdx/src/com/badlogic/gdx/graphics/g3d/model/data/ModelNode.java
I might miss its purpose but this variable is not used at all. 
The same goes for ModelNode.meshId, but I didn't remove it since it is written to (but never read from). Can do another commit if needed.
This is quite a non-important change so feel free to reject it but I thought it would help reduce the complexity of libgdx's node architecture. I'm writing my own model loader right now and the amount of variables in the data classes is a bit overwhelming, and if some of them are not used, it's even more confusing.
> remove unused boneId variable in ModelNode data class

- tests/gdx-tests/src/com/badlogic/gdx/tests/superkoalio/SuperKoalio.java
I found this bug while working with SuperKoalio test (see gif). Debug rendering is added just in case it fits in the Koalio test.
> Clamp delta time and add debug rendering in SuperKoalio test

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/reflect/Method.java
The returned array can be null causing an exception in the GWT backend saying, "Cannot read property 'length' of null"
A simple test
```java
package com.unseenspace.test;
import com.badlogic.gdx.Application;
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.scenes.scene2d.Actor;
import com.badlogic.gdx.utils.reflect.ClassReflection;
import com.badlogic.gdx.utils.reflect.Method;
import java.util.Arrays;
public class AnnotationTest extends ApplicationAdapter {
@Override
public void create() {
Gdx.app.setLogLevel(Application.LOG_DEBUG);
Gdx.app.error("TEST", "Testing class: " + Arrays.toString(ClassReflection.getAnnotations(Actor.class)));
Gdx.app.error("TEST", "Class Annotations: " + Arrays.toString(ClassReflection.getAnnotations(Actor.class))); …
```
> check for null

- CONTRIBUTING.md
By section:
"feature" should be singular
Capitalize "GDX" in "libGDX" (3 times), capitalize "H" in "GitHub", use "send" instead of "sent", make the URL a link
Make the e-mail a `mailto:` link, filling in the subject automatically
Capitalize "GDX", getting rid of a list with only one item
Capitalize "GDX" (x2), format correctly the package name
Capitalize "GDX", fix ordering of letters in "GDX" and capitalize, fix 2 run-on sentences, use a plural noun for "ourselves", "changes" is one word, and "request" is used in a singular context.
> Grammatical errors in `CONTRIBUTE.md`

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationConfiguration.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
This enables locking the orientation of the web application on mobile browsers that support the API. For now this includes Chrome on Android, Firefox and the latest mobile IE. 
The patch does not change the default behaviour, but if fullscreenOrientation is set in GwtApplicationConfiguration, the orientation will be locked when the app enters fullscreen mode. When fullscreen mode is exited, the orientation is unlocked.
Should the user wish to trigger orientation changes manually, there are public methods available in GwtGraphics.
> Added support for locking the screen orientation in the GWT backend

- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
This fixes a bug with the current Setup UI on Linux:
```
java.io.IOException: Cannot run program ""/home/theboss/Software/Android-SDK/tools/android": error=2, Datei oder Verzeichnis nicht gefunden
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at java.lang.Runtime.exec(Runtime.java:620)
at java.lang.Runtime.exec(Runtime.java:450)
at java.lang.Runtime.exec(Runtime.java:347)
at com.badlogic.gdx.setup.GdxSetupUI.generate(Unknown Source)
at com.badlogic.gdx.setup.GdxSetupUI$UI$4.actionPerformed(Unknown Source)
```
The problem comes from manipulating file names directly instead of using the java.io.File API.
I didn't change the Windows branch because I'm not able to test it at the moment.
> Bugfix for GdxSetupUI on Linux when needing a SDK update

- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java
iOS backend did not map touch coordinates to libGDX correctly. libGDX's GL View is stretched over whole screen, but libGDX draws only on a subset of that, because it excludes status bar, if present. Touch mapping was however completely oblivious to this fact - this worked well when the status bar was not visible, but was inaccurate when the status bar was indeed visible.
This PR rewrites rotation/resize handling and touch coordinate mapping to explicitly handle mentioned problems.
This is somewhat related to issues:
#2105 - although this seems to be the opposite issue, it is not present after this PR
#3278 - does not fix this, but allows it to be fixed in user code by overriding `IOSApplication.getBounds` and providing correct bounds
Note that I am not an iOS expert, but I have tested it …
> Fix iOS touch mapping

- CHANGES
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Cursor.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtCursor.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
GWT cursors should work everywhere.
@badlogic forgot the 'Ibeam' system cursor, so I added it.
See 
http://caniuse.com/#feat=css3-cursors
http://quirksmode.org/css/user-interface/cursor.html
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
> Add system cursors to GWT, fix little error in Lwjgl3Cursor

- extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtension.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtensionDependency.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtensionsDialog.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
This PR allows to add external dependencies for extensions defined in `extensions.xml`. Currently there is no way to do it, declared dependencies can't have version specified (it's inherited from extension version). Why is this change needed? Mostly for GWT, sometimes dependencies have separate gwt library which should be only included in html module and thus can't be included in extension itself. This was also discussed [here](https://github.com/libgdx/libgdx/pull/3537#issuecomment-156844608) and would help avoid issues like #3737.
External dependcies are declared like this:
```xml
<dependency external="true">net.onedaybeard.artemis:artemis-odb:1.2.1:sources</dependency>
```
`external="true"` is added to standard declaration.
I also corrected mixed indention in `extensions.xml`.
> Gdx-setup: add support for external dependencies

- gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java
Allows vertex transformation to handle tangent and binormal correctly.
> Add binormal and tangent to MeshBuilder

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextArea.java
Due to not handling the super result in TextArea the key was passed to my parent dialog causing the dialog to close when the ENTER key was enter in the textarea. This is a pull request to fix that bug.
> Get result when calling super in keyDown for later return.

- CHANGES
- CONTRIBUTORS
- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
When rendering true type fonts, I was seeing this:
instead of:
Turns out the `FreeTypeFontGenerator` was generating incomplete kerning info. Before kerning, the library creates glyphs in order from highest to lowest for best packing. During this step, the `characters` array becomes corrupted (highest chars get discarded). For example: `['A', 'V', 'L', 'T', 'Y']` turns into `['T', 'T', 'L', 'T', 'Y']`, so `'A'` and `'V'` will not be considered for kerning.
This fix keeps the `characters` array sorted and intact for kerning purposes.
> Fix broken kerning for freetype fonts

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/lang/System.java
Date.now() is supported on every browser that supports WebGL, so it's save to use it instead of creating a new object on every call.
> Don't create garbage in System.currentMillis

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL20.java
In `LwjglGL20.toIntBuffer` use `intBuffer` instance to pass it to `gl*` functions, but before coping clear `floatBuffer` instance.
> Fix wrong buffer clear

- CHANGES
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowAdapter.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowListener.java
- tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/DragNDropTest.java
- tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3DebugStarter.java
This pull request adds support for external file drag & drop. Files (from e.g. the desktop) can be dragged in a Lwjgl3Window, causing the the Lwjgl3WindowListener to call drop(String[] files).
This is an API change, since i added that drop() method to the Lwjgl3WindowListener interface.
A use case for this are programs like level editors, where you want the user to be able to easily import assets by drag and drop. 
I added a simple test as well.
> Drag'n Drop support for the lwjgl3 backend.

- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSPreferences.java
This PR fixes the memory leak when flushing IOSPreferences on a non-UI thread. 
Also reuses the File instance instead of creating it every flush.
And removes the very noisy debug log every flush. Now logs only if the preferences could not be written to file.
> Fix memory leak in IOSPreferences

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Cursor.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
- tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/MultiWindowCursorTest.java
- tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/MultiWindowTest.java
Next try to fix #3880. Each window disposes its own cursors only. System cursors are disposed on application shutdown.
> LWJGL3: cleanup of per-window / system cursors

- gdx/src/com/badlogic/gdx/graphics/glutils/FloatTextureData.java
Makes it possible to access the FloatBuffer backing the FloatTextureData. Without this it is impossible to alter the contents of the buffer before sending it of to the GPU.
> Added getter for FloatTextureData.buffer

- gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java
I develop an IDE that I distribute [in the Mac app store](https://itunes.apple.com/us/app/nightcode/id827505032?ls=1&mt=12) that includes a template for libGDX projects. It used to build and run the projects, but due to changes in `SharedLibraryLoader` it now gets the following error: `Unable to find writable path to extract file. Is the user home directory writable?`.
It looks like this is because the OS X sandbox causes `canExecute` to return false. I made a change that should have a very low impact on everyone else: It still tests for both write and execute privileges in `getExtractedFile`, but if all attempts fail, it returns a file that *at least* has write privileges. This makes it work in the OS X sandbox.
> Allow building in the Mac OS X sandbox

- gdx/src/com/badlogic/gdx/graphics/glutils/ETC1.java
Fixing ETC1.encodeImagePKM crash due to the null Gdx.app https://github.com/libgdx/libgdx/issues/3914
> fixing #3914

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFragmentApplication.java
I created [this sample project ](https://github.com/SaeedMasoumi/libgdx-android-leak
)to show that how libgdx creates memory leaks on android.
In [LeakFragment](https://github.com/SaeedMasoumi/libgdx-android-leak/blob/master/android/src/io/saeid/libgdx/androidleak/fragment/LeakFragment.java) and [LeakActivity](https://github.com/SaeedMasoumi/libgdx-android-leak/blob/master/android/src/io/saeid/libgdx/androidleak/activity/LeakActivity.java) classes, i created a method called `whatShouldBeDoneOnSuperMethod` without this method, leak canary will show memory leak.
> Fixed memory leaks on android

- extensions/gdx-bullet/jni/swig-src/collision/collision_wrap.cpp
- extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/CollisionJNI.java
- extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btBroadphasePairArray.java
- extensions/gdx-bullet/jni/swig/collision/btBroadphasePairArray.i
- tests/gdx-tests/src/com/badlogic/gdx/tests/BulletTestCollection.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/bullet/PairCacheTest.java
Tested on Desktop and Android platforms.
The test program is not very efficient, since the ```btOverlappingPairCache```, ```btCollisionAlgorithm```, ```btPersistentManifold``` and ```btManifoldPoint``` classes do not use pooling.
> Fixes #3509 and adds a simple test program

- gdx/src/com/badlogic/gdx/utils/ComparableTimSort.java
At the moment ComparableTimSort use a ~~static~~ temp array for performing the sort. The array is not clean up after sorting, therefore maintaining ~~static~~ references to the sorted objects.
This pull request simply mimics what is being done in TimSort which correctly cleanup these references after sorting.
> Fix reference leak in ComparableTimSort

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
Seems that getDisplayModes(Monitor) only returns the getDisplayMode() result
which in turn getDisplayMode() doesn't return the current mode but the initial one that was the window created with (using getDesktopDisplayMode())
> Lwjgl2 backend displayMode tweaks

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/graphics/MockGraphics.java
- backends/gdx-backend-jglfw/src/com/badlogic/gdx/backends/jglfw/JglfwGraphics.java
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
- gdx/src/com/badlogic/gdx/Graphics.java
Add implemenations for all backends.
Note: most desktop backend implementations require a call to 'setWindowedMode' in order for the changes to take effect.
It is worth noting that this is not necessary with the JogAmp backend. However, as of the time of writing, that backend is not included in LibGDX master.
Fixes #3773
> Add setUndeocrated/setResizable APIs to Graphics.

- gdx/src/com/badlogic/gdx/utils/UBJsonReader.java
- gdx/src/com/badlogic/gdx/utils/UBJsonWriter.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/UBJsonTest.java
This is a bug fix for writing and reading long, double and char arrays in UBJSON.
see Issue #3938
> UBJSON reader/writer: fix for writing long/double/char arrays

- gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java
This is a very basic addition to allow applications to check in debug build/unit tests the number of managed shaders to detect ressources leaks.
The code is similar to what we have in [Texture.getNumManagedTextures ](https://github.com/libgdx/libgdx/blob/0c00d4b69fb1ab6746484b8cf2486456a5302978/gdx/src/com/badlogic/gdx/graphics/Texture.java) for the same purpose.
> Add a getter for the number of managed shaders

- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
The x and y local variables are already scaled on lines 175 and 176 in the BaseTmxMapLoader, and scaling them again when modifying the properties ObjectMap makes the x and y properties too small (and inconsistent with the coordinates of Rectangle/Ellipse/etc if the MapObject in question is an instance of one of those objects).
> Fixed MapObject x/y properties being scaled twice

- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/NativeCodeGenerator.java
Methods with a underscore, e.g. `_foo()` can't be used with jnigen, because they are 
transformed to `__1foo()` according to the rules defined in table 2-1 at 
http://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/design.html#wp615
They can't be used, because jnigen always looks for "_" + methodName so jnigen looks for a 
function `__foo()` which doesn't exist.
> Fix issue with underscores in method names

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java
This change allows to select non latin letters.
Previously it was impossible to select "éíúóöäü" as a whole word.
You were only able to select one of those characters.
@NathanSweet
> Fix selection of non latin characters

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglInput.java
Typing with IME only receives a unicode character without keydown event, so I added a KeyChar check.
Note: I only tested it in Windows 7, not sure if it works in other systems.
> Fix Desktop IME input.

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Skin.java
Sometimes it's necessary to have a font atlas split in several images in the form:
```
Arial_0.png
Arial_1.png
Arial_2.png
```
If these images are packed (with other images), the resulting atlas contains regions with repeated names but different indexes, something like this:
```
...
Arial
rotate: false
xy: 2, 518
size: 256, 256
orig: 256, 256
offset: 0, 0
index: 0
Arial
rotate: false
xy: 2, 260
size: 256, 256
orig: 256, 256
offset: 0, 0
index: 1
Arial
rotate: false
xy: 260, 518
size: 256, 256
orig: 256, 256
offset: 0, 0
index: 2
...
```
If we use this atlas as an `Skin` atlas, the loading process ignores region indexes and it ends up with only 1 `TextureRegion` named `Arial` (the last one found). This makes impossible to build a `BitmapFont` using several `TextureRegion` (since the skin …
> Load BitmapFont split in multiple regions in Skin

- CHANGES
- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeType.java
- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
With some fonts, the default FreeType hinter is too aggressive and yields poor results. This commit adds a field to `FreeTypeFontParameter` for configuring the hinting algorithm.
> FreeType - Allow configuration of hinting algorithm

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Window.java
This is a very old bug that I knew and fixed but never made a PR.
The top-left, top-right and bottom-right edges don't seems to synchronize the mouse cursor when going outside of the App border.
And the very simple fix made it work.
> Fixed Scene2D window resize bug.

- gdx/src/com/badlogic/gdx.gwt.xml
- gdx/src/com/badlogic/gdx/graphics/g3d/utils/BaseShapeBuilder.java
- gdx/src/com/badlogic/gdx/graphics/g3d/utils/BoxShapeBuilder.java
- gdx/src/com/badlogic/gdx/graphics/g3d/utils/Debug3dRenderer.java
- gdx/src/com/badlogic/gdx/graphics/g3d/utils/FrustumShapeBuilder.java
Debug3dRenderer allows to visualize camera in 3d space.
This pull request follows the #3856 pull request.
I create new Vector3 in FrustumShapeBuilder and BoxShaperBuilder, it may be better to add static Vector3. I wait for your comments.
@xoppa
> Add Debug3dRenderer with FrustumShapeBuilder and BoxShapeBuilder

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/glutils/VertexBufferObjectWithVAO.java
- gdx/src/com/badlogic/gdx/graphics/glutils/VertexBufferObjectWithVAO.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/VBOWithVAOPerformanceTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
* Adds attribute location caching
* Removes unnecessary gl calls
Performance test shows this change results in a ~95% decrease in total time taken to render a mesh with the VBOWithVAO VertexDataType.
Related issues: https://github.com/libgdx/libgdx/issues/3593
> Clean up performance in VBOWithVAO and supply performance test

- gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java
Remove camera property of DefaultShader because it already exists in BaseShader.
Here : https://github.com/libgdx/libgdx/blob/1.9.2/gdx/src/com/badlogic/gdx/graphics/g3d/shaders/BaseShader.java#L112
> Robustify DefaultShader

- gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java
If a transform matrix is passed to `sphere()` method of MeshBuilder, normal vectors are wrong.
Before this fix : 
After this fix :
> Fix MeshBuilder

- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessNet.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessPreferences.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/input/MockInput.java
> Headless backend. Remove unused stuff.

- backends/gdx-backends-gwt/src/com/badlogic/gwtref/client/Method.java
GWT `Method#getEnclosingType()` and `getReturnType()` methods are broken and always return `com.badlogic.gwtref.client.CachedTypeLookup` instead of actual types. This pull request fixes this issue.
I think that originally `getClass()` method was mistaken for `clazz` getter rather than the default Java method that returns the class of the actual object (in this case - `CachedTypeLookup`). Since `clazz` field was already package-private, I didn't add any getters and just accessed the field directly.
> GWT Method reflection fix.

- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSDevice.java
I cross checked against https://www.theiphonewiki.com/wiki/Models and found that "iPad6,7" was also missing, so I added it too.
> Fixes #4035 and missing "iPad 6,7"

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/conformance/DisplayModeTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
Fixes what #3903 tried fixing. 
I've also added a new test that checks that 
`Gdx.graphics.getDisplayMode()` and `Gdx.graphics.getDisplayMode(Gdx.graphics.getMonitor())` return the same display mode.
The test also checks that 
`Gdx.graphics.getDisplayModes()` and 
`Gdx.graphics.getDisplayModes(Gdx.graphics.getMonitor())` are equal.
> Properly add what PR#3903 tried fixing, also see #3997. Added test

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/ScreenUtils.java
- gdx/src/com/badlogic/gdx.gwt.xml
- tests/gdx-tests/src/com/badlogic/gdx/GdxTests.gwt.xml
- tests/gdx-tests/src/com/badlogic/gdx/tests/FramebufferToTextureTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
Add FramebufferToTextureTest and AlphaTest to GWT, remove obsolete 
tests.
> Emulate ScreenUtils for GWT

- CHANGES
- CONTRIBUTORS
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/ScreenUtils.java
glReadPixels() is about 20 times faster now, ScreenUtils is about 15% 
faster
I also added the CHANGES from my other PRs.
> Improve performance of glReadPixels() and ScreenUtils on GWT

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/ScreenUtils.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
Turns out that javascript engines are jiting as much as java vms, which means that micro benchmarks are pretty useless. (E.g. the speed is dependent on which function is called first) :(
Since there is no benchmarking tool for javascript that is as good as [JHM](http://openjdk.java.net/projects/code-tools/jmh/) is for java, I removed the "optimizations".
> Sort GWT tests, remove "optimization" in ScreenUtils

- tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3TestStarter.java
This is a replacement for the old AWT test starter. It has been
necessary since AWT can't be used with LWJGL 3.
A new test is created in a new window, using the new window APIs from
LWJGL3.
> Add test starter, allows to start all tests using LWJGL3 backend

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowConfiguration.java
Hey folks,
in the moment it is possible to hide windows using Lwjgl3Window#setVisible. This pull requests adds the option to configure windows to be hidden on creation by default. This is handy if the Lwjgl3Application is supposed to only 'spawn' windows using #newWindow. Or (the case why I made the request) if you desire to do offscreen rendering.
While I am not sure if this would be a widely used feature it is a small change and therefor worth considering imho.
-ClaasJG
> LWJGL3 Added the possibility to create windows initially hidden

- CHANGES
- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
- gdx/src/com/badlogic/gdx/graphics/g2d/PixmapPacker.java
Fixing https://github.com/libgdx/libgdx/issues/3521
- ```PixmapPacker``` has a new parameter ```Color currentTransparentColor;``` used by ```Page``` constructor to fill transparent pixels.
- ```FreeTypeFontGenerator``` sets packer to use color of the font but with zero alpha for transparent pixels to avoid leaks.
> remove texture artifacts for FreeTypeFontGenerator

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java
Trying to use FloatTextureData on GWT failed due to the OpenGL wrapper around glTexImage2d unpacking the data into bytes.
> GWT support for sending float data to a texture.

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
Using/checking for extensions in the GWT backend using Graphics.supportsExtension was not working. Code from Android/iOS was being used, even though the WebGL API differs in this regard.
> Fixed supported for extensions in GWT/WebGL backend

- gdx/src/com/badlogic/gdx/math/RandomXS128.java
getState(int) javadoc contains "seed **muse** be 0 or 1"
> Fix typo in RandomXS128.java

- gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleSystem.java
This makes it possible to use multiple `ParticleSystems`.
There is no reason, for `ParticleSystems` being static.
This could also fix https://github.com/libgdx/libgdx/issues/3018 , although it's unclear whether `ParticleSystem` caused the issue at all.
> Make it possible to use multiple ParticleSystems

- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
Updated `gdx-kiwi`, `gdx-lml` and `gdx-lml-vis`.
> Updated third party extension versions

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java
This PR aims to fix #4141, #4142 and #4143.
I also added support to enable OpenGL debug message callbacks. Made debugging a lot easier.
Note: these changes do not fix fullscreen transitions on OS X (with Retina displays) - see https://github.com/glfw/glfw/issues/748 and https://github.com/glfw/glfw/issues/682.
> Lwjgl3 various graphics fixes

- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
- tests/gdx-tests-android/assets/data/maps/tiled/isometric_grass_and_water.tmx
- tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapAssetManagerTest.java
Added property cast for new tiled maps.
You can now use the methods :
- get (String key, Class<T> clazz)
- get (String key, T defaultValue, Class<T> clazz)
of the MapProperties class.
Support String, Boolean, Integer and Float types.
> Implements properties types for tiled map loader

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSInput.java
This fix issue #4114 by removing the 'break' instruction that would discard multiple event processing.
> iOS MOE Input fix

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java
Enable the developer to return a custom widget when WebGL is not enabled. I have been using this to show helpful information, and links to help remedy the problem. It also makes it possible to localize the message.
> Enable custom no-support for WebGL widget

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglCanvas.java
This commit fixes libgdx/libgdx#4203
Please, check ```LwjglCanvasTest.java``` with ```setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE)``` and see that it's now working correct.
> LwjglCanvas disposes listener before OpenGL context get killed

- gdx/src/com/badlogic/gdx/utils/XmlReader.java
- gdx/src/com/badlogic/gdx/utils/XmlReader.rl
The error message generated by this function when the attribute did not exist was was of the form
"Element $attribute doesn't have attribute: $attribute"
instead of
"Element $element doesn't have attribute: $attribute"
> Small fix to error message generated by XmlReader.Element.getAttribute(String name)

- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java
Simple fix for #4210. Repositions the emitter panel to the top so that it isn't hidden on any platform.
> Fix for editor panel being hidden behind image panel

- gdx/src/com/badlogic/gdx/utils/Json.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/JsonTest.java
Related to the issue:
- https://github.com/libgdx/libgdx/issues/4262
ArrayMap and ObjectMap are not affected, but the added test should cover this scenario for them as well.
> Fixed #4262 by skipping typename while deserializing map entries.

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java
```TexturePacker.Settings``` has constructor with another ```Settings``` as param to make a copy instance. Much flexible to have this code in separate method (```Settings#set(Settings)```), to be able to copy fields from another instance anytime.
> TexturePacker.Settings copy ctor extracted to dedicated method

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java
Support the visibilitychange event on a wider range of desktop and mobile browsers. Replaces #4222, which I seem to have mangled using my subpar GIT skills.
I have redone the formatting of the JavaScript by hand as requested.
> Added better cross-browser support for the visibilitychange event in GWT

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java
Fixes undesired behavior introduced in #4233 making Label to set the underlying BitmapFont scale to 1 if Label fontScale was not explicitly set (see #4232 discussion).
Unfortunately this bug made it to 1.9.4.
SCCE for testing purposes:
http://pastebin.com/C2kAd9Q4
**Note**
The fix could make the following check:
```if (fontScaleChanged && (fontScaleX != oldScaleX || fontScaleY != oldScaleY))```
instead of
```if (fontScaleChanged)``` 
in case the user sets the same scale to the BitmapFont and the Label. I've decided to go for the simpler one for code clarity as the optimization is minimal.
> Fixes Label not using BitmapFont scale (caused by #4233)

- CHANGES
- gdx/src/com/badlogic/gdx/graphics/g3d/utils/DefaultRenderableSorter.java
- gdx/src/com/badlogic/gdx/math/Matrix4.java
Useful for cases when ```Renderable``` translation cannot be stored in ```Renderable#worldTransform``` but must be stored in ```Renderable#MeshPart#center```, for example in 3D ```ParticleSystem```. The performance penalty of this change can be tested in e.g. ```Basic3DTest```, but I had a hard time seeing any change. It seems to be insignificant compared to the time it takes to render the models.
> DefaultRenderableSorter accounts for center of Renderable mesh

- extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/HieroSettings.java
Using the command line batch support in Hiero was hampered by Hiero not saving/loading the rendering mode. Since it defaults to FreeType rendering, no effects would get exported by the batch mode since that requires the Java rendering mode.
> Add support for saving/loading the rendering type in Hiero

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePackerFileProcessor.java
`TexturePackerFileProcessor#process(File[], File)` was hardcoded to delete old pack files only with `.atlas` extension. And in case where `Settings#atlasExtension` has set to custom value it crashes on pack. For example if I use `.pack` extension:
```
Exception in thread "main" java.lang.RuntimeException: Error packing images.
at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:649)
at com.badlogic.gdx.tools.texturepacker.Test.main(Test.java:7)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at …
```
> Texture packer now correctly overrides old file if extension is not .atlas

- extensions/gdx-freetype/jni/com.badlogic.gdx.graphics.g2d.freetype.FreeType.cpp
- extensions/gdx-freetype/jni/com.badlogic.gdx.graphics.g2d.freetype.FreeType.h
- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeType.java
This PR adds a way to get the error code most free type functions return.
There is currently no way to get the error code since `if(error) return 0;` hides the error code.
It's possible to know _that_ an error occurred  but not _what_ error exactly occurred.
We could create a wrapper class which contains an error code (if there is one) and the result of the function, but this would be too inefficient.
That's why I came up with this solution.
When a function returns `0` you can now check the error code via `getLastErrorCode()`.
All functions that throw an exception now include the error code.
The PR would allow easier fixing of this issue:
https://github.com/libgdx/libgdx/issues/3692
> Add freetype error codes to exceptions

- tests/gdx-tests/src/com/badlogic/gdx/tests/bullet/VehicleTest.java
Prevents the wheels of the vehicle from twitching up and down. Collision in Bullet works best when triangles of shapes are of similar size.
> Decrease size of ground mesh in Bullet wrapper VehicleTest

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/math/Matrix4.java
Following #4319, a ``hasRotationOrScaling`` method was added to ``Matrix4``.
However, the method had not been replicated in the GWT backend, causing it to stop compiling properly.
> Add Matrix4::hasRotationOrScaling to GWT backend

- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
This allows choosing between the native and auto hinter. The default hinting is unchanged (medium auto hinter).
> FreeType - Support native hinting

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Button.java
- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ImageButton.java
Fixes #4387 
These few constructors (out of all the Button and Button subclass constructors) were missing this pass-through of the Skin reference, causing `getSkin()` to return null when it shouldn't (that is, when a skin was passed to the constructor).
> Buttons keep skin reference

- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSDevice.java
Sources: https://www.theiphonewiki.com/wiki/Models and https://www.techwalls.com/iphone-7-plus-model-differences/. 
Note that the higher N in "iPhone 9,N" is flipped from previous versions and now represents the non-CDMA versions. (_For those who look for symmetry in these things!_)
> Add new iPhone 7 models

- CHANGES
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowConfiguration.java
- tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/MultiWindowTest.java
You can set up your icons as image files and pass them into the app configuration. It takes image filepaths because Pixmaps are difficult to load from files before LibGDX is initialized.
You can also pass Pixmaps to an existing Lwjgl3Window to change the icon dynamically.
And I also added a method to change the title of an existing Lwjgl3Window.
Finally, I fixed a GLFW window size limits bug with a work-around, since I was in the area.
> Allow custom window icons in Lwjgl3

- CHANGES
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowConfiguration.java
- tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/MultiWindowTest.java
I broke this out of #4261 to avoid changing too much at once. This cleans up redundant code by having the app config extend the window config and adding some copy methods to make these easier to maintain without introducing bugs.
I also added the ability to change the window size limits of an existing window.
@code-disaster I can rebase and squash this after you merge #4261 so it isn't so messy.
> Clean up redundant code in Lwjgl3 backend

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
A resize triggers a call to render(). Need to be sure Gdx.graphics, Gdx.input, etc. are correct for the window that's getting rendered.
> Fix potential multi-window resize bug

- CHANGES
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowAdapter.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowListener.java
- tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3DebugStarter.java
Tidying Lwjgl3WindowListener up a bit, since we already modified it.
> Lwjgl3WindowListener.deiconified() removed

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowListener.java
(I feel like the need for requesting rendering in this condition could be very easily overlooked, and there's no harm in doing it automatically.)
Edit: Only the Javadoc needs to be corrected. There is no need to request rendering since it happens anyway.
> Lwjgl3 fix javadoc

- CHANGES
- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java
- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Slider.java
ProgressBar currently always rounds positions and sizes towards zero when drawing its drawables. Also, there was a request to allow rounding to be disabled in #2820, which can be useful if the UI is not pixel perfect. For example, you might be drawing your UI elements enlarged on a high resolution screen, but want to keep the motion of the progress bar looking smooth. Or you might be drawing it scaled down with trilinear filtering and want smoother looking motion.
I kept the same rounding behavior as Table, which doesn't try to round its own bounds (leaving that to the parent). So in the case of  a vertical progress bar, this means the background drawable's vertical position and height are not rounded. And vice versa for horizontal.
> Fix ProgressBar rounding and allow it to be disabled

- CHANGES
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
Problem:
- In LwjglGraphics, glVersion is not initialized until after
#createDisplayPixelFormat is called, yet when all else fails when
creating an OpenGL context in this method, throwing a
GdxRuntimeException, it attempts to call
glVersion#getDebugVersionString, which always results in a
NullPointerException, because glVersion is always null here.
- This NPE swallows the original, useful error message ("OpenGL is not
supported by the video driver: "), as well as the original exception,
which most likely is an LwjglException with the message "pixel format
not accelerated.", which is also useful.
Solution:
- Do not attempt to get the non-existent OpenGL debug string when
re-throwing an exception from #createDisplayPixelFormat.
- Reword the error message to exclude the debug string.
Other: …
> Fix LWJGL2 NPE when GPU driver is unsupported.

- CHANGES
- gdx/src/com/badlogic/gdx/graphics/g2d/Animation.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/AnimationTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/SimpleAnimationTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/superkoalio/SuperKoalio.java
I have found myself copy-pasting the Animation class a few times to support NinePatches or certain types of Drawables. I think PolygonRegions would be another common need. I'm also playing around with multi-texturing for normal-mapped sprites, so an animation made up of TextureRegionPairs would be useful. So it makes sense for the frame type to be generic.
This is one way to do it that shouldn't affect existing code, unless someone is serializing Animations for some reason (although I doubt anyone is trying to serialize TextureRegions, nor does it make sense to serialize assets). I created a new Animation class in the `utils` package (since this theoretically could be used for more than just 2D animation frames, think decals or some sort of state manager). The existing Animation class …
> Generic Animation class

- CHANGES
- gdx/src/com/badlogic/gdx.gwt.xml
- gdx/src/com/badlogic/gdx/assets/AssetManager.java
- gdx/src/com/badlogic/gdx/assets/loaders/ShaderProgramLoader.java
- gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java
- tests/gdx-tests-android/assets/data/g2d/batchCommon.vert
- tests/gdx-tests-android/assets/data/g2d/monochrome.frag
- tests/gdx-tests/src/com/badlogic/gdx/tests/AssetManagerTest.java
It always bothers me that ShaderPrograms can't be managed along with the rest of the assets. And since they're a synchronously loaded type of asset, it would be nice for animated loading screens if they could also be included in step-by-step loading via AssetManager.
Since typically two files are used, it provides various ways to specify the second file. The easiest (zero configuration) way would be to use .vert and .frag file name suffixes, and queue them to AssetManager.load() using either of the file names.
I derived from AsynchronousAssetLoader for future flexibility. I saw that some other synchronous loaders do the same.
> Added ShaderProgramLoader for AssetManager

- gdx/src/com/badlogic/gdx/utils/Queue.java
- gdx/test/com/badlogic/gdx/utils/QueueTest.java
Also adds a new test for this edge-case (verbatim from issue) and cleans up Queue and QueueTest (in separate commits for easy review).
> Fix Queue bug #4300

- extensions/gdx-tools/src/com/badlogic/gdx/tools/bmfont/BitmapFontWriter.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/BMFontUtil.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/unicodefont/Glyph.java
- gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java
Fixes issue #3994 where the Java renderer does not correctly set the BMFont xoffset because `charVector` was not being used.
I was experiencing this issue as well because I want to use the Java renderer in Hiero.  It looks like a simple bug; I compiled Hiero with this change and the fix corrects `xoffset`.  To test, I'm saving Arial using Java Rendering, the Extended character set, and setting 1 page of size 1024x512.  Attached are `.fnt` files before and after the fix (renamed to `.txt` for Github upload).  Notice `xoffset=2` for every character in the "before" file.  The "after" file with this fix renders correctly for me.
[arial-after-fix.txt](https://github.com/libgdx/libgdx/files/446252/arial-after-fix.txt)
[arial-before-fix.txt](https://github.com/libgdx/libgdx/files/446251/arial-bef …
> Fix for issue #3994.

- tests/gdx-tests/src/com/badlogic/gdx/tests/TextAreaScrollTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
Showcases and tests the implementation of a TextArea inside a ScrollPane (As suggested by Nate in Issue #3796)
It currently cannot properly scroll the full TextArea height, I hope this will help iron out the small issues with such use case, and ultimately work as an example on how to implement a scrollable TextArea.
> Added test to check TextArea behaviour when nested in a ScrollPane

- CHANGES
#4286 changed default behavior, so it needs to be mentioned.
> Update changes for the DragAndDrop change

- gdx/src/com/badlogic/gdx/graphics/g3d/utils/RenderContext.java
The begin() method states that it assumes default OpenGL states, but actually it enforces them, regardless of what the state was before calling begin().
> Fix RenderContext Javadoc

- gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java
A recent commit https://github.com/libgdx/libgdx/commit/7420bd0f5111b73e2f1b9c5393640adfbc4aadbb changed a few regular expressions on the BMFont parser, which are now giving problems on GWT.
Desktop jvm expects to match the whole string when matching the expression to find the "id=", while GWT matches part of the string. With the current expression desktop fails to match the string (incorrectly) but gwt seems to find a match, leading to the problem when going through "id.substring(3)" when the id already contains the match group with the expected number and returns an empty string.
Desktop jvm also seems to be more forgiving when matching the expression used to find the "file=", but GWT throws an exception when it encounters "*+".
Just load a font in GWT.
1.9.5
> Fix BitmapFont parsing

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALAudioDevice.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALAudioDevice.java
I had the same problem as in libgdx/libgdx#2252. When writing to audio device, Thread is not sleeping because of a wrong time calculation which result to zero (no sleep at all) with sample rate of 44100 Hz or above.
> fixes libgdx/libgdx#2252 reduce CPU usage in OpenALAudioDevice

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Input.java
Would close #4512.
Suggest that `Lwjgl3Input` should delegate to its `InputEventQueue` for event timestamp reporting, instead of keeping its own `currentEventTime` field.
> Lwjgl3Input delegates to InputEventQueue for event timestamps.

- tests/gdx-tests-lwjgl3/build.gradle
LWJGL3 needs to be started on the first thread on Mac, because
only the first thread can process input and user events.
> Fix #4471 start LWJGL3 on the first thread on Mac

- fetch.xml
Trivial but important change. (Because who knows when someone will change binaries in transit in order to grow their botnet).
> Use only https for fetching binaries with Ant

- CHANGES
- gdx/src/com/badlogic/gdx/graphics/Mesh.java
- gdx/src/com/badlogic/gdx/graphics/VertexAttribute.java
- gdx/src/com/badlogic/gdx/graphics/VertexAttributes.java
- gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java
- gdx/src/com/badlogic/gdx/graphics/glutils/VertexArray.java
- gdx/src/com/badlogic/gdx/graphics/glutils/VertexBufferObject.java
- gdx/src/com/badlogic/gdx/graphics/glutils/VertexBufferObjectSubData.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/MeshShaderTest.java
This builds off of #3936. The expert constructors can be made public with a bit of clean-up to avoid potential pitfalls and clarify the docs. Users will still need to understand the parameters that go into `glVertexAttribPointer`, but I don't think people will try to use any of the constructors unless they know what they're for.
@xoppa 
I think MeshBuilder might be incompatible with customized VertexAttributes, based on a quick look at its `begin()` method. I'm not very familiar with MeshBuilder, but you might want to add a doc clarifying that it only supports the built-in VertexAttributes. I didn't test it, but maybe it would be compatible so long as one of the built-in Usages is used.
Most people will never need these features, but they might open up some ways to optimize mesh vertex …
> Clean up VertexAttribute and expose expert constructors

- gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java
Explanation:
`DefaultShader#canRender(..)` used to call `combineAttributes(..)` on the renderable, and then only use the mask.  `combineAttributes(..)` is very expensive (around O(n<sup>2</sup>log(n)) where n is the number of unique attributes, because it sorts after adding each attribute).  But all the function really needs is the combined mask, and since we keep the masks for both Attributes objects around anyway we can get it with just a bitwise or.
Our game uses a large number of ModelInstances with about 15 shaders, which meant every time it added a renderable to the batch (several times per ModelInstance) it would have to iterate ~7 shaders on average and combineAttributes(..) for each one, which was a major hit to pre-render time.  Implementing this change brought the frame render …
> Vastly improve performance of DefaultShader#canRender(..)

- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
gdx-dialogs extension version is now 1.2.0 and supports GWT
> gdx-dialogs extension version is now 1.2.0 and supports GWT

- gdx/src/com/badlogic/gdx/maps/tiled/TmxMapLoader.java
This commit fixes a bug when loading external tilesets with external images.
Consider the following directory structure:
```
root/
tilemap.tmx [refers to tileset as "tiles/tileset.tsx"]
tiles/
tileset.tsx [refers to images as "tile#.png"]
tile1.png
tile2.png
```
Previously, it would try to load the images using the tilemap's location as a base, so it would look for images in root/tile#.png. Now, it will load from root/tiles/tile#.png as expected.
> Fixes loading external Tiled tilesets with relative images

- gdx/src/com/badlogic/gdx/graphics/g3d/ModelBatch.java
- gdx/src/com/badlogic/gdx/graphics/g3d/utils/shapebuilders/RenderableShapeBuilder.java
This pull request changes ModelBatch.RenderablePool.obtain() and RenderableShapeBuilder.RenderablePool.obtain() to reset renderable.userData as currently it is not reset.
[Forum post](http://badlogicgames.com/forum/viewtopic.php?f=11&t=25563)
> Reset renderable.userData in RenderablePool

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java
Currently TextureAtlas performs 2 iterations to bleed colored pixels to transparent ones, but this is not enough when a MipMapLinearLinear filtering is used, leaving white artifacts in the final result.
This PR exposes the amount of iterations to the user, so they can perform 2, 4, or even 8 iterations if they want to, while keeping the default value unchanged.
> TexturePacker, allow user to set the amount of bleed iterations.

- extensions/gdx-tools/src/com/badlogic/gdx/tools/ktx/KTXProcessor.java
When running KTXProcessor, the process would never exit, eventhough the conversion went fine. This PR fixes this issue.
> Fixed KTXProcessor in gdx-tools never exiting.

- extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers/mappings/Xbox.java
+ Added button code for pressing in thumbsticks
+ Fixed typo where bumpers were referred to as axis, instead of triggers
Also I started mapping out the Windows versions, but I ran into some issues. Namely that the guide button wouldn't register, and both triggers were "Axis 4", with one being negative (resulting in some weirdness and overlapping values). I can make a pull request with a partially complete set of Windows values if you want though.
> + Added mappings for Xbox 360 Controller on Linux

- gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSprite.java
I removed a couple of redundant lines (I'll explain below) and added an optimization when setting a new region.
Resolves #3722 by correcting the docs for the `getColor` methods. I didn't simply say "don't modify the returned color" because it would be valid to pass the color back into `setColor`, which might be convenient if doing some sort of transformation on the existing color.
> PolygonSprite minor improvements

- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
new release to fix [incompatibility](https://bitbucket.org/dermetfan/libgdx-utils/issues/18/not-compatible-with-gwt-html5-on-libgdx#comment-32858945) with libGDX 1.9.5
> Update libgdx-utils 3rd party extension

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/gitignore
as discussed in #4560, here is the fix (maybe not the final fix).
I'm not really confident with these modifications because I'm not using all OS/IDE/Targets. I'm using eclipse on linux and mostly target desktop and android so I think this fix should be validated by more contributors.
Has you can see, what I've done so far is : 
* add leading slashes and full path to avoid unwanted ignore.
* removed some duplicates : for instance html/war/WEB-INF/deploy/ is useless with /html/war
* removed some IMO useless : tmp/
* move local.properties to gradle section
Note that I could use single wildcard instead of path for every sub project (for instance /*/dist/) but it could conflicts with some project specific folder structure.
@Tom-Ski : I don't really understand why you want to keep just one big …
> improve gitignore template fix libgdx/libgdx#4560

- gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java
MeshBuilder will give an error when trying to use Short.MAX_VALUE vertices in a mesh.  This means meshes created using MeshBuilder can only use (Short.MAX_VALUE - 1) total vertices.
A use case requiring the change would be a mesh pooling implementation using MeshBuilder currently needs to check against the size of (Short.MAX_VALUE - 1) instead of the actual number of vertices allocated in the mesh.
> MeshBuilder error using Short.MAX_VALUE vertices

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSApplication.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSNet.java
I am seeing several `EXC_BAD_ACCESS KERN_INVALID_ADDRESS` crash logs happening when `OALSimpleAudio.sharedInstance().setUseHardwareIfAvailable(false);` is called. 
The issue seems to be that the shared instance of `OALSimpleAudio` is sometimes not available and returns `null`. There is already a null-check in https://github.com/libgdx/libgdx/blob/14d89225ae26afc1cc7f52e986e566bf19425275/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSAudio.java#L34 for the very same reason.
This PR adds the same checks to `didBecomeActive` and `willEnterForeground` for the `OALAudioSession` and `OALSimpleAudio` instances. 
I also made a very small change to robovm `IOSNet` to accompany the latest changes to moe `IOSNet`.
> Prevent potential crashes in IOSApplication due to audio being unavailable

- gdx/src/com/badlogic/gdx/maps/tiled/renderers/HexagonalTiledMapRenderer.java
Fixed staggering on even indexes for HexagonalTiledMapRenderer (now the map has the same staggering as it appears in Tiled Editor)
> Fix #4536: HexagonalTiledMapRenderer staggering bug

- gdx/src/com/badlogic/gdx/graphics/Mesh.java
- gdx/src/com/badlogic/gdx/graphics/glutils/VertexBufferObjectSubData.java
I was finding it kind of hacky to work around this missing constructor. I wanted to work with a VertexAttributes object to calculate some stuff before instantiating the Mesh, so I ended up creating one and throwing it away before passing the same individual VertexAttribute objects to Mesh for it to generate another VertexAttributes.
Also, I could see someone possibly wanting to subclass VertexAttributes.
> Add Mesh constructor for VertexAttributes

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java
Pref height is not correctly calculated if BitmapFont scale Y is different to 1.
Label only takes into account fontScaleY correction for the descent value assuming the underlying Bitmap y font scale is 1. The correction should be the relation between the BitmapFont and Label scales.
Find SSCCE test attached that illustrates the issue
http://pastebin.com/EB7mv2AU
Before the fix
After the fix
> Fixes #4495 (wrong Label pref height)

- extensions/gdx-setup/src/com/badlogic/gdx/setup/data/extensions.xml
Updating VisUI to 1.3.0 and removing VisRuntime, no longer maintained.
> Updated Vis extensions

- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java
This make it possible for subclass to access `particles` array without using reflection.
> added getParticles protected method

- CHANGES
- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SplitPane.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/UITest.java
I've been using this in my project for a while and it has saved me a lot of time. This lets you set the SplitPane to respect the min size of the widgets in it, so the handle cannot shrink either inner widget to the point of cropping it. This is a lot easier than trying to manually calculate the split amount limits and also allows it to layout properly when you want this functionality.
I considered using prefSizes instead, but I think going down that path would make it ambiguous in usage. What I mean is, SplitPane crops widgets that are drawn smaller than their min sizes, so that's what we want to prevent. You can wrap it in a container if it doesn't already have a min size, or you want to use the pref size as a min size. Since the inner widgets are often Tables, this is usually not a …
> Add respect-min-size functionality to SplitPane

- gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java
its already allowed to change the debugAll variable in Stage.class, why not allow to access/read it as well ?
(its really inconvenient to access it in other ways)
> Stage: allow to access/read debugAll Variable

- extensions/gdx-controllers/gdx-controllers-android/src/com/badlogic/gdx/controllers/android/AndroidController.java
- extensions/gdx-controllers/gdx-controllers-android/src/com/badlogic/gdx/controllers/android/AndroidControllers.java
- tests/gdx-tests-android/build.gradle
- tests/gdx-tests-lwjgl/build.gradle
POV was reported as axes or buttons (depending on the controller) and not properly translated into `PovDirection`
Tested on Galaxy S6, Asus TF700, Nexus Player and Ouya with the following controllers:
- MOGA Pro Power
- Wireless Bluetooth Gamepad w/ Keyboard
- Nexus Player Gamepad
- Ouya Controller
- Logitech F510
- Thrustmaster Dual Trigger 3-in-1
- Thrustmaster T-Flight Stick X
> Add POV support to Android controller backend

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java
Pixmap's `format` is null, because #4234 incorrectly removed it.
See https://github.com/libgdx/libgdx/pull/4234/files#diff-193f92909143c2ad5b478ee1618ce414L126
> Fix GWT-Pixmap. Add missing format.

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java
Pixmap blending has been global state, but it recently became per pixmap-state.
So setting the blending should only change it for the current pixmap and not for
all pixmaps.
This works fine on desktop, but is broken on GWT.
> Fix blending being incorrectly used for gwt-pixmap

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ImageButton.java
- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ImageTextButton.java
It would be nice to be able to explicitly set the Drawable used by ImageButton and ImageTextButton at will so I'm not locked into the states defined in the style,, but `updateImage()` overrides that change in `draw()`. I know I can subclass Button directly, but this would make the whole process less of a hassle.
> Make updateImage() protected

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java
`TexturePacker$Settings#set(Settings)` used to copy array fields by reference. Now it creates new arrays for own fields.
> TexturePacker$Settings now correctly copies array fields from another instance

- gdx/src/com/badlogic/gdx/scenes/scene2d/utils/TextureRegionDrawable.java
The reason for this is so the TextureRegionDrawable itself, or any WidgetGroup that references it, can be used in a Pool. If you have a widget that is poolable and references any TextureRegion (indirectly through a TextureRegionDrawable), there needs to be a way to null out the TextureRegion reference for returning it to the pool. 
This moves the NPE from `setRegion` to `draw`, but presumably `draw` won't be called on it if it's been sent to a pool.
My use case is that I have a large panel of custom image buttons, and the number of buttons and the images vary each time the panel is brought up, so I wanted to pool the buttons to make it a bit more snappy.
> Can set null region on TextureRegionDrawable

- gdx/src/com/badlogic/gdx/graphics/Camera.java
It was not clear at a glance whether this expected radians or degrees (it's degrees).
> Specify units of angle for camera rotation on `Camera`

- gdx/src/com/badlogic/gdx/math/WindowedMean.java
`WindowedMean.getOldest()` usually returns the second oldest value.
Also added a method for getting the final part of the stream in order, to enable easy serialization/copying.
> Fix WindowedMean bug

- gdx/src/com/badlogic/gdx/graphics/g3d/environment/AmbientCubemap.java
I was running into an issue where sometimes on some versions of android (6.0) there was a crash with the ambient cube map. This issue has been mentioned by the community and looks like it might be an issue with pro guarding the file `AmbientCubemap.java`. I have patched the file and it looks like the crashes have gone away for me.
Since the cube map needs to always be sized with 18 elements anyways, I made a constant for the size as well.
No changes have been made to the actual functionality of the CubeMaps.
Libgdx forum [discussion](http://www.badlogicgames.com/forum/viewtopic.php?t=23411)
Sample Stack Trace:
`java.lang.ArrayIndexOutOfBoundsException: length=18; index=18 at com.badlogic.gdx.graphics.g3d.environment.AmbientCubemap.set(AmbientCubemap.java:60) at …
> Fix issue with ambient cubemap out of bounds

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
I noticed a fatal error during recreate window (second `Lwjgl3Application` instantiation in the same process). 
Bug reproduction:
```java
Scanner reader = new Scanner(System.in);
Lwjgl3ApplicationConfiguration conf = new Lwjgl3ApplicationConfiguration();
Thread t = new Thread(() -> new Lwjgl3Application(new AppListener(),  conf));
t.start();
reader.nextLine();  // press enter
Gdx.app.exit();
t.join();
reader.nextLine(); // press enter
t = new Thread(() -> new Lwjgl3Application(new AppListener(),  conf));
t.start();
reader.nextLine(); // press enter
Gdx.app.exit();
```
Error description:
```
#
#
#
#
#
Compiled method (nm)  194567 7362     n 0       org.lwjgl.system.JNI::invokeV (native)
total in heap  [0x0000000002c99510,0x0000000002c99870] = 864
relocation …
```
> Fix bug with recreate window in lwjgl3 integration

- .gitignore
- extensions/gdx-setup/src/com/badlogic/gdx/setup/BuildScriptHelper.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/Language.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/ProjectBuilder.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/core/build.gradle
- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/desktop/build.gradle
Supporting the new languages was primarily implemented through using a new Language enum containing the language-specific Gradle-related strings for the two supported languages (Java and Kotlin). Could be extended in the future to include other languages like Scala or Clojure.
I also edited the project build.gradle templates to be agnostic as to what language plugin they use.
This is feature that I personally felt I wanted to have, as tweaking new projects to compile Kotlin properly took a lot of time.
> Added "Use Kotlin" option for setup tool

- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
I implemented loading the color custom property from a tiled map file.
This fixes issues #4474 and #4756
I also tried to implement loading the file custom type but realized that it would be impossible without major refactoring or some hacky code.
> Load color properties from tiled maps

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/gitignore
This will improve `.gitignore` file generated by `gdx-setup.jar` tool.
In detail, inside `.xcodeproj` there are also unnecessary files which are
not needed to be included into git source tree. Those files include
local user's data (unique for each local user opening Xcode), but
particular folders are still need i.e. `xcshareddata` (for shared scheme
in case for more complex build process of executing build command
against shared scheme for project from external tool), and of course
`project.pbxproj` project file itself.
Also ignored artifacts as they are built dynamically in `native/` folder
of `ios/xcode/` and `ios-moe/xcode/`. Each built file (`.a`) has a several MBs in
size, and would be much better to exclude it. In tested, for project
that includes only Box2d, `native/` directory …
> Better ignore un-needed files for iOS platform - gdx-setup

- gdx/src/com/badlogic/gdx/math/Interpolation.java
The `clamp` isn't required here, because `a` is expected to be in `[0, 1]` for all `Interpolation` objects anyway. For example, `Interpolation.linear.apply(3)` would return `3` not `1`.
Ken Perlin [clamped only a version](https://en.wikipedia.org/wiki/Smoothstep#Variations) where you interpolate between an `edge0` and `edge1` argument
> Removed unnecessary clamp in Interpolation.smoother

- gdx/src/com/badlogic/gdx/math/WindowedMean.java
Oops, `WindowedMean.getOldest()` is still wrong in some cases. I blame the field name for confusion. :) This fixes it for all cases.
Simple test to prove it:
>     WindowedMean wm = new WindowedMean(5);
>     for (int i=0; i<50; i++){
>         float newValue = MathUtils.random();
>         wm.addValue(newValue);
>         System.out.println(String.format("Added new value %f. Oldest: %f. Latest: %f.",
>                newValue, wm.getOldest(), wm.getLatest()));
>     }
> Fix WindowedMean, part 2

- gdx/src/com/badlogic/gdx/graphics/Mesh.java
This is a pull request to throw an exception if a Mesh tries to render with indices outside of the index array. Created because of #4697
> Mesh needs to check index array, resolves #4697

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java
- gdx/src/com/badlogic/gdx/graphics/Pixmap.java
Pixmap needs a `getFilter()` method so it can be copied or serialized.
**Also:** GWT's Pixmap had initial state of null for `getBlending()`. It should have an initial state so the getter method will have the same results across platforms. That's why I also added a `filter` parameter, even though it goes unused.
> Add getFilter and fix GWT getBlending

- gdx/src/com/badlogic/gdx/graphics/g2d/Animation.java
- gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/AnimationTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/TextureAtlasTest.java
Fixes #4476.
An animation instantiated with an Array was using a backing Object array instead of the correct array type, causing possible CCE when calling `getKeyFrames()` and assigning it to its expected type.
Now it uses the same backing type as the Array that's passed in, so as long as the Array was instantiated with a type parameter, you're good to go. I updated TextureAtlas to return type-aware arrays in `findRegions()` since this is a common source of animation frames.
> Avoid type-unaware Animation (fixes #4476)

- extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/OisControllers.java
When the window handle is lost, for example when going from windowed to full screen, a new instance of OIS is created and the controllers are cleared and re-added. Listeners added to the individual controllers were lost in the process.
This fixes issue #4723 by matching the newly added controllers to the ones being removed and transferring the listeners over.
> Preserve individual OIS controllers listeners on lost window handle

- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffect.java
- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffectPool.java
- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/ParticleEmittersTest.java
Fixes #2893.
The scaleEffect() method is not easily reversible in the ParticleEffect class, unfortunately. But the PooledEffect class has easy access to the original parameters in the prototype effect in the pool, which is the common way ParticleEffects are used anyway.
Since the ParticleEffect super class is unchanged, this fix won't break code that was relying on `reset()` not affecting scale.
> Restore ParticleEffect scale when returning to pool (Fixes #2893)

- extensions/gdx-controllers/gdx-controllers-gwt/src/com/badlogic/gdx/controllers/gwt/GwtController.java
- extensions/gdx-controllers/gdx-controllers-gwt/src/com/badlogic/gdx/controllers/gwt/GwtControllers.java
- extensions/gdx-controllers/gdx-controllers-gwt/src/com/badlogic/gdx/controllers/gwt/support/Gamepad.java
- extensions/gdx-controllers/gdx-controllers-gwt/src/com/badlogic/gdx/controllers/gwt/support/GamepadButton.java
- extensions/gdx-controllers/gdx-controllers-gwt/src/com/badlogic/gdx/controllers/gwt/support/GamepadSupport.java
- tests/gdx-tests-gwt/build.gradle
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
Due to changes in the way browsers handle controllers since the extension was written, the GWT controllers extension wasn't working anymore. Fortunately, all major browsers now pretty much conforms to the W3C working draft so the extension shouldn't break too much in the future.
This updates the extension to use the currently supported controller api. I've also added proper POV support for gamepads reporting a "standard" mapping. In my tests, only XInput gamepads reported as "standard" and everyting else had different ways of reporting their pov, which also differed between browsers.
This was tested as working on Chrome, Firefox and Opera.
> Update GWT controller extension and add POV support

- gdx/src/com/badlogic/gdx/graphics/g3d/particles/particles.fragment.glsl
The changes introduced by #4621 cause the JVM to crash on desktop (just run the FlameEditor and it will crash). It seems like the constructor `mat2(vec4)` causes the crash. Passing the 4 components separately fixes it.
Note that I can only test on desktop.
> Fix jvm crash introduced by changes to the particles shader (#4621)

- tests/gdx-tests/src/com/badlogic/gdx/tests/extensions/FreeTypeFontLoaderTest.java
After spending few hours to understand why I get the "Couldn't load dependencies of asset" when tried loading same font with different parameters, I've found out that the name cannot be fully arbitrary as it says in the comment - It must have the suffix of file format.
> Edited a comment

- gdx/src/com/badlogic/gdx/graphics/glutils/FileTextureData.java
I think this method is left over from when GL 1 support was removed. `gl20` is never null.
> Remove obsolete code

- gdx/src/com/badlogic/gdx/graphics/glutils/VertexArray.java
Easy to reproduce by running Scene2dTest with visualVM : a new DirectFloatBufferU was created for each attribute binding causes a lot of garbage in memory.
Since vertex array already maintains a FloatBuffer view of its bytes it is possible to pass the float buffer for float type and then avoid unnecessary conversion.
> avoid unnecessary FloatBuffer allocation

- gdx/src/com/badlogic/gdx/graphics/glutils/FrameBufferCubemap.java
Easy to reproduce by running FrameBufferCubemapTest with visualVM.
> cache cubemap sides to reduce memory consumption

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java
If the scroll bars won't be visible (either because they aren't needed or the alpha will be 0) then don't bother drawing the bar or the knob.
This was prompted by chasing down why I had a 12 vertex draw call happening that resulted in no change to the backbuffer. The bar's were faded out, and then the camera view changed immediately after drawing the scroll pane which results in a wasted and unneeded draw call.
Edit: CLA was mailed in today as well.
> ScrollPane: Don't render scroll bars if they won't be visible on screen

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidLiveWallpaperService.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidWallpaperListener.java
- tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/LiveWallpaper.java
This adds one more callback for the LiveWallpaperListener, for an icon dropped event, which tells you when and where an icon was dropped on the home screen. I don't think the Android specifications enforce this feature, but it worked in a couple of launchers that I tested.
> Add icon dropped callback to live wallpaper listener

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/List.java
This allows uses like the following, without the need for copying the
entire array:
Array<String> items = list.getItems();
items.add("hello world");
list.setItems(items);
Issue #2834 suggests that this should work, but it doesn't; it clears
the items instead.
It seems unlikely that anyone would use that on purpose (as
`List#clearItems()` already exists), so this change is unlikely to break
anyone.
> Allow List#setItems() with the original items

- CHANGES
- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/EffectPanel.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java
- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffect.java
- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffectPool.java
- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java
This makes it possible to set scale X and Y independently. When scaleY is not active, scaleX is used for both X and Y.
The editor has been updated accordingly. The loader is backward compatible with the previous file format.
This PR is mergeable with my other PR "animated particles"
> Add support for 2d particle independant scale X and Y

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSDevice.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSDevice.java
Provide screen density information for iPhone 8, iPhone X and recent iPads.
Information gathered from:
* https://www.theiphonewiki.com/wiki/Models ("iPhone10,3" style labels & screen density info)
* http://www.gsmarena.com/apple_iphone_8-8573.php#a1863 (CDMA/GSM info)
_Similar to #4037_
> Add iPhone 8, X and new iPads to IOSDevice

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java
WebGL 1 compatible : https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getParameter
I also fixed the error message.
> added GWT retrieve viewport support

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java
Hello,
I am working on improvements for [https://github.com/yangweigbh/Libgdx-CardBoard-Extension](https://github.com/yangweigbh/Libgdx-CardBoard-Extension). It has a lot of duplicated code, I am reducing this extending original classes from libgdx.
But sometimes some methods still need to be called from super so I am turning them into protected to make this improvements easier.
> Turn updatePpi, setupGL and logConfig methods protected

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSApplication.java
- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSInput.java
See my forum topic for my original issue.
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=26824
I'd love to make stuff like the CMMotionManager protected too so it's behavior can be adjusted from subclasses, but as it's a multi os engine binding that might make it easy for people who have no experience with MOE to introduce bugs so I thought I'd check if you guys accept this change first.
About the removal of "HiddenTextField", I am pretty sure that it is not being used. My app works fine without it. I have looked in the forum topic mentioned in the comment (http://www.badlogicgames.com/forum/viewtopic.php?f=17&t=11788) and that seems to be about RoboVM rather than MOE.
If something needs work let me know in the comments or on the forum topic.
> Made it possible to let the IOSApplication use IOSInput subclasses.

- CHANGES
- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/ImageProcessor.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePackerUpscaleTest.java
As per request in #4934, new option addition in Settings under TexturePacker to specify the array of interpolation modes per scale factor. No breaking changes in the API, and fully backwards-compatible assuming Bicubic (which was the default) in case nothing is being specified.
Contributor agreement has been signed and emailed.
> Fix #4934: Option in TexturePacker.Settings to specify the InterpolationMode when scaling

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
Hi,
This weekend we had some fun trying to make get [imgui](https://github.com/kotlin-graphics/imgui) work with libgdx, it took a while but we made it for the moment.
However the [solution](https://github.com/elect86/Platform-Creator/commit/ec27570dcae85702f6572f8677b0f5a38c1da378#diff-8c268ab50f87b7ce67e90b3b258ece0cR175) involvs reflection and doesn't shine as a perfect and clean implementation.
That's why I'd like to have `Lwjgl3Window.getWindowHandle()` as a public method (currently is package only) in order to avoid using reflection to access it.
> Make Lwjgl3Window.getWindowHandle() public accessible to play nice with imgui

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Touchpad.java
`Touchable.disabled` or `Touchable.childrenOnly` was ignoring for `Touchpad ` Actor. So `setTouchable(..)` for it didn't make sense.
> Fix: Touchpad ignore Touchable value.

- gdx/src/com/badlogic/gdx/maps/tiled/AtlasTmxMapLoader.java
There was an issue with tile indexing in tileset when using the AtlasTMXMapLoader.
It actually fix the libgdx test named "TideMapAssetManagerTest", now you can see the missing ground !
I created a SSCCE to illustrate the problem but I saw it fixes an existing libgdx test. I provide my SSCCE though, just in case : there is a static variable "useOriginal" allowing to switch from original (using TMXMapLoader) to the same generated with the TiledMapPacker tool (using AtlasTMXMapLoader).
[tmx-sccce.zip](https://github.com/libgdx/libgdx/files/1463628/tmx-sccce.zip)
> fix AtlasTmxMapLoader tileset tile id offset

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/android/AndroidManifest.xml
- tests/gdx-tests-android/AndroidManifest.xml
Some Bluetooth keyboards need to have the `navigation` element added to the `android:configChanges` part of AndroidManifest in order to trigger the `onConfigurationChanged()` method.
Without this, `Gdx.input.isPeripheralAvailable` will always return false as the `keyboardAvailable` variable doesn't get updated.
This fixes issue #4968
> Fix for some Bluetooth keyboards not being detected

- gdx/src/com/badlogic/gdx/graphics/g2d/Sprite.java
As per this issue/request [Set origin based position on Sprite #4817](https://github.com/libgdx/libgdx/issues/4817)
> Added setOriginBasedPosition to Sprite class

- gdx/src/com/badlogic/gdx/assets/loaders/SkinLoader.java
Skin's Json-loading behavior can be highly customized by overriding `getJsonLoader`, but then the subclass needs a custom Loader class for use with AssetManager. So I exposed a method for instantiating the skin.
Usage:
```
manager.setLoader(Skin.class, new SkinLoader(manager.getFileHandleResolver()){
public Skin generateSkin (TextureAtlas atlas) { 
return new MySkinSubclass(atlas); 
}
});
```
> Can use Skin subclasses with SkinLoader

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Skin.java
- gdx/src/com/badlogic/gdx/utils/Json.java
- tests/gdx-tests-android/assets/data/uiskin.json
This is #4287 revised. Sorry for creating a new PR. I had some kind of name conflict by giving my local branch the same name with different capitalization, and for the life of me cannot figure out how to push to the branch from the original PR.
@NathanSweet I made the method name changes you requested. I started trying out the idea you had for putting `copy()` methods into Json ([here](https://github.com/cypherdare/libgdx/tree/stylecascadeJsonCopy)), but it got really ugly when it came time to copy the classes that are typically used in a Skin. There are many references to Textures and various other objects deep in the object graph of a simple style. I don't think it makes sense to create a bunch of serializers to carefully handle all these fields. Skin has not been set up to write the …
> Add cascading style support to Skin (updated)

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationConfiguration.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtNet.java
- tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/client/GwtTestStarter.java
- tests/gdx-tests/src/com/badlogic/gdx/GdxTests.gwt.xml
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/net/OpenBrowserExample.java
When calling Gdx.net.openURI on a GWT module using 
an iPhone or Android phone you may get a popup blocked (see #5036). This addresses it by changing the windows location.
Tested on Chrome/Safari on computer and mobile devices.
> Gdx.net.openURI blocked as popup when using iOS browser on iPhone or Chrome on Android phone #5036

- extensions/gdx-controllers/gdx-controllers-android/src/com/badlogic/gdx/controllers/android/AndroidControllers.java
This is a partial fix for issue #4969
Based on my testings, compiled in [this handy Google spreadsheet](https://docs.google.com/spreadsheets/d/1oYoYMfCv8QlOgEyPxwcdLifjXVIOveu9aopEXl6UjnE/edit?usp=sharing), I have modified the ``isController`` method to avoid false positives as some keyboard and mice are detected as game controllers with the current detection method.
> Improved Android controllers detection

- extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/FlameMain.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleController.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleEffect.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleSystem.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/emitters/RegularEmitter.java
-The ParticleController stores a frame time in its deltaTime member but this value is hard-coded at 1/60 regardless of framerate. This change adds an overload to the
ParticleController's update() method to take the delta time. This allows the particles to adjust
their time deltas for faster or slower framerate. The change also
allows callers to cause particle effects to be played back at faster or slower
speeds.
-This change also adds overloads for update() and updateAndDraw() of the ParticleSystem class,
each of which takes a frame time and adds an overload for the ParticleEffect update() method.
-RegularEmitter previously only used the floor of the number of milliseconds that had passed since
the last update when calculating percent of the lifetime lived for each particle. For playback …
> make ParticleController deltaTime not hard-coded

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SplitPane.java
Makes it possible on desktop to react to hovering over the handle, such as changing the cursor to indicate it's draggable.
> Add SplitPane.isCursorOverHandle()

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java
In most cases this can be annoying to the user, but I found it necessary after using SWT to pick a file from the native file chooser. Might also be handy if you're using multiple windows for some reason.
> Add focusWindow() to Lwjgl3Window

- gdx/src/com/badlogic/gdx/utils/PropertiesUtils.java
Currently after PropertiesUtils.store, all spaces in values are getting removed.
> Fix PropertiesUtils space handling during output

- extensions/gdx-controllers/gdx-controllers-android/src/com/badlogic/gdx/controllers/android/AndroidControllers.java
This fixes #4969
On Android, when using a hybrid controller w/keyboard, the keyboard key presses were reported as controller buttons.
> Prevent controller extension from swallowing keyboard events

- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
Fixes #5110 
Tested on a iOS 11 device and iOS 8.4 simulator (confirm it doesn't crash on iOS < 11).
I don't have experience on iOS MOE but the fix hasn't been implemented there because it doesn't seem to have the binding for `UIViewController#preferredScreenEdgesDeferringSystemGestures`.
> Fix #5110. Add screen edges that override system gestures on RoboVM configuration

- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
Fixed the missingGlyph of FreeTypeBitmapFontData doesn't initialized.
If the missingGlyph doesn't initialized, any glyph which not found will not rendered by the default glyph.
> Fixed the missingGlyph of FreeTypeBitmapFontData doesn't initialized.

- gdx/src/com/badlogic/gdx/assets/AssetManager.java
AssetManager#isLoaded and AssetManager#finishLoadingAsset normally only take a String for the filename of the asset.
If you want to check if an asset is loaded or you want the AssetManager to block for it to finish loading using an AssetDescriptor, you must use AssetDescriptor.fileName for these methods.
This change adds overloaded methods for both isLoaded and finishLoadingAsset to take an AssetDescriptor for convenience.
> Overload AssetManager#isLoaded and #finishLoadingAsset to take AssetDescriptor as parameter

- tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneTextAreaTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
Renamed the test as to appear among the ScrollPane tests in the test launcher.
There are still bugs when embedding a TextArea in a scroll panel, one line always falls outside the scroll range.
> Added missing ScrollPaneTextAreaTest to GdxTests

- gdx/src/com/badlogic/gdx/graphics/GLTexture.java
ES2.0 does not specify if gltexparameterf does appropriate type conversion. Enums should be integers.
> GLTexture - gltexparameter i instead of f

- extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers/Controllers.java
This allows providing a custom controller manager, while still implementing the controller API and events. This is useful as a resolution for #5166 with a minimal patch set that the application has to carry with it, while still integrating well with the rest of LibGDX.
> gdx-controllers: allow specifing custom controllers

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Button.java
This allows setting a background image for a button in focus.
Modeled it after the was the `focused` field is handled in `TextField`.
It's completely optional, shouldn't break any existing code.  `over` takes priority over `focused`.
`checkedFocused` also included.
Didn't add anything for the `Button` subclasses, but it would be reasonably simple to add equivalent fields for font color, checkbox, etc... in the appropriate subclasses.
The `if` statements I modified also have had curly braces added to match the recommendations in https://github.com/libgdx/libgdx/blob/master/.github/CONTRIBUTING.md
I've contributed in the past so I *believe* I've signed the CLA but if it's not on record I'd be happy to sign again.  I also didn't update `CONTRIBUTORS` or `CHANGES` since it's such a small …
> Add focused to ButtonStyle

- extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers/mappings/Xbox.java
Fix for issue #5061
- Made the check for the "Xbox" string case insensitive as it differs between backends.
- Provided mappings for LWJGL and LWJGL3 backends
- Provided detection and mapping for the Android backend
The triggers on the LWJGL backed behave incorrectly since OIS treats the controller as a DirectInput controller and doesn't provide individual axes for them.
> Update mappings for Xbox controller

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/Wav.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/Wav.java
as explained in #5254 when a WAV file is read from a jar (desktop packaging), the music buffers are not correctly filled (not frame aligned) and OpenAL returns an error. The underlying input stream in this case doesn't respect Java specification : 
> Reads up to len bytes of data from this input stream into an array of bytes. If len is not zero, the method blocks until some input is available
I didn't investigate further since it's related to [zlib native java code](http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/tip/src/share/classes/java/util/zip/ZipFile.java#l744) but i suspect inflater to just inflate a chunk which could give some random output sizes : I checked with debugger, the size returned was always different, sometimes odd sometimes even ...
I was able to test it locally by …
> fix buffer underflow with WAV file music read from jar, fixes #5254

- gdx/src/com/badlogic/gdx/utils/StringBuilder.java
Convenience method clear() for StringBuilder.
Does exatcly the same thing as "stringBuilder.delete(0, stringBuilder.length)" without the in this case unnecessary System.arraycopy and is much nicer to write and understand.
> StringBuilder.clear()

- gdx/src/com/badlogic/gdx/math/Ellipse.java
Hello! I happened to notice that when I use ellipse constructed with a circle, the real area of the shape became smaller.
I changed constructor Ellipse(Circle) and Ellipse.set(Circle). Shouldn't Ellipse's width & height be radius * 2f to match the original circle?
> Shouldn't Ellipse's width & height be radius * 2f to match the original circle?

- gdx/src/com/badlogic/gdx/utils/Json.java
- tests/gdx-tests-android/assets/data/uiskin.json
Reverse the requirements on fields in copyFields(), so superclass objects can be copied to subclass objects.
Fixes #5268: Allow superclasses to be used as parent styles in Skins
> Reverse the requirements on fields in copyFields()

- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeType.java
- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
- gdx/src/com/badlogic/gdx/utils/BufferUtils.java
Should allow a lower memory footprint and faster startup times on Desktop/Android.
Android requires users to manually edit their gradle config to include certain aaptOptions to not compress font files. Would we want to include this in the default project setup?
Such as:
`android {
aaptOptions {
noCompress 'ttf', 'ttc', 'otf'
}
}`
> FreeType - Use zero copy memory mapping when possible

- CHANGES
- gdx/src/com/badlogic/gdx/graphics/Color.java
- gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFontCache.java
- gdx/src/com/badlogic/gdx/graphics/g2d/NinePatch.java
- gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSpriteBatch.java
- gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java
- gdx/src/com/badlogic/gdx/graphics/g2d/SpriteCache.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/MeshShaderTest.java
It is used often in libGDX, sometimes as a private constant. In my projects I often ended up creating such constant myself, but the correct place for it is arguably in the `Color` class itself.
One could argue that this special treatment of single color creates API asymmetry, but WHITE is somewhat special color, so this should be fine.
Some colors were reordered for consistency.
> Shorthand constant for WHITE.toFloatBits()

- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ScaledNumericPanel.java
- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java
Fixes #5280.
Added a new setting ("Independent" checkbox) to Life and Life Offset properties that allows that when defining a ranged value it affects each particle independently instead of all particles. The change is backwards compatible with previously created effects which should behave exactly like before.
As a side note, it has been quite challenging to add the new setting in a clean way (and it's still not great) due to how the Particle Editor is designed and the rigid particle effects file descriptor format. The 2D Particle system definitely deserves a good refactoring :).
There's a link to the new 2D Particle Editor .jar in the issue comments if you want to try it.
I'll squash changes when I get the Ok.
**Do changes to the Wiki need to be part of the PR?**
> Fix #5280 - Added Independent setting to Particle Editor Life properties

- gdx/src/com/badlogic/gdx/math/Intersector.java
On rare occasions, Intersector.intersectSegmentPlane would set the intersect vector to (NaN,NaN,NaN) and return true. I found this was due to divide by zero error from denom. This could be my problem of not validating parameters but it would be helpful if a check was added to return false if denom == 0 or within epsilon.
> Small update to Intersector intersectSegmentPlane

- extensions/gdx-tools/src/com/badlogic/gdx/tools/bmfont/BitmapFontWriter.java
BitmapFontWriter currently has an import of Hiero, which only works on desktop (so I'm informed).
After going through the class, the only place Hiero is used is in a javadocs link that mentions BitmapFontWriter is identical in output to Hiero.
> Fixed BitmapFontWriter not working on Android (and possibly others)

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Slider.java
For example when its in a ScrollPane and we dont want to stop the event.
> Fix invalid position being used when touch focus is cancelled in Slider

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSDevice.java
Provide screen density information for the recent iPhone Xs models.
Information gathered from:
https://www.theiphonewiki.com/wiki/Models ("iPhone10,3" style labels & screen density info)
http://www.gsmarena.com/
Similar to #5295, #4911, #4037
> Add device information for new iPhone Xs models

- tests/gdx-tests/src/com/badlogic/gdx/tests/Box2DTest.java
A diamond op is missing from `Box2DTest` which causes `gradle build` to fail.
> Fix Missing Diamond Op

- gdx/src/com/badlogic/gdx/graphics/g3d/Material.java
This allows subclasses of Material to correctly copy themselves.
Also, the final keyword is rarely used on functions in LibGDX elsewhere.
> Removed final from Material.copy

- gdx/src/com/badlogic/gdx/graphics/g2d/PixmapPacker.java
Fixes an issue where using PixmapPacker in multiple threads would cause incorrect split values.
> Fix pixmap packer concurrency issue in splits

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSApplicationConfiguration.java
- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSUIViewController.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
On new iPhones, all modern games hide the home indicator. In LibGDX there should be this option too.
> flag "prefersHomeIndicatorAutoHidden" is now configurable

- gdx/src/com/badlogic/gdx/utils/JsonValue.java
Getting primitive type from JsonValue leads to exceptions if the given value is 'null'. 
Getting a String has a check for nullType and returning a default value instead. This check is missing for the primitive types (boolean, int, ...)
With this addition all request for values with default values should behave same.
> Added check for nullValue in JsonValue for primitive types

- tests/gdx-tests-android/obb.gradle
In the _build.gradle_ file inside the main project's root folder, the following is set:
`version = '1.9.9-SNAPSHOT'`
In the _zipAssets_ task of _obb.gradle_, which sits in the _tests/gdx-tests-android/_ folder, Gradle appends the value of _baseName_ with the value of version from above.  This results in the tasks depending on _zipAssets_ to fail.
The fix involves the following in the _zipAssets_ task:
a)  Replacing "_baseName_" with "_archiveName_"
b)  Adding _.obb_ to the end of the file name
c)  Deleting _extension_ and its value
> Changed the zipAssets task to produce a proper file name

- extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TextureUnpacker.java
use original region size when unpacking atlas
> Update TextureUnpacker.java (use original region size when unpacking atlas)

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/android/AndroidManifest.xml
The minSDK and targetSDK are configured on build.gradle, this settings are unused
> Removed unused minSDK and targetSDK on android manifest

- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/ParticleEmitterTest.java
fix for issue #5458
If you press '+' while running the particleEmitter test you now create a copy of the existing particleEmitter.
Before the fix the copy is created at position 0,0 after the fix the copy is created at the source position
> fix for issue #5458: ParticleEmitter copy Constructor does not copy position

- gdx/src/com/badlogic/gdx/utils/I18NBundle.java
When developing a project, it's common to hardcode strings during testing rather than localizing them. Usually the developer will miss lots of unlocalized strings. A common method to spot unlocalized strings is to create another localization file with some placeholder value like "X" for every single value. This makes it easy to see what strings haven't been localized in game. To avoid having to maintain another localization file, the debug() method in I18NBundle will set all strings to placeholder to simplify this process.
> Added debug mode to I18NBundle

- gdx/src/com/badlogic/gdx/graphics/PixmapIO.java
PNG libGDX class has an extremely efficient way to flip the Pixmap. Currently the writePNG utility method assumes the Pixmap is already flipped which is quite a heavy task if you need to flip it manually before. For example taking a screenshot using libGDX classes does this https://github.com/libgdx/libgdx/wiki/Taking-a-Screenshot. 
The new overriden method makes taking a screenshot more efficient (30ms improvement on a Nexus 5X) and simplifies the code to 3 lines:
`Pixmap pixmap = ScreenUtils.getFrameBufferPixmap(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());`
`PixmapIO.writePNG(fh, pixmap, true);`
`pixmap.dispose();`
> Add overriden writePNG method with flipY as parameter

- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
Y-positive is naturally DOWN in Tiled. The default value of true makes it UP.
> Fixed documentation in BaseTmxMapLoader

- gdx/src/com/badlogic/gdx/maps/tiled/TiledMapTileLayer.java
Documentation used to say it was in degrees, but it isn't. It's in 0-3 integer value which denotes 90 degree turns.
It is /never/ used as degrees. As shown in the screenshot below
https://i.imgur.com/RYeIucN.png
> Fixed documentation for rotation in TiledMapTileLayer.Cell

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Input.java
Opening a new PR with a proper branch, some improvements and squashed commits.
OSX generates many events when scrolling with the touch pad. This is
also the case for mouses that have a continuous wheel. Lwjgl3 reports
small movements with a scroll value lower than 1. The Lwjgl3 backend
rounds these values to 1 or -1. If there are many such "small" events
the scrolling becomes ultra fast.
The current fix accumulates the scrolling values reported by Lwjgl3
and sends a Gdx scroll event when the summed value is greater than
1. This is done until the accumulated value is lower than 1. This
approach also supports accelerations which are reported as scrolling
value greater than 1. These values become a stream of 1 or -1 scroll
events.
There is also an event which is triggered when the user …
> Fixing scroll event rate

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSUIViewController.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
Using the Firebase Analytics api for iOS (https://firebase.google.com/) and using the MOE backend, the analytics will not generate "screen_view" events either automatically or manually due to the fact the IOSUIViewController overrides the `viewDidAppear(boolean)` method, but does not call `super.viewDidAppear(boolean)`.  So firebase thinks there are no screens showing and does not track the screen view.  In addition, it also does not let you manually set the screen information (to hook it up to scene2d screen views) because it requires at least one view controller appears before doing so.
This issue fixes the issue with Firebase Analytics not detecting that a view controller has appeared so even manual screen tracking gets ignored and you would see this log line:
```
2018-10-26 …
```
> Made ViewController call super.viewDidAppear to allow hooks for screen tracking

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/util/Locale.java
This commit gives I18NBundles on GWT backend the ability to switch to the user language returned from the browser by default, matching the behaviour on other platforms.
For testing, use Firefox and change the preferred language settings or use Chrome on Android and change the system language. (Chrome on desktop always returns the language of the operating system)
I made also a cleanup of the class, deleting all the lines that are just commented out for four years.
> GWT: Default localization depending on user language

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/war/index
This PR avoids blurry resolution when HTML5 build is played on smartphones. See #5340 for more information.
> GWT: Set the viewport for mobiles to device's native resolution

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java
At this point of time, it is not possible to detect if a hardware keyboard is connected on GWT. So we assume that a mobile device has a soft keyboard while a desktop device has a hardware keyboard.
> #5137 isPeriphalAvailable HardwareKeyboard on GWT

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/android/AndroidManifest.xml
The category is used by some launchers to categorize the app icons.
> Add game category to AndroidManifest

- gdx/src/com/badlogic/gdx/Net.java
- gdx/src/com/badlogic/gdx/net/NetJavaImpl.java
Setting the method to "PATCH" on a request causes it to be sent without a body but still with the PATCH verb.
This PR makes PATCH a proper HTTP verb in libgdx. The alternative would be to make the HTTP classes throw an exception when unsupported verbs are used instead of failing silently like it does now.
> Add support for HTTP PATCH

- gdx/src/com/badlogic/gdx/utils/Queue.java
- gdx/test/com/badlogic/gdx/utils/QueueTest.java
Fix for https://github.com/libgdx/libgdx/issues/5471
If head < tail, we weren't accounting for head when computing the index, resulting in the returned index being far too large.
> Change how we compute indexOf to account for a moving head value.

- gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java
There's a bug in the particle emitter when using ellipsis as the spawn shape.
Uncompress and load this file in the [ParticleEditor](https://github.com/libgdx/libgdx/wiki/2D-Particle-Editor):
[test.tar.gz](https://github.com/libgdx/libgdx/files/2683939/test.tar.gz)
The rendered effect is not an ellipsis:
Ellipsis shape is created by generating points in a circle of radius `width/2` and then stretching Y axis to height. The circle was getting clipped since the particles were being generated inside the bounding box of the spawn, which can be smaller than the circle of radius `width/2`.
Generate the particles inside a box of `width` by `width`. Then the stretching will be done properly. Only one line changed.
This is how it looks with the fix.
> fix horizontal ellipsis shape in particle emitter

- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglInput.java
Make desktop input dialog for Gdx.input.getTextInput modal and set it to be always on top, because currently when executing getTextInput on the desktop sometimes the input dialog gets under the game window, so it's invisible.
> Make desktop input dialog modal

- gdx/test/com/badlogic/gdx/math/BezierTest.java
Parameter {0} should be type and {1} should be "use setter" boolean.
> Fix parameters annotation in BezierTest

- gdx/src/com/badlogic/gdx/utils/PooledLinkedList.java
tail.next is still referring to the old (now freed) tail.
So first assign the new value to tail, then change the tail.next value.
> Don't refer to freed element. Fix by order change.

- gdx/src/com/badlogic/gdx/assets/loaders/CubemapLoader.java
- gdx/src/com/badlogic/gdx/assets/loaders/TextureLoader.java
These look to just be left over copy paste artifacts.
> Remove unused Pixmap's from AssetLoaders

- CONTRIBUTORS
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/NumberUtils.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/google/gwt/corp/compatibility/Numbers.java
- gdx/src/com/badlogic/gdx/utils/NumberUtils.java
This has been marked NYI and FIXME for a long, long time, and it's an easy fix, following the behavior of the float and int conversion. This also fixes a compatibility bug introduced in 1.9.9; `NumberUtils.floatToIntColor()` was changed in the main project but not in GWT. There was also an unused import of `Color` in `NumberUtils`. I believe at least one test on GWT fails without this PR, calling `Numbers.doubleToLongBits()`, `Numbers.doubleToRawLongBits()` or `Numbers.longBitsToDouble()` and getting a NYI exception, but I don't know which one it was.
> Implement double to-and-from long on GWT

- gdx/src/com/badlogic/gdx/graphics/g3d/Model.java
I know the ObjLoader isn't considered production ready, but I have an improvement that allows loading large models without using indexing. Although there is talk about the number of vertices in an OBJ needing to be less than 32k to prevent index overflow, it appears there is some effort made to fall back to not using indexing in these cases. As seen in ObjLoader.loadModelData() (234):
```
// if there are too many vertices in a mesh, we can't use indices
if (numIndices > 0) {
for (int i = 0; i < numIndices; i++) {
finalIndices[i] = (short)i;
}
}
```
This leaves the finalIndices to be an array of zero. All of the other Model/Mesh classes all support non-indexed configurations except for Model.convertMesh():
```
meshPart.size = part.indices.length;
```
This causes the mesh part size to be …
> Allow handling of zero length indices which indicates a non-indexed mesh part.

- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneWithDynamicScrolling.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
Calling ScrollPane scrollTo just after changing children size didn't work.
A another way (workaround) was to manually validate scrollPane before calling scrollTo but i think it's better to do it automatically in ScrollPane class. @NathanSweet What do you think?
It fixes #5488 and in some way #4561 as well : I'll comment on the latest issue.
> fix libgdx/libgdx#5488 ScrollPane scrollTo

- gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java
Bug introduced in f78d903329de901f5beaa92de124457b4e122271
[`down` is positive when using flipped fonts](https://github.com/libgdx/libgdx/blob/5b623668791dde2fa93a95af0d2f6a08a465d194/gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java#L703) so we should use addition like we used to with lineHeight.
> Fix GlyphLayout height calculation when using flipped fonts.

- build.xml
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/scripts/build-target.xml.template
* Adding "-Drelease=true" will call "${compilerPrefix}strip --strip-unneeded ${libName}" after compilation.
* Default value for release is "false"
* Stripping has no influence on ram usage, symbol tables are not loaded into ram.
* OSX is not stripped as they appear pre-stripped (in 1.9.9 release) and OSX's gcc implementation lacks `--strip-unnecessary` as an option.
Would allow desktop builds which bundle all libs into a single jar to be ~2.5MB smaller.
```
16614038 1.9.9-unstripped.zip
14134108 1.9.9-stripped.zip
```
1.9.9 unstripped raw sizes:
```
453284   gdx64.dll
711442   gdx-box2d64.dll
609229   gdx-box2d.dll
8445098   gdx-bullet64.dll
8089255   gdx-bullet.dll
2665154   gdx-controllers-desktop64.dll
2153195   gdx-controllers-desktop.dll
390774   gdx.dll
784149   gdx-freetype64.dll …
```
> NativeBuild/Jnigen: add option to strip desktop binaries.

- gdx/jni/gdx2d/gdx2d.c
Pixmap blending is incorrect. Eg, if dst is `0,0,0,0` and src is `255,0,0,40` then the resulting pixel is `40,0,0,39` (alpha would be 40 instead of 39 if round was used instead of cast to int). The expected resulting pixel is `255,0,0,40`. The example code below shows (from bottom to top):
1. the source image
2. no blending
3. gdx2d "source over" blending
4. Java port of [gdx2d blend](https://github.com/libgdx/libgdx/blob/master/gdx/jni/gdx2d/gdx2d.c#L167-L183)
5. a proposed fix
Related: #4364, #3917
```java
import java.nio.IntBuffer;
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.badlogic.gdx.graphics.GL20;
import …
```
> Fixed pixmap blending.

- gdx/src/com/badlogic/gdx/graphics/g3d/utils/BaseAnimationController.java
- gdx/test/com/badlogic/gdx/graphics/g3d/utils/AnimationControllerTest.java
this is a replacement for #4377
It's mostly inspired by the original PR with overall improvements and fixes to not break previous behavior.
It performs a kind of binary search with an heuristic based on time range.
Junit tests included. I had to change method visibility in order to test it.
Don't hesitate to tell me if you think it should be more documentated or if you think i missed some test cases.
> optimize 3D animation key frame search

- extensions/gdx-jnigen/pom.xml
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/parsing/RobustJavaMethodParser.java
- gradle/dependencies.gradle
Reverts libgdx/libgdx#5591
Sorry, I didn't see that it requires Java 8. Besides this, we don't have a strong need to move to Java 8 source. Discussion is here:
https://github.com/libgdx/libgdx/issues/5487
> Revert "Upgrade javaparser"

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java
https://html.spec.whatwg.org/multipage/canvas.html#drawing-images
States that:
1. Check usability. If either dstWidth or dstHeight is zero don't draw anything but return.
2. If either srcWidth or srcHeight is zero don't draw anything but return.
The spec doesn't mention any errors, but e.g. Chrome throws errors in this case, see https://github.com/intrigus/gdx-freetype-gwt/issues/7
> Don't draw on canvas if image dimensions are zero.

- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/CustomShading.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/CustomShadingPanel.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java
This change allows to use custom shader and additional texture units in particle 2d editor.
Shader code/path and additional textures are not saved within particle files. It's for preview purpose only.
A new GUI section is available in Editor properties panel : 
Features : 
* set/reload vertex and/or fragment shader
* display shaders source code (usefull to get initial boilerplate)
* reset shader to default (sprite batch default shader)
* add/remove/reorder/reload extra texture units (starting from texture unit 1)
* shader compilation error messages
* missing texture sampler error messages
> custom shading preview in particle 2d editor

- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/classfile_constants.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/jawt.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/jdwpTransport.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/jni.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/jvmti.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/jvmticmlr.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/linux/jawt_md.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/linux/jni_md.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/mac/jawt_md.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/mac/jni_md.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/win32/jawt_md.h
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/resources/headers/win32/jni_md.h
Current header files are from java6.
There should be no content changes to any preexisting functions. Hide whitespaces changes if you want to compare.
Standout improvement is java6's linux JNIEXPORT definition lacks visibility declaration, and mac's is improved slightly.
https://github.com/libgdx/libgdx/commit/f86296734d516ec38a8d24f8a5889b10a5510a7a#diff-7f7c280adc23530f4911e868ab8c7129L11
If you would prefer to only include the updated jni_md.h I can revise this pull request.
No generated files are included in this PR for readability sake. The following snippet may be used to generate all automatically.
```
mvn install
cd gdx
mvn clean compile exec:java -Dexec.mainClass="com.badlogic.gdx.utils.GdxBuild"
cd ../extensions/gdx-controllers/gdx-controllers-desktop/
mvn clean compile …
```
> jnigen: updated java header files

- gdx/src/com/badlogic/gdx/graphics/glutils/ShapeRenderer.java
Fixed the box render has a triangle facing the wrong way, by viewing with Gdx.gl.glEnable(GL20.GL_CULL_FACE) and Gdx.gl.glCullFace(GL20.GL_BACK) - one of the triangles facing incorrectly. It was discovered when tempting to make a 3D cloud rendering for my voxel engine similar to Minecraft Cloud.
Before and after the fix:
This is my first time doing a pull request on Github. I'm well experienced with LibGDX API.
> Fix for box render has a triangle facing the wrong way.

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtClipboard.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtPermissions.java
- gdx/src/com/badlogic/gdx/utils/Clipboard.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/ClipboardTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
Here's an implementation for setting the clipboard in gwt using the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API). For getting the clipboard I see no possibility because it is an asynchronous event which returns the content of the clipboard asynchronously. Or do you got an idea how to do it?
> Access to the contents of the clipboard is gated behind the Permissions API; without user permission, reading or altering the clipboard contents is not permitted.
For this I created a separate class for querying the permission. It could be also useful in the future for accessing for example the [Accelerometer ](https://developer.mozilla.org/en-US/docs/Web/API/Accelerometer) which needs also permissions.
I added also a test for the clipboard which makes it easier to …
> Setting the "real" clipboard in gwt

- extensions/gdx-controllers/gdx-controllers-gwt/src/com/badlogic/gdx/controllers/gwt/support/GamepadSupport.java
Tested on Chrome Windows, Chrome Linux, Chrome Android, Firefox Windows, Firefox Linux
> Controllers not working on Chrome, closes #4982

- gdx/src/com/badlogic/gdx/net/NetJavaImpl.java
Android uses UTF8 by default, and is a saner default than leaving it up to environment's default character set for desktop.
This could be fleshed out to add specifiable character set to requests, and to attempt to parse response character set from response headers.
> Use UTF8 encoding for strings NetJavaImpl

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/GdxDefinition
Using this for the last 5 months without problems.
> Speed up GWT build by excluding compatiblity for antique IE versions

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationConfiguration.java
We have 2019, Flash is nearly dead, and SoundManager works better without it. Let's turn it off by default.
> GWT: do not use Flash for sounds by default

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationLogger.java
GWT logs the output to an own text area. I don't know why this was made this way, but I think logging to the console like it is done in the other backends is preferable. This is done here.
Due to backwards compatibility the old behaviour is still in place in case a logging text area is given via config.
> GWT: Log to JS console if no log text area is specified

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/AssetDownloader.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/Blob.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/Preloader.java
Add FileHandel.read() support for audio. With the planned removal of
SoundManager 2 it is now needed to read() an audio file on GWT.
(So https://github.com/libgdx/libgdx/blob/7e661eb3cae9aba493b19a3f55226c3db66f1826/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/webaudio/WebAudioAPIManager.java#L166-L189 can be removed)
Previously SM 2 has been responsible for actually loading the file
and libgdx was only preloading it.
> Add FileHandle.read() support for audio

- README.md
Original link points to a dead site. Now that there is a new maintained RoboVM clone, we can probably link to that.
> Updated RoboVM link on main README

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSApplicationConfiguration.java
- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSDevice.java
- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSGraphics.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSDevice.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
New iOS devices pop up regularly, but existing games can't always be updated to the latest libGDX version. This PR makes the device list accessible to the game code. You can add new iOS device information via `IOSApplicationConfiguration.addIosDevice()`.
> iOS: Add possibility to add iOS device information in game projects

- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSApplicationConfiguration.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java
The default setting of allowIpod to false has two disadvantages:
It accesses the audio hardware directly and reserves it for the game only, therefore suppresses other music even if the user deactivated playing sounds in game. Additionally, I experienced some problems with some sound files (stuttering). Both problems are gone since I've changed allowIpod to true. I suspect the flag made sense some years ago on older hardware, but for now I suggest to set the default to true.
> iOS RoboVM/MOE: set allowIpod default to true

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtNet.java
Binary operations on HttpResponse are not available on GWT, unfortunately the implementation just returns null which can lead to confusion. This small change makes the implementation throw an Exception with a hint for the developer how to solve the problem.
> GWT HttpResponse throw exceptions on unavailable operations

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java
It's possible to adjust the preloader animation by overriding `getPreloaderCallback`, but in most cases the game developer just wants to change the logo and the colors of the progress bar. Unfortunately, a whole code copy of the overriden code is needed to do so.
This PR changes it by dividing the code in three overridable methods. This way, the logo and the progress bar style can be adjusted. See the JavaDoc for more info, or this example copied from my HTMLLauncher:
@Override
public Preloader.PreloaderCallback getPreloaderCallback() {
return createPreloaderPanel(GWT.getHostPageBaseURL() + "preloadlogo.png");
}
@Override
protected void adjustMeterPanel(Panel meterPanel, Style meterStyle) {
meterPanel.setStyleName("gdx-meter");
meterPanel.addStyleName("nostripes"); …
> GWT: Make preloader logo and progress bar adjustable

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtAccelerometer.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationConfiguration.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtClipboard.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtSensor.java
You must use https for using the Accelerometer API because it's only available in [Secure Context](https://heycam.github.io/webidl/#SecureContext). You can test it [here](https://libgdx.v22018086706171227.nicesrv.de/) on my Server running the test's or @MrStahlfelge 's [Lightblocks](https://www.golfgl.de/lightblocks/experimental). You have to play _Single Player_ -> _Marathon_ and use the mode _Gravity Control_.
> Accelerometer implementation for gwt

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidZipFileHandle.java
For instance, `new AndroidZipFileHandle("music").list();` would return `[music/x0.mp3, music, music/x1.mp3]` instead of `[music/x0.mp3, music/x1.mp3]`.
> Array returned from AndroidZipFileHandle.list(...) included directory itself.

- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
On iOS, the appearance of the app is controlled by the UIViewController. In order to change some system behaviour, some methods of it must be overriden. 
The UIViewController used in the RoboVM backend was not exposed to the game project, thus not changeable if the default behaviour was not suitable. This commit changes it. 
I tested it to make sure it works by adding a selector/binding that I need in my project for supporting iCade controllers.
I looked into MOE, but it is solved in another way there and so I didn't change anything for the MOE backend.
> iOS RoboVM make UIViewController customizable

- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/AntScriptGenerator.java
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/BuildExecutor.java
- extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/test/MyJniClass.java
* Added missing working directory change in BuildExecutor#startProcess
Original changes were originally in https://github.com/libgdx/libgdx/pull/5556 but includes additional changes from https://github.com/MobiDevelop/gdx-jnigen
> jnigen: Fix double quote issue in BuildExecutor.

- CHANGES
- gdx/src/com/badlogic/gdx/graphics/VertexAttributes.java
- gdx/src/com/badlogic/gdx/utils/Array.java
- gdx/src/com/badlogic/gdx/utils/ArrayMap.java
- gdx/src/com/badlogic/gdx/utils/Collections.java
- gdx/src/com/badlogic/gdx/utils/IdentityMap.java
- gdx/src/com/badlogic/gdx/utils/IntFloatMap.java
- gdx/src/com/badlogic/gdx/utils/IntIntMap.java
- gdx/src/com/badlogic/gdx/utils/IntMap.java
- gdx/src/com/badlogic/gdx/utils/IntSet.java
- gdx/src/com/badlogic/gdx/utils/LongMap.java
- gdx/src/com/badlogic/gdx/utils/ObjectFloatMap.java
- gdx/src/com/badlogic/gdx/utils/ObjectIntMap.java
- gdx/src/com/badlogic/gdx/utils/ObjectMap.java
- gdx/src/com/badlogic/gdx/utils/ObjectSet.java
- gdx/src/com/badlogic/gdx/utils/OrderedMap.java
- gdx/src/com/badlogic/gdx/utils/OrderedSet.java
- gdx/src/com/badlogic/gdx/utils/Predicate.java
- gdx/src/com/badlogic/gdx/utils/Queue.java
Created a new Collections class to hold common configuration/utility methods for all collection classes. Moved allocationIterators from Array class to Collections.
I've made a getter/setter for the property, can change to public as it's not that great anyway.
> Moved allocateIterators config to new Collections class

- gdx/src/com/badlogic/gdx/graphics/g3d/loader/G3dModelLoader.java
changed private methods in G3dModelLoader to protected to allow for easier subclassing. 
A particular reason I'd like to do this is that I'd like to write modified .g3dj model files containing custom vertex attributes in the vertices array. Currently, at line 168 of this file is the line
```
throw new GdxRuntimeException("Unknown vertex attribute '" + attr
+ "', should be one of position, normal, uv, tangent or binormal");
```
The if-else ladder doesn't allow for vertex attributes with names other than those listed in this file. I'd like to be able to add custom vertex attributes but also to be able to use the other methods from this class.
> changed private methods in G3dModelLoader to protected 

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidDaydream.java
- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFragmentApplication.java
Followup to PR #5081 / commit dfaa35111, which fixed this issue for AndroidApplication, but not for Daydream and Fragment.
> Android: Hardware keyboard not detected when connected before app launched

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGL20.java
The new GLES20 code used some convenience methods that were added in API 17, causing instant crashes on older devices. This PR swaps out these methods for older ones that should be compatible with all API levels supported by libGDX.
*If someone has a device with API < 17, please test this to make sure it fixes the problem. This does not seem to cause any regressions on my 7.0 device.*
> Fixed GLES20 NoSuchMethodError on Android API < 17

- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
Fix for https://github.com/libgdx/libgdx/issues/5709
(Base)TmxLoader was refactored (by me) a few weeks ago.
This bug occured because a code block moved without noticing that a variable gets assigned a new value inbetween.
"Element element" (line 544) gets replaced further down in the code (line 570 before change).
To get the correct element to retrieve the attributes the appropriate code block is moved to the top again, as it was before the BaseTmxMapLoader refactor.
In my test this fixed https://github.com/libgdx/libgdx/issues/5709. Please verify.
> Fixed order of getting elements in loadTileSet

- gradle/dependencies.gradle
This is necessary as mentioned [here](https://github.com/jiakuan/gwt-gradle-plugin#gradle-52) because we are using gradle 5.4
I chose 1.0.9 because the setup uses the same version
> Increase gwt plugin version

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/soundmanager2/SoundManager.java
My game was blocked from running on an older version of Chromium, because the browser didn't support mp3. Changing required:!0 to required:!1 for mp3 inside SoundManager2 fixed my game and it runs now. The game uses ogg by the way.
When I say the game was blocked I mean the loading bar doesn't appear. I got this in the console.
SoundManager 2: No Flash detected. Trying HTML5-only mode.
SoundManager V2.97a.20150601 (AS3/Flash 9) + HTML5 audio
SoundManager 2: soundManager: Fatal error: Flash is needed to play some required formats, but is not available.
SoundManager 2 HTML5 support: mp3 = false (using flash), mp4 = false (using flash), ogg = true, opus = true, wav = true
> SoundManager2: Changed mp3 required to false

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java
GWT Accelerometer is reported as present if the web browser supports it even if there is no accelerometer. This is not correct, using Chrome on Desktop reports an available accelerometer.
This commit changes getPeriphalAvailable in a way that accelerometer availability is only returned if real sensor data is present, this matches the behaviour of the other platforms.
Note: At first I wanted to use the onError callback of the sensor, but it was called on my mobile device too. I was not able to find out why, because the callback provides no error message.
Sorry for the diff. GwtInput had CRLF line endings which I was not able to commit. I think this is okay because (most) libGDX sources have LF line endings in general.
> GWT Accelerometer: report availability only if sensor is present

- gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
#5710 didn't really fix the issue #5709 if map uses external tsx tileset. In this case the tileset element in tmx file only has two attributes firstgid and the source to the tsx. All tileset attributes like name,tilewidth,tileheight,... are defined in tsx file.
> fix wrong firstgid when load external tileset

- gdx/src/com/badlogic/gdx/scenes/scene2d/utils/BaseDrawable.java
setMinSize() incorrectly passes minWidth to setMinHeight().
> Fixed BaseDrawable#setMinSize()

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java
This adds a setter to allow someone to set this without having to use reflection, or be in the protected scope. Tested with the NetAPITest setting reasonable/unreasonable values in the lwjgl3 application configuration.
> backend-lwjgl3: expose setter for maxNetThreads

- gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java
Better error message in ShaderProgam class.
When programming shaders, I use visual code studio to program shaders. The issue with visual code studio it doesn't have OpenGL ES error checking or "Code language not supported or defined". When saving the shader file to asset folder with a typo or syntax error, then run the game and a misleading exception "no uniform with the name" show on console log and close the game - this creates confusing from programmer checking the variable is correct without realizing there is an error when compiling the shader, it happens to me once and with a new exception would prevent from happening who using a text editor like visual code studio.
> Better error message when fetching Uniform from uncompiled shader.

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/war/index
Removed "evt.target.style.cursor" lines from default index.html because they are unnecessary. These lines interfere with custom cursors set during runtime (the default arrow always comes back when the user clicks the game).
> Removed "evt.target.style.cursor" lines from default index.html

- backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java
- backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/graphics/MockGraphics.java
- backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java
- backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSGraphics.java
- backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
- gdx/src/com/badlogic/gdx/Graphics.java
- gradle/dependencies.gradle
- tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/GdxTestActivity.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/FullscreenTest.java
We have display cutouts on iPhone X and now after updating on Android API 28 we can also have some on Android (although Android's default behaviour avoids that you have to deal with them).
This PR adds support for iOS RoboVM and Android backend to return the safe area insets. The changed `GdxTestActivity` demonstrates how to expand the game under the Notch on Android. A further change to apply this automatically if immersive mode is set might be useful, but this can be discussed.
This is tested on Android 4.2 and Android 9 and iOS 12.1 with RoboVM. The FullScreenTest tints the badlogic logo red if the logo is outside of the safe display area.
> Android/iOS: Added methods to get safe area insets

- extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/FlameMain.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/RegionInfluencerPanel.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/RegionPickerPanel.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/TextureAtlasPanel.java
- extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/TextureLoaderPanel.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/influencers/RegionInfluencer.java
make it so that in the 3d particle effect editor (Flame), if a texture region
is used, the name of the sub-image (region) is stored. This makes it so that if a texture atlas is updated, the uv-coordinates of the region can be read from the atlas rather than having the uv coordinates stored in the particle effect save file.
> Have Flame store 3d particle texture atlas into save file

- gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java
The documentation currently says `The name of the original image file, up to the first underscore. Underscores denote special instructions to the texture packer.`.
However, for example, if you pack an image called `bob_walking.png`, the returned String will be `bob_walking`.
The JavaDoc is now accurate as of the content of that variable.
> fix #5791 Fixing `AtlasRegion.name` documentation

- gdx/src/com/badlogic/gdx/graphics/g3d/particles/influencers/DynamicsModifier.java
- gdx/src/com/badlogic/gdx/graphics/g3d/particles/influencers/SpawnInfluencer.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/ParticleControllerInfluencerSingleTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/PolarAccelerationTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/TangentialAccelerationTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java
Tangential and Polar acceleration didn't respect the global/relative setting in Flame. this fixes https://github.com/libgdx/libgdx/issues/4894
Also fixed a bug in which rotation information wasn't passed to from SpawnInfluencer to ParticleControllers
> make TangentialAcceleration and PolarAcceleration respect global flag

- CHANGES
- backends/gdx-backend-lwjgl3/.classpath
- backends/gdx-backend-lwjgl3/pom.xml
- fetch.xml
- gradle/dependencies.gradle
- pom.xml
Includes new `windows-x86`, `linux-arm32`, and `linux-arm64` classifiers as dependencies.
> Update LWJGL3 backend to 3.2.3.

- gdx/src/com/badlogic/gdx/math/MathUtils.java
```java
/** Returns the sine in radians from a lookup table. */
static public float sinDeg (float degrees) {
return Sin.table[(int)(degrees * degToIndex) & SIN_MASK];
}
/** Returns the cosine in radians from a lookup table. */
static public float cosDeg (float degrees) {
return Sin.table[(int)((degrees + 90) * degToIndex) & SIN_MASK];
}```
As you can see, the documentation says the returned value is in `radians`, yet they are `degrees`. This PR fixes that.
> Fixed 2 typos in the JavaDoc

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java
- gdx/src/com/badlogic/gdx/Input.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtInputTest.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
note that BACK and FORWARD buttons could be implemented but : 
* [Gwt NativeEvent](http://www.gwtproject.org/javadoc/latest/com/google/gwt/dom/client/NativeEvent.html) doesn't support/provide codes for them.
* Real javascript native codes are not the same as GWT codes.
so i didn't want to mess with these cases.
> fix broken isButtonJustPressed in GWT backend, fixes #5805

- gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFontCache.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/BitmapFontTest.java
This fixes #5834 . It only needs a single `Math.min(int, int)` call to be added per call to `setColors(float, int, int)`, checking to make sure that the calculated end index is no greater than what other parts of the class use (`idx[page]`, where page is always 0 in the broken case). It also technically permits arbitrarily high end values to be given as long as end is greater than start; if too high of an end was supplied to a single-page font before, it would have crashed. I added the reproduction code from #5834 to BitmapFontTest, which needed an if/else block to be changed to actually run the tests on most of the features.
I'm pretty sure the formatting is correct, but the automatic eclipse-formatter was inserting a space after every indent in IntelliJ, so I just manually made sure the …
> Ensure BitmapFontCache.setColors(float, int, int) stays in-bounds

- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtFiles.java
- backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtPreferences.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
We experienced some "Couldn't flush preferences" erros. The cause seem to be that `getLocalStorageIfSupported` can return null if the browser doesn't support it or "block third-party cookies" is enabled. Then in `flush`, GwtPreferences tries to access to LocalStorage but it's null.
Logging the original exception is helpful to get causes of problems.
Also removed the unnecessary creation of objects from the same type in toObject (the constructors are deprecated since java 9)
> Log the exception inside flush and fix NullPointerException if LocalStorage is not supported

- gdx/src/com/badlogic/gdx/net/NetJavaImpl.java
This just allows all the threads a unique name, this is helpful when using a profiler, or when looking at log files that include thread names.
> Give network threads a unique name

- CHANGES
- gdx/src/com/badlogic/gdx/math/collision/Ray.java
create a new pr after closing https://github.com/libgdx/libgdx/pull/5859 with push force on my fork.
So :
- Add javadocs for direction vector must be normalized
public Ray set (Vector3 origin, Vector3 direction)
- Add nor on direction vector3 in method public Ray set (float x, float y, float z, float dx, float dy, float dz)
thx for reading.
> #5858 Ray normalise origin vector after set methods

- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
- backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowConfiguration.java
In the code Lwjgl3Application.java, when constructing a new lwjgl3 application, it clones config instance, then it checks the **cloned** config's title if it is null than replace it with the class's name. The problem within construct initialization, it uses the local config (non-clone) which hasn't check if the title is null, hence when creating a new application with the title set to null will crash when initialization.
With these changes, it will fixes when the title is null, preventing the crash. And will behave similarly to lwjgl2 backend (if the title is null, then replace it with the listener's class name).
> [lwjgl3 backend] fix an empty title and NullPointerException.

- gdx/src/com/badlogic/gdx/Net.java
This pull request fixes the issue outlined in #5868 
However, now that the documentation has been changed to throw GdxRuntimeException instead of returning it, the method documentation for the method that was changed no longer contains a returns attribute.
I am not very experienced with the source code behind this framework, so I did not take the liberty of writing that documentation.
> Fix documentation (Fixes #5868)

- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/desktop/build.gradle
* See https://docs.gradle.org/current/userguide/working_with_files.html
* For project dependencies `compileClasspath` points to class file directories, but does not contain resources.
* For project dependencies `runtimeClasspath` points to fully built jar files.
* `configurations.runtimeClasspath.collect` does not build these jars, so we have to manually add it via `dependsOn`
* Actually actually fix #5716
> Gradle: Proper runtimeClasspath usage for desktop uber jar

- CHANGES
- gdx/src/com/badlogic/gdx/math/collision/Ray.java
finnally ! 
nor() direction vector everytime.
Cause Math.sqrt avoid if vector is already normalized in Vector2#nor().
If you want to avoid the call of nor() , use the public field direction.
thx for reading.
> #5858 Ray.java normalize direction vector in set() methods

- extensions/gdx-setup/src/com/badlogic/gdx/setup/BuildScriptHelper.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/android/build.gradle
- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/core/build.gradle
- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/desktop/build.gradle
- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/build.gradle
- extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/ios/build.gradle
These changes are related to #5700 changes : 
* IDE options in setup dialog (Eclipse and Intellij) are no longer necessary. 
* afterEclipseImport task doesn't exists anymore and was generating errors when Eclipse option was checked.
* Eclipse plugin still necessary for project naming (prevent confliting names in Eclipse workspace)
For the last one there was 2 way to do it, see [Buildship issue](https://github.com/eclipse/buildship/issues/629#issuecomment-354762915) : either by changing projects names in settings.gradle or by using eclipse plugin.
Chaging names in settings.gradle would impact all IDE and is a bit ugly IMO. So i chosed to bring back Eclipse plugin which will only impact Eclipse.
> Setup: removed obsolete options and fix eclipse import

- extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
For supporting another languages (like RTL language) we need to customize the BitmapFont... So,for doing this approach I need to change (override) some methods on BitmapFont that generated glyphs using FreeTypeFontGenerator.
> Access to  BitmapFont for extends It on RTL language support

- gdx/src/com/badlogic/gdx/graphics/glutils/InstanceBufferObject.java
This is a simple bugfix in class InstaneBufferObject. In method "unbind" the function "disableVertexAttribute" must be called on the ShaderProgram instance instead of "enableVertexAttribute".
> unbind method must call 'disableVertexAttribute'
