libgdx/libgdx

gdx/src/com/badlogic/gdx/graphics/Mesh.java

As already mentioned in a feature request (see below) an isInstanced method in the mesh class would be useful. Currently, it is not possible to determine whether instancing is active for a mesh.
Feature request: #5915

added isInstanced()-method to indicate whether a mesh uses instancing

---

gdx/src/com/badlogic/gdx/graphics/Camera.java
gdx/src/com/badlogic/gdx/utils/viewport/Viewport.java
tests/gdx-tests/src/com/badlogic/gdx/tests/CoordinatesTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

i was trying to understand #5854 issue, so i write a test.
It took me a while to understand that project is not the inverse of unproject, there are some Y flips required in between. I thought it was a bug but reading javadoc carefully i understood it was intentional.
Anyway, during my tests i noticed and fixed few little bugs : 
* camera#unproject had a 1 pixel error (propbably a mistake)
* viewport#toScreenCoordinates is only used in GroupTest but this test doesn't show the issue since it use a ScreenViewport (virtual screen bounds are the same as real screen bounds). My test illustrate the issue.
My PR doesn't fix #5854 (if there is an issue) but i think the test class i added could be a good base to track it down.

fix some camera/viewport project/unproject

---

gdx/src/com/badlogic/gdx/utils/IntFloatMap.java
gdx/src/com/badlogic/gdx/utils/IntIntMap.java
gdx/src/com/badlogic/gdx/utils/IntMap.java
gdx/src/com/badlogic/gdx/utils/IntSet.java
gdx/src/com/badlogic/gdx/utils/LongMap.java
gdx/src/com/badlogic/gdx/utils/ObjectFloatMap.java
gdx/src/com/badlogic/gdx/utils/ObjectIntMap.java
gdx/src/com/badlogic/gdx/utils/ObjectMap.java
gdx/src/com/badlogic/gdx/utils/ObjectSet.java
gdx/test/com/badlogic/gdx/utils/MixedPutRemoveTest.java

This should fix #5930 and #5931 , it may also help with #5929 .
This is a relatively small set of changes; the backwards-shift algorithm for deletion was (if I remember it right) correct when the maps and sets used Robin Hood hashing, but not for linear probing. The changes needed to fix all the maps and sets are the same; it just needs to avoid backwards-shifting any keys to before where their place() slot would be without probing. The code is somewhat hard to read because it needs to compare two differences between slots while considering wrap-around from the mask; I don't see any way around this. Each file for a hash-based map or set should have changed in two places (remove() and the iterator's remove()), except IdentityMap, OrderedMap, and OrderedSet, which use a parent …

Fix for ObjectMap/LongMap/others when mixing put()/remove()

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java

In this issue #1419 it was found that the rendering knobBefore taking in consideration the padding of the background was incorrect. The same was true for knobAfter yet nothing was done about it (fix was only applied to knobBefore). This results in knobBefore getting drawn up to the end of the bar without caring about the padding of the background:
Fixed version:
Note that this only affects: Uses of ProgressBar with knobAfter that have a background with non-zero padding. It is possible that nobody noticed this bug for many years given how uncommon the use of knobAfter is. (Even myself don't really need it in a vanilla type of way)
Another issue with progress bar was later fixed after the initial one I mentionned: #4446  But this issue only address the typo which caused the bar to have an …

Fixed incorrect padding of knobAfter

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/ios/robovm.xml

Setting default tree shaker setting to `conservative` is totally safe (confirmed by dkmitsa on Gitter) and saves around 10MB on .app and 2MB on the .ipa file sizes.
A bit of context: Tree shaker was implemented on RoboVM as a mechanism to trim the build sizes for unused branches of code in an early version. For a long time `none` was default but in a late version of RoboVM it was set to `conservative` (see release notes https://www.gamefromscratch.com/post/2015/12/17/RoboVM-112-Released-Adds-Experimental-tvOS-and-iOS-92-Support.aspx).
When MobiVM was forked, the RoboVM version had still not set the default value to `conservative` (which only trims annotated classes/methods) but it should have been set. Until MobiVM changes its default behaviour, libGDX projects can benefit from setting …

[MobiVM] Set default treeShaker setting to conservative

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g3d/ModelBatch.java
gdx/src/com/badlogic/gdx/graphics/g3d/utils/DefaultTextureBinder.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/utils/DefaultTextureBinderTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

DefaultTextureBinder WEIGHTED method doesn't work. Consider this example : 
- a DefaultTextureBinder with count=4
- a model A with 3 textures (textures 1, 2 and 3)
- a model B with 3 other textures (textures 4, 5, 6)
- render model A several times (textures 1, 2, and 3 get high weights)
- render model B : 
- texture 4 is bounds to the last available slot with a light weight
- texture 5 takes texture 4 slot because of its lighter weight, then model B cannot be rendered correctly.
I split my changes in several commits for readability and so you can test it yourself this bad behavior with first commit. (please squash them all when merging)
the new LRU strategy becomes the default which may be a little better than round robin method for most use cases.

Fix DefaultTextureBinder replacing WEIGHTED strategy by LRU

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/ios/Info.plist.xml

~~Current RoboVM version sets the `MinimumOSVersion` to 6 if not declared on the app's `Info.plist`. Currently GDX setup doesn't set it so it defaults to 6 which is not supported even by RoboVM itself.~~ 
Ok, the problem is less important than I originally thought but the PR may still be relevant. Currently RoboVM is not handling properly the `MinimumOSVersion` (see https://github.com/MobiVM/robovm/pull/463) which may lead to confusion in terms of what the actual minimum supported iOS version is.
MobimVM official minimum supported version is 8. If `MinimumOSVersion` is not declared on the app's `Info.plist` it will be set to 8 by default. There's currently a small bug that, in case `MinimumOSVersion` is missing, even if it uses iOS 8, it internally adds the key with a value of 6 (instead …

Set min iOS version to 8.0

---

CHANGES
extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/CustomShading.java
gdx/src/com/badlogic/gdx/graphics/Mesh.java
gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSpriteBatch.java
gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java
gdx/src/com/badlogic/gdx/graphics/g2d/SpriteCache.java
gdx/src/com/badlogic/gdx/graphics/g3d/decals/CameraGroupStrategy.java
gdx/src/com/badlogic/gdx/graphics/g3d/model/MeshPart.java
gdx/src/com/badlogic/gdx/graphics/g3d/shaders/BaseShader.java
gdx/src/com/badlogic/gdx/graphics/glutils/ImmediateModeRenderer20.java
gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java
tests/gdx-tests/src/com/badlogic/gdx/tests/FloatTextureTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/FrameBufferTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/IndexBufferObjectShaderTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/MeshShaderTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/MipMapTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ProjectiveTextureTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ShaderMultitextureTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/VBOWithVAOPerformanceTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/VertexBufferObjectShaderTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/MultipleRenderTargetTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/ShaderTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/TextureArrayTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gles2/HelloTriangle.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gles2/MipMap2D.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gles2/SimpleVertexShader.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gles3/InstancedRenderingTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTest.java

Unbinding a shader program is not necessary, it was useful to enable the old fixed-function pipeline which libgdx don't use.
ShaderProgram begin and end method are deprecated for a smooth transition.
I made a quick dumb test to see how my GPU was impacted (if my GPU driver optimize it or not) : 
here is the code:
```java
private ShaderProgram sp;
public void render () {
int N = 1000;
for(int i=0 ; i<N ; i++){
sp.begin();
sp.end();
}
logger.log();
}
```
by commenting begin/end in all combinations i get:
- calling none of them (baseline): ~ 10 500 FPS
- calling only end: ~ 9500 FPS
- calling only begin: ~ 2000 FPS
- calling both begin and end: ~ 1000 FPS
GPU : Nvidia GTX 950m
I'm not calling this a benchmark, i just wanted to highlight this small optimization and ensure there was no …

remove unnecessary glUseProgram(0)

---

gdx/src/com/badlogic/gdx/utils/IntFloatMap.java

This was a copy-paste error; it was found by Raymond Buckley trying to use 1.9.11-SNAPSHOT with Typing-Label (which doesn't build with the snapshot right now).
I didn't notice any similar problems in IntIntMap, ObjectFloatMap or ObjectIntMap.

Correct IntFloatMap.getAndIncrement() parameter types

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationBase.java

Missed changing this one when we updated to 14. It's just used for a check on app startup in case min SDK is set to a value less than libGDX minimum supported.

Update libGDX min Android SDK version for startup check

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java

If someone tries to generate a new libgdx project, the gdx-setup checks whether the android sdk contains a directory named _tools_. 
During the installation of android studio, the directory does not get created. Also installing the command line tools via the sdk manager of android studio, the directory won't be created.
So users can't create a new project, unless they create the directory themself.
This problem happened also there: #5934

Remove check for tools directory in android sdk root in gdx-setup

---

extensions/gdx-setup/build.gradle

With this config, the old ant config isn't necessary anymore to create the setup jar.
The _gdx-setup.jar_ can be easily created via `gradlew extensions:gdx-setup:jar` and can be found in _extensions/gdx-setup/build/libs_.
The setup can also get started via gradle with the command `gradlew extensions:gdx-setup:run`.

Build.gradle for gdx-setup

---

CHANGES
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALAudio.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALAudio.java

This PR adds a way to obtain the _source id_ of a sound via its _sound id_ by calling `OpenALAudio#getSourceId(long)`. The opposite is already possible via `OpenALAudio#getSoundId(int)`.
**Problem:** Currently only the _sound id_ is known via Sound#play(), but the _source id_ is needed to interact with  OpenAL, e.g. for implementing positional audio (`AL10.alSource3f(AL10.AL_POSITION, sourceId, x, y, z)`, etc.). 
**As for alternative solutions:** extending OpenALAudio is sadly not possible, as the member in question (`soundIdToSource`) is private.

Add method to OpenALAudio to obtain the source id of a Sound

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java

This PR adds a method to obtain the OpenGL handle of a `ShaderProgram`. This is needed for some OpenGL methods (e.g. `GL32C.glBindFragDataLocation(handle, 0, "albedoOut")`).
Extending `ShaderProgram` is not possible, as the variable in question is private.

Add a method to obtain the handle of a ShaderProgram

---

gdx/build.gradle

This PR fixes the issue of IDEA not adding resources from the `gdx` module to classpath when running tests suites from `tests` modules on libGDX project.
Steps to reproduce:
1. On IDEA `Build -> Clean Project`
2. On IDEA `Run` a test suite such as `tests/gdx-tests-lwjgl3` `Lwjgl3TestStarter` (use IDE `Run`, not from the Gradle task list menu).
3. Choose `UISimpleTest` from the list
4. Crash with
```Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: File not found: com\badlogic\gdx\utils\arial-15.fnt (Classpath)
at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:142)
at com.badlogic.gdx.graphics.g2d.BitmapFont$BitmapFontData.load(BitmapFont.java:493)
at com.badlogic.gdx.graphics.g2d.BitmapFont$BitmapFontData.<init>(BitmapFont.java:485)
at …
```

Fix running tests on IDEA

---

extensions/gdx-controllers/gdx-controllers-android/build.gradle
extensions/gdx-controllers/gdx-controllers-desktop/build.gradle
extensions/gdx-controllers/gdx-controllers-gwt/build.gradle
extensions/gdx-controllers/gdx-controllers-lwjgl3/build.gradle
settings.gradle
tests/gdx-tests-android/build.gradle
tests/gdx-tests-gwt/build.gradle
tests/gdx-tests/build.gradle

As discussed in #5846, the android-gradle plugin makes some noise with same named parent and child projects.
So we found a way to fix it without renaming the whole directory, but only changing the module names in gradle.

Rename gdx-box2d and gdx-controllers in gradle

---

gdx/src/com/badlogic/gdx/math/Intersector.java
gdx/test/com/badlogic/gdx/math/IntersectorTest.java

Fixes #5070
`intersectSegmentCircleDisplace` has been replaced by an overloaded method of `intersectSegmentCircle` that now accepts a `MinimumTranslationVector` as optional parameter.
Some design choices justifications
1. Use Vector2 instead of Vector3. This has required creating some static Vector2 instances for temporary use similar to Vector3 ones. To keep simple naming prefix v2 + letter seems the more compact/readable. These instances can be used by any other method in the class that needs temporary Vector2.
2. Use Vector2 operations when possible for readability
3. Use Circle as argument (the old one didn't use it as Circle class was created later in time)
**Even if the new `intersectSegmentCircle` that accepts an MTV parameter could also replace the old one, it has been left for …

Fixes #5070 - Fixed and replaced Intersector intersectSegmentCircleDisplace

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java

A Discord user has requested being able to get the "wrap" property value.
The use case is a shadow object that makes an identical version of the Actor passed in, but light grey and slightly offset. To use it with a label he needs to set the shadow label as all the same features
like width, height, alignment, wrap etc (and there's not a new Label (Label label) constructor either).

Add isWrap() to Label

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowConfiguration.java

* Fixes #5845 on Windows.
* Fix position for maximized window when specifying maximizedMonitor.
* Center default window on primary monitor's working area.

LWJGL3: Window positioning fixes.

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java

Allows overriding those methods for testing purposes. Is a fix for #5995.

Make Lwjgl3Application#loop(), #cleanupWindows() and #cleanup() protected

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java

iOS 8 added a more efficient and robust mechanism to get the iOS version that doesn't require parsing and splitting a String through `NSProcessInfo` (https://stackoverflow.com/questions/3339722/how-to-check-ios-version).
The `getVersion()` implementation on `IOSApplication` has been modified and the unnecessary/duplicated `getIosVersion()` has been deleted.

Use better implementation to get iOS version

---

gdx/src/com/badlogic/gdx/Preferences.java

Clarifies plattform specific behaviour of preferences:
- On Android, prior to flushing, changes to the preferences are not available to the user
- On iOS changes are not synchronized between different preferences instances
Fixes #5558.

Clarify plattform specific behaviour of preferences

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Image.java

I needed to get alignment so I can use `setPosition(x, y, alignment)`, so I can re-position the UI when windows resized.
Not sure why there's no getter for alignment where other UI class does. (Likely forgotten to add getter)

[Image] Add getter for align.

---

CHANGES
gdx/src/com/badlogic/gdx/maps/tiled/TiledMapTileLayer.java

`TiledMapTileLayer#tileWidth/Height` are changed to integers, as the constructor (and the map loaders) are already only allowing integer values. Fixes #3821.

Change TiledMapTileLayer#tileWidth/Height to an integer.

---

CHANGES
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/math/Matrix4.java
gdx/src/com/badlogic/gdx/math/Matrix4.java
tests/gdx-tests/src/com/badlogic/gdx/tests/MatrixJNITest.java

Current Matrix4.setToLookAt methods are design to build a view matrix for camera. Sometimes it's useful to rotate a model toward a target or direction. So i added 2 new methods.

added convenient Matrix4 rotate methods

---

pom.xml

https://github.com/libgdx/libgdx/pull/5979 changed Android SDK version to 9.0. Not that it makes a difference afaik but for consistency sake.

Set correct android version on pom.xml

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidDaydream.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFragmentApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidLiveWallpaper.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidMouseHandler.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidTouchHandler.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidAudio.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java

`AndroidAudioImpl` and `AndroidInputImpl` have been renamed to `DefaultAndroidAudio`and `DefaultAndroidInput` to follow better naming conventions (see comments on https://github.com/libgdx/libgdx/pull/6014).

Rename Android Audio and Input implementations

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java

I removed the `Integer.toString` and replaced it with the `StringBuilder.append` to avoid some object creations. Side effect, some redundant checks in `setText(CharSequence)` are no longer performed.
I also used the `StringBuilder.clear()` instead of the `StringBuilder.setLength(0)` as is more descriptive and more efficient.
I changed slightly the null check (which I now realize is irrelevant) to avoid some redundant checks.
I would also suggest that `setText(CharSequence)` also return a boolean like `setText(int)`.

[Label] Set text to int value opt

---

CHANGES
gdx/src/com/badlogic/gdx/utils/Base64Coder.java

Without specifying a String encoding for String.getBytes(), it uses a platform-dependent encoding that can break Base64 data transmitted between computers. Almost all of libGDX specifies "UTF-8" as the encoding; only a few tests don't (and currently Base64Coder.encodeString()).
This commit also adds Javadocs where they were missing for one encodeString() and makes the spelling of "Base64" consistently "Base64" and not sometimes "Base 64".
EDIT FOR FUTURE REFERENCE:
This PR should have no effect if you only use Base64Encoder's byte array encoding, or if you use String encoding with ASCII strings only. If you previously wrote Base64 data using `Base64Coder.encodeString()` and used non-ASCII characters, then that data was written with the platform's encoding, which can vary at least on …

Specify encoding for Base64Coder.encodeString(), as the rest of GDX does

---

gdx/src/com/badlogic/gdx/graphics/FPSLogger.java

If the fps is lower than bound the behavior is the same as before, but if the fps >= bound nothing is logged (and the one second counter is not reset in order to the have the first log be as soon as the fps goes bellow the bound).
For example: `new FPSLogger(60)`, given a game that should be able to run in 60fps, will only log when the 60fps is not reached instead of spamming 60fps all the time.
The current `new FPSLogger()` behavior (and performance cost) remains the same.

[FPSLogger] Support for an upper bound

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
tests/gdx-tests/src/com/badlogic/gdx/tests/InputTest.java

UIAlertView was deprecated in iOS 8, instead, the recommended way is to use UIAlertController (https://developer.apple.com/documentation/uikit/uialertview).
I've added a small commented snippet in `IOSTest` to allow easy testing of the new implementation. I think it is ok to leave it there as currently that test doesn't provide a mechanism to the test keyboard on mobile devices.

Replaced deprecated UIAlertView by UIAlertController

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g3d/utils/shapebuilders/SphereShapeBuilder.java

Previous algorithm didn't merge sphere poles and used quads to join them to the rings which produced lighting artifacts (because of normals) as you can see here (before fix on the left, after fix on the right) : 
Manually moving vertices poles help to see the flat triangles : 
You can also see how normals on poles was weird (before the fix on the right) : 
UVs was also a bit off because of flat edge on pole. Here is UVs before the fix: 
UVs are now like this (similar to default Blender UV sphere) : 
Note that this change doesn't impact opened spheres (eg. when V angle range from 30 to 150).

fix SphereShapeBuilder poles are now merged

---

gdx/src/com/badlogic/gdx/graphics/Camera.java
gdx/src/com/badlogic/gdx/math/Matrix4.java

This PR will not break anything, it just removed unnecessary normalizations to reduce the number of operations (and errors) when lookAt method is called multiple times. It will avoid 1 square root calculation (2 if you call the update method).
This is an attempt to fix: #5159
A good way to test it is to run the [SimpleDecalTest](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/SimpleDecalTest.java) (or any other test that calls lookAt) and check if the behavior is the same.
The first line will produce a non-unit vector but the second line will calculate the perpendicular vector and normalize it. (as @obigu explained, the length of the vector will not affect the cross product).
```
tmpVec.set(direction).crs(up);
up.set(tmpVec).crs(direction).nor(); …
```

Remove unnecessary normalization

---

CHANGES
gdx/src/com/badlogic/gdx/input/GestureDetector.java
gdx/src/com/badlogic/gdx/scenes/scene2d/Actor.java
gdx/src/com/badlogic/gdx/scenes/scene2d/InputEvent.java
gdx/src/com/badlogic/gdx/scenes/scene2d/InputListener.java
gdx/src/com/badlogic/gdx/scenes/scene2d/utils/ActorGestureListener.java
gdx/src/com/badlogic/gdx/scenes/scene2d/utils/ClickListener.java

Actor#notify used to have a special case: when a listener handles a touchdown input event, it added the listener to the stage's touch focus. 
First, this logic seems to fit better in InputListener, where the touchdown is handled, rather than jamming it in Stage.
Second, it was difficult to manually inject input events for some desired behavior. For example, after sending touchdown/dragged/up using Actor#notify, the actor would have touch focus. That means the actor will see a touchup on the next real click and behave incorrectly. Fixing this with Stage#cancelTouchFocus is problematic, as the actor needs to detect the event is a touch focus cancel else it will act on the touchup. Fixing this with Stage#removeTouchFocus is difficult, as which listeners handled the event aren't easily known. …

Moved adding touch focus from Actor#notify to InputListener#handle.

---

gdx/src/com/badlogic/gdx/utils/Json.java

I have noticed the link in the **Json** class description does not lead to the actual page in the GitHub Wiki, so this tiny PR is to correct that.

Correct link to the Wiki page for Json class

---

gdx/src/com/badlogic/gdx/math/Matrix4.java

Some Matrix4 native methods give significant improvements when replacing them by java code (probably because of JNI overhead). .
I made few tests on a real scenario, gain is around 16% FPS : 320 FPS before, 373 after. 
Context: 1000 model instance, 4000 Matrix4.mul.
Matrix4.mul is heavily used, especially for 3D node tree 
Matrix4.inv is only used by cameras.
others are not used by framework code.
Thanks @Anuken to brought this up and @tommyettinger for the [Matrix4 Comparative Benchmark](https://github.com/tommyettinger/assorted-benchmarks/blob/master/src/main/java/net/adoptopenjdk/bumblebench/examples/Matrix4Benchmarks.md)
Notes: 
* java code was directly copied from GWT emulation implementation.
* my second commit might be questionnable, i made choice of mouving methods instead of …

performance improvements for Matrix4 operations

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGL20.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL20.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3GL20.java
backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosrobovm/IOSGLES20.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGLES20.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20Debug.java
gdx/jni/iosgl/iosgl20.h
gdx/src/com/badlogic/gdx/graphics/GL20.java
gdx/src/com/badlogic/gdx/graphics/profiling/GL20Interceptor.java
gdx/src/com/badlogic/gdx/graphics/profiling/GL30Interceptor.java

In the LWJGL3 backend, `Lwjgl3GL20#glGetActiveUniform` and `...ActiveAttrib` report incorrect sizes and types. This causes the size and type of uniforms and attributes reported by `ShaderProgram` to be incorrect when using the LWJGL3 backend.
From here on I will only describe the case of uniforms.
<details>
<summary>Lwjgl3GL20#glGetActiveUniform implementation</summary>
```java
public String glGetActiveUniform (int program, int index, IntBuffer size, Buffer type) {
IntBuffer typeTmp = BufferUtils.createIntBuffer(2);
String name = GL20.glGetActiveUniform(program, index, 256, size, typeTmp);
size.put(typeTmp.get(0));
if (type instanceof IntBuffer) ((IntBuffer)type).put(typeTmp.get(1));
return name;
}
```
</details>
For some reason, the call to `GL20#glGetActiveUniform` is not given the …

Lwjgl3GL20's glGetActiveUniform and glGetActiveAttrib report incorrect sizes and types

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/surfaceview/GLSurfaceView20.java

On samsung keyboards onKey is not always fired for all key presses, in the current codebase. Because of this, when entering text in TextField, the typed letters don't appear until the keyboard is closed. The user has no idea that anything is being entered until after closing which is very poor UI.
The https://developer.android.com/reference/android/view/View.OnKeyListener#onKey(android.view.View,%20int,%20android.view.KeyEvent) is used inside AndroidInput but as the web page states
`Called when a hardware key is dispatched to a view. This allows listeners to get a chance to respond before the target view.
Key presses in software keyboards will generally NOT trigger this method, although some may elect to do so in some situations. Do not assume a software input method has to be key-based; …

Samsung keyboard TextField fix

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffectPool.java
gdx/src/com/badlogic/gdx/utils/FlushablePool.java
gdx/src/com/badlogic/gdx/utils/Pool.java
gdx/src/com/badlogic/gdx/utils/ReflectionPool.java

Unfortunately I've realised that the constructor based mechanisms that https://github.com/libgdx/libgdx/pull/5773 introduced to prefill a Pool is bad and should be removed (we can keep calling `fill()` after instantiation).
Calling a protected method (`newObject()`) on the constructor is an anti pattern and can cause state consistency issues as the object may not have been fully initialized. A simple example can be seen on `ParticleEffectPool` in which if we use the constructor passing `preFill()` as `true`, `newObject()` will be called before `effect`has been set throwing a `NullPointerException`.
I should have seen this issue before, sorry for that :(

Remove constructor with preFill argument from Pool

---

CHANGES
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Slider.java

Currently every mouse button click triggers a change of a slider. This may be unwanted in certain cases, e.g. a right click shouldn't be able to change the slider's value.
This PR allows registering one mouse button that can trigger the change (`Slider#setButton(int)`). By default it is set to `-1`, so the behaviour stays the same way it was before: every mouse click is registered.
Extending Slider as an alternative solution is, sadly, not possible, as nearly everything in the class is not visible.

Allow Slider to be configured to only trigger on certain mouse button clicks.

---

gdx/src/com/badlogic/gdx/math/Intersector.java

Fixed a minor typo in a comment for Intersector.intersectRayBounds().

Fixed typo in Intersector comment.

---

gdx/src/com/badlogic/gdx/maps/tiled/AtlasTmxMapLoader.java
gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java
gdx/src/com/badlogic/gdx/maps/tiled/TmxMapLoader.java

BaseTmxMapLoader, TmxMapLoader and AtlasTmxMapLoader have a few private methods/interfaces which make it unnecessarily hard or impossible to extend these classes.
This pull request just makes these methods/interfaces protected instead of private.

BaseTmxMapLoader, TmxMapLoader,AtlasTmxMapLoader: private methods -> protected

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/build.gradle

As suggested in #5303, Android's build.gradle file must be changed if AndroidX is enabled in the project. The change works if AndroidX is not enabled.

Android build.gradle template for AndroidX compatibility

---

CHANGES
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNativesLoader.java
extensions/gdx-box2d/gdx-box2d/jni/maven/pom.xml
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/utils/Box2DBuild.java
extensions/gdx-bullet/jni/maven/pom.xml
extensions/gdx-bullet/src/com/badlogic/gdx/physics/bullet/BulletBuild.java
extensions/gdx-controllers/gdx-controllers-desktop/jni/maven/pom.xml
extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/DesktopControllersBuild.java
extensions/gdx-freetype/jni/maven/pom.xml
extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreetypeBuild.java
extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/AntScriptGenerator.java
extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/BuildTarget.java
extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/JniGenSharedLibraryLoader.java
gdx/jni/maven/pom.xml
gdx/src/com/badlogic/gdx/utils/GdxBuild.java
gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java

- Added arm support to BuildTarget/AntScriptGenerator.
- Created default BuildTarget's for arm32(debian's armhf)/arm64
- Fixed aarch64 (arm64) not being detected correctly in SharedLibaryLoader.
- JniGenSharedLibraryLoader is now more consistent with SharedLibaryLoader.
- ~~SharedLibraryLoader#extractFile and SharedLibraryLoader#extractFileTo now have optional resultFileName parameter to support renaming during extraction.~~
- ~~Renamed private SharedLibraryLoader#extractFile to SharedLibraryLoader#extractFileIfRequired to differentiate method signature. (I'm open to better name suggestions)~~
- ~~LwjglNativesLoader will utilize renaming support to always use liblwjgl.so on disk to match expected library name.~~
- Kept as much backwards compatible as possible.
- If compiler is not on …

libgdx/jnigen armhf/aarch64 native build support

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidDaydream.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFiles.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFragmentApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidLiveWallpaper.java
gdx/src/com/badlogic/gdx/Files.java
gdx/src/com/badlogic/gdx/files/FileHandle.java

Since Android 6, the use of the sd card is only possible by showing a runtime permission dialog. This is not easy to implement and somehow scary for most users. Since Android 10, access to the sd card is not possible at all.
This PR changes the used path to the app external storage dir that is intended for the app to write to for other apps to read from. No runtime or other permissions are needed to use it.

Make external files work on Android 10 and up

---

gdx/jni/etc1/etc1_utils.cpp

Fix convert8To4, convert8To5
See "https://android.googlesource.com/platform/frameworks/native/+/2b93f0bf448160b002dec10c5bb1c9985a5950e6"

Fix compilation warnings in etc1_utils.cpp

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/DefaultLwjglInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/DefaultLwjgl3Input.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java
gdx/src/com/badlogic/gdx/Input.java
gradle/dependencies.gradle

Since iOS 13.5, iOS gives us real key events from hardware keyboards. I've added that to our robovm backend.
It is downwards compatible, older iOS versions since 9 have the used callback but don't call it (it was used on tvOS only) and therefore on older iOS versions nothing happens. But the game must be build with iOS SDK 13.5 or newer, that means robovm 2.3.10 is needed and therefore the dependency changed.
Since key event handling is used very different in libGDX (keys vs keyTyped, polling vs event handling, not to speak about Scene2d text fields, I was not able to test every type of key input. However, I tested with my game, with InputTest and SoftKeyboardTest on iOS 12, 13.2 and 13.4. As this is an addition, situation is in any case better with than without it. :-)
EDIT: Can be …

iOS RoboVM: Support hardware keyboard events

---

tests/gdx-tests-android/assets/data/g3d/knight.g3dj

This model have emissive color which was not used before but make this model ultra white now (related to #5529).
I checked all other G3DJ files, only this one was wrong (other doesn't have emissive attribute). I'm not able to fix G3DB files because i don't know where are original models if any.

fix 3D model test emissive color

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/AnimationController.java

As described in issue #6136 there was inconsistency check in 2 methods calling each other, resulting to a StackOverflowError in some cases : 
* queue method considering both animation==null and loopCount==0 as stopped animation
* animate method considering only animation==null as stopped animation

Prevent StackOverflowError in some cases, fixes #6136

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java

This PR makes ios-moe generated by gdx-setup.jar work.
libGDX with Multi-OS Engine(community) is available.
About org.multi-os-engine.community
https://discuss.multi-os-engine.org/t/moe-sdk-gradle-plugin-community-edition-release-1-5-0/2769
Generate project sample (using gdx-setup.jar)
https://github.com/ark100/multi-os-engine-libgdx-generateproject-sample

Makes ios-moe generated by gdx-setup.jar work

---

extensions/gdx-box2d/gdx-box2d/jni/com.badlogic.gdx.physics.box2d.joints.RopeJoint.cpp
extensions/gdx-box2d/gdx-box2d/jni/com.badlogic.gdx.physics.box2d.joints.RopeJoint.h
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/joints/RopeJoint.java
gdx/jni/gdx2d/gdx2d.c

Discovered these while compiling with VC:
* gdx2d.c: use char* instead of void* for pointer arithmetic.
* gdx-box2d: fixed return type for jniSetMaxLength (should be void).

Minor JNI/C fixes

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidLiveWallpaper.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidLiveWallpaperService.java

This exposes the live wallpaper engine's ability to report "visually significant" colors for the launcher and lock screen to use. I don't have a phone that noticeably uses this feature, but one of my users confirmed after I updated my app with this code that their lock screen now correctly shows bright text for the clock overlay when my wallpaper is dark, and vice versa.
I didn't add the method to the `Application` interface, since it would just be clutter for anything that isn't a Live Wallpaper. If it needs to be called from the `core` module, a platform resolver interface can be used.
I thought it would be most convenient to use Gdx's `Color` class for reporting the colors. The Colors are copied rather than directly referenced so this method can be thread-safe. The documentation of …

Add AndroidLiveWallpaper.notifyColorsChanged

---

extensions/gdx-box2d/gdx-box2d/jni/build.xml
extensions/gdx-bullet/jni/build.xml
extensions/gdx-controllers/gdx-controllers-desktop/jni/build.xml
extensions/gdx-freetype/jni/build.xml
extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/AntScriptGenerator.java
gdx/jni/build.xml

Will prevent failure when we dont have certain compilers on path and the downloaded natives from libgdx's website aren't present.
I really don't like this, so I will want to look into this more later.

Jnigen will add `erroronmissingdir="false"` to jar tasks

---

CHANGES
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Sync.java

Add an option to configure the target framerate for a lwjgl3 application. This can be used to circumvent issues with vsync (as described [here](https://github.com/libgdx/libgdx/issues/4274#issuecomment-535882414)) or whenever someone wants to set another target framerate than the display refresh rate, so using vsync doesn't work. This is commonly used as a workaround by the community.
This PR uses the well-proven [Sync class](https://github.com/LWJGL/lwjgl/blob/master/src/java/org/lwjgl/opengl/Sync.java) from lwjgl2. It is licensed under the [LWJGL 2 License](http://legacy.lwjgl.org/license.php.html).

Add a Lwjgl3ApplicationConfiguration#foregroundFPS option.

---

extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Filter.java
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Fixture.java

This PR fixes performance issues caused by JNI overhead in certain Box2D scenarios.
Box2D resolves if 2 objects should collide or not in `World#contactFilter`. Every time 2 fixtures overlap, Box2D needs to know wether they need to collide or not. In certain scenarios with lots of bodies, even if they don't collide with one another, that method will be called many times every time there's an overlap.
In the libGDX Box2D integration we have several ways to make the "should collide" resolution.
1. Mask/Category bits
2. Group id
3. Custom `ContactFilter`
Checking the `World#contactFilter` implementation we see that unless we use option 3, 2 JNI calls to `jniGetFilterData` will be made. The only thing `jniGetFilterData` does is to get the `Filter` data from the `Fixture`. The problem is the …

Cache Box2D Fixture filter data to avoid JNI overhead

---

gdx/src/com/badlogic/gdx/graphics/g3d/Environment.java
gdx/src/com/badlogic/gdx/graphics/g3d/environment/DirectionalShadowLight.java

DirectionalShadowLight has been deprecated for a long time (since the beginning), considered as "experimental". However, some people usie it, it works well and it didn't changed for years.
Most devs was confused about its deprecation state and thought it will be removed in a future version.
Also, in order to add improvements in the future (and probably mark some methods as deprecated), i thought it would be better to cleanup this to avoid confusion.

remove Directional shadows deprecation

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplicationConfiguration.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java

- Add resizable/undecorated options to LWJGL config.
- Add 'forceDisplayModeChange' flag in LwjglGraphics to force 'setWindowedMode' to reconfigure the Display after a call to 'setUndecorated'
See #3956 for past submission.

Add resizable/undecorated options to LWJGL

---

gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java

Each matrix is copied in one go, rather than 1 element at a time.

More efficient way of setting bone state 

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/AnimationController.java
gdx/test/com/badlogic/gdx/graphics/g3d/utils/AnimationControllerTest.java

Issue #6145 describe the edge case where action (queued animation) was not removed when just finished.
The extra update is not necessary with zero delta time in this case.
@asu-talk thank you a lot for your test case, i rewrote it as a JUnit.

AnimationController action end up at duration time, fixes #6145

---

gdx/src/com/badlogic/gdx/scenes/scene2d/Actor.java

Adds scaleChanged callback to Actor similar to the ones for size, position and rotation.
The lack of a scaleChanged callback seemed like an oversight to me that became apparent when drawing an Actor via a FrameBuffer that depended, among others, on an Actor's scale. This would help my and similar issues.
If required for the pull request to be accepted, I'll gladly sign the CLA.

Adds scaleChanged callback to Actor.

---

extensions/gdx-setup/README.md
extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtensionsDialog.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/SetupPreferences.java

Support more location for the preferences file, using the same conventions as git. With no user action the behavior remains the same.
- $HOME/.gdxsetup
- $XDG_CONFIG_HOME/gdxsetup/config
- $HOME/.config/gdxsetup/config
(The corresponding of XDG_CONFIG_HOME for windows and mac could be added)
Also minor visual improvements, mainly a tooltip for the ambiguous destination field (and updated the screenshot).

Gdxsetup config

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationConfiguration.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/src/HtmlLauncher
tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/client/GwtTestStarter.java
tests/gdx-tests-gwt/war/index.html
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtWindowModeTest.java

In the past, we had frequent questions how an application can be made resizable on GWT, that means taking up the available space in browser. This was solved eventually with some example code in HTMLLauncher.
However, this was more a workaround then a real solution, and I am moving the code from HTMLLauncher into the backend with this PR. It is easy to see that the behaviour is unaffected if we start a fixed size application with set width and height, therefore I mark this as non-breaking. 
I also improved the Gwt tests: there was no way to enter superdev debugging mode before, and the windowed mode test had a wrong button label often.
I tested resizeability with usePhysicalPixels on and off on Firefox Desktop, Chrome Desktop, Chrome Mobile, Firefox Mobile and Safari Mobile. I discovered …

Gwt Backend support resizable application

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALLwjglAudio.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALMusic.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALMusic.java
gdx/src/com/badlogic/gdx/math/Interpolation.java
gdx/src/com/badlogic/gdx/math/MathUtils.java
gdx/test/com/badlogic/gdx/math/Vector2Test.java

Minor cosmetic improvements to some of the `MathUtils` public constants not to use hardcoded values. All constants have the same value as before.
I've also added a new constant `MathUtils.HALF_PI` which doesn't introduce extra floating precision in comparison to using `MathUtils.PI / 2f` but it's a common enough value to have it there.
NOTE: I had originally changed `radiansToDegrees` and `degreesToRadians` to improve the float precision error but, even if technically the value is closer to the real one, when working with floats for everything (when using `MathUtils` API), conversions that you'd expect to be exact such as `MathUtils.PI / 6f  * radiansToDegrees = 30`  ended up having a precision error like `30.000001`.

Minor MathUtils constants improvements

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/PreloaderBundleGenerator.java

to calculate MD5 hash, relates to #4314
Commons is on Classpath for Gradle, but not for Ant. It is not really needed, so replace it with own implementation.

GWT PreloaderBundleGenerator don't use Apache Commons 

---

gdx/src/com/badlogic/gdx/assets/loaders/resolvers/ResolutionFileResolver.java

When HDPI support was introduced, a lot of `Gdx.graphics.getWidth()` calls had to be changed to `Gdx.graphics.getBackBufferWidth()`, see #3702. ResoultionFileResolver was still missing. In this case, it makes sense to use the backbuffer (= real) resolution instead of the logical resolution, because the logical resolution does not reflect what the user is really capable of displaying on his/her monitor.

ResolutionFileResolver now uses the back buffer size.

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java

There are some methods like `texImage2D (int target, int level, int internalformat, int format, int type, VideoElement video)` which are not exposed with GwtGL20.

Make the WebGLRenderingContext public

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java
gdx/src/com/badlogic/gdx/graphics/Pixmap.java
tests/gdx-tests/res/com/badlogic/gdx/GdxTests.gwt.xml
tests/gdx-tests/src/com/badlogic/gdx/tests/DownloadTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

Downloading an image from HTTP is easy on JVM platforms, but it is difficult - especially for beginners - to do on GWT. Ironically, GWT backend fetches all images needed for the game from an url before the game starts, so everything needed is already implemented. 
Thus, the new method downloadPixmapFromHttpUrl is on the one hand just a convinience method, on the other hand desperately requested.
Please check the DownloadTest. On GWT, it will throw an expected failure for the first URL to test error handling and will download the next image in the queue.

Net: New method downloadPixmapFromHttpUrl

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java

`GwtGL20` only supports a subset of values being passed to `glGetIntegerv`. This PR adds `FRAMEBUFFER_BINDING`, which is useful if one wants to nest framebuffers inside of each other. This closes #4688.
The implementation is a bit more complex, since, unlike desktop OpenGL, WebGL does not return an integer, but rather a FrameBuffer object. Consequently, a look up is used to determine the ID of that framebuffer.
<details>
<summary><b><I>Click to show an executable example</i></b></summary>
What is supposed to happen: A green triangle is rendered; the console output should be `A: 0`, `B: 1`, `C: 2`, `D: 0` as those are the framebuffers bound at that moment.
```java
public class FrameBufferTest2 extends GdxTest {
FrameBuffer fbo1, fbo2;
ShapeRenderer shapeRenderer;
boolean enableFbo1 = true; …
```

Add FRAMEBUFFER_BINDING support to GwtGL20.

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtFileHandle.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/Preloader.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/webaudio/WebAudioAPIManager.java

With #4314 the file names contain the hash. This breaks the web audio implementation because it loaded the files with the original file names

Fix sound and music not playing because of changed file names

---

CHANGES
gdx/src/com/badlogic/gdx/math/Intersector.java
tests/gdx-tests/src/com/badlogic/gdx/tests/IntersectorOverlapConvexPolygonsTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

Hello everyone, this should fix #5048
Sorry for not adding a non graphical test but the magic happens in the SAT Algorithm. If you are familiar with the algorithm the placement and the orientation of the minimum translation vector happens on the one dimensional axis.
The magic happens when we project the axis of the max and min points of the polygon and based on the scalar value (dot product) of this values i calculate the direction of the minimum translation vector. You can see this with the red line in the graphical Test.
TL;DR i added no functional Test because of math magic. It is hard to predict the assert value so a graphical test with debug output says more than 1mio asserts.
Also you see in the code and in the graphical test i also handle edge cases like when one polygon contains …

- Fixes Issue #5048. The function Intersector.overlapConvexPolygons now should return the right minimum translation vector values.

---

gdx/src/com/badlogic/gdx/math/Bresenham2.java
tests/gdx-tests/src/com/badlogic/gdx/tests/Bresenham2Test.java

Before, it implemented something else, and couldn't complete some common lines, like any 2-point diagonal line. The Bresenham2 test is now much more robust, and can be used to preview any line from the center of a 160x120 area to anywhere in that area. If green is ever visible in the test's line, that means there's some discrepancy between the actual algorithm and what Bresenham2 implements; so far I haven't seen any green and this can connect all lines. This fixes #5012 .

Make Bresenham2 actually implement Bresenham's algorithm

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/core/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/desktop/build.gradle
extensions/gdx-setup/src/com/badlogic/gdx/setup/Language.java

A couple of minor improvements to the Gradle scripts generated by Gdx Setup.
1. On `core` and `desktop` modules, `build.gradle` generated scripts contained the line `apply plugin: "%LANG%"` which is unnecessary as this plugin is already defined per module on root `build.gradle`. Also, in the case of Java it was adding `apply plugin: java` instead of `apply plugin: java-library`.
2. Replaced deprecated `apply plugin: "android"` by `apply plugin: "com.android.application"`.

Gdx Setup minor Gradle fixes

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
fetch.xml
gradle/dependencies.gradle
pom.xml

Remove the temporary workaround to support RoboVM Snapshot versions and set version to 2.3.10.

Update RoboVM to 2.3.10 stable version

---

backends/gdx-backends-gwt/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/build.gradle
extensions/gdx-setup/src/com/badlogic/gdx/setup/BuildScriptHelper.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/Language.java
gradle/dependencies.gradle
tests/gdx-tests-gwt/build.gradle

Since Jetty plugin was removed, we use Gradle's SimpleFileHttpServer to serve the assets in superdev mode.
This has unfortunately some drawbacks:
* Files without extension aren't served, causing older projects (including our test project) to fail in superdev mode
* The server is not killed when super dev process is stopped, so task manager has to be your regular friend while developing
* SimpileFileServer is very simple (hence the name) and does not support caching or default file mechanisms
This PR changes our tests and the template project to use Gretty (Gradle Jetty Plugin), as we used Jetty before. The problems listed above are fixed with this.
I know from the history @Tom-Ski tried to integrate Gretty before, but eventually removed it. I suppose it was because Gretty fails to run out …

GWT: Use Gretty for serving files in superdev mode

---

gdx/src/com/badlogic/gdx/graphics/glutils/VertexBufferObjectWithVAO.java

It's possible to change the buffer data without _(required)_ `glBindBuffer`.
Bug reproduction:
```java
VertexBufferObjectWithVAO vbo1 = new VertexBufferObjectWithVAO(true, nums, attributes);
vbo1.setVertices(vertices, 0, count);
VertexBufferObjectWithVAO vbo2 = new VertexBufferObjectWithVAO(true, nums, attributes);
vbo2.setVertices(vertices, 0, count);
vbo1.bind(shader);
// render
vbo1.unbind(shader);
vbo2.bind(shader);
// render
vbo2.unbind(shader);
vbo1.bind(shader); // no glBindBuffer.
vbo1.setVertices(vertices, 0, count); // ERROR: possibly updates vbo2's buffer instead.
```
I need feedback please, thanks.

Fixed the glBufferData bug in bufferChanged().

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL30.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3GL30.java

Related Issue https://github.com/libgdx/libgdx/issues/6203
glGetActiveUniformiv was calling the `i` (single output) version at all times. I swapped the function calls for the vectorized version.
I've tested the Lwjgl3 backend and it works.
Haven't tried the Lwjgl2 backend yet (but I would assume it's fine)

Lwjgl backends call correct LWJGL function for vectorized input

---

tests/gdx-tests-android/assets/data/shaders/instanced-rendering.frag
tests/gdx-tests-android/assets/data/shaders/instanced-rendering.vert
tests/gdx-tests-android/assets/data/uiskin.json
tests/gdx-tests-lwjgl/build.gradle
tests/gdx-tests-lwjgl/src/com/badlogic/gdx/tests/lwjgl/LwjglTestStarter.java
tests/gdx-tests-lwjgl3/build.gradle
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3TestStarter.java
tests/gdx-tests/res/com/badlogic/gdx/GdxTests.gwt.xml
tests/gdx-tests/src/com/badlogic/gdx/tests/VBOWithVAOPerformanceTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/MultipleRenderTargetTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gles3/InstancedRenderingTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/CommandLineOptions.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTestConfig.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

this PR adds some improvement to Gdx tests and enable distribution for both Lwjgl and Lwjgl3 launchers : 
* gl30 switch can now be enable via CLI argument (--gl30)
* non compatible tests are disabled : 
* with Lwjgl3 launcher, items are disabled (grayed)
* with Lwjgl2 launcher, items are removed (i didn't want to mess with Swing, please forgive me)
* a new Annotation allow to say if a test requires gl30 or not.
* InstancedRenderingTest was missing in the list but it fails with Lwjgl2 (glVertexAttribDivisor method is not properly mapped apparently)
Notes: 
* this new mechanism (argv options and annotation) may be used for future needs, when application configuration needs some special setting for a particular test.
* gl30 options enable GLES 3.2 to be compatible with MacOSX.
Gdx tests …

Improved GdxTests and enable distribution for desktop tests

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/ShaderProvider.java

Since `ShaderProvider` interface does already contain declaration of the `public void dispose()`, it makes sense to allow working with these instances same as with `Disposable` ones.
Also, `import` declarations, which are never used, have been removed here.

ShaderProvider extends Disposable

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DepthShader.java
gdx/src/com/badlogic/gdx/graphics/g3d/utils/BaseShaderProvider.java

Few issues i tried to fix with the less breaking changes as possible :
* Sometimes, a shader created with a given configuration (renderable), cannot render the same configuration (canRender method). This causes an overflow of shader creation at each drawing making shaders list growing indefinitely. Now, an exception is thrown.
* Depth shader configured with maxBones=0 is one of those case : it can't render a skinned mesh even if it has been created with a skinned renderable.
* While i was fixing it, i saw that a new DepthShader is created depending on renderable bones count. DefaultShaderProvider doesn't care about bones count, it provides 2 variants : one with skinning, one without. I changed depth shader to use the same approach. Several models with different bones count means a lot of …

Fix shader providers overflow and depth shader skinning configuration

---

CHANGES
gdx/src/com/badlogic/gdx/math/Intersector.java
gdx/test/com/badlogic/gdx/math/IntersectorTest.java

This PR simply adds a method to calculate the intersection point between three planes.
Returns false if there is no intersection or the intersection is not a point.
Returns true if there is an intersection point.
This post might help to illustrate the math behind it: http://geomalgorithms.com/a05-_intersect-1.html
I need this code (among other reasons) to prove with images that the PR #6086 is not breaking anything and is doing the same calculation as before.
**Tags**
- Non breaking changes
- Math
Closes #6214

Add method to calculate intersection point between three planes

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
gdx/src/com/badlogic/gdx/Graphics.java

Insets API was still returning physical pixels after the changes on https://github.com/libgdx/libgdx/pull/3709. Made the Insets API consistent by returning logical pixels.

Return iOS Insets in logical pixels

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL30.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3GL30.java

fixes https://github.com/libgdx/libgdx/issues/6230
Previously in LWJGL backends `glDrawbuffers` would rely on the `remaining()` of the `IntBuffer` passed in, ignoring the bufsize argument (`n`). This would possibly cause errors when users would expect (`n`) to limit the number of args passed to opengl from the buffer.
Now the buffer is limited by (`n`) properly
I've tested this with framebuffers on my own project and they work.

glDrawBuffers no longer ignores bufsize (n) argument

---

gdx/src/com/badlogic/gdx/math/Intersector.java

Closes #3622. As detailed in that issue, `Intersector.pointLineSide` returns the wrong side. Simple example:
```
Vector2 start = new Vector2(0, 0);
Vector2 end = new Vector2(0, 10f);
Vector2 point = new Vector2(-1, 10f); // clearly left of the line
int side = Intersector.pointLineSide(start, end, point);
System.out.println(side);
```
Instead of changing the actual implementation, which could break code relying on it, I just fixed the documentation.

Fix Intersector#pointLineSide documentation.

---

gdx/build.gradle

Building libGDX project with Gradle was failing (just run `gradlew clean build` to test) due to a bad workaround I added to fix Android and Desktop tests not running on IDEA (https://github.com/libgdx/libgdx/commit/a30ecf0c1f41f9f2e6a7403520e0bdcd7f4bcb72).
This alternative workaround fixes the Gradle issue and keeps IDEA happy (thanks to PokeMMO).

Fixes libGDX Gradle build error

---

gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java

GLFrameBufferBuilder methods return itself for chaining but visibility was protected so the return type couldn't be used. Following example code now compile :
```java
FrameBuffer fbo = new FrameBufferBuilder(w, h)
.addColorTextureAttachment(GL30.GL_RGBA8, GL30.GL_RGBA, GL30.GL_UNSIGNED_BYTE)
.addDepthTextureAttachment(GL30.GL_DEPTH_COMPONENT, GL30.GL_UNSIGNED_SHORT)
.build();
```
This change also allows GLFrameBufferBuilder subclassing as a side effect, not sure it's so bad.
I saw 3 ways to fix this : 
* change return type to void, which would remove builder design pattern.
* messing with generics to return concrete type, which would overcomplexify code and would be a breaking change.
* simply change class visibility (what i did)

fix GLFrameBufferBuilder visibility

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/surfaceview/GLSurfaceView20.java
backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/input/MockInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/DefaultLwjglInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/DefaultLwjgl3Input.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java
gdx/src/com/badlogic/gdx/Input.java
gdx/src/com/badlogic/gdx/input/RemoteInput.java
tests/gdx-tests/src/com/badlogic/gdx/tests/OnscreenKeyboardTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java

Is mainly useful for the ability to open the numeric/phone keyboards directly.
Current implementation adds Default, NumberPad, PhonePad, Email, Password, URI options which are mapped back to Android/iOS types.
Android Password/URI types do not visually change anything on my device, but I do not know if this is keyboard dependent. Password type may also prevent autocomplete data from learning passwords.
iOS code is untested. I am not sure if the current setKeyboardType call is sufficient enough to actually change the keyboard.
Github wont let me reopen #5201 because I force pushed.
I have been running a version of this internally on Android for years, and have recieved a handful of reports that the keyboard will occasionally get stuck on the incorrect type. This is fairly rare, and I …

Support specifying which onscreen keyboard type to use

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java

Fixes #5814 
To support iOS Split screen, the only required change is to calculate the graphics bounds using the iOS window object instead of the screen. Any app that doesn't want to support split screen just has to add the `UIRequiresFullScreen` flag to their `Info.plist`.
In addition to changing that, there's several things related to it that have been improved.
1. Window is now created and set before libGDX is setup and creates Graphics. This way, when Graphics are created and `computeBounds()` called, `window` is not null.
2. The `window` property on `AppDelegate` is now explicitely set with the main window we set key by calling `uiApp.getDelegate().setWindow(uiWindow)`. In libGDX we keep a reference to this window on `IOSApplication` (called `uiWindow`) but on standard iOS apps it is …

Added support ios split screen. Fixes #5814

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphicsLiveWallpaper.java
gdx/src/com/badlogic/gdx/Graphics.java

Fixes #6228.
- `getRawDelta()` has been deprecated as, at least for now, it's a duplicate of `getDelta()`.
- the line `mean.clear()` on `setContinuousRendering()` can be safely removed because it was added to fix an issue caused by the smoothing (https://code.google.com/archive/p/libgdx/issues/962).

Fix #6228. Removed delta smoothing on Android backend

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AsynchronousAndroidAudio.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AsynchronousSound.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidAudio.java

This PR adds an alternative audio implementation (`AsynchronousAndroidAudio`) aimed at improving sound performance.
Current sound implementation has a very poor performance in scenarios in which several sounds are played at the same time. This is caused by the main thread being locked each time a method that returns a "sound id" such as `float play()` is called. For some reason, Android takes much longer to return a sound id in these scenarios and no configuration of the `SoundPool` seems to fix it.
The proposed approach is to play the sounds on a separate thread. The drawback of this approach is that operations that use `soundId` are no longer supported but that's not a big deal in most scenarios. I personally use this implementations in all my games and the results are great.
For an app …

Alternative asynchronous sound  Android Audio implementation

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java

Density not only was being calculated using `IOSDevice` information (which is risky in case there's a mistake) but it was using Android's 160 dpi value which reported wrong density values on iOS (326 ppi / 160dpi = 2,0375 when it should be 326ppi / 163dpi = 2).
We already obtain points per pixel programatically (API available since iOS 8), there's not reason to depend on `IOSDevice` information afaict.

Fix wrong reported density on iOS

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSDevice.java

Updated `IOSDeviceList` with last year devices.
I think we could consider removing unsupported devices (max iOS version < 8). The list keeps growing and I don't think it makes sense to have devices not supported by libGDX.

Updated IOSDevice list with last year devices

---

.github/workflows/build.yml

This change allows skipping the Github Actions CI by adding "[ci skip]" to the commit message. This was a feature in the previously used Travis CI and is useful for README or documentation changes.
It is based on [this](https://github.community/t/github-actions-does-not-respect-skip-ci/17325/9) Github community post.

Add a skip-flag for GH Actions.

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/surfaceview/GLSurfaceView20.java
backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/input/MockInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/DefaultLwjglInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/DefaultLwjgl3Input.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java
gdx/src/com/badlogic/gdx/Input.java
gdx/src/com/badlogic/gdx/input/RemoteInput.java
tests/gdx-tests/src/com/badlogic/gdx/tests/TextInputDialogTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gwt/GwtTestWrapper.java

This is a follow-up to #6235 and adds support for different keyboard types on iOS and Android for `getTextInput` method.

Support specifying which keyboard type to use for getTextInput

---

extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Filter.java
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Fixture.java

Unfortunately this change has unintended consequences on Box2D making collision logic unreliable. 
I pushed a live app with libGDX 1.9.12 and have received several user reports about objects traversing walls in some cases.
I was able to reproduce incorrect collision resolution by changing the filter data of an existing object by calling `setFilterData` but there may be other scenarios. My guess is that this is caused because the filter data is not applied immediately when calling `setFilterData` as stated on this comment:
```
/** Set the contact filtering data. This will not update contacts until the next time step when either parent body is active and
* awake. This automatically calls Refilter. */
```
causing a mismatch between Box2D internal state and libGDX state.
**EDIT: The cause of …

Revert 6118 "Cache Box2D Fixture filter data to avoid JNI overhead"

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java

#6245 changes on `getDensity()` were not following `Graphics` API which specifies:
```
/** This is a scaling factor for the Density Independent Pixel unit, following the same conventions as
* android.util.DisplayMetrics#density, where one DIP is one pixel on an approximately 160 dpi screen. Thus on a 160dpi screen
* this density value will be 1; on a 120 dpi screen it would be .75; etc.
*
```
As a separate PR we can add a new interface method to easily get the amount of physical pixels per logical pixel, maybe promoting the already present on iOS `getBackBufferScale()`.

Fix getDensity() on iOS to be consistent with the rest of backends

---

gdx/src/com/badlogic/gdx/scenes/scene2d/utils/TiledDrawable.java

Fixed by updating the packedColor in `SpiteBatch`.

Fix the TiledDrawable color.

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java

As point out in #6207, I can't see any downside to enable back buffer for all created windows rather then the only first one.
This commit will fix the MSAA issue for multiple windows and allow users to set custom back buffer configuration for any window.
I've tested this in some environments and I haven't noticed any unexpected behavior, also, I can't find online any reason why this was made in the past, please check it.
Thanks

Set back buffer configs for any window

---

backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessApplication.java
backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/graphics/MockGraphics.java

Also report raw delta time instead of 0 (wrong). 
Fixes #4742

HeadlessApplication use nanotime for render interval

---

gdx/src/com/badlogic/gdx/utils/Scaling.java

Scaling.contain was missing from the scaling options. It basically functions like Scaling.fit if the image is too big to fit in the defined space, but will act like Scaling.none if it does fit. This means it will only scale the image down and never up. Useful for icons that are usually all the same size but also allowing you to use icons that are oversized without having to worry about the image spilling over into the rest of the UI.

Added "contains" scaling mode.

---

CHANGES
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java
gdx/src/com/badlogic/gdx/Input.java

Typically, every libGDX HTML project has to tweak around with index.html to prevent browser's default behaviour on certain key presses (F1, Alt, Space, Arrow Keys and stuff).
We already have `setCatchKey` to prevent system or background app behaviour on key presses, but this is only implemented on Android so far. This PR adds the ability to use the setCatchKey methods to prevent browser default behaviour on GWT.
Additionally, this changes `keyForCode` from private static to protected. Since we now can override the input processing class, it makes sense to have this method overridable as well.

GWT use setCatchKey to prevent browser's default behaviour

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java

This fixes key mappings for
* Right shift
* Right ctrl
* Right alt
* Numpad star 
* Numpad divide
on GWT backend

GWT fix some key mappings

---

extensions/gdx-controllers/gdx-controllers-android/src/com/badlogic/gdx/controllers/android/AndroidControllers.java
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/proguard-rules.pro

Removed some unnecessary Proguard rules:
- `dontwarn android.support` rule is default on Android `proguard-android.txt` platform file, no need to add it again (and with migration to AndroidX I don't think is relevant for us anyway).
- `AndroidControllers` rule is not needed after removing reflection code
- `AndroidInput` rule is not needed either (legacy reflection), actually that class is now an Interface, the old one was renamed to `DefaultAndroidInput`.

Simplifiications to Proguard config

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidClipboard.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglClipboard.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Clipboard.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtClipboard.java
gdx/src/com/badlogic/gdx/utils/Clipboard.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ClipboardTest.java

Apple has added a new banner alert to iOS 14 that lets users know if an app is pasting from the clipboard and therefore able to read the clipboard’s contents ([More information](https://9to5mac.com/2020/06/24/ios-14-clipboard-notifications/))
I've added a `boolean hasContents()` method to the `Clipboard` interface and adjusted the iOS and Android implementations, so that the actual clipboard content is not read by the app when calling this method.

Add hasContents to Clipboard interface, to reduce clipboard notifications on iOS 14

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java
tests/gdx-tests/src/com/badlogic/gdx/tests/TextAreaTest.java

This is another way to fix problem #6219  TextField tab traversal on GWT.
The problem is caused by the behaviour of web browsers to not send a keypress event for Tab key. Instead of changing the core component to listen for keydown/keyup, this PR emulates the keypress event on GWT when the keyup event is raised by the browser. This way, we've got the same behaviour on HTML5 as on other platforms.
TextAreaTest can be used to test that this works as intended.

Fix TextField tab traversal on HTML5

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java

This way, the API is more flexible: it will not require people to potentially copy-paste the whole class just to tweak its Listeners.

Extracted the setup of ScrollPane's Listeners

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/DefaultLwjglInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/DefaultLwjgl3Input.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java
gdx/src/com/badlogic/gdx/Input.java

This adds keybindings for F13 to F24 as requested in #5389 
I couldn't test this because I have not such a keyboard. I derived the necessary keybindings from the given constants in the backends. For GWT and Android, there were no constants defined in code. [This page](https://source.android.com/devices/input/keyboard-devices) lists them for Android, [this one](https://keycode.info/) for JS. Lwjgl2 only supports F13 to F18, I did not forget the other ones. :)

Add support for hardware keys F13 to F24

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/surfaceview/GLSurfaceView20.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java

After a post from user "tann" on Discord #android channel we've realised some inconsistencies on the libGDX default color format (RGB565) and the platform defaults on Android (RGB888) and iOS (RGBA8888).
It is currently set to RGB565 because that was the default of `GLSurfaceView` before but, currently (not sure since when), it's RGB888 (https://developer.android.com/reference/android/opengl/GLSurfaceView.html).
> By default GLSurfaceView will create a PixelFormat.RGB_888 format surface.
I've kept RGB565 as fallback in case the provided color format configuration is not supported by the device. This is the safest approach as, in the rare case a device did not support RGB888 it would fallback to previous default but it's not necessarily the best one. It depends if there are actually …

Use platform default color bit depth on Android and iOS

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java

Media key mapping for gwt.
I also tried to map lwjgl and lwjgl3, but both of them return 0 or -1 for each key.
Robovm has already some of the keys mapped. I couldn't find enum entries for the missing ones.

Media Keys for gwt

---

CHANGES
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java

By default Cubemaps are not seamless, it requires either GLES 3.2, OpenGL 3.2 or GL_ARB_seamless_cube_map in order to enable it.
```java
if(Gdx.graphics.getGLVersion().isVersionEqualToOrHigher(3, 2) || 
Gdx.graphics.supportsExtension("GL_ARB_seamless_cube_map")){
Gdx.gl.glEnable(GL30.GL_TEXTURE_CUBE_MAP_SEAMLESS);
}
```

added GL_TEXTURE_CUBE_MAP_SEAMLESS

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL20.java

this toIntBuffer method is only used by shader program `glUniform[1|2|3|4]iv` methods. Those are not used by the framework and rarely used in general, that's probably why the issue was found recently.

fix toIntBuffer, fixes #6112

---

gdx/src/com/badlogic/gdx/graphics/glutils/ImmediateModeRenderer20.java

It might sounds like a breaking change but i can't see a case where user code check compilation and fallback to something else so i think it's fine to merge it as is.

added shader compilation check for ImmediateModeRenderer20

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java

These changes was inspired by #5763. I prefer to split changes from original PR. More will come later.
Current GwtGL20 missing some buffer flips and ByteBuffer support for some methods.

fix/improve WebGL 1.0 backend

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java

d3cbe98eb72ec68bdd8c8630034b50166e8da4f8 introduced resizable applications with no configured with and height, therefore `config.width` and `configh.height` being 0.
The initial call to set the viewport size still based on this constants, causing this call to set an invalid size for resizable applications. This was not noticed because our tests and most games use an own viewport, but of all things, our starter template generated by gdx-setup fails to render correctly without this fix.

GWT: Initial call to set viewport size fails for resizable application

---

gdx/src/com/badlogic/gdx/graphics/Cubemap.java

I refactored a constructor in order to have a common root constructor, filters and wrapping options was already the same as the default one in GLTexture.

add cubemaps to the management, fixes #5047

---

gdx/src/com/badlogic/gdx/math/MathUtils.java

The average and largest error are significantly better for this version (2-3 orders of magnitude), and it can be slightly faster. For comparison, this implementation uses one `Math.sqrt()` call (on a float argument and cast to float, which HotSpot optimizes well), whereas the implementation it replaces uses one float division. These seem to have about the same performance cost on modern Intel hardware; it may be different on AMD processors or ARM. In terms of accuracy, there's no comparison; the previous asin() in MathUtils was only usable if the high error near inputs of -1 and 1 wasn't noticeable.
This algorithm was described in a 1955 research study by RAND Corp, "Approximations for Digital Computers." There are other approximations for asin() described, but the first one, on sheet 35, …

Improve MathUtils.asin(), acos()

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java

On our Discord server, user valdimir asked for help: 
> gwt game on android mobile chrome: first play - success. Second run - appear "Sorry, your browser doesn't seem support WebGL"
> What could be the reason for this strange behavior?
Turned out this output is written out if there is an Exception thrown when initializing GwtGraphics, but there is no easy way to track down the underlying problem because the Exception is sallowed. This PR adds a console log output for debugging purposes.

GWT log failure initializing graphics

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java

I have this crash in my logs:
```
java.lang.IllegalArgumentException: No constant with value 669 (0x29d) found in org.robovm.apple.uikit.UIKeyboardHIDUsage
at org.robovm.rt.bro.ValuedEnum$AsLongMarshaler.toObject(ValuedEnum.java:142)
at org.robovm.rt.bro.ValuedEnum$AsMachineSizedSIntMarshaler.toObject(ValuedEnum.java:158)
at org.robovm.apple.uikit.UIKey.$m$keyCode(Native Method)
at org.robovm.apple.uikit.UIKey.getKeyCode(UIKey.java)
at com.badlogic.gdx.backends.iosrobovm.DefaultIOSInput.onKey(DefaultIOSInput.java:660)
```
A UIKeyboardHIDUsage with value 669 is currently not present in RoboVM bindings. Even if it is added, the IllegalArgumentException might be thrown when Apple adds another newly supported key and the game is compiled with a RoboVM version still not knowing it. To avoid …

iOS catch exception for unknown keys from hardware keyboard

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/robovm.xml
tests/gdx-tests-iosrobovm/robovm.xml

Since iOS 14, there is now a reliable way to detect a connected hardware keyboard. Until now, it is asumed that a keyboard is connected when a key was pressed. Therefore, we cannot detect a keyboard before the first key press which might confuse users, and we can't detect disconnection of the keyboard. Both is fixed with this PR.
The newly used method is part of GameKit framework, which I added to linked frameworks. It could be discussed if improving such a minor feature justifies the addition a new framework. But I am confident that most games out there will add GameKit sooner or later anyway because of GameCenter or other game related features.

iOS 14 detect connected hardware keyboard reliably

---

gdx/src/com/badlogic/gdx/math/MathUtils.java
gdx/src/com/badlogic/gdx/utils/IntFloatMap.java
gdx/src/com/badlogic/gdx/utils/IntIntMap.java

This fixes #6347 ; big thanks to @tomcashman for making the affected code so easy to spot.
In case what this does isn't obvious, IntMap and LongMap correctly check for whether their Values iterators are currently iterating through the "zero value," which is not in the regular array. When iterating over the value for a key that is zero, the iterator is at position `INDEX_ZERO`, which is -1. While IntMap.Values and LongMap.Values don't try to look up INDEX_ZERO in their value table, IntIntMap.Values and IntFloatMap.Values do, which currently causes an index out of bounds exception in 1.9.13. This makes IntIntMap and IntFloatMap match IntMap's correct behavior.

Fix missing checks for zero key during Values iteration in IntIntMap, IntFloatMap.

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java

Playing around with TextAreaTest, I noticed that pressing forward delete had the same behaviour than pressing backspace.
Cause is a wrong mapping to DEL which is NOT forward del. A check turned out that RoboVM also has a wrong mapping.

Fix keycode for FOWARD_DEL on GWT and iOS

---

extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Filter.java
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Fixture.java

This is an attempt to fix the issues caused by #6118 described in #6261.
Instead of setting `filter` to `null` on `Fixture` `reset()` which would cause an allocation every time a `Fixture` is obtained (`reset()` is called after `obtain()` in this case), I've opted to go for a no memory allocation approach by using a boolean flag to indicate if `filter` data is dirty. The drawback of this approach is that `getFilterData()` now returns the `Filter` reference used by `Fixture` meaning that, if  it's changed without calling `setFilterData()`, it will cause inconsistent behaviour. This also means the change may break backwards compatibility.
The approach suggested by @NathanSweet on #6118 asking if it was possible to remove `jniGetFilterData()` alltogether would require some hacks because …

 Cache Box2D Fixture filter data to avoid JNI overhead V2

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/DefaultLwjglInput.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglAWTInput.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/DefaultLwjgl3Input.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtInput.java
gdx/res/com/badlogic/gdx.gwt.xml
gdx/src/com/badlogic/gdx/AbstractInput.java

After we introduced an abstract graphics class, this PR introduces an abstract input class which aims to consolidate code that is implemented on all (or most) platforms.
We start with pressed key and caught key handlings.
This fixes some minor inconsistencies (keycodes going to 260 on Android, 255 on other platforms). We have a minor behaviour change, too: Setting caught keys will report them as caught when checked with `isCatchKey` (which is not really important, but good imo) even on platforms that have no behaviour change when keys are set to be caught.
With this PR, we also get rid of the two-sided mappings for keycodes on Lwjgl and Lwjgl3 which had inconsistencies as well. And the static methods for key mapping are converted to protected to make overriding in game projects possible. …

Introduce an AbstractInput class and consolidate some methods

---

gdx/src/com/badlogic/gdx/math/MathUtils.java
gdx/src/com/badlogic/gdx/utils/ArrayMap.java
gdx/src/com/badlogic/gdx/utils/IntFloatMap.java
gdx/src/com/badlogic/gdx/utils/IntIntMap.java
gdx/src/com/badlogic/gdx/utils/IntMap.java
gdx/src/com/badlogic/gdx/utils/IntSet.java
gdx/src/com/badlogic/gdx/utils/LongMap.java
gdx/src/com/badlogic/gdx/utils/ObjectFloatMap.java
gdx/src/com/badlogic/gdx/utils/ObjectIntMap.java
gdx/src/com/badlogic/gdx/utils/ObjectLongMap.java
gdx/src/com/badlogic/gdx/utils/ObjectMap.java
gdx/src/com/badlogic/gdx/utils/ObjectSet.java
gdx/src/com/badlogic/gdx/utils/OrderedSet.java
gdx/src/com/badlogic/gdx/utils/Queue.java
gdx/src/com/badlogic/gdx/utils/SortedIntList.java
tests/gdx-tests/src/com/badlogic/gdx/tests/JsonTest.java

This is a bit of an odd one, but it's not too complex. Some of the data structures in libGDX have special handling in Json, like IntMap, ObjectIntMap, and LongMap; these output like normal JSON maps, with only the present keys and present values written. Other data structures, like IntIntMap, IntFloatMap, and ObjectLongMap do not have such special handling, and output JSON like this for a 14-item IntIntMap:
```
{size:14,keyTable:[0,0,102,0,0,0,0,0,107,0,0,10,0,0,0,2,0,0,0,0,7,0,0,0,0,0,101,0,0,0,4,0,106,0,0,0,0,0,0,1,0,0,103,0,0,6,0,0,0,0,0,0,0,0,3,0,0,105,0,0,8,0,0,0],valueTable:[0,0,14,0,0,0,0,0,1,0,0,2,0,0,0,1,0,0,0,0,3,0,0,0,0,0,63,0,0,0,2,0,4,0,0,0,0,0,0,1,0,0,2,0,0,2,0,0,0,0,0,0,0,0,1,0,0,6,0,0,2,0,0,0]}
```
instead of what the same data in an IntMap<Integer> looks like:
``` …
```

Fix crash during Json serialization of IntIntMap (and probably others) after iteration

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java

At least some of the font generators in Hiero require the 'x' character to be present in a font to use it, but Hiero also remembers the last-selected font for the next startup, and doesn't forget it if it's invalid. This PR makes Hiero forget the selection of the invalid font (removing its name from Preferences), sets the selected font to Arial (which should be available anywhere, since Hiero already fell back to it as a backup in one other place), and writes out a note in the sample text that says that Arial was selected and why (missing 'x'). The note can be easily removed just by pressing the ASCII, NeHe, or Extended buttons, but it lets the user know why Arial was selected instead of some emoji-only font or something. This fixes #6359 , as far as I can tell. It also means there isn't …

Hiero: If a font lacks 'x', fall back to Arial and place a note.

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGL30.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL20.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL30.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3GL30.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGLES30.java
gdx/jni/iosgl/iosgl30.cpp
gdx/jni/iosgl/iosgl30.h
gdx/src/com/badlogic/gdx/graphics/GL30.java
gdx/src/com/badlogic/gdx/graphics/profiling/GL30Interceptor.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3TestStarter.java
tests/gdx-tests/res/com/badlogic/gdx/GdxTests.gwt.xml
tests/gdx-tests/src/com/badlogic/gdx/tests/gles3/PixelBufferObjectTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

This PR is open for discussion (i'll keep it as draft until we're all set).
I investigated deeply to know why glMapBufferRange was commented from the beginning. Some reasons could be found [in original PR comments](https://github.com/libgdx/libgdx/pull/2527#issuecomment-74588121).
In short, WebGL 2.0 doesn't provide this method for [performance and security reasons when writing to a mapped buffer](https://stackoverflow.com/questions/43530082/how-can-i-upload-a-texture-in-webgl2-using-a-pixel-buffer-object). For read only buffers there is a replacement method (getBufferSubData). So we could provide a limited implementation (read only) for the WebGL 2.0 backend later.
PBO (PixelBufferObject) is one of the use cases using glMapBufferRange. PBO is basically useful to asynchronously transfer …

GLES 3.0 glMapBufferRange implementation and PBO example

---

gdx/src/com/badlogic/gdx/graphics/glutils/FileTextureArrayData.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/TextureArrayTest.java

Mipmap generation was missing.
Note that MipMapGenerator is not used in this context since GL30 is available.

fix TextureArray mipmap generation, fixes #6380

---

gdx/src/com/badlogic/gdx/utils/Pool.java

I'm using libGDX's `Pool` with disposable objects. When an object is freed, but the maximum capacity of the pool is reached, in addition to discarding the object, I'd like to dispose it. However, simply overriding [`Pool<T>#free(T)`](https://github.com/libgdx/libgdx/blob/f99e6947777c89db8e99f351cb73e975a5d7840c/gdx/src/com/badlogic/gdx/utils/Pool.java#L60-L67) and adding that functionality is not possible, since I can't modify the private Array `freeObjects`.
Alternatively, I could just copy the whole class , but that makes it incompatible with [Pools](https://github.com/libgdx/libgdx/blob/80af4ba653789bc44488b9910e04d668eaa3ca7f/gdx/src/com/badlogic/gdx/utils/Pools.java#L22).

Add a Pool#discard(T) method.

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ParticleEffectActor.java

This adds a simple `ParticleEffectActor`. One could discuss if it is useful to show particle effects in Scene2d, but searching on GitHub for ParticleEffectActor shows that there is a need for such an actor in projects. Menus should look good, too, and we have some games completely built on scene2d.
Most ParticleEffectActors out there are inspired by a code from StackOverflow and update the particle effect in `update()` by converting the local coordinates to stage coordinates. This does not work if the ParticleEffectActor is member of a transformed group. The implementation here handles the update in draw(), because only in draw the position is set correctly by the parent.
I am sure this actor will not satisfy everyone's needs and has to be completed in the future. But it is a start.

Add a ParticleEffectActor

---

build.gradle
extensions/gdx-setup/src/com/badlogic/gdx/setup/BuildScriptHelper.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java

jcenter is shutting down in less than 90 days, so we need to remove it from our build scripts. All dependencies we needed from there are available on Gradle Plugins repo as well.

jcenter is shutting down, replace by Gradle Plugins

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/robovm.xml
tests/gdx-tests-iosrobovm/robovm.xml

Setting `arch` in config is not necessary and can be misleading. It defaults to `auto` (which chooses architecture automatically depending on the current host CPU architecture) but in practice it is always overriden both when using the plugin or the command line.

Remove unnecessary arch in robovm.xml

---

CHANGES
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSUIViewController.java

This change adds a HdpiMode option to the iOS backend's IOSApplicationConfiguration, which is used to calculate pixel coordinates for input and return heights and widths in raw pixels on the `getWidth()` etc calls. Safe areas are also returned in raw pixel sizes. The default is left as Logical pixels, the current iOS behaviour.
The rationale behind this is that some LibGDX games - including my own - use pixel scaling for things like UI positioning, texture tiling, and font generation. Porting to the new "logical pixels" system proved to be very difficult. This gives developers the same option they have on the LWJGL3 backend, and more closely matches the Android backend which to my knowledge always uses raw pixels. I've tested it with my own game and it seems to work.

Add HdpiMode option to iOS backend

---

settings.gradle
tests/gdx-tests-android/build.gradle
tests/gdx-tests-gwt/build.gradle
tests/gdx-tests/build.gradle

https://github.com/libgdx/libgdx/commit/446e26910cd30fbcda8518d979f75c43bcf44c82 renamed the subproject to "gdx-box2d-core" which does not match the maven/artifact id. This was done to prevent the issue caused by having two projects named the same. We should instead rename the parent project to "gdx-box2d-parent" like it [is in maven](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-box2d/pom.xml).
This is necessary to be able to publish from gradle eventually™
Addresses an issue brought up in #6369

Rename gdx-box2d projects in gradle to match maven

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidNet.java

See #6377 for full information

Make AndroidNet#openURI compatible with targetSdk 30, fixes #6377

---

CHANGES
gdx/src/com/badlogic/gdx/utils/Scaling.java

This allows custom Scaling methods.
We have a need for multiple new custom scaling elements, some of which have "fixed" parameters. These wouldn't be very useful for much of libgdx. This change would allow us to add them ourselves.
Scaling doesn't really need to be an Enum, it's never used in any switch statements, it only is to map String names to Scaling objects.

Convert Scaling from an Enum to an Object.

---

gdx/src/com/badlogic/gdx/math/MathUtils.java
gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java
gdx/test/com/badlogic/gdx/math/MathUtilsTest.java

This one's an especially intricate piece of code, and the bug it fixes is sorta non-obvious. Before, if you called `MathUtils.nextLong(Long.MAX_VALUE)` many times, you would never get a number with a `1` bit in any of the bottom 10 bits. This is obviously not random; the lack of odd numbers might be the most easily noticeable. That happens because the old code used a double (with 52 bits of mantissa) to generate a random long (with 64 bits). The ensuing precision loss affects all large-enough ranges. The fix is to use Rafael Baptista's technique for getting the upper 64 bits of a 64x64-to-128-bit multiply, treating the inputs as unsigned. It still works for negative bounds, like before, and is inclusive. The lower-bounded long generation is also updated (the regular random(long) calls …

Clean up MathUtils.random() for generating longs

---

tests/gdx-tests-gwt/build.gradle

Gretty pulls it in too, so it's not enough to have it on other classes.
Not sure why it isnt an issue for everyone, but https://mvnrepository.com/artifact/org.gretty/gretty-runner-jetty93/2.3.0 clearly lists it as a dependency.

Exclude apache-jsp from gwt-tests.

---

CHANGES
gdx/src/com/badlogic/gdx/scenes/scene2d/Group.java

`Group.removeActor(Actor child, boolean unfocus)` gives the option to unfocus the removed child.
`Group.removeActor(Actor child)` unfocuses the removed child (calls `removeActor(child, true)`).
For some reason, `Group.clearChildren()` currently does not unfocus the children. This looks wrong.
This PR adds a `clearChildren(boolean unfocus)` method.
Now the question is: do you want `clearChildren()` (no arguments) to unfocus like `removeActor(child)` does, or do you want `clearChildren()` to not unfocus to avoid potentially breaking apps which may rely on the fact that clearChildren() never unfocused until now? I'm all for breaking apps, but 🤷.

Unfocus children in Group#clearChildren()

---

CHANGES
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowConfiguration.java

This PR enables LWJGL 3's `autoIconify` config option by default. All the relevant information can be found here: https://github.com/libgdx/libgdx/issues/4785#issuecomment-744140507.

Enable LWJGL 3's autoIconify by default.

---

build.gradle
extensions/gdx-setup/src/com/badlogic/gdx/setup/BuildScriptHelper.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java

- Fixes #6427
- Replaces Gradle plugin repo by `gradlePluginPortal()`.
- I've also updated the Gdx Setup version to be in sync with libGDX.

Fix #6427. Add Gradle plugins repo to gdx setup project template

---

tests/gdx-tests/src/com/badlogic/gdx/tests/ExternalMusicTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/FloatTextureTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/TextureDownloadTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/net/NetAPITest.java

Hi, i  run gdx test for get some ideas (and it work !)
TextureDownloadTest and NetApiTest was broken cause url.
I get error on FloatTextureTest , i add @GdxTestConfig(requireGL30=true) . Can you check plz, i have 0 knowlegde on GL
```java
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Float texture FrameBuffer Attachment not available on GLES 2.0
at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.checkValidBuilder(GLFrameBuffer.java:284)
at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:116)
at com.badlogic.gdx.graphics.glutils.FloatFrameBuffer.<init>(FloatFrameBuffer.java:53)
at com.badlogic.gdx.tests.FloatTextureTest.create(FloatTextureTest.java:45)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433) …
```

fix some tests

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtNet.java

GWT http implementation calls onResponseReceived with status code 0 when connection couldn't be made at all. To harmonize this with our other backends, we need to call httpResultListener.failed in this case.

GWT: when HTTP connection fails, route to httpResultListener.failed

---

extensions/gdx-box2d/gdx-box2d/jni/maven/pom.xml

Looks like this was just missed when switching over to Github Actions. Current snapshots are missing the macosx dylib.

Add copy of macosx natives for box2d maven build

---

tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/Animation3DTest.java

Hi!
There is a deprecated method calling in the Animation3DTest. I removed it and the remained unnecessary casting.

Removes deprecated method calling and unnecessary casting

---

tests/gdx-tests-lwjgl/src/com/badlogic/gdx/tests/lwjgl/LwjglTestStarter.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3TestStarter.java
tests/gdx-tests/src/com/badlogic/gdx/tests/VertexBufferObjectShaderTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/CommandLineOptions.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTestWrapper.java

Now we can enable GL errors logging when running tests, helpful for debugging.
i also fixed the VertexBufferObjectShaderTest : 
- VertexBufferObjectWithVAO must be used when gl30 is enabled
- `gl.glEnable(GL20.GL_TEXTURE_2D)` is only valid with fixed function pipeline (which is not the case with libGDX).

enable GL errors in tests via commandLine argument, and fix a test

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java

Thanks to an issue raised on Discord by M1 we've noticed https://github.com/libgdx/libgdx/pull/6455 fixed `Logical` HDPI mode but messed `Pixels` just because I didn't test properly. Now everything works as expected, tested on both modes. Sorry for all the changes on iOS HDPI mode support, this one should be the last one.
@Tom-Ski We should not release until this is merged.

Fix wrong sizes provided to glViewport and listener on Physical HdpiMode

---

gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java
gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DepthShader.java

It's a common pitfall to have more bones in a model than what is configured (default is 12). In this case, you only see a model partially rendered without any obvious clue why (especially beginners).

check bones count when creating shaders

---

CHANGES
extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/AlignModeWrapper.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/BlendFunction.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/FlameMain.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/PointSpriteBatchPanel.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/SortMode.java
gdx/src/com/badlogic/gdx/graphics/g3d/particles/batches/PointSpriteParticleBatch.java

PointSpriteParticleBatch can be configured the same way as BillboardParticleBatch (blending and depth test).
I created a new panel in Flame for that renderer, moved shared enums to separate classes and refactor shared methods.

improved PointSpriteParticleBatch options

---

fetch.xml
gdx/.classpath

While #6369 is not merged we still use git tracked eclipse files and jnigen-loader was missing, so i temporarily added it back for Eclipse users.

fetch jnigen loader jar and add it to gdx classpath

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALLwjglAudio.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java
tests/gdx-tests/src/com/badlogic/gdx/tests/conformance/AudioSoundAndMusicIsolationTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

When a sound is finished, a new music playback didn't remove entry in sound/source maps. In this case, any change using the soundID (volume, pan, pitch) applies to the music instead.
I included a test case in order to validate the issue, let me know if you don't want this test in libgdx repo or if you prefer that i move it somewhere else...

fix audio voice stealing

---

CHANGES
gdx/src/com/badlogic/gdx/math/Polygon.java

Hi, 
Actually in Polygon , the only method to change a vertex is to use 
```	
public void setVertices (float[] vertices) {
if (vertices.length < 6) throw new IllegalArgumentException("polygons must contain at least 3 points.");
localVertices = vertices;
dirty = true;
} 
```	
I think a method is missing for change easily a vertex.
If read pr code you can see,
- a param vertexNum -> i start to 0, so for a triangle values allowed are (0,1,2). 
Maybe its more normal to start at 1.
- I change vertex in localvertices array, but should it consider the value as worldvertices ? And transform with scale and rotation to a localvertices
- It throw IllegalArgumentException if vertices dont exist in polygon.
Its better to let an npe appears?
My use case is not  on polygon class but in my own class …

Polygon add method setVertex

---

CHANGES
gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java

Previous PR request: https://github.com/libgdx/libgdx/pull/6465
I've found some time and implemented it in the way @mgsx-dev wanted it.
This however turns the PR into a breaking change compared to previously where it wasn't the case.

Fix #6464: TMX built-in tile property "type" is now supported.

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Net.java
tests/gdx-tests/src/com/badlogic/gdx/tests/net/NetAPITest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/net/OpenBrowserExample.java

This PR changes the method of opening URLs on macOS, since `FileManager.openURL(URI)` is deprecated and will be removed in JDK 17+. See #6542 for more information.

Fix LWJGL3Net#openURI on macOS & JDK >= 16

---

gdx/src/com/badlogic/gdx/assets/AssetManager.java

A deadlock occurs when an asset manager executor thread tries to acquire the lock during a `dispose()` or `clear()` call. This PR alters these methods to only acquire the lock when required (similar to `finishLoading()` having no explicit lock) and yield to the pending async tasks instead.
```
"AssetManager@2033" daemon prio=5 tid=0x17 nid=NA waiting for monitor entry
java.lang.Thread.State: BLOCKED
waiting for main@1 to release lock on <0x81d>
at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:145)
```

Fix asset manager deadlock on dispose and clear

---

gdx/src/com/badlogic/gdx/maps/tiled/tiles/AnimatedTiledMapTile.java

frameCount in AnimatedTiledMapTile is private and not used anywhere. It also cannot be accessed from outside.

Remove frameCount from AnimatedTiledMapTile

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/CameraInputController.java

Without performance penalty during run-time (`if`-statement), because it will just flip the `rotationAngle`.
Related Issue #6544

Implemented inversion of controls in CameraInputController

---

pom.xml

Currently there is no way to skip the natives download when running `mvn install`, this change allows you to run `mvn  -DskipFetchNatives=true install`  to skip natives download and use your existing natives.

Allow skipping natives download during mvn install.

---

gdx/src/com/badlogic/gdx/AbstractGraphics.java
gdx/src/com/badlogic/gdx/Graphics.java

Gdx.graphics.getDensity() returns infinity inside VirtualBox #6537
This way, AbstractGraphics' getDensity will always return 1f as a default value (instead of Infinity).
By the way, this is my first Pull Request for LibGDX ✨

Implemented a guard against invalid values of getPpiX in AbstractGraphics

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java

Hey guys,
this PR fixes a very specific problem: Wrong GlyphLayout for multi-line texts where a line after the first one several runs because of colormarkup. (Unfortunately this is not very obvious with the fonts provided with libgdx so I used my own BitmapFont for the screenshots where it is really obvious)
After going through the code for three hours I found the issue: While creating the runs in GlyphLayout#setText() "lastGlyph" is set to null even if there is no newline, but just a new run because of a colormarkup tag.
**Unfixed:**
One line: Everything works
Several lines: This is not correct. The bug is the distance between the "(" and the "5"
**Fixed:**
The distance between "(" and "5" is correct now also for multiple lines

Fix GlyphLayout multiline with color markup

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java
tests/gdx-tests/src/com/badlogic/gdx/tests/BitmapFontTest.java

Hey, I found another issue while I was doing my other GlyphLayout-PR yesterday, here is the fix for that:
Fixed wrapping of color-markup-runs with just one character (everthing works fine if the color-markup-run has more than 1 character).
I also adjusted the BitmapFontTest to include a 1-character color-markup-run and to use different colors for the debug-borders of the different runs.
State before this PR: The line is not wrapped properly if the targetWidth is at the right border of the "5".
This does not happen any more with this PR, the lines get wrapped properly.

GlyphLayout: Fix wrapping for color-markup-runs with just one character

---

CHANGES
gdx/src/com/badlogic/gdx/utils/StringBuilder.java

Hey guys,
I find myself typing this a lot:
```
...
final String s = stringBuilder.toString();
stringBuilder.clear();
return s;
}
```
So I thought maybe somebody else would also like a convenience method for this?
```
...
return stringBuilder.toStringAndClear();
}
```

StringBuilder.toStringAndClear()

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidMusic.java

On https://github.com/libgdx/libgdx/pull/6472 the check to verify `MediaPlayer` was playing before calling `pause()` was removed but it's actually needed in case `MediaPlayer` is on `Stopped` state to prevent entering `Error` state from which it doesn't recover.
To reproduce the issue just run `MusicTest` and:
1. Play a song
2. Stop it
3. Pause it
4. Try to play it again, it doesn't play (also can check stacktrace)

Protect Android MediaPlayer from getting into invalid state

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidDaydream.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFragmentApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidLiveWallpaper.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidLiveWallpaperService.java
gdx/src/com/badlogic/gdx/utils/GdxNativesLoader.java

fixes #5795 by giving the developer the ability to gracefully handle missing natives, e.g. by catching the SharedLibraryLoadRuntimeException and launching a new activity with an error message.
Note that natives loading was removed entirely from AndroidLiveWallpaperService as that immediately calls into AndoidLiveWallpaper.initialize.
Will print/sign/send the CLA shortly.

Moved Android natives loading out of static init block (#5795)

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java

Hello. I made a blunder. In pull request #6591, the setup tool title was changed from "Libgdx Project Generator" to "libGDX Project Generator". However, this only affects the how it's displayed in the taskbar, and probably a few other places - the title within the window remains the same. Turns out the title is defined twice, and I missed the second instance. Apologies for temporarily creating an inconsistency.
In case you're wondering, those spaces preceding it are surely intentional. They're a hacky way of adding left padding to the title, and it looks bad if they're removed.

libGDX capitalization (continuation of #6591)

---

gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java
tests/gdx-tests/src/com/badlogic/gdx/tests/BitmapFontTest.java

Hey guys,
this PR fixes a bug with colors and wrapping if there is a color tag hidden in whitespace.
The updated text in `BitmapFontTest` shows the problem. The "V" should be pink and will be white if the wrapping removes the whitespace.
@NathanSweet @tommyettinger

GlyphLayout: Fix wrapping with color tag in whitespace

---

backends/gdx-backends-gwt/src/com/badlogic/gwtref/gen/ReflectionCacheGenerator.java

PR fixes logging in `ReflectionCacheGenerator` which was broken in 90fc8f7
The logging is useful for spotting configuration issues with the reflection cache.
1. Build html target to generate reflection cache and look at the logs. (Any project should do).
Observed: Logging shows empty lines at the beginning (see below).
Expected: List of types included in the reflection cache 
```
[INFO]    Computing all possible rebind results for 'com.badlogic.gwtref.client.IReflectionCache'
[INFO]       Rebinding com.badlogic.gwtref.client.IReflectionCache
[INFO]          Invoking generator com.badlogic.gwtref.gen.ReflectionCacheGenerator
[INFO]             com.badlogic.gwtref.client.IReflectionCache
[INFO]               
[INFO]                 
[INFO]               
[INFO]                 
..
[INFO] …
```

[GWT] Fix: Reflection cache generator stopped logging types.

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/ExternalExtensionsDialog.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java

Some super simple changes to the gdx-setup dialogues. Basically makes the extensions text match the new red, and some other minor things done for consistency sake. Inspired by #6463 and about half of this is to match what it changed - I didn't try it until it was merged.
Currently, diauloug text gets truncated on Linux due to the window size not being wide enough. It's something I'd like to fix, but that would require seeing what the situation is on macOS and confirming it's consistent across distros - or make the daiologes so they can be packed without looking silly (more robust solution but also more work) - so it might not be destined for this pull request.

gdx-setup dialogs

---

CHANGES
gdx/src/com/badlogic/gdx/assets/AssetDescriptor.java
gdx/src/com/badlogic/gdx/assets/AssetManager.java

Removes the asset backslash replacement for more predictable asset paths (see #6554 for discussion and rationale).

Remove backslash conversion from asset manager paths

---

backends/gdx-backends-gwt/src/com/badlogic/gwtref/gen/ReflectionCacheSourceCreator.java

This PR solves a NPE in `Type#getDeclaredAnnotation()` itself and `Type#getDeclaredAnnotations()` at callsites caused by a small error in the `ReflectionCacheSourceCreator`.
(Spotted one inconsistency related to this I didn't touch, `Method` and all call sites expect a null for an empty `Method.annotations`, `Type`/`Field` and related call sites expect an empty array)
NPE in `Type#getDeclaredAnnotation` caused by `type.annotations=null` generated in  `ReflectionCacheSourceCreator`.
`ReflectionCacheSourceCreator::getAnnotations` can filter out annotations for various reasons which can produce `null`.
1. Annotate a class in your reflection cache with `@Deprecated` and nothing else.
2. Call `Type#getDeclaredAnnotation` on that class. Observed: NPE
1.10.1-SNAPSHOT.

Fix NPE in Type#getDeclaredAnnotation

---

gdx/src/com/badlogic/gdx/math/collision/BoundingBox.java

A classic pitfall with BoundaryBox: when modifying min and/or max vectors, some internal fields (center and dimensions) need to be updated. Previous workaround was to call box.set(box.min, box.max).
Wording in documentation could probably be better, any feedback appreciated.

better boundary box API and documentation for manual updates

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java

In #6463, the Box2D checkbox was set to be unselected by default, but this was only a visual change. With this pull request, now it should only be included if the user actually selects the checkbox.
This originally had stuff for removing gdx-tools from the UI, as it's unsupported in LWJGL3 so its checkbox does nothing, but following discussions on Discord that's no longer the case until we get a clearer picture on the state of gdx-tools and LWJGL3.

gdx-setup UI: Fix Box2D being included by default

---

gdx/src/com/badlogic/gdx/graphics/glutils/FileTextureArrayData.java

The current code repeats the Gdx.gl20.glGenerateMipmap call for every subtexture, although a single call at the end should be sufficient. This becomes a significant performance problem if a texture array contains a large number of elements.

Prevent repeated mipmap generation in FileTextureArrayData

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidAudioDevice.java
backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/audio/MockAudioDevice.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALAudioDevice.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALLwjglAudio.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALAudioDevice.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/mock/MockAudioDevice.java
gdx/src/com/badlogic/gdx/audio/AudioDevice.java

* Only really useful for Android to save resources when not playing any audio.
A playing AudioDevice will cause Android's audioserver to run constantly, even when the AudioDevice is not being fed any samples. Closing and recreating a new AudioDevice is not cheap, but pausing is.

Audio: Add pause/resume methods to AudioDevice.

---

.github/workflows/build-pullrequest.yml
.github/workflows/build-snapshot.yml
CHANGES

Fixes #6657
Breaking change that may make older linux operating systems no longer compatible. More or less matches changes done by lwjgl3, but we do not target a specific gcc/g++ version just use the default provided by bionic's meta packages.
- https://packages.ubuntu.com/bionic/g++
- https://packages.ubuntu.com/bionic/gcc
- https://packages.ubuntu.com/bionic/g++-aarch64-linux-gnu
- https://packages.ubuntu.com/bionic/gcc-aarch64-linux-gnu
- https://packages.ubuntu.com/bionic/gcc-arm-linux-gnueabihf
- https://packages.ubuntu.com/bionic/g++-arm-linux-gnueabihf

Linux: Shared libraries are now built on Ubuntu 18.04

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSMusic.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/objectal/OALAudioTrack.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/objectal/OALIOSAudio.java

I was seeing the following crashes on iOS on games where I load several `Music` tracks using `AssetManager`:
```
9 more Caused by: com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Error opening music file at /private/var/containers/Bundle/Application/B750969F-4D4E-48D1-9AD1-DB576A12AE1A/IOSLauncher.app/music/song.mp3 at com.badlogic.gdx.utils.async.AsyncResult.get(AsyncResult.java:46) at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:117) ... 12 more Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error opening music file at /private/var/containers/Bundle/Application/B750969F-4D4E-48D1-9AD1-DB576A12AE1A/IOSLauncher.app/music/song.mp3 at com.badlogic.gdx.backends.iosrobovm.objectal.OALIOSAudio
```
The reason is …

Improve iOS Music loading

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSUIViewController.java

Fixed #6643.
Also removed deprecated(on iOS6) method to handle supported orientation `shouldAutorotateToInterfaceOrientation` and improved the one that replaces it, `getSupportedInterfaceOrientations()`, to distinguish between iPad OS and iOS (following official docs recommendation only to add PortraitUpsideDown to iPad. (https://developer.apple.com/documentation/uikit/uiviewcontroller/1621435-supportedinterfaceorientations).

Fix #6643 and improvements to iOS supported orientations logic

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/war/index

The menu that pops up when you right click in the browser is incredibly intrusive when making HTML / web browser games.
Disabling it by default, I believe, is sensible because:
1. More people will ask how to disable it, than how to enable it.
2. Re-enabling it is simpler than disabling it. _(find and commenting out a line, compared to finding what the line is to add and where)_
This PR should also be followed up with @tommyettinger, who maintains lift-off. I believe if this gets merged, he should also make the change
**Alternatives**
To implement this, another thing I came across was
`<body oncontextmenu="return false">`
which, although being incredibly effective, does not achieve the same thing when we imagine telling a beginner which line to get rid of. _(They have to know html and know …

Make new libGDX HTML projects default to disabling the context menu

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/data/extensions.xml

https://github.com/kotcrab/VisEditor/wiki/VisUI is no longer where info about vis-ui is. It's now at https://github.com/kotcrab/vis-ui. Probably not a recent change - I just hadn't paid the links in gdx-setup much notice before. The others seem fine.

Update vis-ui website link

---

CHANGES
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java

The following code snippet is supposed to create a borderless fullscreen window:
```java
Gdx.graphics.setUndecorated(true);
Graphics.DisplayMode displayMode = Gdx.graphics.getDisplayMode();
Gdx.graphics.setWindowedMode(displayMode.width, displayMode.height);
```
However, while [testing some things for #6646](https://github.com/libgdx/libgdx/issues/6646#issuecomment-918095556), we discovered that on some systems the taskbar on Windows just stays visible, while on other systems the taskbar may be no longer visible, but is still clickable (i.e. clicking the lower part of the window just triggers taskbar shortcuts, etc.). To some extent, the bug was introduced in #6178, but even before then, in 1.9.11, this happened when the window was placed on a different monitor than the primary one. 
This …

Fix LWJGL 3 borderless fullscreen.

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/FlameMain.java

Fixed opening effect file error on Windows. When calling "file.getAbsolutePath()" it creates the file location with a backslash. But right after inside the load() we replace in that string all backslashes to a regular slash - thus leading the asset manager not to found the loaded resource.

Fixed opening effect file error on Windows.

---

gdx/src/com/badlogic/gdx/math/MathUtils.java

I had looked around for alternative atan2() approximations a while ago, and somewhat recently found a good series of approximations published in 1955 by RAND Corp. I believe I already used that study for asin() and acos() here. I've ramped up the quality on the approximations here because it can go up quite a bit while still keeping pretty much exactly the same speed as the current MathUtils.atan2(). I also added atan(), because it's quite similar to atan2(). Both max and average error are substantially better here -- my tests show max error was 0.004883076937336028 radians before, and 1.9221310783024137E-6 radians now. Average error goes from 0.0023030318272527724 radians (before) to 1.0570983651010727E-6 radians now. That means in both cases, we go from two zeros (0.00n) to 5 zeros …

Improve MathUtils.atan2() precision.

---

CHANGES
extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java

#6702 
This pull request will add methods for the freetype extension.
There is a method: `FreeTypeFontGenerator#hasGlyph(int)`.
This can check whether the font file has certain glyphs.
There're no tests. According to the [documentation](https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_get_char_index) of freetype, this should work on all platforms.

Add Methods for libgdx-freetype Extension

---

gdx/src/com/badlogic/gdx/scenes/scene2d/Actor.java

Corrected a typo (from 'rectange' to 'rectangle') in the JavaDoc of the scene2d Actor class.

Corrected a typo in the JavaDoc for the scene2d Actor class.

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java

Extracting the method setupMainLoop allows developers to extend GWTApplication and handle the main loop externally.
It might sound very specific but this is how [WebXR works](https://developer.mozilla.org/en-US/docs/Web/API/XRSession/requestAnimationFrame).

GWT: Extract setupMainLoop method

---

CHANGES

it appears that #6379 was a breaking change. It breaks Ashley (see libgdx/ashley#302)

add back breaking change notice

---

gdx/src/com/badlogic/gdx/graphics/g3d/decals/CameraGroupStrategy.java

Camera reference was wrong with some constructor, it uses the camera from parameter which is no longer valid when changing camera later.
note that It's not possible to reference instance variable when calling another constructor, so i had to move it to the final constructor.

fix bad camera reference by using instance variable instead of parameter

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Net.java

When using a libGDX application inside of a linux sandbox container (Snap/Flatpak), Net#openURI will fail to open any url because the Desktop.BROWSE action is unavailable. This is intended behavior of the sandbox. You're supposed to use xdg-portals to access urls in these environments.
The simplest way to workaround this limitation is to call xdg-open for the target uri. There's no guarantee it'll be able to handle your uri if a mime type is undefined for the sandbox, but it'll work most of the time. This binary is standard on freedesktop platforms.

Lwjgl3Net: Fallback to xdg-open on Linux if Desktop.BROWSE is unavailable

---

CHANGES
gdx/src/com/badlogic/gdx/utils/Pool.java

as discussed in #6723, Pool change from #6379 was a breaking change. This PR add back previous behavior.

add back default Pool behavior when object is discarded

---

extensions/gdx-tools/build.gradle
tests/gdx-tests-gwt/build.gradle

Found some issues that look to be side effects of https://github.com/libgdx/libgdx/pull/6652.
The resources from the main gdx module were not being added as sources for the GWT Tests, which was preventing compile.
Runtime dependencies were not included in the runnable jars for tools (e.g. Hiero couldn't launch due to missing ApplicationListener class).

Fixes some Gradle build issues (GWT Tests, Runnable Tools)

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/reflect/ClassReflection.java
backends/gdx-backends-gwt/src/com/badlogic/gwtref/client/ReflectionCache.java

gwtref: Throw ClassNotFoundException instead of RuntimeException in ReflectionCache.forName

---

tests/gdx-tests/src/com/badlogic/gdx/tests/PixmapBlendingTest.java

If I try to run the test for LWJGL3 as-is it gives me an error saying that cannot find test3.png or test4.png files.

Fix PixmapBlendingTest

---

.github/workflows/build-publish.yml

Will need secrets populated similar to gdx-jnigen.
We didn't do releases from github-actions before, but this will add release building from gha when a new release is created.

Use gradle for github-actions publishing

---

.github/workflows/fix-formatting.yml
extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextTooltip.java

The ParticleEditor crashed if you unfocused it and refocused it. For example, clicking out of the ParticleEditor window and then clicking back in would cause the ParticleEditor to freeze and not respond.
The reason is due to the `LwjglCanvas`. I suspect it has to do with the line `Display.processMessages();`. To fix the issue, in ParticleEditor I used a normal Java AWT Canvas, and created a new LwjglApplication passing the Canvas as an argument. This fixes the issue, as far as I can tell;
Tested on Windows machine, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz 
Fixes #6584

Fix ParticleEditor freezing and crashing

---

extensions/gdx-bullet/jni/swig/collision/btCollisionObject.i

Small fix to allow setting null to a body shape.

 Allow setting null to a bullet body shape

---

CHANGES
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Cursor.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtCursor.java
gdx/src/com/badlogic/gdx/graphics/Cursor.java
tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/client/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/SystemCursorTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

This PR:
- adds the `NWSEResize`, `NESWResize`, `AllResize`, and `NotAllowed` `SystemCursor`s, which are now available since LWJGL 3.3.0
- adds a `SystemCursorTest`
Tested on LWJGL 3 and GWT.

Add NWSEResize, NESWResize, AllResize, and NotAllowed SystemCursors

---

backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALAudioDevice.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALAudioDevice.java

This piece of code is dead as it never gets executed. The purpose was to fill the remaining buffers with silence and queue them on the source (the algorithm relies on it) but the code above already takes care of this, so these lines can be safely removed.

Remove dead code in OpenALAudioDevice

---

gdx/src/com/badlogic/gdx/graphics/Pixmap.java
gdx/src/com/badlogic/gdx/graphics/g2d/Gdx2DPixmap.java

Removes the need to create a copy if you already have an image in a **direct** ByteBuffer.

Add new Pixmap constructor for loading from a ByteBuffer

---

extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics/box2d/Shape.java
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Shape.java

Hey i see Shape class got this  comment
``` 
* NOTE: YOU NEED TO DISPOSE SHAPES YOU CREATED YOURSELF AFTER YOU NO LONGER USE THEM! E.g. after calling body.createFixture();
* @author mzechner */
public abstract class Shape implements Disposable {
```
dispose() method is already here.
I check on package except in World class (already impl Disposable) i dont find other occurence of dispose() or jniDispose()
Thanks for reading.

Box2D Shape implements Disposable

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java

https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory
I'm not totally sure if it's safe to use `UnsafeNativeLong`.
> The compiler will then allow you to pass a long into and out of JavaScript. It will still be an opaque data type, however, so the only thing you will be able to do with it will be to pass it back to Java.
from http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsJSNI.html
An alternative would be to convert it to a string and then parse it to a long back.

Get js heap size on gwt

---

publish.gradle

Was missed when adding the new projects. Normally we would have this match all subprojects, but libgdx's weird structure means specifying is better.

Add lwjgl3 extensions to publish.gradle

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java

Making this method public will allow a user to call it manually to override the PrintStream used for the error callback.
Due to how we call this early in [Lwjgl3ApplicationConfiguration#L263](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java#L263) we can't really make it a normal `Lwjgl3ApplicationConfiguration` option.
I'm open to feedback or suggestions on how to handle this better.

LWJGL3: Add errorStream option to initializeGlfw

---

gradle/dependencies.gradle
tests/gdx-tests-iosrobovm/build.gradle

Prior to this the static libs would be included inside the final app bundle which is not a intended behavior.

Remove inclusion of static libs into final app bunlde for iosrobovm test

---

tests/gdx-tests-android/build.gradle

Not sure how this ever worked without this, but it doesn't work without this now.

Copy required natives to gdx-tests-android

---

tests/gdx-tests-android/build.gradle

As requested on https://github.com/libgdx/libgdx/commit/facc7780be9b5cecde0a665fc9fb28ecdfa48429
Will simply pretend it's a normal java-library, and allow gradle to function for other projects without an android-sdk.
This was preferable to skipping the include due to further [references to the project](https://github.com/libgdx/libgdx/blob/facc7780be9b5cecde0a665fc9fb28ecdfa48429/build.gradle#L96)

gdx-tests-android will fallback to simple project when android-sdk is unavailable

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/glutils/VertexBufferObject.java
tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/client/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/MeshWithCustomAttributesTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

Vertex attributes type and normalisation was forced (not respected) in GWT backend for no reason which prevent use of custom types (byte, short, etc...).
Context: We faced this issue because gdx-gltf extension now uses unpacked color with normalized unsigned short instead of floats for vertex color (due to recent changes in Blender and GLTF exporter) which breaks with GWT backend.

fixed forced attributes type/normalize in GWT backend

---

backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSMusic.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/objectal/OALAudioTrack.java

#6654 Introduced an issue causing music not to loop when setting `setLooping(true)` before first `play()`. ObjectAL is a bit weird because the only thing that can't be set beforehand when calling `playFromFile()` is `numberOfLoops` and if not passed is set to 0 instead of taking the value of the property
This is the relevant code on [https://github.com/kstenerud/ObjectAL-for-iPhone/blob/master/ObjectAL/ObjectAL/AudioTrack/OALAudioTrack.m](OALAudioTrack).
```
- (bool) playUrl:(NSURL*) url
{
return [self playUrl:url loops:0];
}
```
Basically the fix is to store if `looping` has been set in order to pass it on first `play`.

Fixes music not looping when setting setLooping() before first play()

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java
gdx/src/com/badlogic/gdx/graphics/g2d/DistanceFieldFont.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Skin.java
gdx/src/com/badlogic/gdx/utils/Json.java
tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/ShaderTest.java

I have made changes in these files and updated old https://github.com/libgdx/libgdx/wiki/ and http://blog.xoppa.com links to their counterparts on libgdx.com and xoppa.github.io. 
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java
- extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java
- gdx/src/com/badlogic/gdx/graphics/g2d/DistanceFieldFont.java
- gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Skin.java
- gdx/src/com/badlogic/gdx/utils/Json.java
- tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/ShaderTest.java
I haven't tested it in any other way than making sure the links I've copied work.

Update dead links with new ones.

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGraphics.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java
gdx/src/com/badlogic/gdx/Graphics.java

Is there any particular reason why we're always returning 8 bits per pixel (256 colours) on the GWT backend?
I've set it to use `screen.colorDepth` instead, which has [supreme compatibility](https://caniuse.com/?search=colordepth). It's identical to `pixelDepth` but is supported by Internet Explorer 4 (and doesn't seem deprecated in any capacity - I don't know why there's two identical properties) so I couldn't resist.
In non-Chromium-based browsers I think it always returns 24bpp. This isn't particularly useful, I must admit, but at least it's one strange number out the way.
There's still no clean way of getting the monitor's refresh rate that I know of. Could measure the frame rate, but it's just not the same.
***
This pull request has now expanded to include Android in the mix, which …

Get color depth on GWT, refresh rate on Android

---

extensions/gdx-lwjgl3-angle/src/com/badlogic/gdx/backends/lwjgl3/angle/ANGLELoader.java

By simply checking if the file exists. It should allow to run more than one app and launch the app with RenderDoc.
Note: This change is untested, and I don't how to test it.
Fixes #6804

Fix crash if there more than one app launched with ANGLE emulation

---

gdx/src/com/badlogic/gdx/files/FileHandle.java

Fixes a minor mistake from #5181 which would prevent mapping files of certain `FileType`s on certain platforms.

FileHandle#map() should use the File from FileHandle#file()

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/List.java

Resolves #6832. I was unable to find any other Scene2D classes where you can set the alignment but not get the alignment.

Add `getAlignment()` to `List`

---

gdx/build.gradle

copyIdeaResources gets run while compiling the jar, leading to duplicate resource entries.
https://github.com/libgdx/libgdx/blob/master/gdx/build.gradle#L53-L57

Set duplicatesStrategy = DuplicatesStrategy.EXCLUDE in gdx/build.gradle

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java

The Jdoc of Lwjgl3ApplicationConfiguration.disableAudio has it the wrong way around. Pretty obvious, and one can easily check Lwjgl3Application line 96 to see what's what, but still.

Tiny correction to Jdoc of disableAudio

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/EffectPanel.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/ParticleEditor.java

As point out in #6816 this commit #6678 has introduced some issues in Emitter reading and manipulating operations. The reason is that since in Swing libGDX rendering runs on a different thread of the UI in some cases `ParticleEffect` emitters list is not synced with what UI shows producing a bunch of out of bounds exception.
This should also fix move emitter up/down operations.
Thanks :)

Fix Particle Editor Issues after recent commits, close #6816

---

build.gradle

Java 11's javadoc seems to ignore any classpath entries in special packages. This leads to the gwt emu classes being unavailable for javadoc processing. Resulting in the following error.
```
$ ./gradlew :backends:gdx-backend-gwt:javadoc 
> Task :backends:gdx-backend-gwt:javadoc
libgdx/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java:22: error: cannot find symbol
import java.nio.HasArrayBufferView;
^
symbol:   class HasArrayBufferView
location: package java.nio
1 error
```
This fix isn't ideal, but I don't really have a better idea how to make this work. Existing [Xdoclint](https://github.com/libgdx/libgdx/blob/7b7d78c175c2f3ed288215cbed9587edb35f70ab/build.gradle#L95) is applied, but doesn't prevent this being a fatal error.

Don't fail on javadocs error for gwt

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3WindowConfiguration.java
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/lwjgl2/src/DesktopLauncher
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/lwjgl3/src/DesktopLauncher
extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java

I don't mean to tread on any toes here, but after a few days of silence I'm proposing this solution for undoing the recent change that causes LWJGL3 projects to default to having no window title. This pull request restores the window title for old projects, corrects the javadoc, makes new projects use the project name for the window title (same as other backends) and changes the default project name in gdx-setup to clarify that the project name can and should have spaces and proper capitalisation.

Set window title to project name

---

CHANGES
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/Info.plist.xml
tests/gdx-tests-iosrobovm/Info.plist.xml

Trying to run libGDX Gdx Tests on Simulator on an Intel Mac throws the following error:
```
targeted OS version does not support use of thread local variables in _stbi__load_and_postprocess_8bit for architecture x86_64
```
This may be related to recent update of stb image (https://github.com/libgdx/libgdx/pull/6818).
Setting min iOS to 9.0 fixes it on Simulator. I'm not able to test on a device with iOS 8.
Before the stb upgrade we were already setting deployment target to 9.0 when building ObjectAL https://github.com/libgdx/libgdx/blob/a1b9b4dfe34fe7a5075844ecbbe6b60f14d65644/backends/gdx-backend-robovm/build-objectal.sh#L17 so I think it makes sense to move up our min iOS version to 9 in any case.

Increase iOS min supported version to 9.0.

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration.java

With the recent push to make lwjgl3 the default backend for desktop. I believe it's time to take a look at the removal of the Deprecated status that was originally placed on setTransparentFramebuffer() back in 2018 during the closure of this issue. #5313
This might seem insignificant, but having this method Deprecated is a big red flag to anyone who may like to use this pretty cool, though niche, feature. But does it even need to be anymore? I've done some digging and that's what we are here to decide.
First, The original comment in the code references an issue in the GLFW repo from 4 years ago which is still open to this day. [issue 1237](https://github.com/glfw/glfw/issues/1237) Which states that a user with an NVIDIA gpu running windows 10 was having issue with a test program using …

Case for Removal of Deprecated status on Lwjgl3ApplicationConfiguration.setTransparentFramebuffer()

---

CHANGES
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSAudio.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/objectal/OALIOSAudio.java

This removes direct calls to ObjectAL functions from IOSApplication and replaces it with calls to new 'activate' and 'deactivate' functions on the IOSAudio interface.
My motivation is to better support alternative IOSAudio implementations, which manage the audio session themselves. (I personally use one based on AVFoundation).

Extract iOS audio session management into methods on IOSAudio interface

---

gdx/src/com/badlogic/gdx/graphics/g2d/Sprite.java

As described in [issue 6862](https://github.com/libgdx/libgdx/issues/6862) `getColor()` returns a vertex's modified color instead of the `color` variable stored in the `Sprite`.
Even if the reason for the current implementation is to keep sync when the user modifies the vertices' colors directly, current `getColor()` implementation only takes `C1` into account.
Thanks to @tommyettinger, @mgsx-dev, @Frosty-J & @MobiDevelop for helping me understand key concepts

Fix Sprite's getColor() behavior

---

CHANGES
extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics/box2d/ChainShape.java
extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/org/jbox2d/collision/shapes/ChainShape.java
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/ChainShape.java

As explained in #6647 `b2ChainShape::Clear()` method must be called if vertices of a chain needs to be updated. I noticed that jbox2d included in libGDX didn't implement the `clear` method, while the official repository yes https://github.com/jbox2d/jbox2d/blob/fa4c74cbcdb607454150db131012c9469a70c55f/jbox2d-library/src/main/java/org/jbox2d/collision/shapes/ChainShape.java#L60 .
I tested changes on LWGL3 and GWT without issues.

Added ChainShape#clear method, close #6647

---

README.md
tests/gdx-tests/src/com/badlogic/gdx/tests/net/HttpRequestExample.java
tests/gdx-tests/src/com/badlogic/gdx/tests/net/NetAPITest.java

As discussed on Discord, the javadocs hosted at libgdx.badlogicgames.com are outdated. While generating our own javadocs and hosting them at libgdx.com would be nice, this is an adequate stopgap in the meantime.
Related: https://github.com/libgdx/libgdx.github.io/issues/105

Change javadocs link to javadoc.io

---

CHANGES
build.gradle

In the discord server James discovered that the generated javadoc doesn't have the "use" navigation tab anymore compared to the old javadoc still hosted on the badlogic servers
This PR is very simple and adds the ["-use"](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDGCJEG) flag to the javadoc generation and therefore adds that feature back.
Example: 
Old ones:
https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/maps/package-use.html
Current ones:
https://javadoc.io/static/com.badlogicgames.gdx/gdx/1.11.0/com/badlogic/gdx/maps/package-summary.html

Added -use option to javadoc generation

---

gdx/src/com/badlogic/gdx/utils/SortedIntList.java
gdx/test/com/badlogic/gdx/utils/SortedIntListTest.java

SortedIntList is used with DecalBatch and doesn't work when using `Collections.allocateIterators = true`.
I didn't investigate for all other collections but i suspect there are similar issues.
Feel free to commit to this PR if you find some other.

fix SortedIntList when used with allocateIterators

---

gdx/src/com/badlogic/gdx/assets/AssetManager.java

I haven't given this solution a great deal of thought, but I've just spent a long time getting to the bottom of the problem and I think you can guess what moods I'm in. I'd like it fixed so others don't have to lose sleep over the same problem. Or if this is a stupid solution but no-one comes up with a better way of doing it, at least document to never call it (in javadocs and/or wiki) with the `millis` overload on GWT.
Passing a number of milliseconds into `AssetManager#update` on GWT is a terrible idea. Not only do you get a reduced frame rate with no reduction in load time (even on localhost), you're also at great risk (only when using a custom asset filter, I think) of running into the `File not prefetched, but finishLoading was probably called` error due to the likelihood of …

Never stall with AssetManager on GWT

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/robovm.xml

See https://github.com/libgdx/libgdx/issues/6884 for more information
After this is merged I will open a reverting pr that should than get merged when releasing the next version.
Fixes https://github.com/libgdx/libgdx/issues/6884

Add back OpenGLES linking for gdx-setup

---

backends/gdx-backend-robovm/build-objectal.sh

~~This is nothing really relevant, I just noticed it by accident.
The embedded bitcode is only relevant when publishing in the App Store.~~
Bitcode appears to be deprecated on XCode 14 and won't be accepted even on AppStore submissions. 

Bitcode is deprecated on XCode 14

---

CHANGES
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java

This is like the Android immersive mode on iOS that should be default for games. 
Current screen edges deferring system gestures defaults were set to `None` initially for backwards compatibility but they are not good for games as the system takes precedence over the game on gestures which means it's easy to "exit" the app or open settings while playing and, depending on the game and UI, some edges areas may even be inaccessible. It is a quite recurrent issue/question on Discord.
Auto-hide home indicator setting is somehow related to system deferring edges settings. If set to `true`, the home indicator keeps appearing and disappearing on swipe movements and one single swipe from the bottom (instead of 2) "exits" the app. It may be appropriate for apps such as video players in which you …

Set new defaults for auto-hide home indicator and screen edges deferring system gestures 

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java

Immersive mode is nowadays enabled on most games and should be default. Backwards compatibility wise should not be a big deal (for those who don't read CHANGES) as the difference is obvious.

Set immersive mode to true by default on Android

---

tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/client/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/math/CollisionPlaygroundTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

Add this test sample to visualize frustum and ray casting. I am using this to debug collision algorithms and I am pretty confident that more people can find it useful too.
At the moment it can handle AABB and Spheres.

Add collision playground test

---

backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java

Currently the keyboard type does not change immediately when running "setOnscreenKeyboardVisible". This can be seen by running the "OnscreenKeyboardTest" test.
This pr fixes the issue.

Fix iOS Keyboard type not changing immediately

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidHaptics.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java

I've been able to run some tests on some Android devices to see how consistent the new haptics/vibration API is and I've found the fallback for Android O devices for the `vibrate(VibrationType)` call is not good enough, there's no feeling of impact whatsoever.
The main problem on Android ecosystem is that AFAIK there's no way to know for sure if the device has proper haptics support or a simple vibrator with amplitude control capabilities which makes all the difference. 
I think the best approach to assume haptics support is to require both amplitude control capaibilities and Android version to be at least Q because in that case the device must implement the Haptics API (https://source.android.com/devices/input/haptics/haptics-implement) and we ensure `vibrate(VibrationType)` will work …

Remove fallback on Android Haptics vibrate(VibrationType)

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/AnimationController.java

zero loopCount doesn't play animation (which make sense in term of API) and from repo history it looks like it always been like that. Also, 1 is the default for methods without loop count parameter.

fix javadoc for AnimationController

---

extensions/gdx-lwjgl3-angle/build.gradle
extensions/gdx-lwjgl3-glfw-awt-macos/build.gradle
gdx/build.gradle

When we upgraded to Gradle 7 (https://github.com/libgdx/libgdx/pull/6811) an issue was introduced that caused Gradle not to apply optimizations to the execution making builds much slower than they were.
There's this warnings spammed all over the place
```
Execution optimizations have been disabled for task ':tests:gdx-tests-gwt:javadoc' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: 'XXX\XXX\libgdx\gdx\build\classes\java\main'. Reason: Task ':tests:gdx-tests-gwt:javadoc' uses this output of task ':gdx:copyIdeaResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to …
```

Remove copyIdeaResources tasks

---

extensions/gdx-tools/build.gradle

I've got the solution from here https://discuss.gradle.org/t/gradle-fat-jar-with-module-dependency-fails-to-build-module-jar/43380
`sourceSets.main.java.outputDir` is deprecated so change it to `sourceSets.main.java.classesDirectory`

Fix building ye runnables

---

gdx/res/com/badlogic/gdx.gwt.xml

In the .gwt.xml file that defines which files are usable sources for GWT, ObjectLongMap was missing as a source, and PauseableThread was spelled incorrectly. Before, if you tried to use ObjectLongMap in conjunction with reflection on GWT, it would fail because the compiler didn't know ObjectLongMap existed. I don't know anything about PauseableThread, other than the name of the class has an 'e' in the middle and the source entry previously didn't. It might not make sense as being usable on GWT, but it was originally an "include" and not an "exclude," so I fixed the spelling only.

Small fixes for gdx.gwt.xml .

---

gdx/res/com/badlogic/gdx.gwt.xml

This fixes the compilation issues that #6946 introduced (by fixing a typo in the name of this class) and that were then encountered by #6963 .

Mark PauseableThread as excluded on GWT.

---

gdx/src/com/badlogic/gdx/utils/I18NBundle.java

It's very difficult to debug why some characters don't work right in properties files when the documentation goes on about charters.
Anyway, the issue in my case is properties are ISO-8859-1 (at least for Java 8 and older) but libGDX defaults to UTF-8. As far as I understand, GWT will always want UTF-8, so to fix this [IDEA/AS' default can be changed](https://www.jetbrains.com/help/idea/properties-files.html#encoding). Setting the encoding at the bottom-right of the IDE is disabled for properties.

`charter encoding` → `character encoding`

---

tests/gdx-tests-lwjgl3/build.gradle

Because of gdx-lwjgl3-glfw-awt-macos, startOnFirstThread isn't needed anymore.

Fix lwjgl3 tests

---

CHANGES
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSUIViewController.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSUIViewController.java

This PR changes the iOS backend to have completely setup OpenGL and call `ApplicationListener.create()` within the `UIApplicationDelegate.didFinishLaunching()` method. Before this PR it was lazily done on the first draw call from `GLKView`.
Once `didFinishLaunching()` returns iOS starts a fading transition from the launch screen to the root view controller. Without this change the root view controller has no contents yet and will therefore display black frames. Please see the following gifs for comparison on the default libGDX app. It is more noticeable if you have more resources to load for your first screen.
[Before](https://media.giphy.com/media/ySB9B0QY9r9MUL12db/giphy.gif)
[After](https://media.giphy.com/media/2h5zI1BY87NQL4fxYF/giphy.gif)
One important note: With this change all …

Optimize first render time of the RoboVM backend. Fixes #6971

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties

I've let https://github.com/tommyettinger/gdx-liftoff/commit/6582f6f0badf7ae1ecc660e51a2ec90c22678251 sit for a bit without catastrophe, so we can probably apply the same to gdx-setup. I don't think 7.5.1 vs 7.5 really makes a lick of difference to libGDX users, but might as well. Next Gradle release looks likely to be 7.6.
* [Release notes](https://docs.gradle.org/7.5.1/release-notes.html)
Budget Lyze:

Gradle 7.5.1

---

extensions/gdx-lwjgl3-angle/src/com/badlogic/gdx/backends/lwjgl3/angle/Lwjgl3GLES20.java

Rendering sprite batches was causing rendering artifacts when using the Angle backend, it looks like commit https://github.com/libgdx/libgdx/commit/a94b96834f541870174cf90f7c9247da6e97c0eb  broke this rendering path due to changing the other GL20 backends but not the Angle path.
Before:
After:

Angle backend: Fixing vertex buffer array indexing for glDrawElements

---

backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSHaptics.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSHaptics.java
extensions/gdx-lwjgl3-angle/src/com/badlogic/gdx/backends/lwjgl3/angle/Lwjgl3GLES20.java

Should be `light`. `soft` will crash on <iOS13 and on >iOS13 doesn't do anything apparently. https://developer.apple.com/documentation/uikit/uiimpactfeedbackgenerator/feedbackstyle

Fixed predefined Light iOS vibration

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/scenes/scene2d/utils/UIUtils.java
extensions/gdx-freetype/build.gradle
extensions/gdx-lwjgl3-angle/src/com/badlogic/gdx/backends/lwjgl3/angle/ANGLELoader.java
gdx/src/com/badlogic/gdx/scenes/scene2d/utils/UIUtils.java

These changes add support for FreeBSD by having `isLinux` be true for it as well. However projects likely need to be manually compiled by the user using self compiled natives, unless a FreeBSD CI system is built which iirc github doesn't offer. 
The changes to [extensions/gdx-freetype/build.gradle](https://github.com/libgdx/libgdx/compare/master...Mia-Rain:libgdx:master#diff-2c01f9a8a05474bdfd5b3225e4178d570d44b86c12212bcfdeacd98e350cd367) are needed so that `$CPP_FLAGS` and `$CC_FLAGS` can be set to `-I/usr/local/include/freetype2` otherwise compilation fails.
fixes: #4606

Modify to allow FreeBSD to build with minimal changes

---

gdx/src/com/badlogic/gdx/input/GestureDetector.java

In [GestureDetector.java](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/input/GestureDetector.java), #5466 is closed by making the `listener` final field non-null and performing a null check in the constructor. Since `listener` is no longer nullable, following `listener` field null checks are no longer necessary.
This PR removes an unnecessary null check in GestureDetector.java

Remove unnecessary null check in GestureDetector

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java

Support positioning on monitors with negative relative coordinates.
Tested it on my Windows machine with a monitor who's coords are negative (top left corner is to left of/above primary monitor).

[LWJGL3] Negative monitor coords

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/build.gradle

Replace usage of `tasks.whenTaskAdded()` to `tasks.matching()` in Android project for comply with Gradle guidelines of ["Task Configurations Avoidance"](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview)
This is implemented in order to avoid initializing ("lazy" configuration phase) all other independent tasks when starting any Gradle task. 
---
Before: [gradle performance link](https://scans.gradle.com/s/tlql5gfkwvgkq/performance/configuration#summary-tasks-created-during-configuration)
After: [gradle performance link](https://scans.gradle.com/s/lmnzq2xswo2jg/performance/configuration#summary-tasks-created-during-configuration)

[Gradle] Replace usage of 'tasks.whenTaskAdded()' to 'tasks.matching()' in Android project

---

gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java

Improved on SpriteBatch.setShader(): it won't flush anymore in case we are drawing and given shader is same as current one.

Avoids unnecessary flushing in case we are drawing

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/DefaultLwjgl3Input.java

Fix https://github.com/libgdx/libgdx/issues/7010
The internal variables `int mouseX, mouseY;` in `DefaultLwjgl3Input` are not updated when calling the `setCursorPosition` method. So, if you call `SetCursorPosition()` and next `getX()` or` getY()` the returned values are not updated.
This only happens in lwjgl3 backend.

Fix lwjgl3 SetCursorPosition

---

.github/workflows/build-publish.yml

Xcode 12.4 got thrown out of macos-latest soon.
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/

Upgrade gha XCode to 13.2

---

backends/gdx-backend-robovm/build-objectal.sh
gdx/build.gradle

https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes
"Building iOS projects with deployment targets for the armv7, armv7s, and i386 architectures is no longer supported. (92831716)"
This leads to build failures when trying to build libGDX from source. This pr fixes these in a first attempt.
The if - else blocks in the roboVM config block are not optimal. It would be best if we would have xcframework support in roboVM, or atleast in jnigen, to handle these cases better.

Make libGDX buildable from source again with XCode 14

---

gdx/src/com/badlogic/gdx/graphics/g3d/decals/CameraGroupStrategy.java

When transparent decals collides, some transparent pixels of one could cull others because they all read from and write to depth buffer.
Since they are already sorted (back to front), there is no reason to write into the depth buffer.
While fixing th issue, i noticed that the same thing was already done in SimpleOrthoGroupStrategy, so i think it's a simple missing or an edge case in CameraGroupStrategy.
I can't see a use case where this change would be a problem. I think it'll fix a lot more cases than breaking anything.

disable depth mask when rendering transparent decals

---

tests/gdx-tests-gwt/build.gradle

I'm readding this plugin because without it some gwt checks aren't run with `gradlew build`. This introduced the problem mentioned in #6946. It seems that some tasks are not called without this plugin. The dist task for gdx-tests-gwt doesn't work currently because of the mentioned PR. SuperDev seem to work on the other hand. I'm not sure why this plugin got removed in 630431293ce3193994055a79b0473baf71a5f6a5

Add war gradle plugin to gdx-tests-gwt

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/GdxNativeLoader.java

Hello! This PR adds an extra option to `AndroidApplicationConfiguration`: `nativeLoader`, which lets the developer specify a different strategy to load the gdx native libraries, for example [ReLinker](https://github.com/KeepSafe/ReLinker).
The motivation behind this PR is to allow devs to workaround issues that might rise by loading native libraries via `System.loadLibrary()`, which is something suggested on the [android docs](https://developer.android.com/ndk/guides/cpp-support#shared_runtimes).
This is my first PR! I think I might be missing something, please let me know in case :)
Should I add these changes under `1.11.1` in the `CHANGES` file?

Allow overriding native library loading in android

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/GdxNativeLoader.java
tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/client/GwtTestWrapper.java

Builds are currently busted because #6940 got merged without the formatter being run, I think. Interestingly, the formatter can run on my own fork - just not in libGDX's master branch because it's protected.

Apply formatter

---

gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java

This is a bug fix for the recently merged PR #6522.
When a vertex attribute is not enabled it uses its generic value. I didn't notice it during my tests probably because it was set to zeros. But in real life, it could be anything and these garbage data break some model skinning.
With this change, all bone weights generic value are set to zeros (bone index 0 with zero weight). Then when a mesh with less bone weights that what has been configured is rendered these default values are used for all disabled bone weights.
Example:
- DefaultShader.numBoneWeights = 4
- a model A with 4 bone weights
- a model B with 1 bone weight
- a single shader will be created for both
- when rendering model A, all bone weights will be enabled and data will be fetched from mesh data in vertex shader.
- when …

fix bone weights default values

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/glutils/VertexBufferObjectWithVAO.java

The object `cachedLocations` can never be `null` as it's initialized and never reassigned. This makes the if statement useless and triggers therefore a bug (`IndexOutOfBoundsException`).

Fix #6790; align GWT with other platforms

---

tests/gdx-tests/src/com/badlogic/gdx/tests/IndexBufferObjectShaderTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/MipMapTest.java

I noticed two tests while working on WebGL2 branch that were complaining of a GL_INVALID_ENUM. Both tests appear to have an old line of code from OpenGL 1.0 Fixed Function Pipeline days in them. 
`Gdx.gl.glEnable(GL20.GL_TEXTURE_2D);`
In OpenGL 2.0 this line serves no purpose if using Fragment Shaders (which the tests do) as documented here: https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glEnable.xml
In GLES 2.0 I do not even see it as an available parameter. https://docs.gl/es2/glEnable
In OpenGL 3.x it's deprecated and results in GL_INVALID_ENUM. 
This PR removes the lines as they appear to serve no purpose on OpenGL 2.0 in this context and result in errors on OpenGL 3.x

Remove unnecessary glEnable calls for TEXTURE_2D

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGL30.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL30.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3GL30.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSGLES30.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGLES30.java
gdx/jni/iosgl/iosgl30.cpp
gdx/jni/iosgl/iosgl30.h
gdx/src/com/badlogic/gdx/graphics/GL30.java
gdx/src/com/badlogic/gdx/graphics/profiling/GL30Interceptor.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gles3/PixelBufferObjectTest.java

This should fix regression introduced in #6309.
Backends status : 
* LWJGL 2 and 3: tested
* IOS: not tested, i'm not confident with my C++ code, @Tom-Ski feel free to fix it if needed.
* Android: not tested, apparently it requires native Android to call related methods but it worked in the previous PR by passing null buffer.
* WebGL: N/A, i checked specifications, WebGL2 have the related methods [texImage2D](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D) and [texSubImage2D](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texSubImage2D), we could implement them in the future.

GLES3 added glTexImage2D and glTexSubImage2D with offset parameter

---

backends/gdx-backends-gwt/issues.txt
extensions/gdx-box2d/gdx-box2d/res/com/badlogic/gdx/physics/box2d.gwt.xml
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/proguard-rules.pro
gdx/res/com/badlogic/gdx.gwt.xml

The jnigen `*Build` classes were removed on https://github.com/libgdx/libgdx/pull/5701 but some references were still around.
I think the `box2d.gwt.xml` file can be fully deleted, please let me know if that's the case, for the moment I've just removed the exclusion.

Removed unused references to old jnigen Build classes

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/lwjgl2/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/lwjgl3/build.gradle
gradle.properties

`enableJetifier` is no longer needed, setting it to default (`false`) should in theory speed up the build. It can be checked using the `:backends:gdx-backend-android:checkJetifier` Gradle task.

Fix Gradle deprecations and remove unnecessary enableJetifier config

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java

While working on WebGL2 PR I spotted an unused float array in GwtGL20. IDE reports no usages and manually searching I cannot find any usages either.

Remove unused float array

---

CHANGES
gdx/src/com/badlogic/gdx/utils/I18NBundle.java

Add `keys()` method to`I18NBundle`, this API returns a key set of loaded properties.
There is currently no public API to get loaded properties from `I18NBundle`. For example, if I want to preload FreetypeFont asset using the characters loaded from `I18NBundle` properties, this API can be useful.
This method will copy keys to a new set, which makes no side effect.

Add API I18NBundle#keys()

---

gdx/src/com/badlogic/gdx/math/Intersector.java
gdx/test/com/badlogic/gdx/math/IntersectorTest.java

Solution have been find by @tylerhasman & @tommyettinger but never merged. Closes libgdx/libgdx#6882
I've add fiew more tests.
I think I's usefull to warn user that because of float use, function may return a bad answer with realy small and realy big x,y,z. But if you think it's not usefull, I can revert comment of isPointInTriangle().
Let me know if anything else should be changed.

Fix isPointInTriangle in 3d (#6882)

---

.github/workflows/build-publish.yml

Soo, GitHub will remove the ubuntu 18.04 image by 4/1/2023.
https://github.com/actions/runner-images/issues/6002
They are already starting to let runner fail at specific times.
This is what happened e.g. here https://github.com/libgdx/libgdx/actions/runs/3250859896/jobs/5335094874 even though date wasn't mentioned as brownout date.
So the only way is probably upgrading. However because of the dynamic linking against libc, afaik this change would make the binarys incompatible with older OS.
The only way I could think of to work around this would be, to run a nested docker container for builds, but not sure whether this would be feasible.

Update gha to ubuntu-20.04

---

gdx/src/com/badlogic/gdx/graphics/Mesh.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gles3/ModelInstancedRenderingTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

ModelInstancedRenderingTest is a copy of InstancedRenderingTest but using renderables instead.
In this case, Mesh used cached vertex attributes location for instanced buffer, which was wrong : instanced attributes are not part of vertex attributes.
Without the fix, the provided test crash because it has more instanced attributes than vertex attributes (index out of bounds exception) but for other cases, it fails silently and instanced data wasn't available in the shader.
This change is not optimal, we could cache instanced attributes locations as well but i'm not sure the best way to do that without breaking API a bit : we would need something like :
* change `Mesh.bind/unbind (final ShaderProgram shader, final int[] vertexLocations, final int [] instancedLocations)`
* add …

fix instanced rendering when used with Renderable or Model

---

tests/gdx-tests-lwjgl/src/com/badlogic/gdx/tests/lwjgl/LwjglTestStarter.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3TestStarter.java

i noticed a crash running InstancedRenderingTest because glVertexAttribDivisor requires OpenGL 3.3+.
Note that OpenGL 4.3 is needed in order to fully emulate GLES 3.0. (see LwjglGL30 and Lwjgl3GL30 java imports)

fix OpenGL version in tests

---

backends/gdx-backend-android/AndroidManifest.xml
backends/gdx-backend-android/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/AndroidManifest.xml
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/build.gradle
tests/gdx-tests-android/AndroidManifest.xml
tests/gdx-tests-android/build.gradle

Moved to get rid of some deprecation warnings

Move AndroidManifest package to build.gradle namespace

---

CHANGES
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALMusic.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALMusic.java

setPosition for MP3 musics wasn't setting time position at the rigth place.
**How to test this fix ?**
You can see that this fix work by running `.\gradlew launchTestsLwjgl3` then choose MusicTest, play the mp3 file go to aproximatly 3:00. File is 3:03 min long, so it should stop at 3:03, but currently it continue over 3:10. (This fix make it stop at 3:03)
You can play file with a music player at libgdx/tests/gdx-tests-lwjgl3/build/resources/main/data/8.12.mp3 at 3:00 music fall down then stop at 3:03
**How does it fix it ?**
My guess is that mp3 reader don't fill buffer as wav & ogg do.
So to calculate how much of the file have been read we need to use the return of read(int) instead of bufferSize. Otherwise we think that 40960 have been read when only 40200. So wrong offset increase …

Fix Mp3 Music setPosition works wrong #6628

---

gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java

Quick PR in order to allow the packed depth stencil render buffer creation even if it's not using GL30 (as it was done at https://github.com/dar-dev/libgdx-pr/blob/ae00db682e3182440099c9d41ab9e7ee3c4a40aa/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java#L230)

Allow packed depth stencil buffer creation

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidAudio.java
backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/audio/MockAudio.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/audio/OpenALLwjglAudio.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/mock/MockAudio.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/objectal/OALIOSAudio.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/objectal/OALIOSAudio.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtAudio.java
gdx/src/com/badlogic/gdx/Audio.java
tests/gdx-tests/src/com/badlogic/gdx/tests/AudioChangeDeviceTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

This pr adds support for three main things (only for lwjgl3):
1. Auto switching the Output device if e.g. a headphone gets disconnected. This is mainly relevant on windows, because before that the audio just died.
2. It reevaluates the default device, if a new device gets connected, and therefor maybe switches to it (the os decides)
3. It adds a API to specifically select a output device. This API supports swapping too, so if the device gets disconnected and reconected, it will be choosen again.
I also added a Test for this.

Add API to (auto) switch output device on lwjgl3

---

gdx/src/com/badlogic/gdx/graphics/g3d/shaders/BaseShader.java

Discovered from Discord chat that NPE is possible with changes from https://github.com/libgdx/libgdx/pull/7128 and replicated on local running Animation3DTest. Instanced VertexAttributes may be null but the code is not checking for null before calling methods (size()) on them. Can be replicated on any test that uses ModelBatch/BaseShader without instanced rendering.

Resolve NPE on null instance attributes

---

.github/workflows/build-publish.yml

I guess the issue is, that the runner image apt cache is out of date.
https://github.com/libgdx/libgdx/actions/runs/5115098538/jobs/9196023119
Even if it is not, change shouldn't hurt.

Another potential CI fix

---

extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java
extensions/gdx-setup/src/com/badlogic/gdx/setup/SettingsDialog.java

#7064 is causing problems for users on Discord, and even myself. If you don't have Build Tools 33.0.2 installed, gdx-setup tells you to update it. It doesn't say *how* to update it, just that it needs updating. For the record: Tools -> [if on IDEA, Android] -> SDK Manager -> SDK Tools -> check Show Package Details -> check or uncheck versions as desired (before this PR, 33.0.2 must be checked) -> OK.
As the Android plugin (for IntelliJ IDEA, or baked into Android Studio) will automatically install the correct Build Tools version (or prompt them to accept the licence if they haven't already done so) I see no need for this check. Frankly, it shouldn't even matter whether someone has 33.0.2 or 33.0.1 - any minor version will work 99% as well as any other.
Tested by:
1. Uninstalling my copy …

Remove Android Build Tools version check from gdx-setup

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/lwjgl2/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/lwjgl3/build.gradle

Gradle now recommends using `tasks.register`. See https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_guidelines

Use latest Gradle API to register tasks

---

gdx/src/com/badlogic/gdx/scenes/scene2d/utils/UIUtils.java

Graal Native Image seems to not define java.runtime.name, which means without a default, `isAndroid` would call `.contains("Android")` on null, and crash. Adding defaults for `System.getProperty()` seems like a vital step for anywhere that gets String properties. This fixes https://github.com/libgdx/libgdx/issues/7111 . Thanks to authorZhao for finding the bug and suggesting a fix.

Use default property values to work on Graal.

---

CHANGES
build.gradle

It was reported on discord, jnigen 2.4.0 has broken min iOS version configuration and app build with it, can't be deployed to the app store.

Upgrade to jnigen 2.4.1 to fix app store publishing

---

CHANGES

#6714 was merged earlier this year, hence isn't in libGDX 1.11.0.

Correct changelog entry

---

backends/gdx-backend-robovm/build-objectal.sh

This pr implements the changes on libgdx for https://github.com/libgdx/ObjectAL-for-iPhone/pull/1
It's related to https://github.com/libgdx/libgdx/pull/7146 in some way.
This and https://github.com/libgdx/libgdx/pull/7146 should imo both get merged before 1.12.0, so that the iOS backend is consistent in regards of min iOS version and library types (all dynamic).

feat: Accommodate for ObjectAL Framework changes

---

gradle/dependencies.gradle

Current androidx.fragment version is from 2020. Now that Android dependencies are properly managed, the Fragment dependeny will be transiently added to all projects so it's important to keep it up to date. I've chosen 1.5.7 instead of 1.6.0 to make sure it's stable.

Upgrade AndroidX fragment version

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/robovm.xml

Reverts libgdx/libgdx#6887
As discussed in #6884, don't merge this before the next libGDX release
@obigu could you milestone this?

Revert "Add back OpenGLES linking for gdx-setup"

---

backends/gdx-backend-android/build.gradle
gradle/dependencies.gradle
tests/gdx-tests-android/build.gradle

The androidx.fragment dependency uses java8 features, and can therefor impose problems with r8/d8.
`androidx.fragment` is not needed by default and apps that do, will include the dependency on their own.
This change was tested and seems to fix the issues reported on discord.

Change androidx.fragment dependency to compileOnly

---

backends/gdx-backends-gwt/res/com/badlogic/gwtref/GwtReflect.gwt.xml

It seems like Tiled now uses reflection for more types than just MapObject in the `com.badlogic.gdx.maps` package, so this preemptively adds all of that package to the reflection cache, like how `com.badlogic.gdx.maps.objects` and `com.badlogic.gdx.maps.tiled.objects` already are added wholesale. It's possible that a more fine-grained set of classes could be added instead of the whole package, but it would just break again on GWT if any code used a class from outside that set.
Without this change, users can work around the bug by adding this to a .gwt.xml file:
```xml
<extend-configuration-property name="gdx.reflect.include" value="com.badlogic.gdx.maps" />
```
The TiledMapObjectLoadingTest and SuperKoalio tests currently fail/crash if run on GWT without this PR (at least those). They …

One-line fix for Tiled failures on GWT.

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL30.java
tests/gdx-tests/src/com/badlogic/gdx/tests/FrameBufferTest.java

Implements `glGetFramebufferAttachmentParameteriv` from both GL20 and GL30 for GwtGL20 and GwtGL30. I tested querying most of the values side by side with Desktop vs GWT on a FBO and received the same values on both platforms.
The WebGL equivalents are `getFramebufferAttachmentParameteri` and `getFramebufferAttachmentParametero`
Desktop Output:
```
[FrameBufferTest] GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: 5890
[FrameBufferTest] GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: 0
[FrameBufferTest] GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: 0
[FrameBufferTest] GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE: 6
[FrameBufferTest] GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE: 35863
[FrameBufferTest] GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE: 0
[FrameBufferTest] GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE: 0 …
```

Update WebGL API - getFramebufferAttachmentParameter

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AsynchronousSound.java

User "@muk" on Discord reported exception being thrown in rare cases when calling `stop()` on `AsynchronousAndroidSound`.
```
Exception java.lang.IndexOutOfBoundsException: index can't be >= size: 7 >= 7
at com.badlogic.gdx.utils.IntArray.get (IntArray.java:131)
at com.badlogic.gdx.backends.android.AndroidSound.stop (AndroidSound.java:59)
at com.badlogic.gdx.backends.android.AsynchronousSound.stop (AsynchronousSound.java:85)
``` 
Running `stop` on the `Handler` thread should fix the issue.

Fixes potential IndexOutOfBoundsException on AsynchronousAndroidSound

---

CHANGES
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java

This simple PR checks if the default audio device set by the OS was changed, and if so, switches the output device internally using the "auto" mode.
Or in other words, if you launch your game, realize the sound is coming out from your speakers instead of your headphones, and change the default device on the OS (e.g. Windows), libGDX will understand that and redirect the output to the device you selected there.
This PR is very simple and works on the assumption that the active device is the first one in the list returned by `getAvailableOutputDevices()`. It was tested on Windows, but it should work everywhere as long as that assumption is held true elsewhere.
https://github.com/libgdx/libgdx/assets/2331058/4f01f0cf-585b-4b7f-9162-89d02edc70d9

Automatically switch audio device if it was changed on the OS

---

gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java

This is just a one-line fix for one case where the operator precedence wasn't immediately clear, and was wrong in MeshBuilder. The line in question uses bitwise AND to mask `indices[i]` with `0xFFFF` and intends to then add `offset`. Because addition binds more tightly than bitwise AND, the mask `0xFFFF` changes to some invalid mask value and only then is it applied to `indices[i]`. This commit clarifies and fixes the precedence by grouping the bitwise AND so it happens first with a valid mask, and only then will `offset` be added.

Fix for #7216 (bitwise precedence).

---

gdx/src/com/badlogic/gdx/Input.java

I couldn't find an online reference for Mac-specific keycodes, so adding this comment to hopefully aid anyone who develops on MacOS for LibGDX in the future.
I'm aware this is probably a very niche group, but I think having some documentation would be helpful here anyway.

Add comment to Input.Keys documentation for ⌘ Command key

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/NumericPanel.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/Slider.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/NumericPanel.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/particleeditor/Slider.java

This is just a small fix for what seems to be a crash in ParticleEditor; it looks like it affects Flame as well. The issue stems from:
- We have a `NumericValue` that stores a `float`.
- We get that float and assign it to a `JSpinner` with a `SpinnerNumberModel`.
- Inside the `JSpinner`, it is promoted and assigned to either a `double` or a `Double`, I'm not sure which.
- We later get a value from the `JSpinner`, which gets returned as a boxed `Double`.
- We try to cast this to `Float` so it can be auto-unboxed.
- This causes a crash! `Double` cannot be cast to `Float`, even though their primitive forms can.
In this PR, we cast to `Number` instead of `Float`, and call `.floatValue()` on it. This is a pattern already used heavily in Hiero.
There are no other changes in this PR. Happy …

Fix some casts in ParticleEditor and Flame.

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Cursor.java

Fix #7175. 
The bug was caused by the fact that the `NONE` system cursor isn't handled as a cursor by GLFW but rather as an input mode. When we set the input mode to `GLFW_CURSOR_NORMAL`, we also overwrote whether the cursor was caught.

Fix setCursor releasing the caught cursor on the LWJGL 3 backend.

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java

Missed removing this hack from `onDreamingStopped()` when it was removed from `onPause()` here
https://github.com/libgdx/libgdx/pull/6871

Remove unnecessary Input hack

---

tests/gdx-tests/src/com/badlogic/gdx/tests/BulletTestCollection.java
tests/gdx-tests/src/com/badlogic/gdx/tests/bullet/HeightFieldTest.java

I was contacted on YouTube for any examples of `btHeightfieldTerrainShape`. I noticed we do not have a test that covers it so I added a new Bullet test to 1. Provide example as a resource and 2. Better test coverage.
Tested Windows Desktop and Android (Note 8)
I have some strange text/font artifacts right now on Desktop on the bullet tests, but this problem is on the other tests too and not related to this PR.
https://github.com/libgdx/libgdx/assets/28971753/c4b6089c-4707-4636-8970-f3f59b11148c

Add Bullet test demonstrating btHeightfieldTerrainShape

---

.github/workflows/build-publish.yml

alternative to https://github.com/libgdx/libgdx/pull/7177
https://github.com/theofficialgman/libgdx/actions/runs/5470509920
I personally prefer the GLIBC reversion script since it allows us to continue using github actions runners (and all the dependencies that are pre-installed). This PR has the same minimum GLIBC requirements (GLIBC 2.17)
I would attempt using musl to build the debs which would have an advantage of being able to statically link (no glibc) however its very difficult to compile projects using its (since everything including a projects dependencies need to be compiled with musl) (see https://github.com/desktop/dugite-native/pull/502#discussion_r1253754491 for my struggles with anothe project doing that)

Lower GLIBC requirements by using building linux natives on ubuntu 18.04 docker

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationConfiguration.java

Based on the linked issue, I have removed the use of deprecated tag on the useGL30 variables for Android, RoboVm, Metal-Angle, GWT. I also removed the experimental comment, but if any one feels some of these should still say experimental ( I don't know much about the IOS side) I can add that back in.
The original issue focused on Android, but I agree with MGSX that using deprecated is not appropriate even if we want to say it is experimental.

Remove usage of deprecated tag on GL30

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/Ogg.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALSound.java

I replaced the jorbis ogg decoder by STBVorbis for Sounds (literally the Sound class, not Music) in the lwjgl3 backend. This drastically reduces the loading time, usually something between 40% and 60%, depending on the file.
"Fixes" [https://github.com/libgdx/libgdx/issues/6635](https://github.com/libgdx/libgdx/issues/6635) I guess?
Since this change will affect almost all users and I don't want to take this lightly, I'd like to mention the limitations of the decoder, that ... I don't understand ... but maybe someone else:
- floor 0 not supported (used in old ogg vorbis files pre-2004)
- lossless sample-truncation at beginning ignored
- cannot concatenate multiple vorbis streams
- sample positions are 32-bit, limiting seekable 192Khz files to around 6 hours (Ogg supports 64-bit)
I only …

Use STBVorbis to decode ogg data for Sound

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java

LWJGL 3.3.3 now disallows to call `ThreadLocalUtil#setFunctionMissingAddresses` multiple times.
This PR, not very elegant, fixes this issue by resetting the `FunctionMissingAddresses` after the `GLES` class set them in their static initializer. This way, when the `GL` class is initialized, it doesn't crash. 
This crash only happens with `Lwjgl3ApplicationConfiguration.GLEmulation.ANGLE_GLES20`
Related LWJGL3 issue: https://github.com/LWJGL/lwjgl3/issues/931
Fixes https://github.com/libgdx/libgdx/issues/7245

Fix ANGLE GLES renderer on dekstop

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidTouchHandler.java

Some custom system Android gestures such as touching the screen with 3 fingers to capure a screenshot can trigger an ACTION_CANCEL event. All pointers need to be reset in those cases to avoid an inconsistent state.
I haven't been able to test the PR because I don't have a device that has these kind of gestures so, even if the change is low risk, testing is needed to confirm the fix works.

Fixes #7256

---

gdx/src/com/badlogic/gdx/input/GestureDetector.java

Fixes #7263. `GestureDetector` needs to reset the long press state when a touch cancel occurs to prevent inconsistent states.
To reproduce the issue adapt `GestureDetectorTest` to catch back key an follow the issue reproduction steps (enable System Gestures).
Fix tested on Pixel 3 with Android 12.

Fix longPress being triggered on back Android System gesture

---

build.gradle

Prevents Spotless from scanning output folders which causes issues with Gradle 8 (see https://github.com/libgdx/libgdx/pull/7246).
The only folders I've found that contain java files not present in a `src` folder are test classes in `gdx/test` and `gdx-backend-robovm-metalangle/generator` class.

Tighten Spotless rules to only include java src folders

---

backends/gdx-backends-gwt/res/com/badlogic/gdx/backends/gdx_backends_gwt.gwt.xml
backends/gdx-backends-gwt/res/com/badlogic/gwtref/GwtReflect.gwt.xml
backends/gdx-backends-gwt/res/com/google/gwt/webgl/WebGL.gwt.xml
backends/gdx-backends-gwt/res/jsinterop/annotations/Annotations.gwt.xml
extensions/gdx-box2d/gdx-box2d-gwt/res/com/badlogic/gdx/physics/box2d/box2d-gwt.gwt.xml
extensions/gdx-box2d/gdx-box2d/res/com/badlogic/gdx/physics/box2d.gwt.xml
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/core/CoreGdxDefinition
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/GdxDefinition
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/GdxDefinitionSuperdev
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/build.gradle
extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
gradle/dependencies.gradle
tests/gdx-tests-gwt/build.gradle
tests/gdx-tests-gwt/res/com/badlogic/gdx/tests/gwt/GdxTestsGwt.gwt.xml
tests/gdx-tests/res/com/badlogic/gdx/GdxTests.gwt.xml

I don't know why there's no dtd for 2.10.0, so I chose the dtd from 2.9.0

chore: Update to gwt 2.10.0

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java
gdx/src/com/badlogic/gdx/graphics/glutils/GLVersion.java

https://github.com/libgdx/libgdx/pull/7251 introduced a hack to temporary solve https://github.com/LWJGL/lwjgl3/issues/931 .
This PR proposes a proper solution, since the current approach is not stable as noted in: https://github.com/LWJGL/lwjgl3/issues/931#issuecomment-1793555387
ANGLE and `Lwjgl3TestStarter#enableGLDebugOutput` are now explicitly stated to not work together, before it would simply crash. A proper fix is out of scope of this PR.

Ensure that all ANGLE calls go through GLES classes

---

CHANGES
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Container.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/HorizontalGroup.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Table.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextArea.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/VerticalGroup.java

When "rounding" for UI layout, floor x/y and ceil width/height.
For example if a label has a fractional width like 123.4, rounding a Container's width gives 123 and the label won't fit.
Table already does this, so I'm pretty sure it's the right thing to do in all other layouts. If others can please check this doesn't negatively affect their apps, that would be great!

Fixed scene2d.ui layout for fractional positions and sizes.

---

backends/gdx-backend-robovm-metalangle/build.gradle
build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/build.gradle
extensions/gdx-tools/build.gradle
tests/gdx-tests-android/build.gradle
tests/gdx-tests-android/obb.gradle
tests/gdx-tests-gwt/build.gradle
tests/gdx-tests-lwjgl/build.gradle
tests/gdx-tests-lwjgl3/build.gradle

Some Gradle build files were still using old syntax after https://github.com/libgdx/libgdx/pull/7134.

Update missing build.gradle files with new syntax for registering tasks

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidNet.java
backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessNet.java
backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNet.java
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Net.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSNet.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSNet.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtNet.java
gdx/src/com/badlogic/gdx/Net.java
gdx/src/com/badlogic/gdx/net/NetJavaImpl.java

This commit adds the public boolean isHttpRequestPending (HttpRequest httpRequest) method to Gdx.net user interface. It allows end users to detect if an httpRequest is pending or already finished. It helpfull for creating advanced business logic.

Adds status detection for an httpRequest

---

extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/core/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/ios/build.gradle
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/lwjgl2/build.gradle
extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java

Since Java 21 (LTS) is the default version when downloading java, many users (specially new libGDX users) are complaining new projects don't work. Even if libGDX iOS backend doesn't fully support Java 8 language features (see https://github.com/libgdx/libgdx/issues/5487) at this point I think, until we decide on the approach to move forward, we should change Gdx Setup source level to 8 on all modules.

Set GdxSetup source level to java 8

---

gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEffect.java
gdx/src/com/badlogic/gdx/graphics/g2d/ParticleEmitter.java

This commit adds the method `public void reset (boolean resetScaling, boolean start)` to particle effect which allows to reset it without starting. In my opinion it's very usefull method for constructing advanced business logic. Previously to reset a particle effect without starting it users had to dispose it, then to reload it again from disk.

Added possibility to reset a particle effect without starting it

---

gdx/src/com/badlogic/gdx/net/NetJavaImpl.java

As mentioned [here](https://github.com/libgdx/libgdx/pull/7305#issuecomment-1870364802), a http request should be removed from the connections and listeners lists even if `HttpResponseListener#handleHttpResponse(clientResponse)` throws an exception. This mirrors the behavior for `HttpResponseListener#failed(e)` in lines 239 and 248 and is important because those list are checked  to see whether the request is still pending.

Move #removeFromConnectionsAndListeners into the finally block.

---

extensions/gdx-tools/build.gradle

This reverts commit fd535ab38900cd266631a7bbeab83d10c1bc5403 that was breaking the build.

Revert "Try to fix build"

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java
tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/GdxTestActivity.java

Currently, the developer is required to know the Android API to get real fullscreen in Android devices with cutouts. This was already worked on before by @MrStahlfelge in #5714 when `Graphics::getSafeInsetsXX` was introduced. He also provided an example of how to get fullscreen on screens with cutouts.
https://github.com/libgdx/libgdx/blob/fd535ab38900cd266631a7bbeab83d10c1bc5403/tests/gdx-tests-android/src/com/badlogic/gdx/tests/android/GdxTestActivity.java#L35C1-L39C4
- Add a config option called `AndroidApplicationConfiguration::renderUnderCutout` that allows the end user to use the space under the cutout.
- Check if the API is available on the device and use it if `AndroidApplicationConfiguration::renderUnderCutout` is set to true.
Not tested on IOS, licensing to expensive for a …

Android: Quality of life improvement for android cutout handling.

---

gdx/src/com/badlogic/gdx/audio/Sound.java

In #4256, docs on how panning only works for mono sounds was added to the `Sound#setPan()` method.
However for anyone trying to use `Sound#play()` with the panning argument, they won't see this note in the Javadocs.
I'd like to suggest adding the same note to these method docs!

Add more docs on stereo sound panning

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java

On the LWJGL 3 backend, resizing causes [additional render calls](https://github.com/libgdx/libgdx/blob/35ac7a1e3f640934e9cac403438a0c4dca49cc35/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java#L104C3-L104C33). However, for those, the delta time is never updated, it just stays the same as for the last 'real' frame. This leads to the game speeding up when the window is resized.
Fixes #7253.

Fix delta time not being reset when resizing.

---

gdx/src/com/badlogic/gdx/utils/ScreenUtils.java

I wanted to use the ScreenUtils clear() with applying antialiasing and found out it didn't support that. Thought it could be useful. I added in the javadocs that it is required in the class launcher to specify the number of samples (`config.numSamples = 2` - recommended for Android is 2, and 3 for desktop )
Thanks

Added antialiasing flag to the ScreenUtils.

---

gdx/src/com/badlogic/gdx/graphics/g2d/Batch.java

In the Javadocs, it's not clear what the units of rotation are for Batch - are they degrees? radians?
After trial and error I found out they're degrees (e.g. 0...360), I think it'd be helpful to have this clearly documented in the API

Document units of Batch rotation

---

gdx/src/com/badlogic/gdx/graphics/Color.java
gdx/src/com/badlogic/gdx/graphics/Colors.java

When you are tinting a texture, you may want to lerp from white to completely transparent. Unfortunately, if you use Color.CLEAR, it will also darken the image as it turns transparent. That's because Color.CLEAR is defined as (0, 0, 0, 0). That has its uses, but in this case Color.CLEAR_WHITE is a better option. It's defined as (1, 1, 1, 0). The texture will not be darkened if users implement this new Color. This change will not impact any existing code.

Added new Color CLEAR_WHITE

---

tests/gdx-tests-iosrobovm/robovm.xml

libGDX RoboVM tests `gdx-tests-iosrobovm` were not updated to use dynamic libraries after we migrated in  https://github.com/libgdx/libgdx/pull/7138 and didn't work, now they work.

Fix RoboVM backend gdx tests

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java

This PR addresses the issue of a user using the scrollwheel inside a ScrollPane nested inside of another ScrollPane causing both to scroll at the same time. If you look at web browsers and other user interfaces, scrolling a nested scroll pane never scrolls the parent at the same time. Advanced layouts with lots of scrollable content will benefit from this.

Only allow scrolling of a scroll pane if it has scroll focus

---

extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java

When using the BitmapFontWriter, fonts that require more than one texture page to fit all their glyphs fail. The resulting FNT file points to glyphs on the wrong page, resulting in a font that renders with odd looking characters. This occurs frequently with large fonts and with glyphs that could potentially land on the last row of the first page.
After some investigation, I discovered that it was a minor issue in FreeTypeFontGenerator causing this. It assigns the page index of each glyph to the last index of `packer.getPages()`. This is wrong because glyphs may still fit on the previous page depending on its dimensions.
The fix just applies the glyph hash code as the pixmap name to find the correct page. It's an inelegant solution, but does not require any API changes to adopt.

Fix incorrect glyph page index in FreeTypeFontGenerator

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java

Fixes #4576 for TextField. Similar could be done for TextArea.

[scene2d.ui] Fixed TextField breaking if the font has markup enabled.

---

extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
gdx/src/com/badlogic/gdx/graphics/g2d/PixmapPacker.java

Sorry I'm late to #7357.
If `pack` returned a PixmapPackerRectangle, it could have a `Page page` field. Then we don't need a unique name, don't need to add to `rects` map, and page index lookup is `indexOf` pages rather than checking the name of all rects on all pages.
PixmapPackerRectangle is already public and exposed by PixmapPacker.Page#getRects, but all the fields are default access so it's not useful outside the package. All the fields could be public, as I'm guessing that was the intent of exposing the class.

Alternative to #7357 for setting glyph page index.

---

CHANGES
extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java

**Problem**:
An oversight in the design of shadows in the gdx-ttf extension: When drawing fonts with shadows, it initialized an additional pixmap "shadowPixmap" without changing it's default fill color, leading it to be transparent black (0, 0, 0, 0). Then it renders the font on top which leads to bleeding the black color on the font
**Example**:
**Fix**:
Fill the shadow pixmap with the transparent color before using it, leaving transparent pixels to be the color choosen by the user.
**Workaround**:
While we wait for this to get merged, here's the fix in the form of a 3 classes: https://gist.github.com/WinterAlexander/5ec4bc65de744fdd90354013e5c0c0d7

gdx-ttf fonts bleed black color onto glyphs when they have shadows of any color

---

gdx/src/com/badlogic/gdx/scenes/scene2d/utils/DragListener.java

DragListener should only stop dragging when touchUp matches the button it cares about.
Repro: left mouse drag, press and release right mouse.
Expected: left drag continues.
Actual: right mouse up stops left drag.

Fix DragListener stopping when another button is pressed.

---

gdx/src/com/badlogic/gdx/Application.java

Corrects "this facilities" to "these facilities" in Application.java

Correct grammatical error in the JavaDoc of the Application interface

---

CHANGES
gdx/src/com/badlogic/gdx/utils/Timer.java
tests/gdx-tests/src/com/badlogic/gdx/tests/TimerTest.java

Timer considers a task "executed" when the timer thread posts it via `Gdx.app.postRunnable`. Code on the app thread may cancel a task that has been posted but not executed yet. It is then very confusing for the app to see a task `run` after it has been cancelled. To be safe, app code needs to check state for every task execution to make sure it is valid. This can be difficult, eg if a task is cancelled and rescheduled, the app could see both the cancelled and rescheduled execution.
We need a way for Timer to post runnables but still be able to remove them before they execute, if needed. This PR does that by having the timer post a single runnable `runPostedTasks` whenever there are one or more tasks that need to be executed. `runPostedTasks` then executes each task in `Array<Task> …

Fixed Timer tasks being run after cancellation.

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java

This fixes the issue as discussed [here](https://github.com/libgdx/libgdx/issues/7360)

fix: avoid unnecessary window.makeCurrent() calls

---

gdx/src/com/badlogic/gdx/graphics/Pixmap.java

`Pixmap` seems to be the only `Disposable` class that is not safe to `dispose()` if already disposed. Unless there's a good reason for this we should treat this scenario more leniently. Issue originally raised in https://github.com/libgdx/libgdx/pull/7334.

Make Pixmap safe to dispose if already disposed

---

.github/workflows/build-publish.yml

Since the NDK version pointed by `ANDROID_NDK_HOME` can change at any time and newer NDK version discontinue support for older android version, I think it is preferable to pin our NDK version to a specific one.
See https://github.com/libgdx/libgdx/issues/7307#issuecomment-1908980174
I verified that the commands work locally, but I haven't verified them integrated into a GHA.

Download NDK versions instead of using shipped ones by the runner

---

.github/workflows/build-publish.yml

XCode 13.2 isn't available anymore
`macos-latest` is currently `macos-14` ([src](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)) and the oldest XCode version there is 14.3.1 ([src](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode))

Upgrade gha XCode to 14.3.1

---

gdx/src/com/badlogic/gdx/math/ConvexHull.java
gdx/test/com/badlogic/gdx/math/ConvexHullTest.java

When using ConvexHull with `sorted == false` and `offset != 0`, an ArrayIndexOutOfBoundsException used to occur due to `end` not being reset properly. This commit fixes this behaviour.

Fix offsets in ConvexHull while unsorted being improperly accounted for

---

gdx/src/com/badlogic/gdx/graphics/OrthographicCamera.java

Currently `position` and `direction` are first added and then in  `Matrix4.setToLookAt` subtracted again. This can lead to loss of floating-point precision if the the components of `position` is much larger than those of `direction`.

Prevent loss of precision in OrthographicCamera.update

---

extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics/box2d/Box2DDebugRenderer.java

Ensures consistent behavior across backends and fixes a (The field Box2DDebugRenderer.XXX is not visible) error thrown when changes to the colors are made in the core package and deployed to web

Debug colors' access modifiers set to public

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtGL20.java
tests/gdx-tests-gwt/src/com/badlogic/gdx/tests/gwt/client/GwtTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/gles2/GlTexImage2D.java
tests/gdx-tests/src/com/badlogic/gdx/tests/utils/GdxTests.java

This PR adds ability to upload bytes as texture with a call to glTexImage2D on gwt target,
Currently on gwt this call expects always int buffers, and if the size is 1, then it is assumed that the int is actually index of a pixmap.
Test was also added targeting lwjgl3 and gwt, to verify that glTexImage2d actually works and that pixmap functionality was not broken (i can check currently only on those two platforms).

glTexImage2D support on GWT

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/DefaultGwtAudio.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplicationConfiguration.java
gdx/src/com/badlogic/gdx/Audio.java
gdx/src/com/badlogic/gdx/audio/Sound.java

Add config for automatic output device fetching on gwt

---

gdx/src/com/badlogic/gdx/graphics/g2d/Sprite.java
gdx/src/com/badlogic/gdx/scenes/scene2d/utils/SpriteDrawable.java

When profiling my apps I've realized the transformations between Color and packed color float have a pretty high CPU usage (in my case about 5%) as it may occur hundreds of times per frame.
Caching packed color in `Sprite` allows the optmization not to do the conversion when the color is the same and avoid lots of unnecessary conversions in some cases. You can see it only makes this check on `setAlpha()` and `setPackedColor()`, the reason being that adding a `this.color.equals(color)` check would cause 2 calls to `toIntBits()` making the optimization worthless.
With this change we open the possibility for further optimizations on the consumer side. For example `ParticleEmitter` currently calls `setColor()` every frame on each single particle. It could now call `setAlpha()` or …

Cache packed color on Sprite

---

tests/gdx-tests/src/com/badlogic/gdx/tests/AudioChangeDeviceTest.java

Pretty simple change, we need to stop/dispose the audio when closing the test.
fixes https://github.com/libgdx/libgdx/issues/7436

fix(tests): Properly dispose audio if test is closed

---

backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplication.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java

addresses https://github.com/libgdx/libgdx/issues/7297
Simple dummy frame during init process. Tested this with the supplied test in the issue report

force a dummy render to make sure gl is initialized at the time of create

---

CHANGES
backends/gdx-backends-gwt/res/com/badlogic/gdx/backends/gdx_backends_gwt.gwt.xml
backends/gdx-backends-gwt/res/com/badlogic/gwtref/GwtReflect.gwt.xml
backends/gdx-backends-gwt/res/com/google/gwt/webgl/WebGL.gwt.xml
backends/gdx-backends-gwt/res/jsinterop/annotations/Annotations.gwt.xml
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/files/FileHandle.java
extensions/gdx-box2d/gdx-box2d-gwt/res/com/badlogic/gdx/physics/box2d/box2d-gwt.gwt.xml
extensions/gdx-box2d/gdx-box2d/res/com/badlogic/gdx/physics/box2d.gwt.xml
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/core/CoreGdxDefinition
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/GdxDefinition
extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/html/GdxDefinitionSuperdev
extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java
gradle/dependencies.gradle
tests/gdx-tests-gwt/build.gradle
tests/gdx-tests-gwt/res/com/badlogic/gdx/tests/gwt/GdxTestsGwt.gwt.xml
tests/gdx-tests/res/com/badlogic/gdx/GdxTests.gwt.xml

This removes the need for any third-party backend to use GWT 2.11.0 . It updates the Maven coordinates to match the current ones for GWT itself (jsinterop didn't change). It updates the DTDs to match 2.11.0 and a working URL for that. It didn't need much else; some version strings needed changing.
The tests run, though they don't behave especially well (and I don't think this is related to 2.11.0). AudioChangeDeviceTest never stops beeping, even after closing the test, and opening it again makes it beep twice as much. The test list itself is over-sensitive to scrolling, and displays blank space at the bottom of the list instead of showing the last entries. Because the test list ScrollPane is essentially broken, I can't test anything after AudioChangeDeviceTest. Everything before that is …

Update to GWT 2.11.0

---

gdx/build.gradle
gdx/jni/iosgl/iosgl30.cpp

The function name definition was changed in https://github.com/libgdx/libgdx/pull/6394, but not the corresponding cpp implementation names. This fixes it.
It also adds gradle tasks to generate and validate the content of these header files.
Fixes https://github.com/libgdx/libgdx/issues/7434

Fix iosgl function name mismatch

---

gdx/src/com/badlogic/gdx/utils/Array.java

Various other iterators were made `transient` a while ago, but Array wasn't touched. `SortedIntList`, `Queue`, all `Set` types, and all `Map` types all use `transient` for their cached iterators, but for some reason `Array` doesn't. This matters when using default (typically reflection-based) serialization in something like [Fury](https://fury.apache.org/), or maybe also Kryo if it allows not writing a serializer. If the `ArrayIterable` and `PredicateIterable` are not marked `transient`, then they get written and form a cycle of references back to the original `Array`. Fury can handle this by tracking refs and by registering `ArrayIterable` and `ArrayIterator`, but this causes a significant increase to file size. Anything can handle this by registering a custom serializer, as well, but I …

Apply `transient` to Array's Iterable, Iterator

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java

This is a simple fix for the line:
```java
if (!Configuration.GLFW_LIBRARY_NAME.get().equals("glfw_async")) {
```
When `Configuration.GLFW_LIBRARY_NAME.get()` returns `null`, this throws an NPE. Flipping the `.equals()` means the LHS will never be null, making it valid when `GLFW_LIBRARY_NAME` is not set.
This also runs Spotless.

Fix when GLFW_LIBRARY_NAME.get() is null.

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/TextureLoaderPanel.java

As a new user to LibGDX's 3D environment and particles, I found myself struggling with the flame editor. When trying to load an atlas, I saw it didn't work but the software provided no feedback. So my first reflex was to run the flame editor with java in command line to get output and this is what I saw:
This was very confusing to me. 
The goal of this PR is to enhance the UX of when trying to load an invalid file as atlas or texture. The most obvious mistake (which was mine) I think is to provide the PNG file instead of the ATLAS file for an atlas, so I made the atlas error message reflect that. There's also an error message when adding a bad texture file. This way we provide feedback to the user in case the operation they requested didn't work.

Flame 3D particle editor UX improvement on bad user manipulations

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java

Eager initialization seems to be not needed, it works fine on my test. But I also fixed the cast for now, or made it more flexible.
At some point this probably needs rework too, but should be good enough for now.
Fixes https://github.com/libgdx/libgdx/issues/7465

Fix custom view usage on android

---

backends/gdx-backend-robovm-metalangle/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java
backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/DefaultIOSInput.java

`loc.getX/Y()` returns a double, which currently gets eagerly casted to an `int`. The leads to loss of accuracy if `HdpiMode.Pixels` is enabled and the `int` location is multiplied by the `pixelsPerPoint` float again.
This pr fixes this by first multiplying the floating point numbers and than casting to an Integer.

Fix floating point inaccuracy with touch position on iOS

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSpriteBatch.java

Change visibility of PolygonSpriteBatch.switchTexture() to protected
Use case: On texture switch pass the new texture size to a shader
(SpriteBatch.switchTexture is already protected)

Change visibility of PolygonSpriteBatch.switchTexture() to protected

---

gdx/src/com/badlogic/gdx/graphics/Camera.java
gdx/src/com/badlogic/gdx/utils/viewport/Viewport.java

These have always referenced screen coords for inputs, but they are actually in TouchCoordinate space (y down).
Given our docs on screen coords being y up, touch coords y down, this brings things in line.

Unproject and pick ray docs for Viewport/Camera

---

CHANGES
gdx/res/com/badlogic/gdx/utils/XmlReader.rl
gdx/src/com/badlogic/gdx/utils/XmlReader.java

Until now XmlReader did not offer any possibility to e.g. replace a child or to access the children of an Element directly to perform actions there.
This PR introduces these two methods to manipulate xml files. (In my case I want to adjust my Tiled .tmx and .tsx files in a custom map packer)
- XmlReader.getChildren()
- XmlReader.replaceChild()

XmlReader.getChildren() + XmlReader.replaceChild()

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/PreloaderBundleGenerator.java

For GWT, we calculate an MD5 hash of the file contents of each asset to assist browsers with caching. The current implementation reads the file fully into a byte array, calculates the MD5, adds it to the destination file name, then copies the source file to the output path. While this is fine for small files (albeit inefficient as we read each file multiple times), it can cause problems with large files.
This proposed implementation instead calculates the MD5 while reading the source InputStream for the copy operation, then renames (moves) the file to include the MD5 hash.
Refer to #4314 for the original addition, and #6848 for the problem this solves.

GWT - Calculate MD5 hash while copying file to avoid errors on very large files

---

.github/workflows/build-publish.yml

`macos-latest` is currently macos-14 ([src](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)) but since the 4th November they've removed XCode 14 and XCode 16 (https://github.com/actions/runner-images/issues/10703).

Upgrade gha XCode to 15.4

---

.github/actions/build-linux-natives/Dockerfile
.github/actions/build-linux-natives/action.yml
.github/actions/build-linux-natives/entrypoint.sh
.github/workflows/build-publish.yml

Similar to https://github.com/libgdx/Jamepad/pull/34, this uses a dockerfile and script to build the linux natives in a Ubuntu 18.04 docker container instead of running the entire natives-linux job in the container. This prevents needing to run actions like checkout and upload-artifact in the container, meaning it can still use glibc 2.17 to build without any issues with Node. Hopefully this means it can continue to work with newer versions of checkout and upload-artifact for the forseeable future. I haven't updated those action versions in this PR, but they can be updated without any issues.
I've done this by moving the docker setup (that was introduced in #7178) into its own action (which is local to the repo) that runs a script in the container that builds the natives. How it works is …

Use docker container action for building Linux natives in natives-linux job to fix issues with Node 20+

---

CHANGES
backends/gdx-backend-android/build.gradle
gradle/dependencies.gradle
tests/gdx-tests-android/build.gradle

https://github.com/libgdx/libgdx/pull/7004 introduced a dependency to `androidx.core` that was not added as a transitive dependency and required users to manually add it to their projects.
The version chosen of AndroidX Core is `1.13.1` which is the latest we can support with out `minSDK` of `19`. This version requires setting `targetSdk` to, at least, `34` which is something we had to do anyway because Google Play requires 34+ target sdk anyway.
The Android Tests module also requires Kotlin BOM dependency to handle a dependency collision that is well documented and should disappear when we upgrade to newer versions in the future.
Finally I've removed the explicit `BuildTools` version as it is automatically set by the AGP.

Add AndroidX Core dependency to Android backend

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java
extensions/gdx-tools/src/com/badlogic/gdx/tools/imagepacker/ImagePacker.java

This makes the small change of replacing the arcane `Font.decode()` with the Font constructor, specifying style PLAIN and size 12 (the defaults). The constructor is said to be equivalent in the `decode()` docs, but this way won't create a size-93 font when reading in a Font called `Bauhaus 93`, for instance, because the number won't get interpreted if we avoid decode(). I also fixed a minor JavaDoc error and a spelling mistake in the same general gdx-tools project, since these popped up when building runnables. This will close #7502 . I'm not sure this requires a CHANGES entry because I don't know if we even track gdx-tools in CHANGES.

Hiero font name validation ( #7502 )

---

CHANGES
gradle/dependencies.gradle

Given the AV false positives of 3.3.4 (https://github.com/libgdx/libgdx/issues/7552) and some on 3.3.5 and the log spamming issue occurring on 3.3.5 (https://github.com/kcat/openal-soft/issues/1086) that won't be fixed until 3.3.6 best approach is to downgrade to stable 3.3.3 for libGDX 1.13.1 release until these problems are fixed.
RISC-V natives won't be shipped with libGDX, if there's any RISC-V user they can upgrade lwjgl and add the dependencies on their end.

Downgrade LWJGL 3 to 3.3.3

---

gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Dialog.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextButton.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Window.java
tests/gdx-tests-lwjgl3/src/com/badlogic/gdx/tests/lwjgl3/Lwjgl3TestStarter.java
tests/gdx-tests/src/com/badlogic/gdx/tests/AbstractTestWrapper.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ContainerTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/GroupCullingTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneScrollBarsTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneTextAreaTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/TreeTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/UITest.java

Replaces all uses of `.expand().fill()` and variations by the appropriate `.grow()`, which is the preferred shorthand.

Replace uses of expand&fill with grow

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/MaxRectsPacker.java

The `TexturePacker` `MaxRectsPacker.MaxRects.pruneFreeList` method is O(n^3) in time, `n` being the number of `freeRectangles`.
`freeRectangles` size increases if you have many sprites with different sizes.
This PR changes the `pruneFreeList` method to use a O(n) approach.
Impirical tests, using 3000 random images generated by the code below showed the packer ran in around 60 seconds for the old method and in around 10 seconds for the new method.
```
public static void generateRandomImages() throws Exception {
Random random = new Random();
for (int i = 0; i < 3000; i++) {
BufferedImage image =
new BufferedImage(
32 + random.nextInt(32), 32 + random.nextInt(32), BufferedImage.TYPE_INT_ARGB);
Graphics2D g2d = image.createGraphics();
g2d.setColor(new Color(random.nextInt(256), …
```

Improve TexturePacker MaxRectsPacker pruning

---

extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/Body.java

Some of the methods to get properties of the Box2D bodies may be executed once per step (or more if user is not attempting to optimize). Because JNI calls are expensive, when having thousands of entities and depending on the platform, this may amount to a not negligible CPU frame time. The aim of this PR is to optmize some of the more popular calls such as getting the position of the Body without introducing any breaking change.
Tests have been run on Mac, iOS and Android, the platforms where JNI is less performant.
On average, the execution time of the calls is reduced by almost 50%.
In a real game scenario where the bodies position is retrieved on every step and there are thousands of bodies interacting, I've measured performance improvements of around 3%* on all platforms.
This …

Optmize JNI performance of Box2D Body methods

---

CHANGES
extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/World.java

On Box2D `World` class we have this [FIXME](https://github.com/libgdx/libgdx/blob/435da504c87b735778e89dca44ba1812fadffb55/extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/World.java#L268-L271). It's been there for many years and I guess the idea was to make it an option to use the default native ContactFilter for performance reasons. 
Currently, every time the decision whether two fixtures are to collide or not, a java upcall to `contactFilter (long fixtureA, long fixtureB)` is made. If the user has defined a custom `ContactFilter` it will be executed, if not, the default Box2D logic based on category, mask and groups to determine if they should collide is run on Java side. 
Looking for the reason on why we are executing the default shouldCollide Box2D logic on the Java …

Add option to use Box2D native ContactFilter for performance optimization

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/util/Locale.java
gdx/src/com/badlogic/gdx/utils/I18NBundle.java
tests/gdx-tests/src/com/badlogic/gdx/tests/I18NMessageTest.java
tests/gdx-tests/src/com/badlogic/gdx/tests/I18NSimpleMessageTest.java

Some small changes to the `I18NBundle` class and a trimming down of GWT's `Locale` documentation, because they are old.
Of course, there's more places than this where `String#isEmpty()` could be used. Search for `.length() == 0`, `.length() > 0`, `.equals("")`, and `"".equals` to find other instances. But this isn't very important to change, so I won't do so for unrelated classes in this pull request.

Use `Locale.ROOT` instead of `ROOT_LOCALE`

---

extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java
gdx/src/com/badlogic/gdx/graphics/g2d/PixmapPacker.java
gdx/src/com/badlogic/gdx/graphics/g2d/PixmapPackerIO.java

`PixmapPackerRectangle` inherits from `Rectangle` which is a `Shape2D` from `math` package that represents a geometric rectangle and is not appropriate to use it to simply store x,y,width and height integer values of a box/rectangle bounds, and in this case even less to do it via inheritance instead of composition.
I'm not sure if creating a separate `Box` or `Bounds` class instead of the inner class would make sense as it's a pretty standard use case probably used in many games and some other libGDX classes such as `IOSScreenBounds` could benefit from it.

Replace PixmapPackerRectangle Rectangle inheritance by Bounds

---

extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java

When multiple scales are set in the settings, an out-of-bounds exception occurs during the generation of the scaled pack file name, so this issue has been fixed.

Fix out-of-bounds exception in TexturePacker

---

backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/io/DataInputStream.java
backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/io/DataOutputStream.java

The first change is just using the added-a-few-years-ago Numbers.longBitsToDouble(), which is faster, instead of GWT's slow Double.longBitsToDouble() . There's an extended discussion (with pictures!) of the second change here, https://tommyettinger.github.io/libGDX-GWT-checks/ . The reason the second change looks the way it does now is optimistically hoping that JS will be able to pipeline two non-dependent bit operations before it ORs them. This mostly affects UBJson, but it may affect other places that used DataInputSteam.readLong() on GWT. Long story short, an `L` was missing from a mask literal, and so it wasn't masking an int at all, letting it implicitly promote to long afterwards and sign-extending then if the int was negative.

Two GWT emu fixes re: long in DataInputStream.

---

CHANGES
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java

Given how long ago libGDX dropped Android Donut support, I think this can be removed from the app config without so much as a deprecation period. Nobody should still be using this, especially not setting it to 16ms on 90Hz+ devices. It's a hack for a problem long gone.
Once upon a time, I looked into this. It seemed Android 1.x would absolutely batter your app with touch events while the touchscreen was pressed, even if the user's finger wasn't moving, which was bad news for your single-core device without JIT. But I don't have a device old enough to test that on, and it's difficult to buy one for testing since many were updated to Android 2 and sellers don't always have pictures that confirm whether they've been updated. Not that there'd be any point in testing this now - I just find the …

Remove `touchSleepTime`

---

.github/labeler.yml

>  If a base option is provided without a top-level key, then it will default to any.
https://github.com/actions/labeler
So, seems like it's just an "OR" currently and not an exclusion filter.

Hopefully fix labeler labeling everything as android

---

backends/gdx-backend-lwjgl3/build.gradle
gradle/dependencies.gradle
tests/gdx-tests-iosrobovm/build.gradle
tests/gdx-tests-lwjgl3/build.gradle

Fixes https://github.com/libgdx/libgdx/issues/5487
All the discussion happened in the issue.
The main summary is, that new java 8 API's cannot be used. But it is still worth to bump the target, to be able to use java 8 syntax features and allow building with the newest JDK again.
An immidiate improvement to both performance and safety would be being able to merge and apply to the core repo: https://github.com/libgdx/libgdx/pull/7474#issuecomment-2710053369

Bump project target to java 8

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java

This is a small experiment to test the viability of improving some of the Android backend codebase.
Android backend code is filled with warnings due to deprecations as well as code style/good practices warnings. Changing everything in one go is both risky and very hard to review (and thus unmergeable). The warnings affect both IDEs as well as build (Gradle) console outputs.
Let's try one class and one type of change at a time.
I've started with `DefaultAndroidInput`. Most changes are trivial and I expect to be viewed as positive by the great majority of contributors including adding the diamond operator (except from @NathanSweet) which is already present in this class (and most of libGDX code base except from Scene2d where there's a de facto veto).
If this "easy to review" PRs approach …

Minor code improvements to DefaultAndroidInput

---

CHANGES
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Button.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/List.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SelectBox.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Skin.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SplitPane.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Styleable.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextTooltip.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Touchpad.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Tree.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Window.java

This PR replaces the resolution of the `getStyle` and `setStyle` methods in `Skin#setEnabled` with a `Styleable` interface.
The reflection based approach does not work well with shrinker/dead code elimination and is more error prone when it comes to type safety. It also runs risks of duplicate `get/setStyle` methods, especially with subclassing.
The interface added fixes these issue, while retaining full backwards-compatibility. Therefore, this change is non-breaking.
A deprecation warning is issued to users, if the interface is not present and `Skin#setEnabled` is called.
@NathanSweet pinging you as the original author

Migrate set/getStyle calls in `Skin#setEnabled` to an interface

---

CHANGES
gradle/dependencies.gradle

Fixes provisioning profiles not being found on XCode 16.

Upgrade to MobiVM 2.3.23

---

CHANGES
backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java

This is a simple change that avoids unnecessary reflection for creating the lwjgl3 sound classes.
Since lwjgl3 requires java 8+, we can safely use the BiFunction here.

Remove reflection use for lwjgl3 sound/audio creation

---

CHANGES
backends/gdx-backend-robovm-metalangle/build.gradle
backends/gdx-backend-robovm-metalangle/res/META-INF/robovm/ios/robovm.xml
tests/gdx-tests-iosrobovm/build.gradle
tests/gdx-tests-iosrobovm/robovm.xml

The MetalANGLE repo, which we use, is currently unmaintained: https://github.com/kakashidinho/metalangle
I made a port of the MetalKit replacement and combined it with the official ANGLE sources: https://github.com/Berstanio/MetalANGLEKit
It is compatibility wise identical to MetalANGLE, the only difference is, that the OpenGLES compatibility backend is removed. This means, that macOS simulator/hackintosh wont be able to run the app in the iPhone simulator anymore.
However, for those the normal OpenGLES libGDX backend is still present.
The new MetalANGLEKit has been tested in two production apps so far.

Use official ANGLE for MetalANGLE

---

CHANGES
gdx/src/com/badlogic/gdx/scenes/scene2d/utils/BaseDrawable.java
gdx/src/com/badlogic/gdx/scenes/scene2d/utils/Drawable.java

These methods are just for convenience. There's a very small risk that someone's Drawable already has methods with these names (they'd have to not extend BaseDrawable).
Do all our targets handle default interface methods correctly? I would assume so, but these are the first in libgdx.

Add Drawable default interface methods

---

extensions/gdx-tools/build.gradle

With #7525 completed and merged. As discussed, to get a working runnable for this tool.
I spent some time working on a new section for the TiledMapPacker as well as modifications to all the pages which should reference it in the wiki. You can find my PR in the website repo here https://github.com/libgdx/libgdx.github.io/pull/244.
This PR is simply just a small change to what I think needs to be done in order to get us a built jar for the TiledMapPacker tool.
I'm not gradle guru, so I just did what I saw for the other tools. So correct me if I am incorrect in my assumption.

Added task to extentions:gdx-tools build.gradle so buildRunnables can produce a jar for the TiledMapPacker

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParallelArray.java
gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleChannels.java

This PR finishes of, what was started in https://github.com/libgdx/libgdx/pull/7605
The only downside I can see is, that an additional object allocation happens, when a `ChannelDescriptor` is allocated. However, this should not be a real issue I think.

Remove reflection use in ParallelArray

---

backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java

This is just a propose for a workaround to fix #6860 , I didn't understand the real root cause of this issue, this only info I was able to find was in GLFW docs https://www.glfw.org/docs/3.3/window_guide.html#GLFW_CONTEXT_CREATION_API_hint they advice some special behaviors with some Linux systems and X11 which looks like linked to the problem.
Any comments or insights would be highly appreciated.

Fix GLFW window creation with ANGLE and Ubuntu with Nvidia GPU Drivers

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java

- Changed the default alpha channel bits from 0 to 8 in the Android backend.
- This resolves rendering issues with textures and masks that require alpha blending.
- Ensures consistent behavior between Android and desktop backends.

Fix: Set alpha channel bits to 8 for Android backend

---

CHANGES
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/HorizontalGroup.java
gdx/src/com/badlogic/gdx/scenes/scene2d/ui/VerticalGroup.java

HorizontalGroup and VerticalGroup are intended for UI and should have transform set to false, like Table, Container, and Stack. It was just never noticed until now!
This is a breaking change, since someone could be relying on transform being true, though that is probably unlikely.

[scene2d.ui] HorizontalGroup and VerticalGroup set transform false by default.

---

backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.java
backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java

This PR updates `BufferFormat` to use the provided configuration instead of hardcoded values, as suggested in #7415 by @obigu.
It also adds a `coverageSampling` setting to `AndroidApplicationConfiguration`. While I’m not personally familiar with what it does, users who need it will benefit from having the option. For those who don’t, it remains harmless and has no effect.
**Note:**
The only place where `BufferFormat` is constructed with `coverageSampling` set to anything other than `false` is in [AndroidGraphics#logConfig](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java#L346)

Respect AndroidApplicationConfiguration in BufferFormat creation

---

gdx/src/com/badlogic/gdx/utils/OrderedSet.java

first, hashCode, equals avoids digging through the whole keyTable. ensureCapacity also does it for items.

OrderedSet overrides for efficiency

---

gdx/src/com/badlogic/gdx/math/Vector2.java
gdx/src/com/badlogic/gdx/math/Vector3.java
gdx/src/com/badlogic/gdx/math/Vector4.java

Vector classes have static field `Zero` with all fields initialized with 0.
This PR add fields `One` with all fields initialized with 1.

Add Vector.One static fields for convenience

---

gdx/src/com/badlogic/gdx/utils/Array.java

This was accidentally broken in https://github.com/libgdx/libgdx/pull/7605
It should be kept as "? extends T", because the array is cloned and therefore no type issues can occure and it should acceppt sub-types.

Fix accidental breakage in Array constructor

---

CHANGES
gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java

Adding convenience functions in `ShaderProgram` to input integer arrays into a shader program without needing to call OpenGL directly. Directly matches the already present `glUniform_fv` functions.
Important use case: array of texture sent to the shader, for example with cascaded shadow maps

Support for integer arrays `glUniform_iv` functions in ShaderProgram

---

gdx/src/com/badlogic/gdx/maps/tiled/TmjMapLoader.java

While checking out the leftover Tiled PRs, after rebasing I noticed the TMJ map tests were failing.
This was because of a change to the JsonValue class, recently on August 8th.
A new method, JsonValue.getIgnoreCase()  was added and the case insensitivity from .get() was removed.
In the TmjMapLoader we were mistakenly using "tileSets" instead of the proper "tilesets".
But since the original JsonValue.get() was always comparing with equalsIgnoreCase. It just "worked" anyways.
But it was wrong to be checking against that string, it should be looking for "tilesets". So I have fixed it.
If you are wondering why I did not instead change it to use the newly added JsonValue.getIgnoreCase() method. It is because the tmx loader IS case sensitive so we should keep functionality the same.
That is …

Small but Important fix to the TmjMapLoader.

---

.github/workflows/gradle-wrapper-validation.yml
gradle/wrapper/gradle-wrapper.properties
gradlew

Well tested stable release and probably the last 8.X one. Will allow us to upgrade AGP version when needed.

Update Gradle to 8.14.3
